### ISSUE TITLE
💡 Have "mounts" configurations take priority over "statics" configurations

### ISSUE THREAD

**Issue by rustygreen** [TypedProject/ts-express-decorators#1457]
## Informations
**Is your feature request related to a problem? Please describe.**
I would like the `mounts` to take priority over the `statics` in terms of resolving a route. The main use case I have for this is the ability to serve a single-page application (Angular, React, etc.) at the root route (`/`) but then also have other routes available such as `/v1/docs` or `/rest`.

**Describe the solution you'd like**
When routing, the following routes they would resolve in this order:
1. Mounts
```ts
  mount: {
    '/api': [TemplatesController],
    '/docs': [IndexCtrl]
  }
```
2. Statics
```ts
  statics: {
    '/': [{ root: `${rootDir}/public` }]
  },
```

For example, with the following configuration:
```ts
@Configuration({
  port: 3000,
  mount: {
    '/rest': [MyController],
    '/docs': [DocsController]
  },
  statics: {
    '/': [{ root: `${rootDir}/public` }]
  }
})
```
When a request is made to `http://localhost:3000/rest/*` it routes to the mounted `/rest` controller(s).
When a request is made to `http://localhost:3000/docs/*` it routes to the mounted `/docs` controller(s).
When a request is made to `http://localhost:3000/ANYTHING_ELSE` it routes to the statics configuration.

http://localhost:3000/rest/my-data --> REST service
http://localhost:3000/docs--> docs page
http://localhost:3000/ --> application
http://localhost:3000/some/route/in/my/app --> application

**Describe alternatives you've considered**
An alternative to this would be to setup the routing outside of the nodeJS app and do it in nginx or Traefik or higher level routing option. Being able to do it from within the application would make everything much simpler. The described behavior above can be accomplished with .NET core, but I'd rather use ts.ED 😉

## Acceptance criteria

- [ ] Routes will first try to match any mounted configurations, then will resolve to match static configurations (if no mounted configurations match)

**Comment by Romakita** [comment]
Hello @rustygreen 
The statics are loaded after /rest controllers so I don’t understand your point…

**Comment by Romakita** [comment]
https://github.com/tsedio/tsed/blob/production/packages/common/src/platform/builder/PlatformBuilder.ts#L338

**Comment by rustygreen** [comment]
Thanks, @Romakita. You're, right - I was just confused. The incorrect behavior I was seeing was a result of the application having a service worker which was caching the root ('/') request and then subsequently returning the application content for all other requests (`/rest/*`). I'll close this issue. Thanks, for the quick responses!
