### ISSUE TITLE
🚀 Ability to display API version in Swagger UI

### ISSUE THREAD

**Issue by rustygreen** [TypedProject/ts-express-decorators#1459]
## Informations
**Is your feature request related to a problem? Please describe.**
I would like the ability to pass the API Docs version into the swagger configuration to display the API version in the swagger UI:

![image](https://user-images.githubusercontent.com/1774477/125853892-e37db756-ccaf-486d-9b17-7da087970190.png)

**NOTE:** I am not talking about the openApi version, I'm looking for a way to cleanly display API versions.

**Describe the solution you'd like**
I would like to be able to set the displayed version in the swagger UI by using the swagger configuration:

```
  swagger: [
    {
      path: "/docs/v1",
      doc: "v1",
      version: "1.0.0"
    },
    {
      path: "/docs/v2",
      doc: "v2",
      version: "2.0.0"
    },
  ],
```

**Describe alternatives you've considered**

![image](https://user-images.githubusercontent.com/1774477/125853892-e37db756-ccaf-486d-9b17-7da087970190.png)
![image](https://user-images.githubusercontent.com/1774477/125854039-5704a990-bbd9-4e1e-a5d4-b50b185dbaca.png)

## Acceptance criteria

- [ ] Setting a version on the swagger configuration sets the "version" display in the swagger UI
- [ ] Switching definitions (from the dropdown) updates the displayed version

**Comment by Romakita** [comment]
Hello @rustygreen 
It's already possible by using the spec option:
```js
  swagger: [
    {
      path: "/docs/v1",
      doc: "v1",
      spec: {info: {version: "1.0.0"}}
    },
    {
      path: "/docs/v2",
      doc: "v2",
      version: "2.0.0"
    },
  ],
```
See you
Romain

**Comment by rustygreen** [comment]
Thanks, @Romakita! You guys have built a really great framework! 👏👏👏

Unfortunately, setting the `spec.info.version` doesn't appear to affect the displayed version in the UI.
![image](https://user-images.githubusercontent.com/1774477/125951175-a5e28f7b-1907-41df-a9ce-6c3945073db2.png)

![image](https://user-images.githubusercontent.com/1774477/125951220-8290103e-71f1-47ef-a604-56a279ec1084.png)

**Comment by Romakita** [comment]
what? hum not normal it should change the version... let me see

**Comment by Romakita** [comment]
Hoooo my apologies. Ts.ED use the version from configuration. So you've right, I need to fix the code :)

**Comment by Romakita** [comment]
Hum in fact, the code works:

<img width="332" alt="Capture d’écran 2021-07-16 à 15 20 00" src="https://user-images.githubusercontent.com/1763311/125954513-2ee5e756-d9f3-4da3-9149-7e04fdd085f7.png">

```typescript
@Configuration({
  ...config,
  version: "1.5.0",
  acceptMimes: ["application/json"],
  httpPort: process.env.PORT || 8083,
  httpsPort: false, // CHANGE
  mount: {
    "/rest": [
      `${rootDir}/controllers/**/*.ts`
    ]
  },
  exclude: [
    "**/*.spec.ts"
  ],
  swagger: [
    {
      path: "/docs",
      specVersion: "3.0.1",
      spec: {
        info: {
          title: "Api Title",
          description: "Description",
          version: "1.5.0"
        }
      }
    }
  ]
})
```
See  https://github.com/tsedio/tsed-example-commands-typeorm

**Comment by Romakita** [comment]
@rustygreen The code works as expected.

<img width="332" alt="Capture d’écran 2021-07-16 à 15 20 00" src="https://user-images.githubusercontent.com/1763311/125954930-90736367-6932-48be-9291-629273414167.png">

See also: https://github.com/tsedio/tsed-example-commands-typeorm

**Comment by rustygreen** [comment]
@Romakita it looks like the docs are using the version from the `server configuration` rather than the version from the individual swagger `doc configuration`. Is that the desired behavior? That behavior doesn't allow the ability to maintain several versions of the API within the same code base (server instance). Having the version pulled off of the server configuration means that every doc configuration will have the same version number.

![image](https://user-images.githubusercontent.com/1774477/125957021-85503c37-9c08-4c0b-a5e0-b09af5dc1402.png)
![image](https://user-images.githubusercontent.com/1774477/125957291-b18cac3b-dc7e-464a-a178-34ad6a489f7e.png)

**Comment by Romakita** [comment]
Just remove the version on top level ;)
The version on top level is only consumed by the swagger so remove it will have no other side effect ^^

**Comment by Romakita** [comment]
@rustygreen  fixed ;)

**Comment by rustygreen** [comment]
Awesome! Looks good. Thanks, @Romakita!
