### ISSUE TITLE
[BUG] Swagger documentation is broken after update to 6.59.6 or above

### ISSUE THREAD

**Issue by AlexDede** [TypedProject/ts-express-decorators#1471]
## Information

- **Version:** 6.59.6 or above
- Packages: 
@tsed/swagger

A few sentences describing the overall goals of the issue.

After upgrading of  all packages version to `6.59.6 or above` swagger documentation is broken. It's take around to 10 seconds to load swagger UI (it seems like all times  spends to load `swagger.json`) with only list of tags. But all tags are empty and no any information about models.  

Current swagger configuration:
```
 swagger: [{
        path: '/api/1.0/docs',
        showExplorer: true,
        specVersion: '3.0.1'
    } as SwaggerOS3Settings]
```

**Comment by Romakita** [comment]
@AlexDede Can you give me a reproducible example please (repo). 

There is a lot of integration test over Swagger spec generation which cover many usecases (and it works) so I need more details!

See you
Romain

**Comment by AlexDede** [comment]
@Romakita Thank you for response. I found the reason of empty swagger in my project. It is related to the path of routes.

If `@Controller`, `@Get`, `@Post`, `@Put` or other related decorators contains `.` in the path it will break swagger. Also `mount` section in `@Configuration` decorator break swagger if path contains `.`

For example:
```
@Controller('/api/1.0/test')`
```
or
```
@Configuration({
...
mount: {
 "/api/1.0": [
  '${rootDir}/controllers/**/*.ts'
  ]
}
...
})
```


You can easy reproduce this with any project or I can create a test project and share with you.

**Comment by Romakita** [comment]
Ok I see. Update your dependencies to 6.60.2. it should works.

**Comment by AlexDede** [comment]
The same issue with the latest version (6.60.2)

**Comment by Romakita** [comment]
Cannot reproduce:
<img width="1261" alt="Capture d’écran 2021-07-26 à 18 56 41" src="https://user-images.githubusercontent.com/1763311/127028804-8af67876-19d8-4247-868d-92341de0fee0.png">

:(  This is why I insist on creating an example repo so as not to waste time.

Here my repo example: https://github.com/Romakita/tsed-issue-1471

So give me an example with the broken swagger and the expected result! Without that I wouldn't do an investigation ^^
See you
Romain

**Comment by AlexDede** [comment]
@Romakita Sorry for missing example. I spend a lot of time to find the reason in my big project (I can not share it). 

But here you can find small repo: https://github.com/AlexDede/tsed-issue-1471 with the bug example.

And current result is:

<img width="1916" alt="Screenshot 2021-07-26 at 21 10 51" src="https://user-images.githubusercontent.com/17781943/127037727-9f447337-4477-4df1-bb6b-471316096f54.png">

Expected result

<img width="1920" alt="Screenshot 2021-07-26 at 21 26 47" src="https://user-images.githubusercontent.com/17781943/127039693-79471099-b117-466e-b626-7ba2caddc2c9.png">


I also submitted pull request to your example repo to reproduce bug.

**Comment by Romakita** [comment]
Ok I see now. The problem is occurs when there is twice controllers or more.

**Comment by AlexDede** [comment]
@Romakita thank you!
