### ISSUE TITLE
Dynamic Multer file field

### ISSUE THREAD

**Issue by jappyjan** [TypedProject/ts-express-decorators#1485]
## Informations
so the problem is the following:

I receive a dynamic object from the client with n fields from which i know the names BUT only at runtime (inside the controller/service function) and not before so i cannot statically add the field names to the multer decorator.
Some of these fields may be files, some may not. again i know if they are at runtime, but not before.
How can i use Multer to make this work?

I could add a decorator that accepts an array of files to a static field name but i would like to not do this ...
an option to solve this is the multer.any() middleware, but this is not mentioned in the TSED.io documentation.

**Comment by jappyjan** [comment]
okay i found a solution by creating a custom Multer.any() middleware and applying it using @UseBefore()

```
import Multer from 'multer';
import {multerConfig} from '../../../../config/sub-configs/multerConfig';
import {IMiddleware, Middleware, Next, Req, Res} from '@tsed/common';

// same config that would get passed to multer via TSED.io
const MulterAnyFileMiddleware = (Multer(multerConfig)).any();

@Middleware()
export class UploadAnyFileMiddleware implements IMiddleware {
    use(@Req() req: Req, @Res() res: Res, @Next() next: Next): void {
        MulterAnyFileMiddleware(req, res, next);
    }
}
```

**Comment by Romakita** [comment]
Hello @jappyjan 
Sorry for the late answer. Yes the quick solution is to create custom middleware!
