### ISSUE TITLE
Unable to manually register protocols and/or services 

### ISSUE THREAD

**Issue by dkini** [TypedProject/ts-express-decorators#1487]
We manually register controllers and entities in our Ts.ED project and are unable to use glob patterns to automatically scan and register them due to our project structure. What would be the best way to manually register protocol and/or services instead of using the componentScan with the glob pattern?

**Comment by Romakita** [comment]
Just import the services/protocols with a classic ES6 import on server.ts

**Comment by dkini** [comment]
After importing it in Server.ts, do we add it to the configuration like this? Or is there a better way?
![image](https://user-images.githubusercontent.com/10350685/129089521-fab51407-9681-400d-8bad-b33cdcab8af6.png)

**Comment by Romakita** [comment]
Also. But ´import “./path/to/protocols/Protocol“;’ works

**Comment by diego-rapoport** [comment]
> After importing it in Server.ts, do we add it to the configuration like this? Or is there a better way? ![image](https://user-images.githubusercontent.com/10350685/129089521-fab51407-9681-400d-8bad-b33cdcab8af6.png)


Is that documented? Couldn't find it anywhere I was looking.

**Comment by Romakita** [comment]
just use ES6 import. 

```typescript
import "./path/to/protocols/BearerProtocol";

@Configuration()
```

Ts.ED discover automatically imported classes.
