### ISSUE TITLE
Breaking @QueryParams camelCase vs snake_case between 6.60.0 vs 6.62.3

### ISSUE THREAD

**Issue by bkniffler** [TypedProject/ts-express-decorators#1493]
## Information

- **Version:** 6.62.3

Between 6.60.0 and 6.62.3 at some time, `@QueryParams` behavior must have changed. Using something like `@QueryParams("camelCase")` used to work fine, but after updating to the latest version, the argument will be empty even though set via query (`/somepath?camelCase=123`). `req.query` shows an object `{ camel_case: '123' }`, so it looks like query params are now automatically snake cased. Is this a bug? Is this expected? Any way to customize this behavior?

I got loads of places where I use camelCased query params and I only coincidentally found this bug (because it doesn't really yield an error).

**Comment by Romakita** [comment]
@bkniffler Can you create a reproducible repository example. Because there is no code that change the query params to snake case in Ts.ED itself ^^. A quick search on the repository confirm that point (no snakeCase function). This is very unlikely to come from the framework.

See you
Romain

**Comment by Romakita** [comment]
Here is a repo example. https://github.com/Romakita/tsed-query-params 
All works as expected!

Maybe you use a middleware / code that change the query object in express ^^.
