### ISSUE TITLE
[BUG] `mount` is ignored when used in modules

### ISSUE THREAD

**Issue by derevnjuk** [TypedProject/ts-express-decorators#1500]
## Information

- **Version:** `>=5.5x`
- **Packages:** `di`

I use modules to avoid duplicating common components. It works well when we speak about middleware, filters, and pipes. However, controllers are just ignored. See example below:

```ts
@Controller('/')
export class HealthController {
  @Get()
  @Get('/health')
  @Returns(204)
  public health(): void {
    // noop
  }
}

@Module({
  mount: {
    '/api/v1/': [HealthController]
  }
})
export class HealthModule {
  // ...
}

@Configuration({
  // ...
  mount: {
    '/api/v1/': [ /* other controllers */ ]
  },
  imports: [HealthModule]
})
export class Service {

}
```

I have tried to add controllers on the `$beforeInit` hook, it also has no effect.

```ts
@Module({
  deps: [Configuration]
})
export class HealthModule {
 constructor(private readonly configuration: Configuration) {}
 
  public $beforeInit(): void {
    const endpoint = '/api/v1/';

    this.configuration.mount[endpoint] = (
      this.configuration.mount[endpoint] ?? []
    ).concat(HealthController);
  }
}
```

It seems it somehow connected with [importProviders](https://github.com/tsedio/tsed/blob/fb696ea257022a764bf2649cb273f648444a4448/packages/common/src/platform/builder/PlatformBuilder.ts#L263). That method resolves all providers concurrently, while `imports` must be initialized before building the module itself according to docs.

**Comment by Romakita** [comment]
Because it's $beforeInit ^^ (or $onInit).
But it's better to resolve the problem around the mount properties.

**Comment by Romakita** [comment]
For me it's works with the latest version (6.x): https://github.com/tsedio/tsed-example-modules

**Comment by derevnjuk** [comment]
@Romakita Hmm... It seems I missed something) I guess we can close this issue

**Comment by Romakita** [comment]
You've mentioned the v5 ^^. My example is on v6. So your issue is on v5?

**Comment by derevnjuk** [comment]
Thanks) Everything works on v6
