### ISSUE TITLE
[FEAT] IoC container does not resolve nested async deps

### ISSUE THREAD

**Issue by derevnjuk** [TypedProject/ts-express-decorators#1502]
## Information

- **Version:** `6.x`
- **Packages**:  `di`

Currently, there is no way to register multiple providers, which depend on each other, using the async factory.

### Steps to reproduce

1. Register an async factory (`A`)
2. Register another async factory (`B`) so that it depends on the `A` provider 
3. Build all providers from the container

### Example

```ts
import { InjectorService, registerProvider } from '@tsed/di';
import { ok } from 'assert';

registerProvider({
  provide: 'async_provider_1',
  async useAsyncFactory(): Promise<unknown> {
    return {};
  }
});

registerProvider({
  provide: 'async_provider_2',
  deps: ['async_provider_1'],
  async useAsyncFactory(asyncProvider1: unknown): Promise<unknown> {
    ok(
      asyncProvider1 instanceof Promise,
      'The dependency is an instance of Promise.'
    );

    return {};
  }
});

const injector = new InjectorService();

injector.load(); //  AssertionError [ERR_ASSERTION]: The dependency is an instance of Promise.
```

## Actual result

The IoC container passes a dependency as an instance of Promise.

## Expected result

The IoC container passes a value of resolved Promise.

**Comment by Romakita** [comment]
Hello @derevnjuk 
This is not a bug. Async factory cannot depend on another async factory because the invoke method is synchronous. Unfortunatly changing that will be a breaking change if the DI is used manually. I’ll try to take a time to propose an improvment on it and maybe introduce that for v7.

**Comment by Romakita** [comment]
With v6 you can do that:

```typescript
import { InjectorService, registerProvider } from '@tsed/di';
import { ok } from 'assert';

registerProvider({
  provide: 'async_provider_1',
  async useAsyncFactory(): Promise<unknown> {
    return {};
  }
});

registerProvider({
  provide: 'async_provider_2',
  deps: ['async_provider_1'],
  async useAsyncFactory(asyncProvider1: Promise<unknown>): Promise<unknown> {
    const dep = await asyncProvider1

    return {};
  }
});

const injector = new InjectorService();

await injector.load(); 
```

**Comment by derevnjuk** [comment]
Yeah, that's what I use to bypass these limitations) Thanks 👍🏾

**Comment by Romakita** [comment]
I found solution. Release is on going :D
