### ISSUE TITLE
[BUG] Inheritance not working with @UseAuth 

### ISSUE THREAD

**Issue by sidharthv96** [TypedProject/ts-express-decorators#1535]
## Information

- **Version:** 6.70.1
- Packages: 
```json
    "@tsed/ajv": "^6.70.1",
    "@tsed/common": "^6.70.1",
    "@tsed/core": "^6.70.1",
    "@tsed/di": "^6.70.1",
    "@tsed/exceptions": "^6.70.1",
    "@tsed/json-mapper": "^6.70.1",
    "@tsed/mongoose": "^6.70.1",
    "@tsed/platform-express": "^6.70.1",
    "@tsed/schema": "^6.70.1",
    "@tsed/swagger": "^6.70.1",
```

I tried to implement inheritance as mentioned in https://tsed.io/docs/controllers.html#inheritance, but it won't work when `@UseAuth` decorator is used.

Will have routes from BaseController
```ts
@Controller("/parent")
export abstract class ChildController extends BaseController {
```

Will **not** have routes from BaseController
```ts
@Controller("/parent")
@UseAuth(UserAuthMiddleware)
export abstract class ChildController extends BaseController {
```

## Acceptance criteria

- [ ] Base routes should be available even when using `@UseAuth` Decorator

**Comment by sidharthv96** [comment]
```ts
@Controller({
  path: "/parent",
  middlewares: {
    use: [UserAuthMiddleware],
  },
})
```

This works as a temp fix.

**Comment by sidharthv96** [comment]
Repro: https://github.com/sidharthv96/tsed1535

**Comment by Romakita** [comment]
Fixed by this pr https://github.com/tsedio/tsed/pull/1545

**Comment by sidharthv96** [comment]
Thanks a ton @Romakita !!
