### ISSUE TITLE
[BUG] Header decorator value overwrites PlatformResponse headers

### ISSUE THREAD

**Issue by dgrdl** [TypedProject/ts-express-decorators#1537]
## Information

- **Version:** 6.70.1
- Packages: schema

Hi, I am running into an issue while trying to use the Headers decorator to document a response header that is created dynamically. Since the value property of the decorator only takes static values, I am trying to set the response header manually inside the controller method, but it seems to get overwritten at a later point and always returns `undefined`. When I remove the header decorator completely, the functionality is correct, but it will not create an entry in the OpenApi spec.

## Example

```typescript
@Post("/")
@Summary("Create a new xxx")
@(Returns(201, MyModel).Headers({
  Location: {
    description: "URL to the new xxx",
    type: "string"
  }
}))
async create(
  @BodyParams() @Groups("creation") foo: MyModel,
  @Res() response: PlatformResponse
): Promise<MyModel> {
  const model = await this.service.create({data: foo});
  
  // location header is "undefined"
  response.setHeader("Location", `/v1/foo/${model.id}`);
  
  return model;
}
```

## Acceptance criteria

- [ ] PlatformResponse values should take precedence over Header / Headers decorator values.

**Comment by Romakita** [comment]
Thanks for the issue @dgrdl 
The problem is here: https://github.com/tsedio/tsed/blob/production/packages/platform/common/src/utils/setResponseHeaders.ts#L5

But the fix isn't simple. We need to know if the header is already set dynamically from the endpoint...
If you have an idea,  tell me :)?

See you
Romain
