### ISSUE TITLE
Mikro-ORM support

### ISSUE THREAD

**Issue by wguerram** [TypedProject/ts-express-decorators#1547]
## Informations
**Is your feature request related to a problem? Please describe.**

Mikro-ORM support

**Describe the solution you'd like**

Is there a way to use Mikro-ORM instead of TypeORM?

**Describe alternatives you've considered**

I'm just looking a framework and got here because of Koa support, I've not tried tsed yet but before jumping in I realized Mikro-ORM is not listed in the documentation.

## Acceptance criteria

- [ ] Mikro-ORM Support

**Comment by Romakita** [comment]
Hello @wguerram 
Basically, there is no needs to create a dedicated package to support an ORM with Ts.ED since the asyncFactory exists.

https://tsed.io/docs/custom-providers.html#use-factory

Here is an example with this ORM:



```typescript
import {Configuration, registerProvider} from "@tsed/di";
import MicroORM from "mikro-orm";

export const CONNECTION = Symbol.for("CONNECTION");

registerProvider({
  provide: CONNECTION,
  deps: [Configuration],
  async useAsyncFactory(settings: Configuration) {
    const options = settings.get("mikroORM");
    return MikroORM.init(options);
  }
});

```

```typescript
import {Inject} from "@tsed/di";
import {promisify} from "utils";
import MicroORM from "mikro-orm";

const create = promisify(RequestContext.create)

@Middleware()
export class RequestContextMiddleware {
   @Inject(CONNECTION)
   protected orm: ReturnType<typeof MikroORM.init>;

   async use(){
     await create(this.orm.em);
   }
}
```

Then:
```typescript
import {Configuration} from "@tsed/di";
import {PlatformApplication} from "@tsed/common";
import "./services/Connection.ts";

@Configurtion({
   mikroORM: {  
     entities: [Author, Book, BookTag],  
     dbName: 'my-db-name',  type: 'mongo', // one of `mongo` | `mysql` | `mariadb` | `postgresql` | `sqlite` 
     clientUrl: '...', // defaults to 'mongodb://localhost:27017' for mongodb driver
   }
})
export class Server {
   @Inject()
   app: PlatformApplication;

   $beforeRoutesInit() {
      this.app.use(RequestContextMiddleware);
   }
}
```
You can start with this example. Tell me if you have any question or issue ;)

If an official support is required, we can try to develop a premium module like @tsed/prisma to sponsoring the development or a you or a contributor can make a PR on the Ts.ED repository :)

See you
Romain

**Comment by rizchaerul** [comment]
Hi, I'm new to Ts.ED and trying to use Mikro-ORM. Can you tell me on which file to put all the code that you wrote? Thanks.

**Comment by Romakita** [comment]
@rizchaerul You have to create one file per examples:

- Connection.ts
- RequestContextMiddleware.ts

then import files with an ES6 import in Server.ts like is described in the last example.

**Comment by rizchaerul** [comment]
Thanks, right now I'm having trouble with the middleware. Where do i get the orm instance and promisify?
![image](https://user-images.githubusercontent.com/72289631/142025861-902ad206-7ea4-4b59-871d-a67e71722780.png)

**Comment by Romakita** [comment]
From « util ». It’s a basic nodejs function. It’s described in my example ;)

import {promisify} from "utils"

**Comment by rizchaerul** [comment]
Yeah sorry my bad. It showed an error on the import statement before, so i removed it. But it solved now.

One more thing though, where do i get the `orm.em`  from?

**Comment by Romakita** [comment]
Ho sorry, I just copied the code example from MikroORM but I realize, isn't clear:

```typescript
import {promisify} from "utils"

const create = promisify(RequestContext.create)

@Middleware()
export class RequestContextMiddleware {
   @Inject(CONNECTION)
   protected orm:  /* the typeof of returned value from  MikroORM.init */
   
   async use(){
     await create(this.orm.em);
   }
}
```

See you,
Romain

**Comment by rizchaerul** [comment]
Thank you! You really helped me out.
