### ISSUE TITLE
TypeError 'isHeadersSent'

### ISSUE THREAD

**Issue by jpc-dnr** [TypedProject/ts-express-decorators#1550]
**Version:** 6.72.2

We regularly encounter an exception like this:

```
TypeError: Cannot read property 'isHeadersSent' of undefined
    at PlatformExpressHandler.onError (/app/node_modules/@tsed/common/lib/index.js:978:27)
    at /app/node_modules/@tsed/common/lib/index.js:962:21
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

For information, we just migrated from version 6.43.3 to 6.72.2.

Is this something someone has already seen? What can be the root cause of this error?

Thanks!

**Comment by Romakita** [comment]
Hello @jpc-dnr 
this error occurs when an handler send headers after the response... If I look the code, you have an error caught by the onCtxRequest method, but the response is already sent to the client.

here is the code:

```typescript
import {HandlerMetadata, HandlerType, OnRequestOptions, PlatformHandler} from "@tsed/common";

export class PlatformExpressHandler extends PlatformHandler {
  protected createRawHandler(metadata: HandlerMetadata): Function {
    if (metadata.type === HandlerType.ERR_MIDDLEWARE) {
      const handler = this.compileHandler(metadata);
      return async (err: any, req: any, res: any, next: any) =>
        handler({
          err,
          next,
          $ctx: req.$ctx
        });
    }

    return super.createRawHandler(metadata);
  }

  protected async onCtxRequest(requestOptions: OnRequestOptions): Promise<any> {
    try {
      return await super.onCtxRequest(requestOptions);
    } catch (er) {
      return this.onError(er, requestOptions);
    }
  }
}
```
Are you able to reproduce the bug? Can you add a log in the compiled js (node_modules/@tsed/platform-express) here:
```typescript
    try {
      return await super.onCtxRequest(requestOptions);
    } catch (er) {
console.log(er)
      return this.onError(er, requestOptions);
    }
```
I'll try to secure the code and gives more information in dev mode to understand where come from the error.

See you
Romain

**Comment by jpc-dnr** [comment]
Hi,

Thank you for the explanation.
We encountered this error many times yesterday but today it is impossible to reproduce :/
We added some console.log as advised so we should be able to investigate more if the error happens again.

Thanks!

**Comment by Romakita** [comment]
@jpc-dnr A release is on going. It add a detailed log.warn:
https://github.com/tsedio/tsed/pull/1554/files

You should be able to track this issue with a kibana/logentries or something else ;)

See you
Romain

**Comment by jpc-dnr** [comment]
Oh thank you for that! I will try with this new release
