### ISSUE TITLE
Support for nestjs-like folder architecture

### ISSUE THREAD

**Issue by AlexandrosMelissas** [TypedProject/ts-express-decorators#1558]
## Informations
**Is your feature request related to a problem? Please describe.**
Due to scalability issues, i always use a folder architecture similar to NestJs. 

**Describe the solution you'd like**
I would like, when creating a ts ed project via cli, to have an option for a different folder architecture similar to NestJs

**Describe alternatives you've considered**
Maybe if we could change it after the code/folder generation

**Comment by Romakita** [comment]
Hello @AlexandrosMelissas 
Can you describe the folder architecture pls.

but your are free to chnge the folder tree as your conveniente. It’s not really importante for Ts.ED ^^

see you

**Comment by AlexandrosMelissas** [comment]
I'ts not very convenient to change the architecture since generating controllers, services etc becomes a pain. Τhe architecture looks like this. Each "module" has services, controllers, etc inside of it. 

![image](https://user-images.githubusercontent.com/56912034/136004820-be58a14f-6faf-4745-972d-1ee9700c9188.png)

**Comment by Romakita** [comment]
ha ok it's feature approach. And the command try to use controllers/services depending of the provider type. Ok, I think, it's possible to disable the subpath via an option ^^
