### ISSUE TITLE
Is Discriminator working properly?

### ISSUE THREAD

**Issue by alexdonh** [TypedProject/ts-express-decorators#1568]
## Information

- **Version:** 6.x (reproducible on latest 6.73.6)
- Packages: @tsed/mongoose

When I follow Discriminator guide on the documentation, I got confused because it doesn't seem to work as I expected.

## Example

```typescript
// First, have some models

@Model({ name: "events" })
class EventModel {
  @ObjectID()
  _id: string;

  @Required()
  time: Date = new Date();

  @DiscriminatorKey()
  type: string;
}

@Model({ discriminatorValue: "clicked" })
class ClickedLinkEventModel extends EventModel {
  @Required()
  url: string;
}

// Next, have a repository class
@Injectable()
export class ClickedLinkEventRepository {
  @Inject(ClickedLinkEventModel) private model: MongooseModel<ClickedLinkEventModel>;

  // and some methods for CRUD
}

// Then inject the repository in a controller and start inserting some data

```

## Expected

- [ ] Collection `events` created
- [ ] Data inserted into this collection
- [ ] `type` field automatically filled with "clicked" - the discriminator value

## Observed

- [ ] Collection `clickedlinkeventmodels` created
- [ ] Data inserted into this collection
- [ ] No `type`

## Findings

In [utils/createSchema.ts](https://github.com/tsedio/tsed/blob/production/packages/orm/mongoose/src/utils/createSchema.ts) it seems that when `createModel` function gets called, somehow `ancestorModel` is undefined (not registered).

## Workaround

In the repository class, if I use

```
@Injectable({
  deps: [EventModel] // this forces the parent model class to load first
})
```

Then `ancestorModel` is available and it works as expected. This applies for any injectable class. As long as the parent model class gets registered before it will work.

**Comment by Romakita** [comment]
Hello @alexdonh 

Can you produce a repository example please. I don't use discriminator and I don't understand exactly the goal of this mongoose feature. 

See you
Romain

**Comment by alexdonh** [comment]
@Romakita here you go https://github.com/alexdonh/tsed-sample-discriminator

Please have a look into `PostControler` and also `Repository` classes in `services`

**Comment by alexdonh** [comment]
Basically discriminator enables you to have multiple models with overlapping schemas on top of the same underlying MongoDB collection.

Imagine you have a set of users

```
class UserModel {
  id: string;
}

class BasicAuthUserModel extends UserModel {
  username: string;
  password: string;
}

class TokenUserModel extends UserModel {
  token: string;
}
```

you want to have they all stored in the same database collection namedly `users` like this

```
{ "_id": ObjectId(...), "type": "basicAuth", "username": "hello",  "password": "world" }
{ "_id": ObjectId(...), "type": "token", "token": "this is a token" }  
```

**Comment by alexdonh** [comment]
@Romakita I updated the sample to latest version but it doesnt seem to fix the issue. What am I missing here? FYI the sample is here https://github.com/alexdonh/tsed-sample-discriminator

**Comment by Romakita** [comment]
Hello @alexdonh 
you example is to huge. So I created a new project example based on the official documentation:
https://github.com/Romakita/tsed-example-discriminator

You can compare my example with your example. For me the problem is fixed. Field type is correctly displayed in the response:

<img width="1072" alt="Capture d’écran 2021-10-15 à 10 04 41" src="https://user-images.githubusercontent.com/1763311/137453828-1119aac1-ab9b-4107-8c81-a84ed9202b56.png">

See you
Romain

**Comment by Romakita** [comment]
Also type have been correctly filled in the database before fix. The type field wasn't declared as a serializable property. I fixed that part there. Everything else was working as expected at mongoose level.

**Comment by alexdonh** [comment]
Please check out my fork of your repo then you will understand what I am trying to express.
https://github.com/alexdonh/tsed-example-discriminator

**Comment by alexdonh** [comment]
You dont event need to run any controller action. Just `yarn start` my repo you will notice in mongodb it creates multiple collections for the models. discriminator apparently doesnt apply.

**Comment by Romakita** [comment]
@alexdonh I created a simple repository and it works. Compare my example with your example pls.

see you
Romain

**Comment by Romakita** [comment]
Ok... The bug isn't on discriminator itself but only when the EventModel isn't injected into another class. 
Right now, the workaround is just to inject the model in a the repository.

I'll try to understand why the injection change the behavior.

See you
Romain

**Comment by Romakita** [comment]
Ok the injector order have an effect to:

works:
```typescript
  @Inject(EventModel) private eventModel: MongooseModel<EventModel>;
  @Inject(ClickedLinkEventModel) private clickedLinkEventModelModel: MongooseModel<ClickedLinkEventModel>;
  @Inject(SignedUpEventModel) private signedUpEventModelModel: MongooseModel<SignedUpEventModel>;
```

doesn't works:
```typescript
  @Inject(ClickedLinkEventModel) private clickedLinkEventModelModel: MongooseModel<ClickedLinkEventModel>;
  @Inject(SignedUpEventModel) private signedUpEventModelModel: MongooseModel<SignedUpEventModel>;
  @Inject(EventModel) private eventModel: MongooseModel<EventModel>;
```
O_o

**Comment by Romakita** [comment]
Ok got it !
