### ISSUE TITLE
pnpm support

### ISSUE THREAD

**Issue by tripodsgames** [TypedProject/ts-express-decorators#1574]
## Informations
**Is your feature request related to a problem? Please describe.**
In all my projects i started using pnpm, i love the shared node_modules and the speed of pnpm.

**Describe the solution you'd like**
Add pnpm to supported package managers

## Acceptance criteria
- [x] pnpm support.

**Comment by Romakita** [comment]
Hello @tripodsgames 

There is a special thing to know about PNPM?

The code responsible to install dependencies with a specific Package manager is here:
https://github.com/tsedio/tsed-cli/blob/master/packages/cli-core/src/services/ProjectPackageJson.ts#L305

We need to update the prompt:
https://github.com/tsedio/tsed-cli/blob/master/packages/cli/src/services/Features.ts#L455

And add information to InitCmd:
https://github.com/tsedio/tsed-cli/blob/master/packages/cli/src/commands/init/InitCmd.ts#L123

See you
Romain

**Comment by tripodsgames** [comment]
> Hello @tripodsgames
> 
> There is a special thing to know about PNPM?

Yes, it creates a non-flat node_modules

See: https://pnpm.io/motivation and https://pnpm.io/faq

I can make a pull request to add support for it, actually I'm already using it, works as expected

**Comment by tripodsgames** [comment]
Pnpm support was added via https://github.com/tsedio/tsed-cli/releases/tag/v3.13.0
