### ISSUE TITLE
[Doc] Add Serverless documentation page based on the platform/serverless/readme.md

### ISSUE THREAD

**Issue by Romakita** [TypedProject/ts-express-decorators#1575]
# Information

The new serverless package is available on NPM but there is not page on our website.

See readme package here:
 https://github.com/tsedio/tsed/tree/production/packages/platform/platform-serverless

The goal is to add a new page in the website dedicated on Serverless framework.

## Steps

-  Create the new markdown file `serverless.md` here https://github.com/tsedio/tsed/tree/production/docs/tutorials (use aws.md as example
- Get content from the actual readme.  https://github.com/tsedio/tsed/tree/production/packages/platform/platform-serverless
- Add menu entry here to update website menu: 
   - https://github.com/tsedio/tsed/blob/production/docs/.vuepress/config.js#L235
   - https://github.com/tsedio/tsed/blob/production/docs/.vuepress/config.js#L374
   - https://github.com/tsedio/tsed/blob/production/docs/.vuepress/config.js#L408
- Add serverless badge to the home page: https://github.com/tsedio/tsed/edit/production/docs/readme.md  Line: 191 

Make the PR when it's ready :)

Note: to start the website locally. Run `npm run vuepress:serve` inside '/docs' directory where this package.json is located https://github.com/tsedio/tsed/blob/production/docs/package.json

**Comment by vishal-codes** [comment]
can I try this?

**Comment by Romakita** [comment]
Sorry @vishal-codes 

@loic5 is already assigned on this issue.

See you
Romain

**Comment by vishal-codes** [comment]
> Sorry @vishal-codes
> 
> @loic5 is already assigned on this issue.
> 
> See you Romain

np
