### ISSUE TITLE
embedded mongodb models

### ISSUE THREAD

**Issue by VinzSpring** [TypedProject/ts-express-decorators#1576]
## Informations
With mongoose it is possible to [embed documents into another document for performance reasons ](https://docs.mongodb.com/manual/tutorial/model-embedded-one-to-many-relationships-between-documents/).
I have not figured out how to do this using the ts.ED decorators.

It would be really handy if there were a decorator which could be used to describe such a document relationship.
```
@Model
class BlogEntryModel {
...
@Embedded(CommentModel)
private comments: Embeddable<CommentModel>[];
...
}

```
I know about the possibility of using plain mongoose models, however that's very unsatisfactory.

## Acceptance criteria

- there must be a possibility to embedd documents into other models
- the decorator should work similar to `@Ref`

**Comment by Romakita** [comment]
Hello @VinzSpring 
I think you just need to use `@CollectionOf` and @MongooseSchema decorators to create sub document. In your link, there is no speciale things to do to create sub document. Also the link refere to mongo and not mongoose.
Give me a valid mongoose example if the CollectionOf/MongooseSchela doesn’t works for you.
See you
