### ISSUE TITLE
[BUG] Page Session & cookies - /tutorials/session

### ISSUE THREAD

**Issue by sidharthv96** [TypedProject/ts-express-decorators#1581]
> Note Since version 1.5.0, the cookie-parser middleware no longer needs to be used for this module to work. This module now directly reads and writes cookies on req/res. Using cookie-parser may result in issues if the secret is not the same between this module and cookie-parser.

https://github.com/expressjs/session#sessionoptions

So should the cookieParser option be removed from the middlewares in the example page?

**Comment by sidharthv96** [comment]
body-parser is also deprecated in latest express versions right?
express.json() is what I'm using in Express 4.16+.

**Comment by Romakita** [comment]
Hello @sidharthv96 

> So should the cookieParser option be removed from the middlewares in the example page?
I didn't known that ^^. You can edit the documentation, If you have a time to do it ;)

> body-parser is also deprecated in latest express versions right?
Where have you seen that? There is not mention of that in the npm module page: https://www.npmjs.com/package/body-parser

See you
Romain

**Comment by Romakita** [comment]
## req.body

Contains key-value pairs of data submitted in the request body. By default, it is undefined, and is populated when you use body-parsing middleware such as express.json() or express.urlencoded().

The following example shows how to use body-parsing middleware to populate req.body.


Ok. But use body-parser is correct :)
