### ISSUE TITLE
[BUG] Session Setting values direcly doesn't work

### ISSUE THREAD

**Issue by sidharthv96** [TypedProject/ts-express-decorators#1582]
```
@Post("/login")
  @Returns(204)
  login(@BodyParams("name") name: string, @Session("username") username: string) {
    username = name;
  }
```

Assigning directly to a variable doesn't work.

Is this the intended behavior?
If so, I think we should add it in the documentation and make it clear.

**Comment by Romakita** [comment]
… it’s a basic javascript issue. Assign value to an input parameter won’t be visible from the caller. I don’t need to write that in the documentation ^^

But I agree, the document haven’t an explicite example to set value in session

the solution:

UpdateSession(@Session() session: any)  {
   session.user = 1
}

**Comment by sidharthv96** [comment]
Yup, I've been using the session directly.
 Just wanted to point out that an example might be useful. 😄

**Comment by Romakita** [comment]
Totally agree ;)
