### ISSUE TITLE
[BUG] Properties without @Required are set as undefined if any property is decorated with @Required in the same class

### ISSUE THREAD

**Issue by yusufsamsudeen** [TypedProject/ts-express-decorators#1586]
## Information

Given a class with several ``` @Required ```  fields only these fields get mapped from request

- **Version:** 6.75.0
- **Version:** 6.59.2

## Example

```
export class UserProfileDTO{
    id: number
    @Required()
    firstName: string
    @Required()
    lastName: string
    dateOfBirth: string
}

```
Only the fields with ```@Required``` get mapped during request the rest are set as ```undefined```

**Comment by Romakita** [comment]
It's not a bug. This is the intended behavior. You have to add `@Property` at least on all properties or add `@AdditionalProperties(true)` on class to work. 
Read the documentation here please: https://tsed.io/docs/model.html#example

<img width="909" alt="Capture d’écran 2021-10-18 à 07 42 54" src="https://user-images.githubusercontent.com/1763311/137675198-3c3bba6a-69c1-4f05-8982-ccdee31c87a9.png">

See you
Romain
