### ISSUE TITLE
[BUG] API freezes when input body payload is greater than 100kb

### ISSUE THREAD

**Issue by ashprojects** [TypedProject/ts-express-decorators#1598]
## Information

- **Version:** 5.45
I have following handlers in app in Server.ts:
```
$beforeRoutesInit():` void {
    this.app
      .use(cors())
      .use(cookieParser())
      .use(compressExceptCached())
      .use(methodOverride())
      .use(bodyParser.json())
      .use(
        bodyParser.urlencoded({
          extended: true
        })
      );
  }
```
When API payload of size > 100kb is received, there is no exception thrown and API is just stuck.
We can solve this by using limit in bodyParser.json as:
```
bodyParser.json({
    limit: "10mb"
  });
  ```

but the point is, API should throw some error.

**Comment by Romakita** [comment]
Hello @ashprojects 
Well, If the bodyParser doesn't throw an error, I won't be able to do something...

Give a pure express usecase that emit an error when the bodyParser.json emit an error when the size is exceeded ... And I'll inspect your issue.

See you
Romain
