### ISSUE TITLE
[BUG] BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'

### ISSUE THREAD

**Issue by lgmf** [TypedProject/ts-express-decorators#1604]
## Information

- **Version:** 6.x
- Packages: 
 "@tsed/testing-mongoose": "^6.62.0",

The test fails when using an aggregation pipeline on an update function

## Example

```
class SomeRepository {
  @Inject(SomeModel)
  private readonly model: MongooseModel<SomeModel>;
  
  update(id, patch) {
    return this.model.updateOne([
       { $match: { id } },
       { $set: patch }
    ]);
  }
}
```

## Acceptance criteria

- [ ] Should be able to test updates with aggregation pipelines

**Comment by Romakita** [comment]
Hello @lgmf 
I don’t know how I can help you. @tsed/testing-mongoose wrap mongodb-memory-server without additional things. 

So the only solution is to reproduce the bug with a pure mongoose code.

another point is: your issue title is not really aligned with the issue description. I’m not sure if your issue is about a deserialization or an issue about mongodb-memory-server.

please clarify your issue. 
see you

**Comment by lgmf** [comment]
Sorry about the description

The problem happens when I'm testing my endpoint using `import {TestMongooseContext} from "@tsed/testing-mongoose";`

When running the application with MongoDB version 4.4.10 my code works, but in the test environment, it doesn't.

Basically, I have a repository that executes a find and replaces operation on a string property using the aggregate operator `$replaceAll`

```
async function findAndReplaceRecords(id: string, propName: string, payload: { find: string; replace: string }) {
  const doc = await this.getDocumentById(id);

  const { find, replace } = payload;

  const pipeline = [
    {
      $set: {
        records: {
          $map: {
            input: "$records",
            as: "record",
            in: {
              $mergeObjects: [
                "$$record",
                {
                  [propName]: {
                    $replaceAll: {
                      input: `$$record.${propName}`,
                      find,
                      replacement: replace
                    }
                  }
                }
              ]
            }
          }
        }
      }
    }
  ];

  return doc.updateOne(pipeline);
}
```

**Comment by Romakita** [comment]
Ok the problem is related to mongodb-memory-server repository. Open an issue on his repo. I won’t be able to help you. Sorry.

Romain

**Comment by lgmf** [comment]
Ok. Thanks for the help
