### ISSUE TITLE
[BUG] DeepClone Maximum Call Stack Exceeded Exception

### ISSUE THREAD

**Issue by schnelldigital** [TypedProject/ts-express-decorators#1619]
## Information

- **Version:** 6.73.8
- Packages:     "@tsed/ajv": "6.73.8",
    "@tsed/common": "6.73.8",
    "@tsed/core": "6.73.8",
    "@tsed/di": "6.73.8",
    "@tsed/exceptions": "6.73.8",
    "@tsed/json-mapper": "6.73.8",
    "@tsed/mongoose": "6.73.8",
    "@tsed/platform-express": "6.73.8",
    "@tsed/schema": "6.73.8",
    "@tsed/socketio": "6.73.8",
    "@tsed/swagger": "6.73.8"

Sporadically, a maximum call stack exceeded exception is encountered on a post or put event when using Multer (in this case with MinIO-S3 client). There are days, where this exception never occurs, but on others several times, where only a restart of the complete application can help.

According to the log in, this occurs as follows:
name: 'RangeError',
    message: 'Maximum call stack size exceeded',
    status: 500,
    errors: [],
    stack: 'RangeError: Maximum call stack size exceeded\n' +
      '    at deepClone (./node_modules/@tsed/core/src/utils/objects/deepClone.ts:14:17)\n' +
      '    at deepClone (./node_modules/@tsed/core/src/utils/objects/deepClone.ts:33:21)\n' +

(the last line will continue for several times...)

The request is just a simple POST with a few headers (Authorization token and several other with 40 to 60 bytes in length. The file content, which is transferred via Multer is about 200-300 Bytes in length. 

I don't call the deepClone function by myself, which means, there has to be a specific part in tsed/core, which calls this function and maybe tries to clone a (corrupt?) object from Multer.

I was looking into the deepClone function but couldn't find any suspicious, according to this I am unfortunately not able to narrow down the source of the error more exactly.

## Acceptance criteria

- [ ] Call a POST/PUT with Multer without crashing due to this exception

**Comment by Romakita** [comment]
Hello @schnell-technology 

Have you a minimal reproducible repository ? Based on your information, I'm not able to find a reason to have maximumCall stack sporadically.

See you
Romain

**Comment by Romakita** [comment]
@schnell-technology 
I worked on this PR to avoid circular ref issue: https://github.com/tsedio/tsed/pull/1620

I also added a env variable TSED_TRACK_CIRCULAR_REF to print a trace when a circular ref is detected. it would be nice if you gave me to activate this variable so that we know where the call that is causing your problem is coming from :)

I'll release the fix today !

See you
Romain

**Comment by Romakita** [comment]
@schnell-technology  Can you confirm that the fix solve your issue please ?

**Comment by Romakita** [comment]
@schnell-technology  Can you confirm that the fix solve your issue please ?

**Comment by schnelldigital** [comment]
Hi Romakita,

thank you for your fast response and fix.
The last day, this error didn't occur, it seems very promising.
I'll test it the next few days further more with your given environment-variable and give you a response.

Thank you very much!

**Comment by schnelldigital** [comment]
Hi Romakita,

after the last days, this error didn't occured and no anomalities in the output/logs could be found. 
This ticket will no be closed.
Thank you for your support and have a nice day.

See you
Patrick
