### ISSUE TITLE
[BUG] DataTypeNotSupportedError: Data type "Object" in "Product.type" is not supported by "mysql" database.

### ISSUE THREAD

**Issue by thanhchuongbmd** [TypedProject/ts-express-decorators#1629]
## Information

- **Version:** 6.x
- Packages: 
    "@tsed/ajv": "^6.79.1",
    "@tsed/common": "^6.79.1",
    "@tsed/core": "^6.79.1",
    "@tsed/di": "^6.79.1",
    "@tsed/exceptions": "^6.79.1",
    "@tsed/json-mapper": "^6.79.1",
    "@tsed/platform-express": "^6.79.1",
    "@tsed/schema": "^6.79.1",
    "@tsed/swagger": "^6.79.1",
    "@tsed/typeorm": "^6.79.1",
    "typeorm": "^0.2.39"

## Example

```
My config typeorm

const typeormConfig: MysqlConnectionOptions = {
    type: 'mysql',
    host: process.env.DATABASE_HOST,
    port: +process.env.DATABASE_PORT,
    username: process.env.DATABASE_USERNAME,
    password: process.env.DATABASE_PASSWORD,
    database: process.env.DATABASE_NAME,
    bigNumberStrings: false,
    name: "default",
    synchronize: true,
    entities: [`${__dirname}/src/entity/*{.ts,.js}`],
    migrations: [`${__dirname}/src/migrations/*{.ts,.js}`],
    subscribers: [`${__dirname}/src/subscriber/*{.ts,.js}`],
    logging: process.env.IS_DEV == 'true'
}

```

## Acceptance criteria

- [ ] Criteria 1

**Comment by Romakita** [comment]
Hello @thanhchuongbmd 

this issue is related to typeorm project. Open an issue on his repo please.

see you
Romain
