### ISSUE TITLE
[BUG] QueryParams validation doesn't work as expected

### ISSUE THREAD

**Issue by rizchaerul** [TypedProject/ts-express-decorators#1643]
## Information

- **Version:** 6.85.0

Hi, when I insert two query with the same key such as q=1&q=2, the q variable in the get() method becomes an array. Is this the right behavior? If it is, then what should I do to make sure that the query is not an array.

Thank you.

## Example
![image](https://user-images.githubusercontent.com/72289631/142709557-cd6b3f57-2e6d-48d2-bd9b-70340646bdfb.png)

**Comment by Romakita** [comment]
Hello @rizchaerul 

it’s not a bug. It’s a part of official spec about the query params parsing (querystring node module).
If you have @tsed/ajv, it should emit a bad request.

see you
Romain

**Comment by rizchaerul** [comment]
I see, do I also have to install ajv, alongside @tsed/ajv?

**Comment by Romakita** [comment]
Avj is installed with @tsed/ajv
