### ISSUE TITLE
[FEAT] Allow using a custom token with `@Injectable` decorator

### ISSUE THREAD

**Issue by derevnjuk** [TypedProject/ts-express-decorators#1695]
## Informations

As a user, I would like to have a convenient way to override an injection token, that is needed to resolve an instance, using the `@Injectable` decorator. A token may be either a string, a symbol, a class constructor.
 

```ts
@Injectable({ provide: 'foo' })
class Foo {}

const injector = new InjectorService()

await injector.load()
        
const foo = injector.get<Foo>('foo')
```

**Comment by Romakita** [comment]
Sure, the decorator can be improved. The mechanism is here. The required change is here :)

https://github.com/tsedio/tsed/blob/production/packages/di/src/decorators/injectable.ts#L27
