### ISSUE TITLE
[BUG] Redis sessions start or not by URL

### ISSUE THREAD

**Issue by xantos008** [TypedProject/ts-express-decorators#1720]
Hey guys! Thank you for product, BUT...
In `app.ts`

` this.app.use(`
`  session({`
`        proxy: true,`
`        store: sessionConfig.store,`
`        secret: 'keyboard cat',`
`        resave: false,`
`        saveUninitialized: true,`
`        cookie: { secure: false }`
`      })`
`    );`

It happens always when any user makes any request. How to define store by url? Because with API I don't need to store any of session data.

UPD:
I solved it by middleware, but i don't think this was good.

**Comment by Romakita** [comment]
Hello,
This question must be addressed to the owner session middleware. But the middleware solution is the best approach.

see you
