### ISSUE TITLE
[QUESTION] Is @RequiredGroups able to adapt the swagger documentation ?

### ISSUE THREAD

**Issue by Grutula** [TypedProject/ts-express-decorators#1721]
## Information

- **Version:** 6.98.0
- Packages: tsed/schema && tsed/swagger

I try to use the RequiredGroups decorator in order to build a swagger doc with the "required" flag set only on `POST` endpoints but I failed to do this

Did I miss something ? Or is this decorator only useful for validation ?

## Example

```typescript
export class CustomRequest {
    @Required()
    @Property(String)
    a: string;

    @RequiredGroups("creation")
    @Property(String)
    b: string;

    @Groups("creation")
    @Property(String)
    c: string;
}
```

```typescript
import { AcceptMime, BodyParams, Controller } from "@tsed/common";
import { ContentType, Groups, Name, OperationId, Patch, Post, Returns } from "@tsed/schema";
import { CustomRequest } from "./Request";

@Controller("/test")
@Name("Test")
export class TestController {

    @Post("/1")
    @AcceptMime("application/json")
    @ContentType("application/json")
    @OperationId("Check Health 1")
    @Returns(204)
    async test1(@BodyParams() @Groups("creation") body: CustomRequest): Promise<void> {
        return undefined;
    }

    @Patch("/2")
    @AcceptMime("application/json")
    @ContentType("application/json")
    @OperationId("Check Health 1")
    @Returns(204)
    async test2(@BodyParams() @Groups("update") body: CustomRequest): Promise<void> {
        return undefined;
    }
}
```

## Expectation

I expect the property `b` to be marked as required in my `POST` route (as the `a` property).  

## Current Result

![image](https://user-images.githubusercontent.com/4665028/148997512-3fde7324-b796-411a-846b-1f0814f4856c.png)

**Comment by Romakita** [comment]
Hello @Grutula 
You’ve missed the required decorator:

export class CustomRequest {
    @Required()
    @Property(String)
    a: string;
 
    @Required(true)
    @RequiredGroups("creation")
    @Property(String)
    b: string;

    @Groups("creation")
    @Property(String)
    c: string;
}

see you

**Comment by Grutula** [comment]
Hello @Romakita 

Thank for your quick answer.  
Indeed it works now with this, thanks 💪
