### ISSUE TITLE
[BUG] Groups deserialization is not working with collection

### ISSUE THREAD

**Issue by Grutula** [TypedProject/ts-express-decorators#1723]
## Information

- **Version:** 6.98.0

`@Groups("group")` is used to omit some properties before accessing the controller (during the deserialization).  
But in my case it does not work with an array

## Example

```
import { deserialize } from "@tsed/json-mapper";
import { CollectionOf, Groups } from "@tsed/schema";

export class CustomRequest {
    @CollectionOf(String)
    @Groups("creation")
    a?: string[];

    @Groups("creation")
    b?: string;
}

const req = new CustomRequest();
req.a = ["a"];
req.b = "b";
const res = deserialize(req, { type: CustomRequest, groups: ["update"] });
console.log(JSON.stringify(res)); // {"a":["a"]}

```

**Comment by Romakita** [comment]
Hum your example is a bit strange? You create an object with the class and then you deserialize it?  why ?

**Comment by Grutula** [comment]
> Hum your example is a bit strange? You create an object with the class and then you deserialize it? why ?

Hum yes sorry if the example was confusing 😅  I was reading the documentation and just try to put less lines as possible to target my problem efficently 

```
import {deserialize} from "json-schema";

const result = deserialize({
  id: "id", // will be ignored because creation doesn't include `id` field
  firstName: "firstName",
  lastName: "lastName",
  email: "email@tsed.io",
  password: "password"
}, {type: User, groups: ['creation']});

console.log(result); // User {firstName, lastName, email, password}
```

But yes indeed it may be confusing because I didn't explain it and use an instance of my object directly

Thanks for you're release 🚀

**Comment by Romakita** [comment]
You’re welcome ;)
