### ISSUE TITLE
[BUG] Can't open playground with NODE_ENV=production

### ISSUE THREAD

**Issue by navalta3030** [TypedProject/ts-express-decorators#1743]
## Information

- **Version:** 6.95.9
- Packages: 

Can't view graphql playground when going into NODE_ENV=production

## Logs

```
[2022-01-29T03:03:33.174] [INFO ] [TSED] - Listen server on http://0.0.0.0:3000
[2022-01-29T03:03:33.174] [INFO ] [TSED] - [default] GraphQL server is available on http://0.0.0.0:3000/graphql
[2022-01-29T03:03:33.175] [INFO ] [TSED] - Started in 1299 ms +6ms
[2022-01-29T03:03:43.615] [INFO ] [TSED] - {
  reqId: 'ba8224853606480c96240e61648aeab3',
  method: 'GET',
  url: '/graphql',
  duration: 6,
  time: 2022-01-29T03:03:43.615Z,
  event: 'request.start'
}
[2022-01-29T03:03:43.632] [INFO ] [TSED] - {
  reqId: 'ba8224853606480c96240e61648aeab3',
  method: 'GET',
  url: '/graphql',
  duration: 23,
  time: 2022-01-29T03:03:43.632Z,
  event: 'request.end',
  status: 400
}
```

## Server.ts
```
@Configuration({
  mount: {
    "/health": "${rootDir}/controllers/**/*.ts"
  },
  componentsScan: [
    `${rootDir}/gql/**/*.ts` // add this pattern to scan resolvers or datasources
  ],
  typegraphql: {
    default: {
      path: "/graphql",
      playground: true
    }
  },
  rootDir,
  acceptMimes: ["application/json"],
  httpPort: process.env.PORT || 8083,
  httpsPort: false,
  typeorm: typeormConfig,
  exclude: ["**/*.spec.ts"]
})
```

run command : `yarn cross-env NODE_ENV=production node dist/index.js`

- [ ] be able to run playground on browser when performed the run command above.

**Comment by Romakita** [comment]
@navalta3030  Why did you have this:

 playground: process.env.PRODUCTION_ENVIRONEMNT !== "production"
 
 It's confusing. Because, you disable the playground in production, so the result is normal (to not have the playground).
 
 By the way, I found the issue :) Fix is going.

**Comment by navalta3030** [comment]
@Romakita - Sorry, I should have just changed that one to true on this issue. It's actually `true` on our staging platform. Thanks for taking a look into this! 

Edited the description to make it more understandable.
