### ISSUE TITLE
Class instanciation order

### ISSUE THREAD

**Issue by attilaorosz** [TypedProject/ts-express-decorators#1757]
Hi,

I'm not sure if it's really a bug or by design but I find it weird that the controllers are instanciated before the server itself.
I'm using version 6.101.0 and I observed that when I'm using direct controller mounting the controller constructor runs before the server constructor.

```
mount: {
  '/v1': [
    AuthController
  ]
}
``` 

This leads to some problems with DI, for example if I have a dependency in the controller it won't be resolved.

```
@Controller('/auth')
export class AuthController {
  constructor(private userLoginService: IUserLoginService) {
  }

  @Get('/login')
  async login() {
    const response = await this.userLoginService.storeUserLogin('asd', 'asd');
    return null;
  }
}
```

I'm providing the service in the server in the $beforeInit hook like this:

```
registerProvider({provide: IUserLoginService, useClass: MongoUserLoginService});
```
The results is `TypeError: this.userLoginService.storeUserLogin is not a function` when I call that endpoint.

This actually works completely fine if I provide it separately in the main.ts file before I call bootstrap but the problem is that I won't be able to access the entity manager from mikro-orm since that is only provided in the server configuration.

Is there a way to delay controller instanciation or I'm missing something?

Thanks in advance!

Edit: IUserLoginService is an abstract class not an interface :)

**Comment by Romakita** [comment]
@attilaorosz  just upgrade the Ts.ED version. This design was changed since v6.80+.

See you
Romain

**Comment by attilaorosz** [comment]
@Romakita thanks for the quick reply! However I’m using 6.101.0 already.

**Comment by Romakita** [comment]
Ha ok. But the server is instanciated before controllers… so I don’t understand your point…

**Comment by attilaorosz** [comment]
Thats what I thougt too buf if I add logging the order is 
1. Controller constructor
2. Server constructor
3. Constructor before init
4. Server before init

I’m bulding this in an nx monorepo with webpack build but I doubt that should affect this.

**Comment by Romakita** [comment]
Ok sorry. My bad. The platfotm adapter is build in first then services and finally the module. It’s not weird. The server depend on all services.

**Comment by attilaorosz** [comment]
It makes sense but is there a way then to make custom providers that depend on platform modules that register before the controllers?

**Comment by Romakita** [comment]
I’m not sure why your service is undefined, but use an abstract class as token provider isn’t a covered usecase. I think the injector is not able to link the correct class with the token. I’m not sure if that you to accomplish is correct or not. Also, I’m not sure what is the relation between the server built after controller and your problem.

**Comment by Romakita** [comment]
```typescript
@Controller('/auth')
export class AuthController {
  @Inject(IUserLoginService)
   private userLoginService: IUserLoginService

  @Get('/login')
  async login() {
    const response = await this.userLoginService.storeUserLogin('asd', 'asd');
    return null;
  }
}
```

**Comment by Romakita** [comment]
PlatformModule?

**Comment by attilaorosz** [comment]
If I do this it works fine it is resolved correctly.

```
registerProvider({provide: IUserLoginService, useClass: MongoUserLoginService});

    const platform = await PlatformExpress.bootstrap(
      Server,
      {
        port: 4444
      }
    )
```

If I do this then the service is undefined

```
@Configuration({
  imports: [MikroOrmModule],
  mount: {
    '/v1': [
      AuthController
    ]
  },
  mikroOrm: [
    {
      contextName: 'default',
      type: 'mongo',
      dbName: 'gg',
      entities: [UserLogin]
    }
  ]
})
export class Server implements BeforeInit {
  @Inject() app: PlatformApplication;
  @Configuration() settings: Configuration;

  constructor() {
    console.log('Server constructor');
  }

  $beforeInit(): void | Promise<any> {
    console.log('Server Before init');
    // Register application providers
    registerProvider({provide: IUserLoginService, useClass: MongoUserLoginService});
  }
}
```
Which what I found odd, since the "Load routes" hook is way after the server constructor.

**Comment by Romakita** [comment]
Heu ok… but it’s normal. All providers are already build. You can’t change the service during this hook and it’s not really logical to do that. Or you have a really good reason…

**Comment by attilaorosz** [comment]
My reason was to wait for the MikroOrm module to provide the entity manager service first, then provide my own service which depends on it. At least that's what seemed logical to me in terms of execution order but I might be wrong here.

**Comment by Romakita** [comment]
Ok maybe there a solution by using lazy loading injection.

**Comment by attilaorosz** [comment]
Is there a way to lazy load a module? That would basically solve these scenarios because i could then just provide my mounting in the module so everything is ready when that registers.

I did some additional testing and if I provide my service before bootstrapping, the controller resolves my class correctly and actually my service can inject the entity manager instance by using the @em decorator (which I still find a bit odd, maybe this gets injected for every request?). So that’s a workaround I guess. Feel free to close this if you feel like I’m beating the bush here for too long and this is actually working how it supposed to :)

I just wanted to understand the reason behind why it works/doesn’t work in my scenario.

Thanks again,
Attila

**Comment by Romakita** [comment]
Lazy loading a module or class is possible yes :)

You can see the usage here: https://tsed.io/docs/providers-lazy-loading.html#getting-started

It could be the right solution for you :)
See you
Romain
