### ISSUE TITLE
[DI/FEAT] Container configuration

### ISSUE THREAD

**Issue by Romakita** [TypedProject/ts-express-decorators#176]
## Informations

Type | Version
---|---
Improvement | 2.x

****

## Description
As a developer I want to manually configure services and controllers.

```typescript
import  { ServerSettings, ServerLoader, Env} from "ts-express-decorators";

const env = process.env.NODE_ENV

@ServerSettings({
    controllers: [
        MyController,  // will use the controller path
        {provider: MyController, useClass: MyController, path: "/rest"}, // custom configuration,
        {provider: MyController, useClass: MyController, paths: ["/rest", "v1"]}, // custom configuration
    ],
    components: [
        MyService,
        {provide: ValidationService, useClass: MyValidationService},
        {provide: GatewayService, useClass: env === Env.PROD ? GatewayProdService : GatewayDevService}
    ]
})
export class Server extends ServerLoader {}
```
## Acceptance criteria
- [x] Migrate all registry under Providers (globalRegistry).
  - [x] Filters
  - [x] Converters
  - [x] Middlewares
  - [x] Services & Factory
  - [x] Interceptors
  - [x] SocketService
  - [x] SocketMiddleware
  - [x] Controllers
- [x]  Refactoring code which use a global symbol (InjectorService, GlobalServerSettings, etc...). 
- [x] Move common/di to his own package `@tsed/di`.
- [x] Create container configuration and use it into the injector (instead of the global registry).
- [ ] Add configurations on ServerSettings.

**Comment by Romakita** [comment]
@lwallent , @Ionaru, @ : I need your feed back about this feature :) 

See you

**Comment by lwallent** [comment]
Hi @Romakita and @Ionaru

As I mentioned in my (lengthy) comment to the pull request (#174) my primary interest in this feature is for testing purposes as I like the dynamic approach. However I like the design and the readability of the aliases are especially welcome for new users of the framework! 👍 

What do you guys think of my bootstrapper builder pattern thoughts?

KR Lasse

**Comment by Romakita** [comment]
Cf. PR #174 

Additional proposal for this feature:
```typescript
import { bootstrap, cleanupServer } from "ts-express-decorators/testing";
before(bootstrap(Server, {
    controllers: [...],
    services: [...]
}));
after(cleanupServer);
```

**Comment by Romakita** [comment]
- [ ] Migrate all registry under Providers (globalRegistry).
- [ ] Create container configuration and use it into the injector (instead of the global registry).

**Comment by Romakita** [comment]
- [ ] Refactoring code which use a global symbol (InjectorService, GlobalServerSettings, etc...).
