### ISSUE TITLE
[BUG] TypeError: Cannot read properties of undefined (reading 'set') in PassportService.js

### ISSUE THREAD

**Issue by victorsmits** [TypedProject/ts-express-decorators#1765]
## Information

- **Version:** ^6.98.1

Hello, I encounter a weird issue with tsed passport and passport-discord. At random time my server crash and give me this error 
```log
TypeError: Cannot read properties of undefined (reading 'set')
```
![image](https://user-images.githubusercontent.com/22278315/153861805-a884cc8d-0a80-405a-85b5-a3741277c50a.png)

It seems appearing after the discord callback, but all other user encounter no issue. The only way I found to stop my server crashing with this error is by adding the following code after the server init.

```ts
process.on('uncaughtException', function (err) {
            console.log("UNCATCH ERROR")
            console.error(err);
        });
```

**Comment by Romakita** [comment]
Ok. It means the request is done before the response is sent. I’ll try to fix that
