### ISSUE TITLE
[BUG] DynamicRef serializes to `[object Object]`

### ISSUE THREAD

**Issue by ochrstn** [TypedProject/ts-express-decorators#1767]
## Information

- **Version:** 6.102.1
- Packages: mongoose

I can at least say that it worked in `5.59.2` (thats where I upgraded from 😅 )

## Example

for full example, see: https://github.com/ochrstn/tsed/blob/fix-dynamicref-serialize-object/packages/orm/mongoose/test/dynamicRef.integration.spec.ts

```ts
describe("DynamicRef Integration", () => {
  @Model()
  class ClickedLinkEventModel {
    @ObjectID("id")
    _id: string;

    @Required()
    url: string;
  }

  @Model()
  class SignedUpEventModel {
    @ObjectID("id")
    _id: string;

    @Required()
    user: string;
  }

  @Model()
  class EventModel {
    @ObjectID("id")
    _id: string;

    @DynamicRef("eventType")
    event: Ref<ClickedLinkEventModel | SignedUpEventModel>;

    @Enum("ClickedLinkEventModel", "SignedUpEventModel")
    eventType: "ClickedLinkEventModel" | "SignedUpEventModel";
  }

  beforeEach(TestMongooseContext.bootstrap(Server));
  afterEach(TestMongooseContext.clearDatabase);
  afterEach(TestMongooseContext.reset);

  it("should serialize", async () => {
    const EventRepository = TestMongooseContext.get<MongooseModel<EventModel>>(EventModel);
    const ClickedEventRepository = TestMongooseContext.get<MongooseModel<ClickedLinkEventModel>>(ClickedLinkEventModel);
    const SignedUpEventRepository = TestMongooseContext.get<MongooseModel<SignedUpEventModel>>(SignedUpEventModel);

    const clickedEvent = await new ClickedEventRepository({url: "https://www.tsed.io"}).save();
    const event1 = await new EventRepository({eventType: "ClickedLinkEventModel", event: clickedEvent}).save();
    expect(serialize(event1, {type: EventModel})).toStrictEqual({
      id: event1.id,
      eventType: "ClickedLinkEventModel",
      event: {id: clickedEvent.id, url: "https://www.tsed.io"}
    });
    // bug: event serializes to "[object Object]"

    const signedUpEvent = await new SignedUpEventRepository({user: "test"}).save();
    const event2 = await new EventRepository({eventType: "SignedUpEventModel", event: clickedEvent}).save();
    expect(serialize(event2, {type: EventModel})).toStrictEqual({
      id: event2.id,
      eventType: "SignedUpEventModel",
      event: {id: signedUpEvent.id, user: "test"}
    });
    // bug: event serializes to "[object Object]"
  });
});
```

## Acceptance criteria

- [ ] DynamicRef should serialize the (populated) object

**Comment by Romakita** [comment]
Hello @ochrstn 

I created a pr to fix this issue. But I'm not sure about the result:
https://github.com/tsedio/tsed/pull/1777

One thing that is strange, is about the `@Property(String)` used in th DynamicRef. This decorator wasn't added here for nothing. DynamicRef is specific kinf of Ref right ? So DymanicRef can return an object or a string, if the populare method is called or not.

Another things, is about the result. the id keep the _id. It's normal, because mongoose doesn't give a real class Object. and there is no metadata to retrieve the correct class according to the `type` field. So the question is, how it's work in v5 (I'm not sure that this point worked before or not).


See you
Romain

**Comment by ochrstn** [comment]
> I created a pr to fix this issue. But I'm not sure about the result:
> https://github.com/tsedio/tsed/pull/1777

Thanks for looking into it.

> DynamicRef is specific kinf of Ref right ? So DymanicRef can return an object or a string, if the populare method is called or not.

Correct

> Another things, is about the result. the id keep the _id. It's normal, because mongoose doesn't give a real class Object. and there is no metadata to retrieve the correct class according to the type field. So the question is, how it's work in v5 (I'm not sure that this point worked before or not).

I just tried that in the old version and (to my own surprise) it does work. `_id` of the dynamic reference serializes to `id`

**Comment by Romakita** [comment]
Arff… so I don’t why it doesn’t work as expected now…

**Comment by ochrstn** [comment]
I did some debugging and in v5.x the actual class behind the populated dynamic ref is known at this point:

https://github.com/tsedio/tsed/blob/4db4290f1e009f14bcfb5fc37f0fbc5503fcc90c/packages/mongoose/src/utils/createSchema.ts#L21

and therefore can be serialized correctly

**Comment by Romakita** [comment]
I don't know how is it possible... Mongoose doesn't return the class behind the object:

<img width="490" alt="Capture d’écran 2022-03-10 à 07 50 26" src="https://user-images.githubusercontent.com/1763311/157605334-145c6166-d53b-4bd5-9c68-8459296c997e.png">

In my capture, the EventModel is here, but we see that the event instance value isn't an instance of SignedUpEventRepository, but it's an object. I haven't metadata to infer correctly the model. If it's works in v5, it was probably a mistake...

**Comment by ochrstn** [comment]
How it works to my understanding in 5.x (not sure about my wording 😅 ):

When the `@Model()` get evaluated the `target` gets captured in the `target.prototype.serialize` closure. That function is then later called for serialization.

https://github.com/tsedio/tsed/blob/4db4290f1e009f14bcfb5fc37f0fbc5503fcc90c/packages/mongoose/src/utils/createSchema.ts#L17-L26

Like you said, the instance obtained by mongoose isn't an instance of the class but calling `this.converterService.serialize(mongooseResult)` calls the serialize function shown above which has the class information.

Where does the `serialize` function of then mongoose object come from? I thought from a custom transform function `toObject.transform` set on the schema (https://mongoosejs.com/docs/guide.html#toObject https://mongoosejs.com/docs/api.html#document_Document-toObject) but I couldn't find it in the code being used

**Comment by Romakita** [comment]
I finally found a better way to fix that :)

**Comment by Romakita** [comment]
Here is the PR: 
https://github.com/tsedio/tsed/pull/1777

using OnDeserialize and OnSerialize, it works and you retrieve the correct typings + the JSONSchema is aligned with the models declaration.

I'll merge it
Romain

**Comment by Romakita** [comment]
Sorry for the delay @ochrstn ;) this issue wasn't easy ^^
