### ISSUE TITLE
[BUG] @tsed/exception 6.102.4 does not install @tsed/core... 

### ISSUE THREAD

**Issue by belgattitude** [TypedProject/ts-express-decorators#1768]
## Information

Some peer-dependencies are missing in the `@tsed/exception` [6.102.4](https://www.npmjs.com/package/@tsed/exceptions/v/6.102.4) version.

I could track it down to this commit: 

https://github.com/tsedio/tsed/commit/babd289f05ef05e71342cad24580147df205d550#diff-8a4d8f6fa07ba09d2cf9fb1a773783ccf9f6cb428cb879f4fdd0bb9ad1e79238.

Not a big issue, but the exception package seems to use at least @tsed/di and @tsed/core (probably more). 

See here for example: https://github.com/tsedio/tsed/blob/b5a666c76d494705886fa3848ccfdfa0a6df9ca2/packages/platform/platform-exceptions/src/services/PlatformExceptions.ts#L1.

So the package manager won't be able to get the info of "needed" deps.

As an example of failing build:

https://github.com/belgattitude/nextjs-monorepo-example/pull/1368.

## Workaround 

Lock to to previous version or manually state required deps

**Comment by Romakita** [comment]
Hello @belgattitude 
Yes I’m sorry. I tried to fix an issue with pnpm because It install the di package twice (same di version) until the logger package isn’t installed. It’s crazy and I don’t understand why. I’ll rollback the commits and publish another versions.

see you

**Comment by Romakita** [comment]
fixed :)

**Comment by belgattitude** [comment]
That was fast 😅

**Comment by belgattitude** [comment]
Hey @Romakita thanks a lot for quick response, 

I've properly tested it with the latest.

A direct dep

>  Unmet transitive peer dependency on @tsed/schema@^6.102.5, via @tsed/exceptions@6.102.5 

A transitive from @tsed/schema

> Unmet transitive peer dependency on @tsed/core@^6.102.5, via @tsed/schema@6.102.5

I just had to install @tsed/schema  and @tsed/core (with yarn 3).

Not a big deal for me. I'm totally fine, just sharing few thoughts. 

In my experience peer-deps are always complex to deal with in a consistent manner (depends on npm version 6/7/8, yarn or pnpm...), especially when they're transitive Latest npm always installs them, but others ? 

Possible solutions:

- add in the readme (npm --install @tsed/exceptions @tsed/schema). It would act as a reminder (and works all the time).
- Maybe use peerDependenciesMeta like

```json5
  "peerDependencies": {
    "@tsed/schema": "^...",
  },
  "peerDependenciesMeta": {
    "@tsed/schema": {
      "optional": false
    },
  }
```

That might help to fail rather than printing a warning. I could see some pnpm / yarn docs about it. Not even sure if they're able to make it working (ie:  transitive peer-deps).

- Or as @tsed/exceptions seems only to rely on getConstants from @tsed/schema... maybe a reorg, or isolates package ? (forget about it, it would your life harder :)

Anyway, that's a detail.

Wanted to say that I really appreciate what you're doing with tsed. I'm not really using it, but see some nice stuffs.

**Comment by Romakita** [comment]
Thanks for the feedback @belgattitude. I’ll publish a new realease. But the schema package should already installed if you use @tsed/common package no?

yes it’s complicated to deal with npm/yarn/pnpm.

see you

**Comment by Romakita** [comment]
Ok. After reading your repo, you use only the @tsed/exceptions package. This is why you have a warning. I’ll fix that ;)

**Comment by belgattitude** [comment]
Nice.  Tested latest release. Now having

WebServer Error: Cannot find module 'change-case'

In my e2e https://github.com/belgattitude/nextjs-monorepo-example/runs/5257988300?check_suite_focus=true#step:12:24

A transitive deps of status probably

**Comment by belgattitude** [comment]
BTW just to add about previous comment.  It's not totally the warnings that made me comment.  More the e2e that fail on the p/r. That's why I'm informed quick.

Hope it's helpful,  don't want to create work about this.  😅

**Comment by Romakita** [comment]
T.T my bad. Now it’s totally my fault. 
the problem is, I use monorepo / workspace with yarn and there is no tool to prevent missing dep in this case.

I’ll fix again

**Comment by Romakita** [comment]
The release is on going. I'm sorry about that. 

I wanted to remove the unnecessary dependency between @tsed/exceptions and @tsed/schema in order to simplify the package to his strict minimum (so it's better for you, less code and less dependencies).

I forgot to add the change-case dependency :(

The package should be ok for your usecase :)

See you
Romain
