### ISSUE TITLE
API Key based authentication using tsed/Passport

### ISSUE THREAD

**Issue by ramprasathb-foxsense** [TypedProject/ts-express-decorators#1792]
##Information

**Is your feature request related to a problem? Please describe.
Having a use-case where the backend has to validate the incoming request and verify the API key from header before processing and returning a response. But in the current situation, am unable to use ```passport-headerapikey``` library in tsed.

**Describe the solution you'd like
It would be great if tsed/passport can support headerapikey strategy of authentication.

```ts
import {OnVerify, Protocol} from "@tsed/passport";

import {$log, Req} from "@tsed/common";
import {HeaderAPIKeyStrategy} from "passport-headerapikey";
import {Unauthorized} from "@tsed/exceptions";

@Protocol({
  name: "apiKey",
  useStrategy: HeaderAPIKeyStrategy,
  settings: {
    header: "X-API-KEY",
    prefix: ""
  }
})
export class ApiKeyAuthenticationProtocol implements OnVerify {
  async $onVerify(@Req() req): Promise<boolean> {
    return new Promise(async (resolve, reject) => {
      $log.info("Authetication Failed");
      reject(new Unauthorized("Authentication Failed"));
    });
  }
}
```

**Describe alternatives you've considered
Currently setting up a custom middleware which will validate the api-key configured against the one that is passed on the request header.

##Acceptance criteria
- [ ] headerapikey strategy working on tsed/passport

**Comment by Romakita** [comment]
Hello @ramprasathb-foxsense 

HeaderAPIKeyStrategy doens't follow the classic signature of other passport plugin.

So you have to wrap the HeaderAPIKeyStrategy to match the expected signature.

```typescript
import {OnVerify, Protocol} from "@tsed/passport";

import {$log, Req} from "@tsed/common";
import {HeaderAPIKeyStrategy} from "passport-headerapikey";
import {Unauthorized} from "@tsed/exceptions";

class CustomStrategy extends HeaderAPIKeyStrategy {
    constructor(settings: any, verify: any) {
       super(settings, true, verify)
    }
}

@Protocol({
  name: "apiKey",
  useStrategy: CustomStrategy,
  settings: {
    header: "X-API-KEY",
    prefix: ""
  }
})
export class ApiKeyAuthenticationProtocol implements OnVerify {
  async $onVerify(@Req() req) {
      $log.info("Authetication Failed");
       throw new Unauthorized("Authentication Failed"));
    });
  }
}
```
