### ISSUE TITLE
Ability to disable headers being sent

### ISSUE THREAD

**Issue by rjchicago** [TypedProject/ts-express-decorators#1800]
### Problem

We're setting up end-to-end streaming and are looking for the ability to disable headers and status from being sent by TsED. The reason for this is we need to determine first if there is an issue with the stream - if not, then we send status 200 and set headers appropriately for streaming:

``` js
res.writeHead(200, {
   'Content-Type': 'application/json; charset=utf-8',
   'Transfer-Encoding': 'chunked',
   'X-Content-Type-Options': 'nosniff'
 });
```

If there is an error during streaming, and if determined prior to the head being sent, we instead want to send an appropriate error status (i.e. 500).

The problem we're seeing when using TsED is that the headers and status are sent as soon as the pipe is established, thus not allowing to return an error status on error.

### Solution

My proposal is to add a flag onto PlatformContext (i.e. `disableSetResponseHeaders`) thus allowing disabling in [`setResponseHeaders`](https://github.com/tsedio/tsed/blob/c22a4a6ecfdcaa3931e7a66678da47c05f2d5e4b/packages/platform/common/src/utils/setResponseHeaders.ts#L18):

``` js
export function setResponseHeaders(ctx: PlatformContext) {
  const {response, endpoint} = ctx;
  const {operation} = endpoint;

  if (response.isDone() || ctx.disableSetResponseHeaders) {
    return;
  }

  ...
```

### Alternatives Considered

I've set up a [basic NodeJS project](https://github.com/rjchicago/pg-query-stream-demo) that implements the header handling for example.
If the stream is successful, the headers are written once data begins streaming via a [`prehook`](https://github.com/rjchicago/pg-query-stream-demo/blob/master/service/src/StreamingService.js#L31).
If there is an error in streaming, then an error status is sent via an [`errorHook`](https://github.com/rjchicago/pg-query-stream-demo/blob/master/service/src/StreamingService.js#L57)

Where preHook and errorHook are defined in [`options`](https://github.com/rjchicago/pg-query-stream-demo/blob/master/service/src/StreamingService.js#L5):

``` js
preHook: () => {StreamingService.writeHead(outStream, 200)}
errorHook: () => {StreamingService.writeHead(outStream, 500)}
```

If I am missing that there's already a flag for this - or an alternative I may not have considered - please let me know.

Thanks!

**Comment by Romakita** [comment]
If you return a Stream/Buffer from the controller it shouldn't be a problem... In this case, the stream have a priority on the default behavior :)

**Comment by Romakita** [comment]
Have you an example of your Controller ?

**Comment by Romakita** [comment]
Hum ok you've right, the status and headers are set automatically. But I need a controller example to see if there something wrong when a stream is returned.

**Comment by rjchicago** [comment]
An example of our Controller...

``` js
  @Get('/:company_id/media')
  @CustomAuth()
  @(Returns(200, Array).Of(MediaResponse).Description('Success'))
  async getMedia(
    @Context() ctx: Context,
    @HeaderParams('Authorization') auth: string,
    @HeaderParams('X-Request-Id') xRequestId: string,
    @PathParams() params: any,
    @PathParams('company_id') company_id: number,
    @QueryParams() @UsePipe(ParseArraysPipe) filter: MediaFilter
  ): Promise<any> {
    this.setCtx(ctx, [filter, params]);
    const queryBuilder: QueryBuilder = this.getQueryBuilder(auth, filter, params);
    const data = await this.companyService.getMedia(queryBuilder);
    return this.sendResponse(ctx, data);
  }
```

which calls this method in our BaseController...

``` js
    protected sendResponse = (ctx: Context, data: any = undefined): string | void => {
        // for sql=true, data will be the raw sql query as a string.
        if (typeof data === 'string' || data instanceof String) return data as string;
        // for non-streaming queries, data will be result rows.
        // for streaming queries, data will be a readable stream.
        const isStream = !Array.isArray(data);
        const stream = isStream ? data : new Stream.Readable({objectMode: true});
        const rows = isStream ? undefined : data;
        this.streamingService.streamResponse(ctx.response.raw, stream, {}, rows);
    }
```

We were going to handling streaming internally by enabling via a query param flag.
`streamResponse` is then similar to the [demo project](https://github.com/rjchicago/pg-query-stream-demo/blob/master/service/src/StreamingService.js#L54) I linked above.

for reference

``` js
    public streamResponse = (
        res: ServerResponse,
        inStream: Readable | Duplex,
        options: StreamingServiceOptions = {},
        data: any[] | undefined = undefined
    ): void => {
        const {preHook, errorHook, errorHandler} = this.getOptions(res, options);
        inStream.on('error', (error) => {
            errorHook();
            inStream.push({error: error.message});
        });
        const transform = this.getTransform(preHook, res);
        pipeline(inStream, transform, res, errorHandler);
        if (data) {
            (Array.isArray(data) ? data : [data]).map(record => inStream.push(record));
            inStream.push(null); // signal stream end
        }
    };
```

**Comment by Romakita** [comment]
Ok the problem is about your implementation:

You should return the stream, instead of handle it manually. For me, you should return the inStream to Ts.ED and Ts.ED will pipe your stream with the response.

**Comment by rjchicago** [comment]
Ok, is there a way to provide an error handler and return an appropriate error status?

Also, NodeJS recommends to [use `pipeline` instead of `pipe`](https://www.youtube.com/watch?v=aTEDCotcn20&t=442s) to ensure no memory leaks with streams not being properly closed. Would returning the stream use `pipeline`?

**Comment by Romakita** [comment]
haaa ok
So the immediate solution is to cancel the response handling from Ts.ED, and let your controller method to manage correctly the response.
```typescript
    public streamResponse = (
        res: ServerResponse,
        inStream: Readable | Duplex,
        options: StreamingServiceOptions = {},
        data: any[] | undefined = undefined
    ): void => {
        const {preHook, errorHook, errorHandler} = this.getOptions(res, options);
        inStream.on('error', (error) => {
            errorHook();
            inStream.push({error: error.message});
        });
        const transform = this.getTransform(preHook, res);
        pipeline(inStream, transform, res, errorHandler);
        if (data) {
            (Array.isArray(data) ? data : [data]).map(record => inStream.push(record));
            inStream.push(null); // signal stream end
        }
        
        return res // cancel the response managed by Ts.ED
    };
```

In this case, the headers and status won't be sent. But you have to add it by your own way!

**Comment by rjchicago** [comment]
Hey hey! That worked for the successful query!
However, a failure returned an empty response:
``` sh
curl: (52) Empty reply from server
```

However, this may be on my side still - checking...

**Comment by rjchicago** [comment]
Yep, I needed to add `res.end()` back in the `on error`...

``` js
        inStream.on('error', (error) => {
            errorHook();
            inStream.push({error: error.message});
            res.end();
        });
```

This is working now - thank you so much for the quick replies! (and awesome framework!!!) 😉

**Comment by Romakita** [comment]
You’re welcome ;) I have to add this example on the website. You are probably not alone about this need ;)

see you
Romain
