### ISSUE TITLE
[BUG] Missing nested controllers when using `pathPatterns` on swagger settings

### ISSUE THREAD

**Issue by weirongxu** [TypedProject/ts-express-decorators#1802]
## Information

- **Version:** 6.105.2
- Packages:

Missing nested controllers when using `pathPatterns` on swagger settings.

## Example

```ts
import "@tsed/ajv";
import { PlatformApplication } from "@tsed/common";
import { Configuration, Controller, Inject } from "@tsed/di";
import "@tsed/platform-express"; // /!\ keep this import
import { Get } from "@tsed/schema";
import "@tsed/swagger";

@Controller("/articles")
export class ArticlesController {
  @Get("/")
  get() {
    return "articles";
  }
}

@Controller({
  path: "/home",
  children: [ArticlesController]
})
export class HomeController {
  @Get("/")
  get() {
    return "home";
  }
}

@Controller({
  path: "/api",
  children: [HomeController],
})
export class ApiController {
  @Get("/")
  get() {
    return "api";
  }
}

@Configuration({
  acceptMimes: ["application/json"],
  httpPort: process.env.PORT || 8086,
  httpsPort: false, // CHANGE
  componentsScan: false,
  mount: {
    "/": [ApiController],
  },
  swagger: [
    {
      path: "/doc",
      pathPatterns: ["/api/home/**"],
      specVersion: "3.0.1",
    },
  ],
})
export class Server {
  @Inject()
  protected app: PlatformApplication;

  @Configuration()
  protected settings: Configuration;
}
```

## Acceptance criteria

- [ ] It should be possible to extract the nested controllers and display on swagger.json

**Comment by Romakita** [comment]
Hello @weirongxu 

The problem is probably here:
https://github.com/tsedio/tsed/blob/cae4435f52f8412ba169d05581bbf8a44bd63a95/packages/specs/swagger/src/utils/includeRoute.ts

I haven't time to fix it but you can try to edit the node_modules and find a way to fix it. Then if you have a time, you can make  PR ;)

See you
Romain

**Comment by weirongxu** [comment]
Thanks for the quick response, I'll try to make PR first.

**Comment by weirongxu** [comment]
I noticed that `Platform.getMountedControllers` only returns the root controllers, should we make `getMountedControllers` including all nested controllers, considering that there may be similar functionality elsewhere in the future.

https://github.com/tsedio/tsed/blob/3b7a421f079d88b9d8cc7ed66e901baff0a8da06/packages/platform/common/src/services/Platform.ts#L86
