### ISSUE TITLE
[BUG] PlatformMulterMiddleware invalid status message

### ISSUE THREAD

**Issue by dark544** [TypedProject/ts-express-decorators#1809]
## Information

- **Version:** 6.105.4
- Packages:

The middleware catches errors from Multer and puts them into an exception.  
It takes the error code multer throws as the status for the exception.  
The result is an error because the exception is trying to cast it to an HTTP error (I guess).  
  
```js
{
    name: 'Error',
    message: 'invalid status message: "LIMIT_FILE_SIZE"',
    status: 500,
    errors: [],
    stack: 'Error: invalid status message: "LIMIT_FILE_SIZE"\n' +
      '    at getStatusCode (node_modules/@tsed/exceptions/node_modules/statuses/index.js:97:11)\n' +
      '    at status (node_modules/@tsed/exceptions/node_modules/statuses/index.js:145:10)\n' +
      '    at getStatusConstant (node_modules/@tsed/exceptions/src/core/Exception.ts:5:67)\n' +
      '    at new Exception (node_modules/@tsed/exceptions/src/core/Exception.ts:48:17)\n' +
      '    at PlatformMulterMiddleware.use (node_modules/@tsed/common/src/middlewares/PlatformMulterMiddleware.ts:44:47)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
 }
```

## Example
Im using the fileSize limit for multer: 

```ts
@Configuration({
  multer: {
    storage: multer.memoryStorage(),
    limits: { fileSize: 1048576 }
  }
})
export class Server implements BeforeInit {
}
```

**Comment by Romakita** [comment]
Hello @dark544 
What is the expected status code and response ?

**Comment by dark544** [comment]
@Romakita Well if you ask me:  
I think it would be best to have a separate Exception type for this.  
I could then use an error middleware to customize the response.  
  
I personally would use a status code of 400 and the code as message.

**Comment by Romakita** [comment]
Right ;). I’ll fix that and create a custom BadRequest.

**Comment by dark544** [comment]
Brilliant, thank you :)
