### ISSUE TITLE
[BUG] Incorrect casing in generated Prisma types

### ISSUE THREAD

**Issue by SaswatB** [TypedProject/ts-express-decorators#1815]
## Information

- **Version:** 5.x
- Packages: @tsed/prisma

When using lowercase model names in Prisma, the repository types generated by @tsed/prisma have incorrect casing on the `aggregate` parameter which results in broken types.
Prisma's behavior is likely caused by this line:
https://github.com/prisma/prisma/blob/f35af40ffed4cc96d990ab26c96d99c5f104c178/packages/client/src/generation/utils.ts#L134

## Example

```
model user {
  id            String
}
```

```
#13 12.77 node_modules/.prisma/client/entities/repositories/userRepository.d.ts(18,28): error TS2724: '"/app/node_modules/.prisma/client/index".Prisma' has no exported member named 'userAggregateArgs'. Did you mean 'UserAggregateArgs'?
```

## Acceptance criteria

- [ ] @tsed/prisma should generate valid types

**Comment by Romakita** [comment]
By convention, Ts.ED use a pascal case for model and it seems to be the same thing for prisma.

The problem seems to be here: https://github.com/tsedio/tsed/blob/production/packages/orm/prisma/src/generator/transform/transformModelToClass.ts#L7

**Comment by Romakita** [comment]
```
export function capitalize(str: string): string {
  return str[0].toUpperCase() + str.slice(1)
}
```
