### ISSUE TITLE
[QUESTION]: How to handle auth in serverless?

### ISSUE THREAD

**Issue by vincent-thomas** [TypedProject/ts-express-decorators#1818]
I'm thinking of switching my backend from nest to tsed. But then i saw tsed doesn't support middleware with serverless. Why is that? And how do i approach authentication reliably and in a maintainable way?

**Comment by Romakita** [comment]
The middlewares are supported if you use @tsed/serverless-http.

the @tsed/serverless module don’t use express or koa. It’s more designed to create function (but it’s less interesting than a pure js small function). 
authentication in this case can be implemented with interceptor.

See you

**Comment by vincent-thomas** [comment]
Nice, thanks for the info!
