### ISSUE TITLE
[BUG] Some links are broken in documentation

### ISSUE THREAD

**Issue by MartinMuzatko** [TypedProject/ts-express-decorators#1825]
I was trying to read up on functional programming to use tsed, then I found a dead link.
I then looked through the documentation to find a few more dead links.
Lastly I was running https://www.deadlinkchecker.com/website-dead-link-checker.asp to find any dead links.

There seem to be a few md pages that are linked, that links are not turned to html. That is probably because they are missing.

| Status | URL | Source page|
|--------|-----|------------------|
| 404 Not Found | https://ajv.js.org/images/ajv_logo.png | https://tsed.io/tutorials/ajv.html |
| 404 Not Found | https://ajv.js.org/lib/compile/codegen/index.ts | https://tsed.io/tutorials/ajv.html |
| 404 Not Found | https://ajv.js.org/docs/codegen.html | https://tsed.io/tutorials/ajv.html |
| 404 Not Found | https://www.serverless.com/fr/ | https://tsed.io/tutorials/serverless.html |
| 404 Not Found | https://socket.io/css/images/logo.svg | https://tsed.io/tutorials/socket-io.html |
| 404 Not Found | https://socket.io/docs/server-api/ | https://tsed.io/tutorials/socket-io.html |
| 404 Not Found | https://socket.io/docs/rooms-and-namespaces/ | https://tsed.io/tutorials/socket-io.html |
| 404 Not Found | https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github | https://tsed.io/contributing.html |
| 404 Not Found | https://tsed.io/https://www.npmjs.com/package/@tsed/platform-express | https://tsed.io/getting-started/ |
| 404 Not Found | https://tsed.io/https://www.npmjs.com/package/@tsed/platform-koa | https://tsed.io/getting-started/ |
| 404 Not Found | https://tsed.io/docs/models.html | https://tsed.io/getting-started/ |
| 404 Not Found | https://tsed.io/gettings-started/migration-from-v5.html | https://tsed.io/getting-started/ |
| 404 Not Found | https://tsed.io/getting-started/configuration.html | https://tsed.io/getting-started/ |
| 404 Not Found | https://tsed.io/docs/swagger.html | https://tsed.io/ |
| 404 Not Found | https://tsed.io/tutorials/socketio.html | https://tsed.io/ |
| 404 Not Found | https://tsed.io/docs/filters.html | https://tsed.io/docs/providers.html |
| 404 Not Found | https://tsed.io/docs/middlewares/override/global-error-handler.html | https://tsed.io/docs/controllers.html |
| 404 Not Found | https://tsed.io/appenders/insight.md | https://tsed.io/docs/logger.html |
| 404 Not Found | https://tsed.io/appenders/logentries.md | https://tsed.io/docs/logger.html |
| 404 Not Found | https://tsed.io/appenders/logstash-http.md | https://tsed.io/docs/logger.html |
| 404 Not Found | https://tsed.io/appenders/logstash-udp.md | https://tsed.io/docs/logger.html |
| 404 Not Found | https://tsed.io/appenders/loggly.md | https://tsed.io/docs/logger.html |
| 404 Not Found | https://tsed.io/appenders/rabbitmq.md | https://tsed.io/docs/logger.html |
| 404 Not Found | https://tsed.io/tutorials/seq.md | https://tsed.io/docs/logger.html |
| 404 Not Found | https://tsed.io/tutorials/slack.md | https://tsed.io/docs/logger.html |
| 404 Not Found | https://tsed.io/docs/models | https://tsed.io/docs/validation.html |
| 404 Not Found | https://tsed.io/api/common/filters/decorators/BodyParams.html | https://tsed.io/tutorials/ajv.html |
| 404 Not Found | https://tsed.io/tutorials/tutorials/ajv.html | https://tsed.io/tutorials/mikroorm.html |
| 404 Not Found | https://tsed.io/tutorials/tutorials/swagger.html | https://tsed.io/tutorials/mikroorm.html |
| 404 Not Found | https://tsed.io/docs/custom-provider.html | https://tsed.io/tutorials/typeorm.html |
| 404 Not Found | https://tsed.io/docs/[https://github.com/mscdex/busboy | https://tsed.io/docs/upload-files.html |
| 404 Not Found | https://tsed.io/https://api-docs.tsed.io/api | https://tsed.io/license.html |

**Comment by Romakita** [comment]
How!! Awesome! And thanks for the detailled feedback. I’ll take a time to fix it ;)

**Comment by Romakita** [comment]
@sofianeSghiouar To prevent future broken link, I suggest to use https://www.npmjs.com/package/linkinator with a github action in his dedicated workflow.

It will help us to detected broken link :)
