### ISSUE TITLE
TypeORM v0.3.x example: Error: Provider.provide is required

### ISSUE THREAD

**Issue by tkroll** [TypedProject/ts-express-decorators#1845]
## Information

- node:  v16.14.2
- "@tsed/*": "^6.110.0"
-  "typeorm": "^0.3.5"

Moving my 0.2 code over using your examples at [https://tsed.io/tutorials/typeorm.html#typeorm-v0-3-x](https://tsed.io/tutorials/typeorm.html#typeorm-v0-3-x).

This code:

```
registerProvider({
  token: USER_REPOSITORY,
  useValue: UserRepository
});
```

Errors with _Error: Provider.provide is required

Tried many values for **provide** but all give
TypeError: Cannot set property token of [object Object] which has only a getter

What should **provide** be?

**Comment by Romakita** [comment]
Hello @tkroll

thanks for the issue. if you change useValue by:

useFactory: () => UserRepository

it works?

**Comment by tkroll** [comment]
> 

Thanks for the quick reply.

provider is required on ProviderOpts in registerProvider, so same issue

**Comment by Romakita** [comment]
Ok wrong example. Sorry ;) The new documention will be released in few minutes!

Here is the right example:
```typescript
import {Injectable} from "@tsed/di";
import {DataSource} from "typeorm";
import {MySqlDataSource} from "../datasources/MySqlDataSource";
import {User} from "../entities/User";

export const UserRepository = MySqlDataSource.getRepository(User);
export const USER_REPOSITORY = Symbol.for("UserRepository");
export type USER_REPOSITORY = typeof UserRepository;

registerProvider({
  provide: USER_REPOSITORY,  // replace token by provide
  useValue: UserRepository
});
```

**Comment by Romakita** [comment]
https://github.com/tsedio/tsed/commit/28df0616507e25b327350e11a0e949315f0c7021

**Comment by tkroll** [comment]
Jackpot! Thank you kindly @Romakita

**Comment by tkroll** [comment]
Any db operation now gives error EntityMetadataNotFoundError: No metadata for "User" was found now.
Using SQLite3 btw.

My data source:

```
import { DataSource } from 'typeorm'
import { Logger } from '@tsed/logger'
import { registerProvider } from '@tsed/di'

export const SQLITE_DATA_SOURCE = Symbol.for('SqliteDataSource')
export const SqliteDataSource = new DataSource({
    type: 'sqlite',
    database: 'test.sqlite'
})

registerProvider<DataSource>({
    provide: SqliteDataSource,
    type: 'typeorm:datasource',
    deps: [ Logger ],
    async useAsyncFactory(logger: Logger) {
        await SqliteDataSource.initialize()

        logger.info('Connected with typeorm to database: sqlite3')

        return SqliteDataSource
    },
    hooks: {
        $onDestroy(dataSource) {
            return dataSource.isInitialized && dataSource.close()
        }
    }
})
```

**Comment by tkroll** [comment]
@Romakita I figured this out.

Datasource constructor needs an array of entities:

```
new Datasource({
   ...,
   entities: [Entity1, Entity2]
})
```
Ref: [What is an Entity (TypeORM)](https://typeorm.io/entities#what-is-entity)
Docs should probably include this.

**Comment by Romakita** [comment]
Ha ! True. I’ll add it ;)

**Comment by tkroll** [comment]
This works too:

```
new Datasource({
   ...,
   entities: [ 'src/entity/*.ts' ]
})
```
