### ISSUE TITLE
[BUG] TypeError at Object.getMetadata / TypeORM 0.3.x tutorial/documentation is broken

### ISSUE THREAD

**Issue by KBroichhausen** [TypedProject/ts-express-decorators#1881]
## Information

- **Version:** 6.114.2
- Packages: @tsed/di

I try to upgrade to every packages' latest version in my project and therefore want to implement a TypeORM 0.3.x DataSource.
Following the tutorial from https://tsed.io/tutorials/typeorm.html#typeorm-v0-3-x, I removed `@tsed/typeorm`.

I did the Injection as described with
```typescript
  @Inject(MYSQL_DATA_SOURCE)
  protected mysqlDataSource: DataSource;
```
and the log tells me, that the connection is established but the injection into the service is not working with 
```
[2022-04-29T06:35:07.598] [ERROR] [TSED] - TypeError

    at Object.getMetadata (/usr/src/app/common/temp/node_modules/.pnpm/reflect-metadata@0.1.13/node_modules/reflect-metadata/Reflect.js:354:23)

    at Function.getParamTypes (/usr/src/app/common/temp/node_modules/.pnpm/@tsed+core@6.114.2/node_modules/@tsed/core/lib/cjs/domain/Metadata.js:468:24)

    at Map.mapInvokeOptions (/usr/src/app/common/temp/node_modules/.pnpm/@tsed+di@6.114.2_c42bf0d589f40e1879f18ff2f52ac0d7/node_modules/@tsed/di/lib/cjs/services/InjectorService.js:584:44)

    at Map.resolve (/usr/src/app/common/temp/node_modules/.pnpm/@tsed+di@6.114.2_c42bf0d589f40e1879f18ff2f52ac0d7/node_modules/@tsed/di/lib/cjs/services/InjectorService.js:500:35)

    at Map.invoke (/usr/src/app/common/temp/node_modules/.pnpm/@tsed+di@6.114.2_c42bf0d589f40e1879f18ff2f52ac0d7/node_modules/@tsed/di/lib/cjs/services/InjectorService.js:171:29)

    at resolver (/usr/src/app/common/temp/node_modules/.pnpm/@tsed+di@6.114.2_c42bf0d589f40e1879f18ff2f52ac0d7/node_modules/@tsed/di/lib/cjs/decorators/inject.js:54:45)

    at Map.bindProperty (/usr/src/app/common/temp/node_modules/.pnpm/@tsed+di@6.114.2_c42bf0d589f40e1879f18ff2f52ac0d7/node_modules/@tsed/di/lib/cjs/services/InjectorService.js:361:15)

    at /usr/src/app/common/temp/node_modules/.pnpm/@tsed+di@6.114.2_c42bf0d589f40e1879f18ff2f52ac0d7/node_modules/@tsed/di/lib/cjs/services/InjectorService.js:320:26

    at Array.forEach (<anonymous>)

    at Map.bindInjectableProperties (/usr/src/app/common/temp/node_modules/.pnpm/@tsed+di@6.114.2_c42bf0d589f40e1879f18ff2f52ac0d7/node_modules/@tsed/di/lib/cjs/services/InjectorService.js:314:35)
```
Since Injection in general is working, and was before upgrading, of course the `emitDecoratorMetadata` option is set.
The error (with a lots of other services and injection) is gone when removing the injection of the datasource.

I tried to understand custom providers in general, and think that is related to that, but can't see what is missing from https://tsed.io/docs/custom-providers.html

Besides that the code blocks from https://tsed.io/tutorials/typeorm.html#typeorm-v0-3-x have several issues.
1. `tsed generate` does not offer an option for creating a DataSource. Is this in another plugin?
2. `MySqlDataSource` is sometimes written as `MysqlDataSource` (Sql vs. sql). Neither `Configuration` is needed nor `createConnection` but is imported. The package for the second one is not even necessary according to the introduction written in the yellow block on top.
3. Is Missing the import for `Inject`.

Thanks!

**Comment by Romakita** [comment]
Hello @KBroichhausen 
I'd just updated the Typeorm project example. All works as expected. I encourage you to checkout the project and compare the code with your project: https://github.com/tsedio/tsed-example-typeorm

With the exception of typos in the documentation, there is no error (the documentation fix is on going). Typos are not blocking to make a project work on the new version of typeorm. But thanks for the feedback.

The latest CLI version have the DataSource generation option. You probably forgot to update your CLI and the `@tsed/cli-plugin-typeorm`.

<img width="553" alt="Capture d’écran 2022-04-29 à 09 41 25" src="https://user-images.githubusercontent.com/1763311/165906262-ed30d5bd-89a9-4185-b6a7-a5939242dd40.png">

See you
Romain

**Comment by KBroichhausen** [comment]
Hi @Romakita,
I highly appreciate your fast answer!
EDIT: NVM, I just realised that the `USER_REPOSITORY` in your example is injected and declared via `registerProvider`. I try to solve and check what the issue is in my setup and will return later to this issue.

**Comment by Romakita** [comment]
OK ^^

**Comment by Romakita** [comment]
In the Server.ts, I changed the following code to see if there is an issue with the datasource injection:

```typescript
  async $onReady(): Promise<void> {
    const dataSource = this.injector.get<DataSource>(MYSQL_DATA_SOURCE)!;

    const count = await dataSource.manager.count(User);

    if (!count) {
      const user = deserialize(
        {
          email: process.env.ROOT_EMAIL || "admin@admin.fr",
          password: process.env.ROOT_PWD || "admin",
          firstName: "admin",
          lastName: "admin",
          age: 18
        },
        {type: User}
      );

      await dataSource.manager.save(User, user);
    }
  }
```
The server start correctly in this case :)

**Comment by KBroichhausen** [comment]
Ok, I found the error and was able to reproduce it in your example with just small changes.
The second code block from https://tsed.io/tutorials/typeorm.html#typeorm-v0-3-x contains this line
```
  provide: MysqlDataSource,
```
while it needs to be
```
  provide: MYSQL_DATA_SOURCE,
```
(which is of course correct in the github example you linked)

Instead of using the variable for the `DataSource` you need to use the variable for the symbol for that.

It is obvious now but hard to see. So, once again: Please update the documentation for this part and thanks for an amazing framework ;)

**Comment by Romakita** [comment]
Fixed: https://github.com/tsedio/tsed/blob/production/docs/tutorials/typeorm.md

Note: The documentation is open-source and can be fixed by making a PR ;)

**Comment by Romakita** [comment]
## 🎉 Are you happy? 

If you appreciated the support, know that it is **free** and is carried out on **personal time** ;)

A support, even a little bit **makes a difference** for me and  **continues to bring you answers**!

[![github](https://img.shields.io/static/v1?label=Github%20sponsor&message=%E2%9D%A4&logo=GitHub&color=%23fe8e86)](https://github.com/sponsors/romakita) [![opencollective](https://img.shields.io/static/v1?label=OpenCollective%20sponsor&message=%E2%9D%A4&logo=OpenCollective&color=%23fe8e86)](https://opencollective.com/tsed)
