### ISSUE TITLE
[BUG] @Returns won't return correct status with 200 and 202 defined

### ISSUE THREAD

**Issue by MatejSkrbis** [TypedProject/ts-express-decorators#1894]
## Information

- **Version:** 6.114.6

When both decorators `@Returns(200)` and `@Returns(202)` are set, it is not possible to set status 200

## Example

```ts
import { Get, Returns } from "@tsed/schema";
import { PlatformResponse, Response } from "@tsed/common";
import { Controller } from "@tsed/di";

@Controller("/test")
export class TestController {
    @Get('/')
    @Returns(200).Description('Success')
    @Returns(202).Description('Processing')
    doneOrProcessing(@Response() response: PlatformResponse): string {
        response.status(200);

        return 'done';
    }
}
```

When only `@Returns(200)` is set, it is possible to set both statuses. (200 and 202)
When only `@Returns(202)` is set, it is only possible to set status 202, but not status 200

## Acceptance criteria

What is set in `response.status(`**XXX**`)` should be returned in all cases.

**Comment by Romakita** [comment]
It’s not a bug. Use only one status in 2xx please.
See you
