### ISSUE TITLE
[BUG] ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

### ISSUE THREAD

**Issue by LywLover** [TypedProject/ts-express-decorators#1901]
## Information

- **Version:** 6.x
- Packages:    
    "@tsed/ajv": "^6.114.9",
    "@tsed/common": "^6.114.9",
    "@tsed/core": "^6.114.9",
    "@tsed/di": "^6.114.9",
    "@tsed/exceptions": "^6.114.9",
    "@tsed/json-mapper": "^6.114.9",
    "@tsed/logger": "^6.1.2",
    "@tsed/mongoose": "^6.114.9",
    "@tsed/openspec": "^6.114.9",
    "@tsed/platform-express": "^6.114.9",
    "@tsed/platform-middlewares": "^6.114.9",
    "@tsed/schema": "^6.114.9",

## Error

```bash
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

services/test
├─┬ @tsed/common
│ └─┬ @tsed/platform-views
│   └─┬ consolidate
│     ├── ✕ unmet peer react-dom@^16.13.1: found 18.1.0
│     └── ✕ unmet peer react@^16.13.1: found 18.1.0
└─┬ @tsed/platform-express
  └── ✕ unmet peer body-parser@1.19.0: found 1.20.0
```
Could you please update these packages? I have tested ts.ed is compatible with new version of these packages.
This error will result in an exit code of 1

## Acceptance criteria

- [ ] compatible with new version of these packages

**Comment by Romakita** [comment]
Hello @LywLover,

I think I'll drop the support of PNPM ^^. But about the body parser it's easy to fix it. For react, it should be optional. I only fix the issue for body-parser, right know !

See you
Romain

**Comment by Romakita** [comment]
Also, you can easily make a PR instead of filling an issue. Any contribution is welcome!

**Comment by LywLover** [comment]
Thanks for your help! 

I'm using Ts.ED + Next.js app.requestHandler. Could you please change to```"react": "^16.0.0 | ^17.0.0 | ^18.0.0"``` in order to compatibility with react.

**Comment by Romakita** [comment]
https://github.com/tsedio/tsed/blob/production/packages/engines/package.json#L66

**Comment by Romakita** [comment]
The problem for react isn't under my control. It's related to consolidate package. You can switch on @tsed/engine. It's a fork of consolidate and use the same configuration. See https://tsed.io/docs/templating.html
