### ISSUE TITLE
Browser and useragent

### ISSUE THREAD

**Issue by xantos008** [TypedProject/ts-express-decorators#1916]
Hello there!
Is there any functions or decorators that defines useragent and browser?
Something like
@Request('browser') browser // return string like 'Chrome' or 'Safary' or 'Other Browser' and etc.
@Request('useragent') useragent // return string like 'Windows' or 'Mac Os' or 'iOs' or 'Other Platform' and etc.

**Comment by Romakita** [comment]
Use ˋ@Header` and https://www.npmjs.com/package/express-useragent

**Comment by xantos008** [comment]
@Header() is sets headers to response. But we want to get browser info and useragent info in middleware

**Comment by Romakita** [comment]
rhooo.... HeaderParams, please... take a time to read the documentation.
