### ISSUE TITLE
[BUG] or [🚀 Feature request] logger.debug() is not shown on stdout when use with other package

### ISSUE THREAD

**Issue by imoyakin** [TypedProject/ts-express-decorators#1927]
## Information

- **Version: v6.1.3 
- Packages: logger

A few sentences describing the overall goals of the issue.

when i try to use $log.debug() on  function who called by the other library, without ts.ed context. Logs are output at the default level instead of setting.

## Example

```ts
import {} from "@tsed/common";
import { Queue, Worker as BullWorker } from "bullmq";

export worker = new BullWorker("key", async job => {await watchUser(job.data)}, conn)

async function watchUser(userCache: any) {
     $log.debug("data:", userCache)
}
```

```ts
@Configuration({
    logger: {level: 'debug'}
})
export class Server {
  @Inject()
  protected app: PlatformApplication;

  @Configuration()
  protected settings: Configuration;
}
```

## Acceptance criteria

- [ ] Show the expected debug log with setting, doesn't care if it's not in `ts.ed` context

**Comment by Romakita** [comment]
I don't understand your issue. $log.debug is on outputted by default on stderr. 

If you look at the documentation you can choose at any time what the debug should be mapped to. Read the doc here:
https://logger.tsed.io/appenders/stderr.html

See you
Romain
