### ISSUE TITLE
[BUG] favicon

### ISSUE THREAD

**Issue by Paul75** [TypedProject/ts-express-decorators#1935]
Hello,

It seams not have favicon when open sxagger.json  (http://localhost:3000/doc/swagger.json) get errors...

Thanks

**Comment by Romakita** [comment]
Hello Paul,
You mean, when open swagger-ui. Is it really important ?

But your issue Just expose the favicon with the static express module! 
Look here: https://tsed.io/docs/serve-files.html

Isn't really an issue, it's just a problem with the original swagger ui template. I won't fix that personally :)
