### ISSUE TITLE
[BUG] Page Model - /docs/model

### ISSUE THREAD

**Issue by xferqr** [TypedProject/ts-express-decorators#1944]
Hi. 
If you follow the instructions in the documentation, then the validator does not see changes in the model fields.

![image](https://user-images.githubusercontent.com/45597852/174356876-2daff8ec-a3fb-4419-9fec-2c16a36cc82b.png)
![image](https://user-images.githubusercontent.com/45597852/174356953-75b12e78-e79c-4880-b7de-25b63eb76365.png)
![image](https://user-images.githubusercontent.com/45597852/174357009-5b2f139b-a2ef-462d-ab89-532fb4509d2b.png)

**Comment by Romakita** [comment]
Hello @xferqr 

please give me reproducible and complete example. (Avoid capture, prefer text so I can copie your example).

For me the groups works as expected, many devs use it and I use groups in many project. 

Please take a time to create reproducible example ;)

see you
