### ISSUE TITLE
tsed prisma generator creates ambiguous imports for enum types

### ISSUE THREAD

**Issue by str11ngfello** [TypedProject/ts-express-decorators#1946]
## Information

- **Version:** 6.114.17
- Packages: prisma

Prisma generate creates ts files that will not transpile with ```yarn build``` due to ts2308 error regarding ambiguous imports created by tsed generator. Specifically the index file in the generated directory has the import error. See my VSCode screenshot where I've positioned everything you need in view. In the project explorer you can see my directory structure and the index.ts file containing the error. In the code editor you can see the line number in the file that has the error and in the terminal you can see the errors returned by trying to build.

Please let me know if you have any questions. Thanks! Looking forward to using this feature - its one of the main draws to tsed for me.

## Screenshot

Here is the relevant portion of of my schema.prisma file showing I export ts files outside of node_modules

![image](https://user-images.githubusercontent.com/877000/174465403-90af219b-e2d3-4845-9f45-b31260361cd6.png)

and here is the screenshot that shows the details of the error and data structure

![err](https://user-images.githubusercontent.com/877000/174465418-9bfbd069-f9b7-4239-9199-913a084c39ed.png)

## Acceptance criteria

- The prisma generate command should produce files that transpile without errors.

**Comment by Romakita** [comment]
Hello @str11ngfello 
It should helpful if you can provide small repository with code example please. 

> /!\ IMPORTANT: Before opening issue
>
> - Please update all of your packages. I won't investigate on the issue if you are on an old version.
> - Please check that you have the same version for all Ts.ED dependencies (expected the logger). Many issues are related to a misconfigured packages.
> - Please provide a reproducible example (avoid screenshot, prefer copy/pasted code). The stack trace isn't enough to investigate.
>
> If theses requirements aren't checked, I WON'T INVESTIGATE (excepted if you are a PREMIUM SPONSORS!) and issue will be CLOSED!

See you
Romain

**Comment by tomapp** [comment]
Hello,

Before using the import from "@tsed/schema" I was importing most of my stuff from "@prisma/client" at first and it did not cause any problem during the build.

Now I meet the exact same issue. I'm trying to build a small example to help you to reproduce, but it works. I can't figure out what trigger this behaviour.

Maybe it can give you a clue : I think this could come from some conflict between "@prisma/client" and "@tsed/schema" where Tsed schema is trying to import the generated client from prisma again ?

**Comment by Romakita** [comment]
If you are not able to reproduce with a small repo, I can't help you. The problem is located on your repo and how you implement your code.

Your supposition is wrong ^^. @tsed/schema is a base of all others tsed module. It doesn't depend or import any other module expected `@tsed/core`. 

The typescript error you have, shows a symbol problem exported twice or because typescript is incorrectly configured. On things is the generated typescript code is outside src. Which is probably incorrect, if you have used the tsconfig.json generated by the CLI.

See you
Romain

**Comment by tomapp** [comment]
Hello !

I found a way to reproduce the bug with a simple example right [here](https://github.com/tomapp/enum-issue)!
Definitly something related to the enum type.

**Comment by Romakita** [comment]
Thanks. I’ll a look ^^

**Comment by Romakita** [comment]
Ok the bug is related to the build command. Prisma/client generate enums and tsed also with same names.

I'm surprised it hasn't been brought up sooner.

**Comment by Romakita** [comment]
PR is ready: https://github.com/tsedio/tsed/pull/1960

**Comment by Romakita** [comment]
@str11ngfello @tomapp It's released ;)
