### ISSUE TITLE
[FEAT] Use ALS to map EM to requests in the background

### ISSUE THREAD

**Issue by derevnjuk** [TypedProject/ts-express-decorators#1949]
## Information

To utilize implicit transactions using the whole power of UoW, `@tsed/mikro-orm` provides the ability to register an interceptor using the `@Transactional` decorator. The interceptor is in charge of forking an entity manager within the async context mapping it to the particular call.

There are a few issues with this approach:

* Missed `@Transactional` might lead to race conditions or a growing memory footprint, that is why using a global entity manager is strictly forbidden by default in `mikro-orm`.
* It is almost impossible to propagate an entity manager to other services called in middlewares since they are called before an interceptor catch a request.

## Possible solution

We should introduce a middleware that comes in handy to map a fork to TsEd context. We should register this middleware as the last one just before request handlers and before any custom middleware that is using the ORM:

```ts
@Middleware()
export class MikroOrmContextMiddleware implements MiddlewareMethods {

  constructor(@Inject() private readonly registry: MikroOrmRegistry) {}

  public use(@Next() next: (...args: unknown[]) => void): void {
    const instances = [...this.registry.values()];
    const entityManagers = instances.map((orm) => orm.em);

    RequestContext.create(entityManagers, next);
  }
}
```

However, we can notice an issue using a util class from `mikro-orm`. Please take a look at the following example:
```ts
@Controller('/')
export class UserController {
  @Em() private readonly em!: EntityManager;

  @Get()
  @Use(MikroOrmContextMiddleware)
  public getAll(): Promise<void> {
    return this.em.find(User, {});
  }
}
```
Running the example above, `this.em.find()` will raise an error: `Using global EntityManager instance methods for context-specific actions is disallowed. If you need to work with the global instance's identity map, use the allowGlobalContext configuration option or fork() instead` (for details see  https://github.com/tsedio/tsed/issues/1289#issuecomment-800295504 ). To solve this issue Ts.ED provides the `@tsed/async-hook-context` package to manage natively the `async_hook`. 

So, we can rewrite the example above as follows:
```ts
@Middleware()
export class MikroOrmContextMiddleware implements MiddlewareMethods {

  constructor(@Inject() private readonly registry: MikroOrmRegistry) {}

  public use(@Next() next: (...args: unknown[]) => void): void {
    const instances = [...this.registry.values()];
    const entityManagers = instances.map((orm) => orm.em);
    getContext()?.set('entity_managers', entityManagers)
  }
}
```

**Comment by Romakita** [comment]
@derevnjuk There is regression around the context created by the server. The runInContext(next), doesn't works.

Are sure it was the good way to create context with express.js ?

```typescript
app.use((req, res,next) => {
   runInContext(next) 
})
```

I'll rollback the change and call the runInContext in PlatformHandler until the problem with next() isn't resolved

**Comment by derevnjuk** [comment]
@Romakita if there is a way to preserve context in the chain of middleware, it would be nice.

> Are sure it was the good way to create context with express.js ?

Yeah, this is how it works in express.js:

```ts
app.use((req, res, next) => {
  RequestContext.create(orm.em, next);
});
```

and, finally, in Koa:

```ts
app.use((ctx, next) => RequestContext.createAsync(orm.em, next));
```

Until it has been fixed I propose to rework `MikroOrmModule` to apply a workaround as follows:

```ts
interface RawMiddleware {
  (req: Express.Request, res: Express.Response, next: Express.NextFunction): unknown;

  (context: Koa.Context, next: Koa.Next): unknown;
}

const rawMiddleware: RawMiddleware = (reqOrContext: Express.Request | Koa.Context, resOrNext: Express.Response | Koa.Next, next?: Express.NextFunction) =>
  this.createContext(next ?? resOrNext);

this.app.use(rawMiddleware);
```

**Comment by Romakita** [comment]
Hello @derevnjuk 
Rework isn't necessary. The hook to bind context is called by the PlatformHandler. 
See the PR here: https://github.com/tsedio/tsed/pull/1973/files

**Comment by Romakita** [comment]
```
app.use((req, res, next) => {
  RequestContext.create(orm.em, next);
})
```
Maybe it don't use the same thing. But I'm sure, the binding with the next function doesn't work with the Ts.ED async hook context. I updated my project this week and the context was lost.

I think the best approach is to make a small express app with an async hook context and see if it works :)

**Comment by Romakita** [comment]
Hum it works. https://github.com/Romakita/express-app-context

So ... what is wrong in Ts.ED ???
