### ISSUE TITLE
[BUG] Agenda tasks not executed

### ISSUE THREAD

**Issue by yohannlog** [TypedProject/ts-express-decorators#1954]
## Information

- **Version:** 6.114.17
- **Packages**: @tsed/agenda, agenda(4.3.0)
- **Tested versions**: 18.3.0 and 16.15.0

I tried to add agenda support to my project and I can't execute tasks. All tasks are registered in mongodb database but are not executed. I see the agenda use UTC Time but if I used date object, he didn't work as well. (UTC or not). Is it a bug or a code problem?

## Example

Configuration:
```ts
@Configuration({
	agenda: {
		enabled: true,
		maxConcurrency: 20,
		db: {
			address: "mongodb://localhost:27017/agenda",
			options: {}
		},
	}
})
export class Server implements OnReady {
	@Inject()
	protected app: PlatformApplication;

	@Configuration()
	protected settings: Configuration;

	@Inject()
	private agenda: AgendaService

	async $onReady() {
		console.log("called");
		await this.agenda.start(); //This line or not didn't work
		await this.agenda.now("hello", undefined);
	}

	@Define({name: "hello"})
	hello() {
		console.log("hello called?");
	}
}
```

**Comment by Romakita** [comment]
Don’t use @Define on server please. The document show you the right way to declare agenda task. Please follow the document before opening an incorrect issue ;)

see you
