### ISSUE TITLE
[BUG] Body parser configuration cause a build error

### ISSUE THREAD

**Issue by tomapp** [TypedProject/ts-express-decorators#1961]
## Information

- **Version:** 6.114.17
- Packages:

Hello,

Since I've updated my packages, I can't get my json payload in my `@Req() req.body` `@BodyParams()`.
I've migrate the bodyParser to be compliant with the new approach, but it does not solve the problem, and even generate a build error sinces the options are not recognizes.

[I've provided you a example so you can reproduce the issue](https://github.com/tomapp/enum-issue)

(You can just pull if you kept it from the previous issue). 

The last commit show you the changes I've made.

Thanks in advance for your time !

## Example

```ts
// src/Server.ts

@Configuration({
  express: {
    bodyParser: {
      text: {},
      json: {},
      urlencoded: {
        extended: true
      }
    }
  },
}) // The code which cause the issue
```

## Acceptance criteria

- Get the body payload in the controllers
- Build the project throughout `npm run build`

**Comment by Romakita** [comment]
@tomapp I don't see any change on your repo :)

**Comment by tomapp** [comment]
Sorry, here you go !

**Comment by Romakita** [comment]
Where did you find the new approach in the documentation exactly. Because the CLI generate the correct configuration :)

**Comment by tomapp** [comment]
So I've built the project a couple month ago, since I've updated my dependencies, I could not get my json body again.
Then I remember it was a typical body parser issue.

After research, I saw that's you change the way you deal with body-parser described here : https://tsed.io/docs/configuration.html#platform-options implemented in this [PR](https://github.com/tsedio/tsed/pull/1851)

And at the end I also got a build error: 

![image](https://user-images.githubusercontent.com/3684625/176113910-566858c2-1d2e-46a8-98f2-b667f5fa8722.png)

**Comment by Romakita** [comment]
Ok. As I see, the problem is about the typings. I'll fix that.

**Comment by tomapp** [comment]
Thanks for that !

I also get troubles with the empty body. But I guess it is related to the typing issue.

**Comment by Romakita** [comment]
It’s strange, but I’ll investigate to sure. The integration test cover theses scenarios ^^

**Comment by tomapp** [comment]
Alright I guess I'm getting tired. I check again, and the first approach you've done `bodyParser.json()` in the middleware key works perfectly. I think the documentation is a bit to early compare to the current version ? Other than that no problem other there ! :)
