### ISSUE TITLE
[BUG] Invalid swagger path is generated

### ISSUE THREAD

**Issue by denis-vogrincic** [TypedProject/ts-express-decorators#2019]
## Information

- **Version:** 6.123.1

Invalid swagger API path is generated when mounting controller with same path as defined in config.

## Example

index.ts
```ts
...
const importConfig = {
    mount: {  '/tests/': [`some-path\\**\\controllers\\**\\**.[jt]s`] },
    imports: [ `some-path\\**\\**.[jt]s` ]
};
const scannedProviders = await importProviders(importConfig);
...
```

controller.ts
```ts
...
@Name('test')
@Controller('/test')
export class CustomerController {
    @Get('/')
    testFn(): string {
        return 'it works';
    }
}
...
```

For above configuration, swagger path is generated as following:
```json
{
    "paths": {
        "/s/test/test": {
            "get": {}
        }
    }
}
```

API is still accessible as it should be on path '/tests/test'.

**Comment by Romakita** [comment]
Hello @denis-vogrincic 
Your example seems to be wrong... The slash is missing in you provider configuration:

```typescript
const importConfig = {
    mount: {  'tests': [`some-path\\**\\controllers\\**\\**.[jt]s`] }, /// here
    imports: [ `some-path\\**\\**.[jt]s` ]
};
const scannedProviders = await importProviders(importConfig);
```

It should be:

```typescript
const importConfig = {
    mount: {  '/tests': [`some-path\\**\\controllers\\**\\**.[jt]s`] }, /// here
    imports: [ `some-path\\**\\**.[jt]s` ]
};
const scannedProviders = await importProviders(importConfig);
```

Please fix it!

> Note: componentsScan will be removed in v7. Please don't use it for new project :)

**Comment by denis-vogrincic** [comment]
Issue was with slash, but your example is also wrong.

I found out that 'tests' and 'tests/' both work as expected.
But '/tests' and '/tests/' don't. I had the latter.

Thanks!

**Comment by Romakita** [comment]
Isn't clear XD

For me this example is correct:

```typescript
@Controller('/test')
export class CustomerController {
    @Get('/')
    testFn(): string {
        return 'it works';
    }
}

const importConfig = {
    mount: {  '/tests': [`some-path\\**\\controllers\\**\\**.[jt]s`] }, /// here
    imports: [ `some-path\\**\\**.[jt]s` ]
};
const scannedProviders = await importProviders(importConfig);
```

And will output:  '/tests/test'
I'm sure about that ^^ (integration test is here for that).

That I see is an issue when 'tests' is set for the mount options (but it's not correct to declare the path like that).

See you
Romain
