### ISSUE TITLE
[TECH] Migrate the repository on YARN berry

### ISSUE THREAD

**Issue by Romakita** [TypedProject/ts-express-decorators#2024]
# Information

Migrate all workspaces on yarn berry. See the migration guide here:
https://yarnpkg.com/getting-started/migration

You can take as example the [@tsed/logger](https://github.com/tsedio/logger) repository.

### Acceptance criteria

- [ ] All test pass
- [ ] The repository build

**Comment by yohannlog** [comment]
I am working on it. Almost complete. There may be documentation to update and other small details.
Work done:

- [x] Tests
- [x] Build
- [x] Docker container
- [ ] Verify Documentation
