### ISSUE TITLE
[QUESTION] How to Inject current request into request scoped provider?

### ISSUE THREAD

**Issue by supercoffee** [TypedProject/ts-express-decorators#2034]
## Goal
I'm building a multi-tenant SaaS app where each tenant's data is housed in a separate DB.  I'd like to be able to inject a DB connection on a per-request basis.  My thinking here is to consolidate the DB selection logic to avoid polluting the application logic with tenant DB selection logic.  The DB connection will be selected based on the hostname in the request. 

## Current challenge
I have a request scoped provider set up and it currently does execute on every request.  However, I can't seem to figure out how to inject the current request into the factory function.  When inject `PlatformRequest`, it seems to be an object with a `$ctx` property, but everything else under `$ctx` are undefined. 

I've seen a similar example in NestJs where a request scoped provider is able to grab the current request in order to construct a DB connection. I was hoping that something  similar is possible in tsed.

From the docs, I know it's possible to inject context or request into methods using decorators, but that doesn't seem possible here since the factory function is not a method and decorators can't be used here. 

What class or token do I need to specify in the `deps` property in order to get the current request into my factory function?

## Example

```ts
registerProvider({
    provide: CONNECTION,
    scope: ProviderScope.REQUEST,
    type: ProviderType.FACTORY,
    useFactory (req: PlatformRequest) {
        console.log('creating DB connection');

        // TODO: how do we get the request context injected here?

        return  someDbConnections;
    },
    deps: [PlatformRequest]
});

```

## Acceptance criteria

- [ ] Ability to inject request context into a request scoped provider

## Information

- **Version:** 6.121.1
- Packages:

**Comment by Romakita** [comment]
Hello @supercoffee 

$ctx cannot be injected like that because it use the async_hook from nodejs. You have to use the `getContext()` function to retrieve it :)

```typescript
registerProvider({
    provide: CONNECTION,
    scope: ProviderScope.REQUEST,
    type: ProviderType.FACTORY,
    useFactory () {
        console.log('creating DB connection');
        const $ctx = getContext():
        const {request} = $ctx

        // TODO: how do we get the request context injected here?

        return  someDbConnections;
    }
});
```
See you
Romain

**Comment by Romakita** [comment]
Re @supercoffee,

I see you trying to build a multi tenant app using Scope request. Use Scope Request on every class will cause a performance issue.

The PlatformContext and async_hook can help you to design a multi tenant app. You don't need to declare each controllers and services with the scope Request annotation. You just need to use a class that will be responsible to use the correct database connection by using the `$ctx` object.

Example:

```typescript
import {PlatformContext} from "@tsed/common";
import {deserialize} from "@tsed/deserialize";
import {Inject, Injectable, InjectContext} from "@tsed/di";
import {BadRequest} from "@tsed/exceptions";
import {Property} from "@tsed/schema";
import {Connection, createConnection} from "my-orm";
import {TENANT_DB_CONNECTION} from "../connections/TenantDBConnection";

export class TenantMetadata {
  @Property()
  id: string;

  @Property()
  dbName: string;

  connection: Connection;
  ///  other metadata stored in your DB
}

@Injectable()
export class TenantManagerClient {
  @InjectContext()
  protected $ctx: PlatformContext;

  @Inject(TENANT_DB_CONNECTION)
  protected tenantDbConnection: TENANT_DB_CONNECTION;

  /**
   * Hook which is always called by Ts.ED, when a request is handled.
   */
  $onRequest() {
    return this.init();
  }

  get() {
    const tenant = this.$ctx.get(TenantMetadata);
     
    if (!tenant) {
       throw new BadRequest("Unable to find the tenant ID");
    }

    return tenant
  }

  async init() {
     const tenantId = this.$ctx.request.get("x-tenant-id"); // or other discriminant from the request (domain, query, pathparams);
    
    if (!tenantId) {
       return; // skip init connection
    }

    if (!this.$ctx.has(TenantMetadata)) {
     

      const tenant = await this.tenantDbConnection.table("tenants").findOne({ id: tenantId });

      if (!tenant) {
        throw new BadRequest("Unable to find the tenant ID");
      }
      const tenantMetadata = deserialize(tenant, { type: TenantMetadata });
      tenantMetadata.connection = await createConnection(tenantMetadata.dbName);

      this.$ctx.set(TenantMetadata, tenantMetadata);
    }

    return this.$ctx.get(TenantMetadata)!;
  }
}

@Injectable()
export class ClientsRepository {
  @Inject()
  protected tenantManagerClient: TenantManagerClient;

  get table() {
    const tenantMetadata = this.tenantManagerClient.get();

    return tenantMetadata.connection.table("clients");
  }

  async get(id: string) {
    return this.table.findOne({ id });
  }
}
```

Here the TenantManagerClient use the $ctx to retrieve the tenantId and retrieve metadata and create automatically the connection.

I hope this example will help you ;)
See you
Romain

**Comment by Romakita** [comment]
An alternative to $onRequest can be used if you don't want to create a tenant connection for all routes. You can use a middleware:

```typescript
@Middleware()
class InitTenantConnectionMiddleware {
 @Inject()
 protected tenantManagerClient: TenantManagerClient;

 async use() {
     await this.tenantManagerClient.init()
 }
}

// then

@Controller('/clients')
@UseBefore(InitTenantConnectionMiddleware)
class ClientsController {

}
```
See you
Romain

**Comment by supercoffee** [comment]
@Romakita Thank you for the detailed suggestions.  I like the idea of using middleware or a connection manager instead of reconstructing controllers on each request.

**Comment by supercoffee** [comment]
@Romakita I followed your first example and I can't get the context.  When `$onRequest` is called, `this.$ctx` is always undefined.   I also tried calling `getContext` inside the `$onRequest()` method which also returns `undefined`.   Am I missing something here?

I worked around this by making the `get` method async and creating a new connection every time, but that approach implies that a new connection would be created multiple time in the same request context.

```typescript

import {getContext, Injectable, InjectContext} from "@tsed/di";
import {Context, Inject, PlatformContext} from "@tsed/common";
import {APP_DATA_SOURCE} from "./database/app-data-source";
import {DataSource} from "typeorm";
import {NotFound} from "@tsed/exceptions";
import {Property} from "@tsed/schema";
import {SiteModel} from "./database/models/SiteModel";
import {getSiteDbConnection} from "../database/site-db-connection";

export class TenantMetadata {

    @Property()
    id!: number;

    @Property()
    dbName!: string;

    connection!: DataSource;
}

@Injectable()
export class TenantManager {

    @InjectContext()
    $ctx?: Context

    @Inject(APP_DATA_SOURCE)
    protected appDataSource!: DataSource;

    $onRequest() {
        console.log('$onRequest');
        console.log(this.$ctx); // context is undefined
        console.log('getContext()=', getContext()); // also undefined
    }

    // called in controller method
    async get(): Promise<TenantMetadata> {
        const tenant = await this.init();

        if (!tenant) {
            throw new NotFound('Site does not exist.');
        }

        return tenant;
    }

    async init() {

        console.log(`this.$ctx=`, this.$ctx); // context is injected at this point

        const context = getContext()!;
        const tenantDomain = context.request.host;

        if (!tenantDomain) {
            return;
        }

        if (!context.has(TenantMetadata)) {
            const sitesRepo = await this.appDataSource.getRepository(SiteModel);
            const site = await sitesRepo.findOneBy({domain: tenantDomain});
            if (!site) {
                throw new NotFound('Site does not exist.');
            }
            const tenantMetadata = new TenantMetadata();
            tenantMetadata.dbName = site.databaseName;
            tenantMetadata.id = site.id;
            tenantMetadata.connection = await getSiteDbConnection(site.databaseName);
            context.set(TenantMetadata, tenantMetadata);
        }

        return context.get(TenantMetadata);
    }
}

```

Info
* node 14
* typescript: 4.4.3
* tsed 6.126.1
* "ts-node": "^10.9.1"
* "ts-node-dev": "^1.1.8"

**Comment by Romakita** [comment]
Context is alvailable by this because async hook isn’t executed. The context is given as the first parameter:

$onRequest($ctx: Context) {
       
 }
