### ISSUE TITLE
[BUG] MultipartFile not show input file on swagger

### ISSUE THREAD

**Issue by thanhchuongbmd** [TypedProject/ts-express-decorators#2039]
## Information

- **Version:** 6.126.1
- Packages:
    "@tsed/common": "6.126.1",
    "@tsed/core": "6.126.1",
    "@tsed/exceptions": "6.126.1",
    "@tsed/json-mapper": "6.126.1",
    "@tsed/platform-express": "6.126.1",
    "@tsed/swagger": "6.126.1",
    "@tsed/typeorm": "6.126.1",

## Example

```ts
import { MultipartFile, Controller } from "@tsed/common";
 @Post('/upload/avatar')
  async uploadAvatar(
        @Req() req: Request,
        @Res() res: Response,
        @MultipartFile('file') file: Express.Multer.File,
    ) {
}
```

## Acceptance criteria
See image, no input file
<img width="1026" alt="Screen Shot 2022-08-15 at 13 44 03" src="https://user-images.githubusercontent.com/67777599/184589093-15c157ec-ae39-43a1-8c75-87bb4abd64ce.png">

**Comment by Romakita** [comment]
Hello @thanhchuongbmd 

For me it works in OS3 version:
<img width="1916" alt="Capture d’écran 2022-08-15 à 10 25 18" src="https://user-images.githubusercontent.com/1763311/184601923-914431a6-1e93-44aa-81c6-fb10f0ad8085.png">


For OS2, it's not supported probably.
Please switch your swagger on OS3.

See you
Romain
