### ISSUE TITLE
[BUG] v7: npm install -g @tsed/cli@4

### ISSUE THREAD

**Issue by xferqr** [TypedProject/ts-express-decorators#2067]
Hi! I try create new project on v7

**npm install -g @tsed/cli@4**

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @tsed/cli@4.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

_Windows 10.
Node.js v16.17.0._

**Comment by Romakita** [comment]
Haaaaa sorry

here is the correct command:

npm i -g @tsed/cli@4.0.0-rc.1

**Comment by xferqr** [comment]
thnx ;)
