### ISSUE TITLE
[BUG] creating a project with cli@4.0.0-rc.1

### ISSUE THREAD

**Issue by xferqr** [TypedProject/ts-express-decorators#2068]
Hi!
Questions disappeared when creating a project

![image](https://user-images.githubusercontent.com/45597852/187292094-6204bec7-089c-4b72-808f-2afb10f26a1f.png)

**Comment by Romakita** [comment]
Hello @xferqr 

I think isn’t a bu. the v4 is exactly the same as v3 for that ^^.

Maybe it’s specific on windows. Inquirer and listr maybe have a small issue on this terminal ^^.

But when you run `tsed init .ˋ have you all prompted question and the project is correctly generated?

see you
Romain

**Comment by xferqr** [comment]
I try in ubuntu
![4427](https://user-images.githubusercontent.com/45597852/187453453-a884b948-af1f-418b-a758-19d721ef46c3.png)

**Comment by xferqr** [comment]
I am now getting this behavior on two different OS (win10/ubuntu) on different devices. 
And now even after npm install -g @tsed/cli

**Comment by Romakita** [comment]
I’m not sure to understand correctly the problem…

the project is correctly generated or not?

**Comment by xferqr** [comment]
No, when creating a project, questions do not appear

**Comment by Romakita** [comment]
Humm ookk. I’ll fix that ;) 

sorry for the misunderstood!

**Comment by xferqr** [comment]
Thanks for the help!

**Comment by xferqr** [comment]
@tsed/cli@4.0.0-rc.2 now it works correctly!
![1231935](https://user-images.githubusercontent.com/45597852/187774417-9f7ccefd-7aa2-451b-8b8e-24b9b73f93b0.png)
