### ISSUE TITLE
[BUG] V7 create project with "Choose the architecture for your project: feature"

### ISSUE THREAD

**Issue by xferqr** [TypedProject/ts-express-decorators#2076]
Hi!
If "choose the architecture for your project: **feature**" 
i get  "Error: ENOENT: no such file or directory, scandir '.../parttec_api_v7/src/controllers/rest'"

_@tsed/cli@4.0.0-rc.2_

**Comment by Romakita** [comment]
hum Ok the problem is related to barrels.
