### ISSUE TITLE
[BUG] V7 watching file changes not working

### ISSUE THREAD

**Issue by xferqr** [TypedProject/ts-express-decorators#2077]
Hi!

The message is shown only once, but no changes are shown: 
[INFO] 18:42:24 Restarting: /home/xf/dev/parttec_api_v7/src/controllers/rest/UsersController.ts has been modified

{
  "name": "parttec-api-v7",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "build": "npm run barrels && tsc --project tsconfig.compile.json",
    "barrels": "barrelsby --config .barrelsby.json",
    "start": "npm run barrels && tsnd --inspect --ignore-watch node_modules --respawn --transpile-only -r tsconfig-paths/register src/index.ts",
    "start:prod": "cross-env NODE_ENV=production node dist/index.js",
    "prisma:migrate": "npx prisma migrate dev --name init",
    "prisma:generate": "npx prisma generate"
  },
  "dependencies": {
    "@prisma/client": "^4.3.1",
    "@tsed/ajv": "^7.0.0-rc.5",
    "@tsed/cli-core": "4.0.0-rc.2",
    "@tsed/common": "^7.0.0-rc.5",
    "@tsed/components-scan": "^7.0.0-rc.5",
    "@tsed/core": "^7.0.0-rc.5",
    "@tsed/di": "^7.0.0-rc.5",
    "@tsed/engines": "^7.0.0-rc.5",
    "@tsed/exceptions": "^7.0.0-rc.5",
    "@tsed/json-mapper": "^7.0.0-rc.5",
    "@tsed/logger": "^6.2.2",
    "@tsed/logger-file": "^6.2.2",
    "@tsed/passport": "^7.0.0-rc.5",
    "@tsed/platform-cache": "^7.0.0-rc.5",
    "@tsed/platform-exceptions": "^7.0.0-rc.5",
    "@tsed/platform-express": "^7.0.0-rc.5",
    "@tsed/platform-log-middleware": "^7.0.0-rc.5",
    "@tsed/platform-middlewares": "^7.0.0-rc.5",
    "@tsed/platform-params": "^7.0.0-rc.5",
    "@tsed/platform-response-filter": "^7.0.0-rc.5",
    "@tsed/platform-views": "^7.0.0-rc.5",
    "@tsed/prisma": "^7.0.0-rc.5",
    "@tsed/schema": "^7.0.0-rc.5",
    "@tsed/socketio": "^7.0.0-rc.5",
    "@tsed/swagger": "^7.0.0-rc.5",
    "ajv": "^8.11.0",
    "barrelsby": "^2.4.0",
    "body-parser": "^1.20.0",
    "compression": "^1.7.4",
    "cookie-parser": "^1.4.6",
    "cors": "^2.8.5",
    "cross-env": "^7.0.3",
    "dotenv": "^16.0.2",
    "dotenv-expand": "^9.0.0",
    "dotenv-flow": "^3.2.0",
    "express": "^4.18.1",
    "method-override": "^3.0.0",
    "passport": "^0.6.0",
    "socket.io": "^4.5.1"
  },
  "devDependencies": {
    "@tsed/cli-plugin-passport": "4.0.0-rc.2",
    "@tsed/cli-plugin-prisma": "4.0.0-rc.2",
    "@types/compression": "^1.7.2",
    "@types/cookie-parser": "^1.4.3",
    "@types/cors": "^2.8.12",
    "@types/express": "^4.17.13",
    "@types/inquirer": "^9.0.1",
    "@types/method-override": "^0.0.32",
    "@types/multer": "^1.4.7",
    "@types/node": "^18.7.14",
    "@types/passport": "^1.0.10",
    "prisma": "^4.3.1",
    "ts-node": "^10.9.1",
    "ts-node-dev": "^2.0.0",
    "tsconfig-paths": "^4.1.0",
    "tslib": "^2.4.0",
    "typescript": "^4.8.2"
  },
  "tsed": {
    "packageManager": "npm",
    "convention": "default",
    "architecture": "default"
  }
}

**Comment by xferqr** [comment]
upd: A clean project on v^6.129.0 has the same problem

**Comment by Romakita** [comment]
This part is related to `tsnd` aka ts-node-dev, and not to the framework itself. 
developers are free to use another ts watcher ;)

I close the issue because, I'm not able to resolve that :)

**Comment by xferqr** [comment]
hmm
but then you can’t start a project on a framework -.-
If anyone experiences this problem, then you can add a webpack when generating a project
