### ISSUE TITLE
Is componentsScan deprecated or not?

### ISSUE THREAD

**Issue by borjapazr** [TypedProject/ts-express-decorators#2087]
As I see in the documentation `componentsScan` [seems to be deprecated](https://tsed.io/docs/configuration.html#componentsscan-deprecated). However, reviewing other parts of the documentation it appears exposed as a functionality that can be used, even in the examples on GitHub there are references to this functionality. Is `componentsScan` deprecated or not? In case its use is not recommended, what alternatives are there if we have a set of components that are not imported explicitly in another components and we want them to be detected by the TSED dependency container?

**Comment by Romakita** [comment]
Hello @borjapazr 

Here is the complete answers :)
https://v7.tsed.io/getting-started/migration-from-v6.html#components-scan

Ts.ED don't need Components Scan to works. Components Scan is just a feature that simplify the development process.
 It can be replaced by barrelsby (tooling) or manual ES6 import.

Using ES6 import: 
```typescript
import {MyService} from "./MyService"; // if the symbole is used
import "./MyService"; // if the symbole isn't used but you have use it because you use hooks
```

See you
Romain

**Comment by borjapazr** [comment]
Great! Very good answer @Romakita 😊

So from v7 `componentsScan` will no longer be available inside `@Configuration` and `mount` can no longer be used with globs, right?

I think it's perfect to use `barrelsby`. I'm already using barrel files, so the upgrade won't be too dramatic.

Thank you! 🙏

**Comment by Romakita** [comment]
Mount option will only accept Symbols and not a globpattern. componentsScan will be removed ;)
