### ISSUE TITLE
[BUG] Unexpected token on "prisma generate" with "@TsED.Ignore()" in schema

### ISSUE THREAD

**Issue by xferqr** [TypedProject/ts-express-decorators#2089]
![tsed_20220915010116](https://user-images.githubusercontent.com/45597852/190271856-fc5ac086-5aec-47c7-8c64-d031375f5175.png)

**Comment by Romakita** [comment]
Problem is here: https://github.com/tsedio/tsed/blob/production/packages/orm/prisma/src/generator/utils/parseDocumentationAttributes.ts

Unit can be updated here: https://github.com/tsedio/tsed/blob/production/packages/orm/prisma/src/generator/utils/parseDocumentationAttributes.spec.ts
