### ISSUE TITLE
[BUG] @Default does not take effect

### ISSUE THREAD

**Issue by sh-winter** [TypedProject/ts-express-decorators#2098]
## Information

- **Version:** 6.x
- Packages: @tsed/json-mapper

During deserialization, the default value set by @ Default is not applied

## Example

```ts
import { deserialize } from '@tsed/json-mapper';
import { Default } from '@tsed/schema';

export class Test {
  @Default(0)
  prop: number;
}

const test = deserialize({}, { type: Test });
console.log(test);  // => {}
```

## Acceptance criteria

- `{ prop: 0 }`

**Comment by Romakita** [comment]
This decorator is just for swagger documentation and has no effect on property value. 
It’s totally intented.

Correct code:

```ts
export class Test {
  @Default(0)
  prop: number = 0
}

```
