### ISSUE TITLE
💚 This is my experience and my contribution! Thank you 🙏

### ISSUE THREAD

**Issue by borjapazr** [TypedProject/ts-express-decorators#2108]
# 🧪 This is my experience and my contribution! 

About a year ago, I started developing a production-ready template with `Node.js`, `Express.js`, `TypeScript`, etc. using [routing-controllers](https://github.com/typestack/routing-controllers) as framework/base library. Although this stack was good, `routing-controllers` was not being maintained by the community, which made me suspicious as I had discovered several issues.

In this issue https://github.com/typestack/routing-controllers/issues/900 It was questioned if the project was dead and the developers did not give an answer, so I wanted to look for an alternative. I evaluated the possibility of using [NestJS](https://nestjs.com/), but it seemed to me that this framework was going to add too much rigidity to my template and it was going to be too coupled to the framework. After reviewing other frameworks carefully I came across [Ts.ED](https://tsed.io). I can only say that since I discovered it I fell in love with it.

The migration from `routing-controllers` to `Ts.ED` was very easy, on the one hand due to the architecture I had chosen to implement the template (Hexagonal Architecture) and, on the other hand, the ease of use of `Ts.ED`. During the migration I only encountered a single bug, which I reported and in less than three days it was solved.

> The template I created is this one: [borjapazr/express-typescript-skeleton](https://github.com/borjapazr/express-typescript-skeleton). If you find it interesting and want to use it as an example of using Ts.ED, go ahead, I would be more than happy.

My intention is to try to use my template as a base for all the `Node.js` projects that are made in the area where I work in my company.

**It only remains for me to say thank you very much. If at any time you need support with the development I will be happy to help 🚀**

**Comment by Romakita** [comment]
Thanks a lot @borjapazr for your message :)

Your template is awesome and should be added on our website. You can add your repository on this page:
https://v6.tsed.io/getting-started/#project-examples

(or create a new section to present your project template)

See you and thanks again :)

**Comment by borjapazr** [comment]
Thankk you, @Romakita.

I just created [a PR](https://github.com/tsedio/tsed/pull/2109) to add the template to the Ts.ED project examples.

Thank you again 🙏
