### ISSUE TITLE
[BUG] Enum in query param work is incorrect

### ISSUE THREAD

**Issue by thanhchuongbmd** [TypedProject/ts-express-decorators#2112]
## Information

- **Version:** 6.133.0
- Packages:
 "@tsed/ajv": "6.133.0",
    "@tsed/common": "6.133.0",
    "@tsed/core": "6.133.0",
    "@tsed/di": "6.133.0",
    "@tsed/exceptions": "6.133.0",
    "@tsed/json-mapper": "6.133.0",
    "@tsed/platform-express": "6.133.0",
    "@tsed/schema": "6.133.0",
    "@tsed/swagger": "6.133.0",
    "@tsed/typeorm": "6.133.0",

In case I import enum from a other module, the swagger docs understand enum is a object, I wana it a string, but enum in file it's work correctly. Because when I send query param is "NEW", it's throw error 'Bad request on parameter \"request.query.status\".\nValue must be object. Given value: \"NEW\"'

## Example

```ts
import { Controller, Post, UseAuth, Req, Request, Res, Response, HeaderParams, BodyParams, Get, PathParams, QueryParams, Delete, Patch } from '@tsed/common';
import { CustomerStatus } from '../entity/Customer';

enum CustomerStatusOk {
    New = 'NEW'
}

@Get('')
async getAll(
    @QueryParams('status') status: CustomerStatus, //error
    @QueryParams('statusOk') statusOk: CustomerStatusOk, // ok
    @Req() req: Request,
    @Res() res: Response
) {
}
```

**Comment by Romakita** [comment]
hello @thanhchuongbmd 
Please take a time to read the doc before opening issue ^^

https://tsed.io/docs/model.html#enumerated-values

```ts
@Get('')
async getAll(
    @QueryParams('status') status: CustomerStatus, //error
    @QueryParams('statusOk') @Enum(CustomerStatusOk) statusOk: CustomerStatusOk
) {
}

```

> don’t inject req/res if it’s not necessary. Prefer returning object (or use `@Context` instead https://tsed.io/docs/request-context.html).

See you
Romain

**Comment by thanhchuongbmd** [comment]
> hello @thanhchuongbmd Please take a time to read the doc before opening issue ^^
> 
> https://tsed.io/docs/model.html#enumerated-values
> 
> ```ts
> @Get('')
> async getAll(
>     @QueryParams('status') status: CustomerStatus, //error
>     @QueryParams('statusOk') @Enum(CustomerStatusOk) statusOk: CustomerStatusOk
> ) {
> }
> ```
> 
> > don’t inject req/res if it’s not necessary. Prefer returning object (or use `@Context` instead https://tsed.io/docs/request-context.html).
> 
> See you Romain

Thanks for your help!
