### ISSUE TITLE
Incomplete documentation on how to connect TsEd with ObjectionJS

### ISSUE THREAD

**Issue by icode247** [TypedProject/ts-express-decorators#2119]
## Information

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

```ts
import {} from "@tsed/common";
```

**Describe alternatives you've considered**

## Acceptance criteria

- [ ] Criteria 1

**Comment by Romakita** [comment]
Hello @icode247 
Please take a time to fill the issue correctly and follow the guideline.

The documentation is complete and describe how you can create connection configuration for knex. See this page:

https://tsed.io/tutorials/objection.html#installation

Until, you haven't clarify your issue, I won't be able to give you a correct answer :)

See you
Romain
