### ISSUE TITLE
[BUG] Can not inject socket service and connection event not trigger

### ISSUE THREAD

**Issue by thanhchuongbmd** [TypedProject/ts-express-decorators#2125]
## Information

- **Version:** 6.121.0
- Packages:
"@tsed/common": "6.121.0",
    "@tsed/core": "6.121.0",
    "@tsed/di": "6.121.0",
    "@tsed/engines": "6.121.0",
    "@tsed/exceptions": "6.121.0",
    "@tsed/json-mapper": "6.121.0",
    "@tsed/platform-express": "6.121.0",
    "@tsed/schema": "6.121.0",
    "@tsed/socketio": "^7.1.1",
    "@tsed/swagger": "6.121.0",
    "@tsed/typeorm": "6.121.0",
     "socket.io": "^4.5.3"

- Issue: The socket event not trigger ($onNamespaceInit, $onConnection) and can not inject service into controller (throw error, see image)
<img width="1090" alt="Screen Shot 2022-10-17 at 13 30 02" src="https://user-images.githubusercontent.com/67777599/196104602-75abe9e1-dfea-446d-b9c7-599f8591e905.png">

## MySocketService.ts

```ts
import { Args, Emit, Input, IO, Nsp, Socket, SocketService, SocketSession } from "@tsed/socketio";
import * as SocketIO from "socket.io";

@SocketService("/socket")
export class MySocketService {
    @Nsp nsp: SocketIO.Namespace;


    constructor(@IO private io: SocketIO.Server) { }

    /**
     * Triggered the namespace is created
     */
    $onNamespaceInit(nsp: SocketIO.Namespace) {
        console.log('onNamespaceInit:', nsp)

    }

    /**
     * Triggered when a new client connects to the Namespace.
     */
    $onConnection(@Socket socket: SocketIO.Socket, @SocketSession session: SocketSession) {
        console.log('socket onConnection:', socket)

    }

    @Input(SocketEvent.JoinRoom)
    @Emit(SocketEvent.JoinRoom)
    async joinRoom(@Args(0) data: { token: string, room: string }, @Socket socket: Socket) {
        console.log('socket joinRoom:', socket)
        const { token, room } = data
        return { status: true, total: 0 }
    }

    /**
     * Triggered when a client disconnects from the Namespace.
     */
    $onDisconnect(@Socket socket: SocketIO.Socket) {
        console.log('onDisconnect:', socket)

    }
}

export enum SocketEvent {
    JoinRoom = 'JOIN_ROOM'
}
```

## ExampleController.ts

```ts
import { Controller, UseAuth, Req, Get, Res, Response, HeaderParams, PathParams, QueryParams, Post, BodyParams } from '@tsed/common';

@Controller("/example)
@Docs("example")
export class ExampleController {
    constructor(private mySocketService: MySocketService) { }
}
```

**Comment by Romakita** [comment]
Hello @thanhchuongbmd 
I've mix tsed version. This is the first guideline displayed when you update or install a Ts.ED module:

<img width="933" alt="Capture d’écran 2022-10-17 à 08 55 02" src="https://user-images.githubusercontent.com/1763311/196109005-0e2d2319-c0da-4db1-a958-8e62d7c36d67.png">

Please follows the rules before opening issue ;)

See you
Romain
