### ISSUE TITLE
Usage of servers in the Open Api specification with mount prefix

### ISSUE THREAD

**Issue by borjapazr** [TypedProject/ts-express-decorators#2127]
Currently, when all controllers of an API are loaded using the `mount` parameter of the global configuration, they are assigned the same prefix in the `Open API` specification as shown in the following image.

![CleanShot 2022-10-17 at 16 46 16@2x](https://user-images.githubusercontent.com/9295713/196208469-5487cf60-145a-4767-b7e9-71c79afb9d80.png)
![CleanShot 2022-10-17 at 16 47 07@2x](https://user-images.githubusercontent.com/9295713/196208666-404d99d0-2182-49c7-a691-3bf0dedf2dc7.png)

The question is. Is there currently any way to remove this common prefix from all endpoints and configure it, for example, in the servers section of the `Open Api` specification?

![CleanShot 2022-10-17 at 16 48 39@2x](https://user-images.githubusercontent.com/9295713/196209325-0eeba43c-19c2-4893-b1bc-92d1138fbc6a.png)

![CleanShot 2022-10-17 at 16 50 16@2x](https://user-images.githubusercontent.com/9295713/196209516-59f66d31-dd2e-44e8-92ca-3371ffc8dda9.png)

Currently, if the servers section is configured in the `Open Api` specification, the path that is configured is concatenated to the prefix defined in the `mount` configuration.

Thanks in advance 🙏

**Comment by Romakita** [comment]
It’s not possible and I haven’t time to support this comestic usage unfortunatly. Just remove /api from config because isn’t supposed to change when you build your application ;)

see you

**Comment by Romakita** [comment]
You can set "/" instead "/api" on servers

**Comment by Romakita** [comment]
Also, tsed support various configuration. Mount option can many root paths, not onlu /api or /rest. In this case your needs isn’t possible.

**Comment by borjapazr** [comment]
Thank you very much, @Romakita . It was just to confirm. It's nothing blocking or extremely necessary, so I close the issue.

Thank you again 🙏
