### ISSUE TITLE
Required validation on parameters is not enforced unless UseValidation used

### ISSUE THREAD

**Issue by gullerya** [TypedProject/ts-express-decorators#2130]
## Information

- **Version:** 6.114.18
- Packages:

I'm using `@Required()` in front of couple of parameters in my controller, but that is not effective until added `@UseValidation` decorator as well.
Is it supposed to be so? If yes - then all of the documentation should be updated.
I'd actually expect `@Required()` alone to be sufficient.

## Example

```ts
import { Controller, Get, HeaderParams, UseValidation } from '@tsed/common';
import { Required, Returns } from '@tsed/schema';

@Controller('/test')
export class TestCtrl {

	@Get()
	@Returns(200)
	public test(
		@UseValidation() @Required() @HeaderParams('x-a') a: string,
		@UseValidation() @Required() @HeaderParams('x-b') b: number
	) {
		return {};
	}
}
```

## Acceptance criteria

- [ ] Throw 400 without `@UseValidation` decoration

Right now, if not using that, it passes 200 OK.

**Comment by Romakita** [comment]
Hello @gullerya 

Yes, by default the headerParams doesn't run validator. It can be changed by using that:

```typescript
@HeaderParams('x-a', {useValidation: true})
```

I agree this point isn't documented on the website. I'll fix that.

**Comment by Romakita** [comment]
This PR add more details HeaderParams decorator:
https://github.com/tsedio/tsed/pull/2131
