### ISSUE TITLE
[FEAT] @tsed/prisma should create classes for prisma type definitions

### ISSUE THREAD

**Issue by aksharp12** [TypedProject/ts-express-decorators#2135]
## Information

- **Version:** 7.2.3
- Packages:
- @prisma/client: 4.5.0

prisma schema.prisma files allow the definition of type which can provide type safety for su-objects in a model. When using the @tsed/prisma generator, there is an exception that is thrown stating that there was an exception trying to access a property of name which is undefined.

The exception occurs [here](https://github.com/tsedio/tsed/blob/19f9cb5fee7f0f944790c2c38de860cab5bfdc2a/packages/orm/prisma/src/generator/utils/generateModels.ts#L11) and [here](https://github.com/tsedio/tsed/blob/19f9cb5fee7f0f944790c2c38de860cab5bfdc2a/packages/orm/prisma/src/generator/utils/generateRepositories.ts#L41). The issue is that tsed only checks for models and no other objects that are supported by prisma

## Example

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["interactiveTransactions"]
}
datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}
generator tsed {
  provider = "tsed-prisma"
  output   = "../node_modules/prisma"
}
model User {
  /// @TsED.Groups("!creation")
  id        String   @id @default(auto()) @map("_id") @db.ObjectId
  /// @TsED.Email()
  email     String   @unique
  info      Info
  /// @TsED.Groups("!creation")
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
type Info {
  firstName String
  lastName  String
}
```

## Acceptance criteria

- [ ] running prisma generate, while using the @tsed/prisma generator and having types outside of just model in the schema.prisma, should successfully generate the correct classes and models.

**Comment by Romakita** [comment]
Hello @aksharp12 

Thank you for the PR ;)

I think the Type should be an interface and not a class. right ?

See you
Romain

**Comment by aksharp12** [comment]
Not a problem at all, @Romakita!

Yes, I would think that an interface would be enough. There is no need for a repository to be generated either since types are referenced in models for prisma

**Comment by Romakita** [comment]
Finally, the generator will generate a class. It's better to have class for the json-mapper and there is no extra code to support it :)

**Comment by Romakita** [comment]
@aksharp12  PR Ready https://github.com/tsedio/tsed/pull/2175
