### ISSUE TITLE
Update cache-manager to latest to support refreshThreshold

### ISSUE THREAD

**Issue by petermenkeepsilon** [TypedProject/ts-express-decorators#2145]
## Information

**Is your feature request related to a problem? Please describe.**
When using the "memory" cache and the `@UseCache` decorator, the `refreshThreshold` option does not work because [cache-manager@^4](https://github.com/node-cache-manager/node-cache-manager/blob/4.1.0/lib/stores/memory.js) does not have a `ttl` method. [cache-manager@^5](https://github.com/node-cache-manager/node-cache-manager/blob/master/src/stores/memory.ts#L66) does have the `ttl` method.

**Describe the solution you'd like**
Update the dependencies of `@tsed/platform-cache` to include cache-manager@^5 instead of cache-manager@^4, so that the "memory" cache store works with the `refreshThreshold` option of `@UseCache`.

**Describe alternatives you've considered**
Suggest in the documentation an alternative memory cache package to use that satisfies the above requirements. 

## Acceptance criteria

- [ ]  The "memory" cache store works with the `refreshThreshold` option of `@UseCache`.

**Comment by Romakita** [comment]
Hello @petermenkeepsilon 
Thanks for your Issue :)

PR is welcome. I think the change will be on the package.json here : 

https://github.com/tsedio/tsed/blob/production/packages/platform/platform-cache/package.json#L25

The change isn't a breaking change so it could be integrated on the v7 release :)

See you
Romain

**Comment by Romakita** [comment]
PR ready

**Comment by petermenkeepsilon** [comment]
Thanks you @Romakita!
