### ISSUE TITLE
[BUG] mysql datasource create tell status 201 but not created

### ISSUE THREAD

**Issue by Paul75** [TypedProject/ts-express-decorators#2146]
## Information

- **Version:** 7.2.3
- Packages:

A few sentences describing the overall goals of the issue.

When Create line on BDD with TypeOrm, it response 201 but not created on database...

## Example

```ts
import {Controller, Inject} from "@tsed/di";
import { BodyParams } from "@tsed/platform-params";
import {Get, Post, Status} from "@tsed/schema";
import { MYSQL_DATA_SOURCE } from "../../datasources/MysqlDatasource";
import { DataSource } from "typeorm";
import { Artiste } from "../../entities/Artiste";

@Controller("/artistes")
export class ArtistesController {
  @Inject(MYSQL_DATA_SOURCE)
  protected mysqlDataSource: DataSource;
  
  @Get("/")
  getList(): Promise<Artiste[]> {
    return this.mysqlDataSource.manager.find(Artiste);
  }

  @Post("/")
  @Status(201)
  create(@BodyParams() artiste: Artiste): Promise<Artiste> {
    console.log("BodyParams => " + artiste);

    return this.mysqlDataSource.manager.create(Artiste, [artiste]);
  }
}
```

Thanks for help

**Comment by Paul75** [comment]
Hello,

When I do this (use save and not create) :

```
import {Controller, Inject} from "@tsed/di";
import { BodyParams } from "@tsed/platform-params";
import {Get, Post, Status} from "@tsed/schema";
import { MYSQL_DATA_SOURCE } from "../../datasources/MysqlDatasource";
import { DataSource } from "typeorm";
import { Artiste } from "../../entities/Artiste";

@Controller("/artistes")
export class ArtistesController {
  @Inject(MYSQL_DATA_SOURCE)
  protected mysqlDataSource: DataSource;
  
  @Get("/")
  getList(): Promise<Artiste[]> {
    return this.mysqlDataSource.manager.find(Artiste);
  }

  @Post("/")
  @Status(201)
  save(@BodyParams() artiste: Artiste): Promise<Artiste> {
    // return this.mysqlDataSource.manager.create(Artiste, [artiste]);
    return this.mysqlDataSource.manager.save(artiste);
  }
}
```

it works .....

**Comment by Romakita** [comment]
Hello @Paul75,

it seems to be an issue with typeorm itself or a bad understanding from you about the typeorm API.

I won’t be able to help, because this question must be answered and clarifyed by the typeorm team ;)

I propose to close this issue!

See you

**Comment by Romakita** [comment]
Also to  clarify the decorator Status behavior.

Status will always return the given status (here 201) independently of the executed code in inside controller method (lib or framework). The status change only if an exception occurs from your code. So, Starus is agnotics from the typeorm or other library. If you want a dynamic status depending on your usecase you have to call the `ctx.response.status(2xx)` explicitly in your code.

See you
