### ISSUE TITLE
[BUG] Deployment to npm registry does not fail the release action job

### ISSUE THREAD

**Issue by StefanPuia** [TypedProject/ts-express-decorators#2149]
## Information

- **Version:** 7.2.4

The release to npm has failed in this pipeline, but the action itself completed succesfully
https://github.com/tsedio/tsed/actions/runs/3356587797/jobs/5561840132#step:5:7125

```
You cannot publish over the previously published versions: 7.2.4.
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.
```

Not sure if this was just a one-off thing, but it would be worth for the exit code to be propagated up to the action, so that the failure can be registered.

**Comment by Romakita** [comment]
Aïe :( 
Thanks for the issue I’ll take a time to investigate!

**Comment by Romakita** [comment]
It's fixed :)
Thanks for the issue!
