### ISSUE TITLE
[BUG] Using OIDCRedisAdapter results in invalid_grant  from the token endpoint for authorization_code grants

### ISSUE THREAD

**Issue by mockorp** [TypedProject/ts-express-decorators#2161]
## Information

- **Version:** 7.2.3
- Packages: @tsed/adapters-redis

When attempting to use the OIDCRedisAdapter, all attempts at performing an exchange from a code to a refresh/access token via the token endpoint will result in an invalid_grant error.

The full reproduction of this requires a complete OIDC implementation, but the underlying issue can be reproduced more easily.

The full behavior that happens with a complete implementation is as follows:

The main auth flow works correctly and issues an Authorization Code. However, when the OIDCRedisAdapter saves the Authorization Code, a bug in the RedisAdapter causes the Authorization Code to be saved with a uuid as the ID instead of the Authorization Code itself as intended. When the token endpoint is then called to exchange the Authorization Code, it cannot be found since it was saved with a UUID instead of the code itself as a key. This results in an invalid_grant since the Authorization Code cannot be found.

The underlying bug behind this is that the RedisAdapter's findById implementation for hgetall is flawed. The hgetall method returns an empty object when no item is found. However, the implementation of findBydId expects the result to be a falsy value in the implementation:

```ts
    if (!item) {
      return undefined;
    }
```

In the Authorization Code scenario, this causes a cascading issue:

1. The upsert call attempts to findById to see if this is a new or existing record
2. Since findById returns an empty object, the calls is interpreted as an update instead of an insert
3. The update method is called which assigns a new uuid since the logic in upsert that assigns the id is bypassed
4. This leaves the Authorization Code unfindable since it does not have a valid id.

While this all takes quite a bit of setup and discovery to debug and reproduce, the actual issue is rather easy to demonstrate via the RedisAdapter itself. The example includes a new unit test for RedisAdapter that demonstrates the issue.

## Example

```ts
    // Within RedisAdapter.spec.ts for findById()
    it("should handle no item found by id (hgetall)", async () => {
      const {adapter} = await createAdapterFixture<any>({
        collectionName: "AuthorizationCode",
        model: Object
      });

      const result = await adapter.findById("does not exist");

      // fails, an empty object is not falsy and the logic to return undefined is not triggered.
      expect(result).toBeFalsy();
    });
```

## Acceptance criteria

- [ ] The RedisAdapter findById implementation returns undefined for records that are not found
- [ ] Using OIDCRedisAdapter in a full OIDC solution allows Authorization Codes to be used as grants to the token endpoint.

**Comment by mockorp** [comment]
I created https://github.com/tsedio/tsed/pull/2162 which includes the test to reproduce this issue as well as the resolution.

**Comment by Romakita** [comment]
hello @mockorp 

perfect issue. I’ll compare the redis adapter with the custom redis adapter implemented for one of my client. I think we already have fixed that, but isn’t repported on the opensource module ;)

see you

**Comment by Romakita** [comment]
merged :)
