### ISSUE TITLE
It is recommended to avoid using the default export of socketio io

### ISSUE THREAD

**Issue by sh-winter** [TypedProject/ts-express-decorators#2165]
path: `tsed/packages/third-parties/socketio/src/services/SocketIOService.ts`

It is recommended to use '* as SocketIO' to replace the default export, because such writing method will throw an error when using 'rollup' packaging.

Poor English, machine translation is used, thanks for understanding.

**Comment by sh-winter** [comment]
![image](https://user-images.githubusercontent.com/48613217/202355504-8f233002-9ee3-4ce1-bf55-280e01f6e9de.png)
`socket.io` does not provide a default export.

**Comment by Romakita** [comment]
Hum… what the report between Ts.ED and rollup? 

Rollup is a front-end bundler and tsed is a backend framework. I hope you don’t use it to build your code for a backend environment!!!
Because I won’t support it!
See you

**Comment by sh-winter** [comment]
The error report is as follows:
![image](https://user-images.githubusercontent.com/48613217/202365372-91e94332-a806-45e7-a452-a5a8ffe645d1.png)

**Comment by sh-winter** [comment]
> Hum… what the report between Ts.ED and rollip?
> 
> Rollup is a front-end bundler and tsed is a backend framework. I hope you don’t use it to build your code for a backend environment!!! Because I won’t support it! See you

Yes, I understand, but I need to build an extremely compact Docker image because the production environment is very sensitive to the image size

**Comment by sh-winter** [comment]
It is only necessary to make such modifications:
![image](https://user-images.githubusercontent.com/48613217/202366557-67405501-b5eb-4e84-b661-efd7d79d21a5.png)

**Comment by Romakita** [comment]
You are free to make a PR. If the test passed, I'll merge it. 

Rollup support default export, and my tsconfig use esInteropModule so it should be correctly supported. I think they many library that use default export, or commonjs exports so asking all projects to change that will be complicated instead of fixing rollup / tsconfig on your side.

See you

**Comment by sh-winter** [comment]
Thank you Bye

**Comment by Romakita** [comment]
@sh-winter  again your are free to make a PR ;)
It’ll take few minutes for you!
See you

**Comment by sh-winter** [comment]
After making changes, I don't know why the test failed, so I used `patch-package` locally to solve this problem.

**Comment by Romakita** [comment]
The ci can confirm if it’s just a timeout or a real problem. Try to push the change on the repo and create a PR. 

see you ;)
Romain

**Comment by sh-winter** [comment]
@Romakita Sorry, I'm still uncertain. Do you want to run the `npm run build` command before submitting?

**Comment by Romakita** [comment]
No. Just push the code and we'll see if there is an issue with unit test :)

**Comment by sh-winter** [comment]
Thanks you @Romakita!
