### ISSUE TITLE
[BUG] @tsed/common is missing "accepts" dependency

### ISSUE THREAD

**Issue by jojoxd** [TypedProject/ts-express-decorators#2182]
## Information

I'm trying to use PlatformTest to test a service (That actually does little with requests)

- **Version:** 7.8.0
- Packages:
  - @tsed/common
  - @tsed/core
  - @tsed/exceptions
  - @tsed/platform-params
  - @tsed/schema

## Example

PlatformTest uses the "accepts" package, but it isn't defined in the package.json.
https://github.com/tsedio/tsed/blob/production/packages/platform/common/src/services/PlatformTest.ts

## Acceptance criteria

- [ ] @tsed/common has the "accepts" package defined in it's package.json, or the docs should be changed to reflect that you need to install it yourself (optional peerDependency)

**Comment by Romakita** [comment]
Hello @jojoxd 
Accepts is an express dependencies. Maybe it’s missing if you use koa.js.

You can make a PR to fix that if you have a time ;) 
See you

**Comment by Romakita** [comment]
Fixed
