### ISSUE TITLE
Make Ts.ED Core work in browser environments

### ISSUE THREAD

**Issue by endurance** [TypedProject/ts-express-decorators#2194]
## Information

`@tsed/schema` allows me to decorate my Typescript types, and generate a JSON Schema, which is an amazing tool.

It depends on `@tsed/core` which seems to fail to build in a Browser environment (e.g. running `webpack` with node disabled)

I'd like to be able to use this tool isomorphically, so I don't have have to make a different build between browser and node environments.

I have an example project that I believe can serve as a good test.

After applying browserify on the dependencies, this is the final error.

<img width="1466" alt="image" src="https://user-images.githubusercontent.com/872355/208458825-a47bd808-9736-4f11-bc89-d323b3b4f68c.png">

If i don't apply `browserify` to the depenencies, `webpack` will just have tons of hard errors against `fs`, etc...

The example is working, so it does show that we can run Core/Schema if the Core library were to install Browser friendly dependencies

## Acceptance criteria

- Mainly, allow Ts.ED's Core and Schema package to be workable on browser environments.

## EXAMPLE REPO

https://github.com/endurance/tsed-isomorphic-example

## Suggestions

- https://hackernoon.com/building-isomorphic-javascript-packages-1ba1c7e558c5

**Comment by Romakita** [comment]
Released with v7.10 :)
