### ISSUE TITLE
[BUG] Generics OnSerialize not being called

### ISSUE THREAD

**Issue by ecalvert** [TypedProject/ts-express-decorators#2195]
## Information

- **Version:** 7.9.0
- Packages:

Hooks are not being executed when serializing a generic model.  In the provided example repo in the [rest/HelloWorldController ](https://github.com/ecalvert/tsed-repro/blob/master/src/controllers/rest/HelloWorldController.ts)there are 2 routes. One that behaves as expected and one that doesn't.  If the class that is being serialized contains a generic, the `OnSerialize` decorator function is never being called. The `/good` route correctly returns the `name` property transformed, while the `/bad` route does not. This makes it difficult to reliably re-use response models throughout an application.

## Example

https://github.com/ecalvert/tsed-repro

## Acceptance criteria

- [ ] Alter hooks should be executed for generic models the same way they are for non-generic models.

## Additional Context

We don't use Mongoose or any other ORM.  We generally take the raw results from an executed mongo query and are relying on TSED to do the serialization to the client for us.

**Comment by Romakita** [comment]
Hello @ecalvert 

thanks for the repo example.

I see an error on your example:
```ts

 @Get("/bad")
  @Returns(200, PagedModel<PeopleResponse>)
  get() {
    return {
      data: [{
        id: 'foo',
        name: 'bar'
      }]
    }
  }
```
The Returns decorator is wrongly declarated. The documentation is pretty clear and give an example to implement the Returns decorator with a generic model:  https://tsed.io/docs/model.html#generics

```ts

 @Get("/bad")
  @Returns(200, PagedModel).Of(PeopleResponse)
  get() {
    return {
      data: [{
        id: 'foo',
        name: 'bar'
      }]
    }
  }
```
Please fix your example ;)

See you
Romain

**Comment by ecalvert** [comment]
@Romakita Thank you for the quick response.  I [updated the decorator](https://github.com/ecalvert/tsed-repro/blob/master/src/controllers/rest/HelloWorldController.ts#L27) and the `@OnSerialize` function is still not being executed. 

Hitting `http://localhost:8083/rest/hello-world/bad` is still returning: 

```json
{
  "data": [
    {
      "id": "foo",
      "name": "bar"
    }
  ]
}
```

when we would expect it to return:

```json
{
  "data": [
    {
      "id": "foo",
      "name": "BAR"
    }
  ]
}
```

After doing some digging it looks like there is some special checks that happen when deserializing a generic here: https://github.com/tsedio/tsed/blob/production/packages/specs/json-mapper/src/utils/deserialize.ts#L189-L202

But there is no generic check when serializing in https://github.com/tsedio/tsed/blob/production/packages/specs/json-mapper/src/utils/serialize.ts

Could this be part of the issue?

**Comment by Romakita** [comment]
In your exemple you don’t return a real instance of PagedModel. It could explain the issue.
