### ISSUE TITLE
[BUG] Order of `@Model` and `@DiscriminatorValue` decorators can result in wrong discriminator value

### ISSUE THREAD

**Issue by ochrstn** [TypedProject/ts-express-decorators#2227]
## Information

- **Version:** 7.13.1
- Packages: `@tsed/schema`, `@tsed@mongoose`

Order of `@Model` and `@DiscriminatorValue` decorators can result in wrong (default) discriminator value.

## Example

```ts
import {DiscriminatorKey, DiscriminatorValue, Property, Required} from "@tsed/schema";

@Model()
export class Event {
  @DiscriminatorKey()
  type: string;

  @Property()
  value: string;
}

@Model()
@DiscriminatorValue("page_view")
export class PageView extends Event {
  @Required()
  url: string;
}
```

Because of this line here:

https://github.com/tsedio/tsed/blob/production/packages/orm/mongoose/src/decorators/model.ts#L51

the custom discriminator value gets overwritten by the class name, based on the order of the decorators.

This works:

```ts
@DiscriminatorValue("page_view")
@Model()
export class PageView extends Event {
// ...
```

Also still works (but deprecated):
```ts
@Model({ discriminatorValue: "page_view" })
export class PageView extends Event {
// ...
```

## Acceptance criteria

- [ ] Discriminator value should not depend on the order of the `@Model` and `@DiscriminatorValue` decorators.

**Comment by Romakita** [comment]
Haaa okey :D

I don't know why exactly I need to declare discriminator value for all declared model.

Replacing this line:

```ts
DiscriminatorValue(options.discriminatorValue || nameOf(target))(target);
```

by:
```ts
options.discriminatorValue && DiscriminatorValue(options.discriminatorValue)(target);
```
should works as expected!

See you

**Comment by Romakita** [comment]
Ok this line is to init the discriminator value from class name.

But it's a bad behavior it think, because isn't intended to have a default discriminator value for each declared model. And I think isn't used like that in a real project.
