### ISSUE TITLE
Allow exporting enums in openapi specs components.schema section

### ISSUE THREAD

**Issue by edwinveldhuizen** [TypedProject/ts-express-decorators#2237]
## Information

**Is your feature request related to a problem? Please describe.**
Currently we define and use enums, like:
```ts
export enum PlatformID {
    gp = 'gp',
    sp = 'sp',
    vi = 'vi',
    vn = 'vn',
    vp = 'vp',
}
```

And use this in several places, e.g. in endpoints:
```ts
@PathParams('platform')
@Enum(PlatformID)
platform?: PlatformID,
```

and several model properties:
```ts
@Required()
@Enum(PlatformID)
platformID: PlatformID;
```

The current result is that in the openapi specs we have **16** times the exact following block in our openapi documentation:
```
"schema": {
  "type": "string",
  "enum": [
    "gp",
    "sp",
    "vi",
    "vn",
    "vp"
  ]
}
```

Besides that, the generated php, typescript, swift and kotlin clients will have no exported enum with these values, so to work with it we manually need to add the exact same enum in each code base.

**Describe the solution you'd like**

Something like
```ts
@Enum(PlatformID, 'PlatformID')
export enum PlatformID {
    gp = 'gp',
    sp = 'sp',
    vi = 'vi',
    vn = 'vn',
    vp = 'vp',
}
```
or
```ts
@PathParams('platform')
@Enum(PlatformID, 'PlatformID')
platform?: PlatformID,
```
or
```ts
export enum PlatformID {
    gp = 'gp',
    sp = 'sp',
    vi = 'vi',
    vn = 'vn',
    vp = 'vp',
}
enums(PlatformID).label("PlatformID") => Returns a JsonSchema instance
```

That will then use and reference to one components/schemas/PlatformID

**Describe alternatives you've considered**
Ideally all used Enums in @Enum() would be exported, but @Romakita responded:
> "Enum haven't name that can be used to declare it in components.schemas section. "

Or extracting the Enum definition from the TypeScript code by inspecting the AST:
- ts.ed generates the OAS
- Extract the enum definitions by inspecting the AST and add them to the OAS
- Replace inline enums with references to the corresponding enum definitions. Matching is done by comparing the list of enum values. (This won’t work if 2 enum definitions have the same values.)
@Romakita mentioned on this proposal:
> "Not a solution. Implement AST will introduce a huge effort for a small benefits. And the enum name isn’t the necessary the name that you to expose to your consumers. The most simple solution could be to use a function to associate the enum to a label (and add it to a small registry):"

## Acceptance criteria

- [ ] Used enums will be added to and referenced from components/schemas/

**Comment by Romakita** [comment]
https://github.com/tsedio/tsed/pull/2273 @edwinveldhuizen  ;)

**Comment by Romakita** [comment]
Selected solution:

```ts
import {enums} from "@tsed/schema";

enum ProductTypes {
  ALL = "ALL",
  ASSETS = "ASSETS",
  FOOD = "FOOD"
}

enums(ProductTypes).label("ProductTypes");

// in models
class Product {
  @Property()
  title: string;

  @Enum(ProductTypes)
  type: ProductTypes;
}

// in controller

import {Enum} from "@tsed/schema";
import {QueryParams, Controller} from "@tsed/common";

@Controller("/products")
class ProductsController {
  @Get("/:type")
  @Returns(200, Array).Of(Product)
  async get(@PathParams("type") @Enum(ProductTypes) type: ProductTypes): Promise<Product> {
    return [new Product()];
  }
}
```
