### ISSUE TITLE
Specify the OpenAPI schema name when using the @Groups decorator

### ISSUE THREAD

**Issue by michael-pxr** [TypedProject/ts-express-decorators#2249]
## Information

When the `@Groups` decorator is used in a controller, the OpenAPI Specification (OAS) will create schemas with names specific to the used groups.
For example, given this controller
```ts
@Controller('/news')
class NewsController {
    async create(
        @BodyParams()
        @Groups('action.create', 'scope.admin')
        @Required()
        news: News,
    ) {
        // ...
    }
}
```

the OAS will contain a schema named `NewsActionCreateScopeAdmin`.

When we change the groups, the schema will be renamed accordingly. Since our clients are generated from the OAS, a change in the groups will create new types for the clients as well.

To prevent this from happening, we would like to be able to specify the name of the schema instead of having it be generated based on the groups.

You've made a suggestion of possible solutions:
> Maybe something like `@Groups(...).GroupsName()`. or alternative `@Groups("Name", ['groups'])` by introducing another signature

Either solution would be fine.

## Acceptance criteria

When it is possible to specify the name of a schema when using the `@Groups` decorator.

**Comment by Romakita** [comment]
Selected solution:

```ts
@Groups("Name", ['groups'])
@Returns().Groups("Name", ['groups'])
```

Add `"Name"` to the original model name when the groups have an impact on the generated model.
