### ISSUE TITLE
[BUG] Testing with jest using more and more heap memory.

### ISSUE THREAD

**Issue by Krzysztof-Nerwinski** [TypedProject/ts-express-decorators#2253]
## Information

- **Version:** 7.14
- Packages: 
``` "dependencies": {
    "@tsed/ajv": "^7.14.0",
    "@tsed/common": "^7.14.0",
    "@tsed/core": "^7.14.0",
    "@tsed/di": "^7.14.0",
    "@tsed/engines": "^7.14.0",
    "@tsed/exceptions": "^7.14.0",
    "@tsed/json-mapper": "^7.14.0",
    "@tsed/logger": "^6.3.4",
    "@tsed/logger-file": "^6.3.4",
    "@tsed/platform-cache": "^7.14.0",
    "@tsed/platform-exceptions": "^7.14.0",
    "@tsed/platform-express": "^7.14.0",
    "@tsed/platform-log-middleware": "^7.14.0",
    "@tsed/platform-middlewares": "^7.14.0",
    "@tsed/platform-params": "^7.14.0",
    "@tsed/platform-response-filter": "^7.14.0",
    "@tsed/platform-views": "^7.14.0",
    "@tsed/schema": "^7.14.0",
    "@tsed/swagger": "^7.14.0",
    "ajv": "^8.12.0",
    "barrelsby": "^2.5.1",
    "body-parser": "^1.20.1",
    "compression": "^1.7.4",
    "cookie-parser": "^1.4.6",
    "cors": "^2.8.5",
    "cross-env": "^7.0.3",
    "dotenv": "^16.0.3",
    "dotenv-expand": "^10.0.0",
    "dotenv-flow": "^3.2.0",
    "express": "^4.18.2",
    "method-override": "^3.0.0"
  },
  "devDependencies": {
    "@babel/cli": "^7.20.7",
    "@babel/core": "^7.20.12",
    "@babel/node": "^7.20.7",
    "@babel/plugin-proposal-class-properties": "^7.18.6",
    "@babel/plugin-proposal-decorators": "^7.20.13",
    "@babel/preset-env": "^7.20.2",
    "@babel/preset-typescript": "^7.18.6",
    "@tsed/cli-plugin-eslint": "4.2.2",
    "@tsed/cli-plugin-jest": "4.2.2",
    "@tsed/components-scan": "^7.10.0",
    "@types/compression": "^1.7.2",
    "@types/cookie-parser": "^1.4.3",
    "@types/cors": "^2.8.13",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.4.0",
    "@types/method-override": "^0.0.32",
    "@types/multer": "^1.4.7",
    "@types/node": "^18.13.0",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.51.0",
    "@typescript-eslint/parser": "^5.51.0",
    "babel-plugin-transform-typescript-metadata": "^0.3.2",
    "babel-watch": "^7.7.2",
    "eslint": "^8.33.0",
    "eslint-config-prettier": "^8.6.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "^29.4.2",
    "supertest": "^6.3.3",
    "ts-jest": "^29.0.5",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.1.2",
    "tslib": "^2.5.0",
    "typescript": "^4.9.5"
  },
```

First I'd like to thank everyone involved in this very cool framework. The reason I'm createing this issue is because me and my team stumbled on a problem after adding ~500 tests most of them intergration tests.

We're getting the following error in our pipelines:
```FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory```.

To test if same issue occurs on a new project I've created an unmodofied projectwith `tsed init .` command. Below are the options I've chosen:
? Choose the target platform: **Express.js**
? Choose the architecture for your project: **Ts.ED**
? Choose the convention file styling: **Ts.ED**
? Check the features needed for your project **Swagger, Testing, Linter, Bundler**
? Choose unit framework **Jest**
? Choose linter tools framework **EsLint**
? Choose extra linter tools 
? Choose your bundler (Use arrow keys)
❯ **Babel** 

After installing `components-scan` I've tried running `node --expose-gc ./node_modules/.bin/jest --logHeapUsage --detect-leaks` without any modification to tests created on `init`.

It returns that the default tests are leaking:

```
EXPERIMENTAL FEATURE!
    Your test suite is leaking memory. Please ensure all references are cleaned.

    There is a number of things that can leak memory:
      - Async operations that have not finished (e.g. fs.readFile).
      - Timers not properly mocked (e.g. setInterval, setTimeout).
      - Keeping references to the global scope.

      at onResult (node_modules/@jest/core/build/TestScheduler.js:150:18)
      at node_modules/@jest/core/build/TestScheduler.js:254:19
      at node_modules/emittery/index.js:363:13
          at Array.map (<anonymous>)
      at Emittery.emit (node_modules/emittery/index.js:361:23)

```

Even without `--detect-leaks` you can observe heap size growing with every test that bootstraps Server application.
```
 PASS  src/controllers/rest/HelloWorldController.spec.ts (160 MB heap size)
 PASS  src/Server.integration.spec.ts (209 MB heap size)
 PASS  src/controllers/rest/HelloWorldController.integration.spec.ts (209 MB heap size)
```

Do you know about this issue and maybe have a solution we could implement?

**Comment by Romakita** [comment]
Hello @Krzysztof-Nerwinski 

thanks for this issue.

Ts.ED use a lot of integration test but I haven’t constated that. But it’s totally possible. Memory leaks in express app is easy to create it but complicated to solve it.

I haven’t a lot of experience to found memory leaks. I already tried to optimize the framework as is it possible but it’s very complicated. For this issue I need help.

I’ll be happy to help and give the all details needed around the framework architecture and solve this issue.

I’ll make this issue as top priority!

See yoy

**Comment by Romakita** [comment]
https://github.com/Romakita/tsed-jest-memory-leaks

**Comment by Romakita** [comment]
Interesting point. With Koa, Leaks isn't presents:
https://github.com/Romakita/tsed-jest-memory-leaks-koa

So the problem is around the PlatformExpress.ts :D

**Comment by Krzysztof-Nerwinski** [comment]
Nice, that narrows it down, thanks!

I didn't have much time last couple of days. I tried debugging it with chrome inspector but no luck for now.

**Comment by Romakita** [comment]
It seems to be related to the runInContext function combined with Express.js here (https://github.com/tsedio/tsed/tree/production/packages/platform/platform-express/src/components/PlatformExpress.ts):

```typescript
class PlatformExpress {
  useContext(): this {
    const app = this.getPlatformApplication();
    const invoke = createContext(this.injector);

    this.injector.logger.debug("Mount app context");

    app.use(async (request: any, response: any, next: any) => {
      const $ctx = await invoke({request, response});
      await $ctx.start();

      $ctx.response.getRes().on("finish", () => $ctx.finish());

// if we send response immediately here, there is no memory leaks:
// response.send("hello") 

// when it's called, the memory leaks occurs
      return runInContext($ctx, next);
// Note:
// - maybe the memory leaks is under the handlers executed by runInContext? 
// - runInContext in Koa run handlers also and haven't memory leaks
    });

    return this;
  }
}
```

Here the equivalent in PlatformKoa (https://github.com/tsedio/tsed/tree/production/packages/platform/platform-koa/src/components/PlatformKoa.ts):

```typescript
  useContext(): this {
    const app = this.getPlatformApplication();
    const invoke = createContext(this.injector);
    const platformExceptions = this.injector.get<PlatformExceptions>(PlatformExceptions);

    this.injector.logger.debug("Mount app context");

    app.use(async (koaContext: Context, next: Next) => {
      const $ctx = await invoke({
        request: koaContext.request as any,
        response: koaContext.response as any,
        koaContext
      });

      return runInContext($ctx, async () => {
        try {
          await $ctx.start();
          await next();
          const status = koaContext.status || 404;

          if (status === 404 && !$ctx.isDone()) {
            platformExceptions?.resourceNotFound($ctx);
          }
        } catch (error) {
          platformExceptions?.catch(error, $ctx);
        } finally {
          await $ctx.finish();
        }
      });
    });

    return this;
  }
```

In koa, the next function returning a promise will in express next return nothing. So cleaning cleaning resource is more simple in Koa.

Also Ts.ED create circular ref between `PlatformContext`/`PlatformRequest`/`PlatformResponse` (like Koa do).  

that's all i've analyzed so far ^^
See you
