### ISSUE TITLE
[BUG] injecting Ctx doesn't bring request info in graphql resolvers. Cannot access any request header in a resolver method.

### ISSUE THREAD

**Issue by i-void** [TypedProject/ts-express-decorators#2260]
I have a default installation of Ts.ED application using Prisma, TypeGraphql, Koa selected. It created a standard config for graphql like this:

```typescript
export const config: Partial<TsED.Configuration> = {
  version: pkg.version,
  envs,
  logger: loggerConfig,
  graphql: {
    default: {
      path: "/graphql",
      buildSchemaOptions: {
      },
    }
  },
  // additional shared configuration
};
```

I have a user resolver and a simple signup mutation;

```typescript
@ResolverService()
export class UserResolver {
  // ...

  @Mutation(() => User)
  async signUp(
    @Arg('username') username: string,
    @Arg('email') email: string, 
    @Arg('password') password: string,
  ): Promise<User> {
    // const ipAddr = ... <- trying to get ip address of requester
    return this.userService.signUp(ipAddr, email, password, username)
  }

}
```
I tried to inject @Ctx() but it doesn't have request data in it (or I couldn't find).

Also when I use a service injectable along request, I can set a field of it to context by help of a middleware. But when I tried to access it from resolver its field of context become null.

**Comment by Romakita** [comment]
Hello @Romakita 
Isn’t a bug. Typegraphql use its own DI and it’s another framework. All resolver are outside the Ts.ED execution context.
Also`@Context()ˋ can only be used on a Ts.ED controller. 

A potential alternative is to use `getContext` function.

I close this issue ;)

See you
Romain

**Comment by Romakita** [comment]
Maybe ˋInjectContext()` will works.

**Comment by Romakita** [comment]
Or accessing to the request.ctx if typegraphql have a decorator to inject the nodejs request.
