### ISSUE TITLE
[BUG] Prisma model generated by Ts.ED is incompatible with the one generated by Prisma

### ISSUE THREAD

**Issue by borjapazr** [TypedProject/ts-express-decorators#2275]
## Information

- **Version:** 7.x
- Packages: `@tsed/prisma`

@eliectrlshift made a fork of the [production ready template](https://github.com/borjapazr/express-typescript-skeleton) and, created a `Prisma schema` with a one-to-many relationship and when seeding the database gets the following error:

```bash
Type 'ProjectDriveModel' is not assignable to type '(Without<ProjectDriveCreateInput, ProjectDriveUncheckedCreateInput> & ProjectDriveUncheckedCreateInput) | (Without<...> & ProjectDriveCreateInput)'.
  Type 'ProjectDriveModel' is not assignable to type 'Without<ProjectDriveUncheckedCreateInput, ProjectDriveCreateInput> & ProjectDriveCreateInput'.
    Type 'ProjectDriveModel' is not assignable to type 'Without<ProjectDriveUncheckedCreateInput, ProjectDriveCreateInput>'.
      Types of property 'id' are incompatible.
        Type 'number' is not assignable to type 'undefined'.
```

- `Prisma schema`:

```
model Project {
  id                Int             @id @default(autoincrement())
  uuid              String          @unique @db.VarChar(1000)
  publicName        String          @db.VarChar(255)
  privateName       String          @db.VarChar(255)
  slug              String          @db.VarChar(255)
  description       String          @db.VarChar(500)
  projectDrive      ProjectDrive?
  createdAt         DateTime?       @default(now()) @db.Timestamptz(3)
  createdBy         String?         @db.VarChar(255)
  updatedAt         DateTime?       @default(now()) @updatedAt @db.Timestamptz(3)
  updatedBy         String?         @db.VarChar(255)
  deletedAt         DateTime?       @db.Timestamptz(3)
  deletedBy         String?         @db.VarChar(255)
}

model ProjectDrive {
  id                        Int                   @id                                   @default(autoincrement())
  uuid                      String                @unique                               @db.VarChar(1000)
  folderId                  String?               @unique                               @db.VarChar(500)
  name                      String?               @unique                               @db.VarChar(500)
  url                       String?               @db.VarChar(500)
  project                   Project?              @relation(fields: [puid], references: [uuid])
  puid                      String?               @unique
  createdAt                 DateTime?             @default(now())                       @db.Timestamptz(3)
  createdBy                 String?               @db.VarChar(255)
  updatedAt                 DateTime?             @default(now())                       @updatedAt                    @db.Timestamptz(3)
  updatedBy                 String?               @db.VarChar(255)
  deletedAt                 DateTime?             @db.Timestamptz(3)
  deletedBy                 String?               @db.VarChar(255)
}
```

- `ProjectDriveModel` generated by `Ts.ED` :

```
export declare class ProjectDriveModel implements ProjectDrive {
    id: number;
    uuid: string;
    folderId: string | null;
    name: string | null;
    url: string | null;
    project: ProjectModel | null;
    puid: string | null;
    createdAt: Date | null;
    createdBy: string | null;
    updatedAt: Date | null;
    updatedBy: string | null;
    deletedAt: Date | null;
    deletedBy: string | null;
}
```

- `ProjectDriveCreateInput` generated by `Prisma`:

```
export type ProjectDriveCreateInput = {
    uuid: string
    folderId?: string | null
    name?: string | null
    url?: string | null
    project?: ProjectCreateNestedOneWithoutProjectDriveInput
    createdAt?: Date | string | null
    createdBy?: string | null
    updatedAt?: Date | string | null
    updatedBy?: string | null
    deletedAt?: Date | string | null
    deletedBy?: string | null
}
```

- `ProjectDriveUncheckedCreateInput` generated by `Prisma`:

```
export type ProjectDriveUncheckedCreateInput = {
    id?: number
    uuid: string
    folderId?: string | null
    name?: string | null
    url?: string | null
    puid?: string | null
    createdAt?: Date | string | null
    createdBy?: string | null
    updatedAt?: Date | string | null
    updatedBy?: string | null
    deletedAt?: Date | string | null
    deletedBy?: string | null
  }
```

## How to reproduce the issue

1. `git clone https://github.com/eliectrlshift/express-typescript-skeleton-306`
2. `yarn install`
3. `cp .env.exemple .env`
4. Change values for `PostgreSQL` database
5. `yarn run prisma:migrate`
6. `yarn run prisma:seed`

The original issue can be found at the following link: https://github.com/borjapazr/express-typescript-skeleton/issues/306

Thank you in advance 🙏

**Comment by borjapazr** [comment]
Hi, @Romakita 👋. Did you have a chance to review this issue?

Thanks!

**Comment by Romakita** [comment]
Hello @borjapazr ,

I already read the issue. But I haven't time to works on it. Making PR is totally possible!
The code generator is here:

- https://github.com/tsedio/tsed/tree/production/packages/orm/prisma/src

You can start by opening a PR, with a integration test that reproduce the issue: 
-  https://github.com/tsedio/tsed/tree/production/packages/orm/prisma/test

> You can duplicate the mongo or postgres integration test and update the prisma schema and then run the unit test on @tsed/prisma package.

Then we'll try to add some tests to cover your usecase.

Also, you reporting a typescript issue, but you don't give where the problem occurs. I expect at least to have this kind of information :) (is it the generated repository?)

See you
Romain

**Comment by borjapazr** [comment]
Hello, @Romakita 😊.

Sorry for not specifying enough information. Anyway, I think the problem is easy to see. In fact, it can be reproduced by following the steps indicated in the issue. Basically, when you run the database seed `yarn run prisma:seed`, the mentioned error occurs.

As you say, it is a `TypeScript` error, but it is related to the model generated by `Ts.ED`. In this particular situation, the problem occurs when performing the insertion of an element through the `PrismaClient` or through the repositories generated by `Ts.ED`.

`In summary, the model generated by Ts.ED for each of the entities participating in a One To Many relationship is not compatible with what Prisma expects.`

At the moment I have not been able to check what could be the solution to this problem either, I simply limited myself to report this issue since several people reported it in my project. If I have time this weekend I will try to check it, but no promises. Sorry.

I will keep you updated.

Thank you for your work and effort.

Regards.

**Comment by borjapazr** [comment]
Hi again, @Romakita!

Maybe it's a Prisma problem? 🤔

https://github.com/prisma/prisma/issues/15946
https://github.com/prisma/prisma/issues/8797

**Comment by Romakita** [comment]
Yes the second seems to be similar ^^
