### ISSUE TITLE
[BUG] Title

### ISSUE THREAD

**Issue by eduardo-lunarbyte** [TypedProject/ts-express-decorators#2290]
## Information

- **Version:** 7.18.2
- Packages:
        "@tsed/common": "7.18.2",
        "@tsed/core": "7.18.2",
        "@tsed/di": "7.18.2",
        "@tsed/exceptions": "7.18.2",
        "@tsed/json-mapper": "7.18.2",
        "@tsed/passport": "7.18.2",
        "@tsed/platform-express": "7.18.2",
        "@tsed/schema": "7.18.2",
        "@tsed/swagger": "7.18.2"

tsconfig.json file: 

"compilerOptions": {
    "target": "es2018",                       
    "module": "commonjs",       
     "lib": [
         "es7",
         "dom",
         "esnext.asynciterable"
     ],                          
    "outDir": "./dist",                 
    "strict": true,                        
    "esModuleInterop": true,           
     "experimentalDecorators": true,       
     "emitDecoratorMetadata": true,
  }

I get the following errors while trying to build/compile using docker.

node_modules/@tsed/common/lib/types/services/FakeAdapter.d.ts(29,5): error TS2416: Property 'mapHandler' in type 'FakeAdapter' is not assignable to the same property in base type 'PlatformAdapter<any>'.
Type '(handler: PlatformContextHandler<PlatformContext<PlatformRequest<any>, PlatformResponse<any>>>) => PlatformContextHandler<...>' is not assignable to type '(handler: Function, layer: PlatformHandlerMetadata) => Function'.
Types of parameters 'handler' and 'handler' are incompatible.
Type 'Function' is not assignable to type 'PlatformContextHandler<PlatformContext<PlatformRequest<any>, PlatformResponse<any>>>'.
Type 'Function' provides no match for the signature '($ctx: PlatformContext<PlatformRequest<any>, PlatformResponse<any>>): any'.

**Comment by Romakita** [comment]
Please create a reproducible example. I haven’t this issue using docker.
See you

**Comment by Romakita** [comment]
Hello @eduardo-lunarbyte 

Using the Ts.ED CLI I'm not able to reproduce your issue. The docker compose build works as expected.

**Comment by eduardo-lunarbyte** [comment]
Thanks for checking this out. I was able to figure out how to replicate the issue. 

The tsconfig.json needs to have the "strict" flag set to true. 

The error shows up after npm run build

**Comment by Romakita** [comment]
Ok. thanks :)

My point is: remove strict option or add skipLibCheck option, until a fix is released.

Or make a PR to fix all compilation issue on the framework.

See you
Romain

**Comment by Romakita** [comment]
I checked the error with strict option, and some error isn't relevant, because some props are initialized by decorators.
Your choice to enable this option has a huge side effect on the framework that isn't acceptable at this time. Strict option should only have an effect on your code and not on the framework.

See you
Romain

**Comment by Romakita** [comment]
Maybe you have to exclude the node_modules from the files compiled (or checked) by the tsconfig ;)

**Comment by eduardo-lunarbyte** [comment]
> Ok. thanks :)
> 
> My point is: remove strict option or add skipLibCheck option, until a fix is released.
> 
> Or make a PR to fix all compilation issue on the framework.
> 
> See you Romain

Thank you! This took care of the issue

**Comment by Romakita** [comment]
I already trying to fix compilation issue by addind strict option.
It’s complicated and not trivial. 
I also checked if other open source framework like nestjs use this option (the answer is no).
And personnaly I don’t want to enable this option because on framework is too constraignant for me.

I’m pretty sure you can exclude node_modules from this option ;).

**Comment by eduardo-lunarbyte** [comment]
No worries, that makes a lot of sense. Adding skipLibCheck solved the errors I was encountering. 
Thanks for taking the time to look into this.
