### ISSUE TITLE
[BUG] Properties with DateFormat decorator serializes JS date objects into wrong format

### ISSUE THREAD

**Issue by markusenglund** [TypedProject/ts-express-decorators#2310]
## Information

- **Version:** 7.20
- Packages: @tsed/ajv @tsed/common @tsed/core @tsed/di @tsed/engines @tsed/exceptions @tsed/json-mapper @tsed/openspec @tsed/platform-express @tsed/schema @tsed/swagger

A few sentences describing the overall goals of the issue:

When using the `DateFormat` decorator, the property is supposed to have the format `yyyy-mm-dd`. I expected that if I pass a JS Date object to the controller, it would be serialized into that format. However, it's serialized into a regular ISO date-string like this: `"2023-04-12T14:51:00.193Z"`. Is that intended behavior?

## Example

```ts

export class User {
    @Property()
    userName?: string;

    @DateFormat()
    birthDay?: Date;
}
```
```ts

    @Get('/:id')
    @Summary('Get user by id.')
    @Returns(200, User)
    async getById(
        @PathParams('id')
        @Integer()
        id: number,
    ): Promise<User> {

        const user = { userName: "user", birthDay: new Date() }
        return user;
    }
```

Response:

```
{
  "userName": "user",
  "birthDay": "2023-04-12T14:51:00.193Z",
}
```

Expected response: 
```
{
  "userName": "user",
  "birthDay": "2023-04-12",
}
```

## Acceptance criteria

- [ ] Serialize Dateformat properties into correct format

Thanks for all your hard work!

**Comment by Romakita** [comment]
Hello @markusenglund 

isn’t really a bug. Ts.ED doesn’t transform the date currently, it just call the `toISOString()` method of the object.

Date transformation is complexe, depend on each project guideline and this why isn’t implemented by the framework.

it’s your responsability to implement the date mapper to feat with your need ;).

**Comment by Romakita** [comment]
This PR will help you to implement the Date Mapper with the expected date format and with your preferred lib (moment, Date API, etc...)

https://github.com/tsedio/tsed/pull/2313
