### ISSUE TITLE
[BUG] Swagger Does Not Generate Correct Type for PathParams

### ISSUE THREAD

**Issue by Feasoron** [TypedProject/ts-express-decorators#2342]
## Information

- **Version:** 7.28.0
- Packages: @tsed/swagger

The Swagger documentation is not properly generating the types from PathParams - when there is a PathParam defined as a number, the Swagger UI is displaying it as a string. It also passes it as a string, generating a validation issue.

## Example

```ts
@Get('/:id')
public async getModel(@PathParams() modelId: number): Promise<Model> {
```
![image](https://github.com/tsedio/tsed/assets/1660215/96389979-4fae-483a-b809-089289f83564)

## Acceptance criteria

- [ ] A numeric path param is properly described in swagger

**Comment by Romakita** [comment]
Hello,

this usecase is covered here and works:
https://github.com/tsedio/tsed/blob/1ab3bc8fff3a1bb2a4b4cef666288e1090d4b784/packages/platform/platform-test-sdk/src/tests/testPathParams.ts#L46
There is no validation issue. Ts.ED cast the string value as number.

The only problem is maybe the generated swagger-ui not the validation.

See you

**Comment by Romakita** [comment]
You can try:`@PathParams('id', Number)`

**Comment by Romakita** [comment]
Ok I just saw your code example.
You have a typo. You’ve missed to give the expression to the decorator: 
`@PathParams('id')ˋ

See you,
Romain

**Comment by Feasoron** [comment]
Thank you so much!
