### ISSUE TITLE
[BUG] enums function doesn't work @Default decorator

### ISSUE THREAD

**Issue by markusenglund** [TypedProject/ts-express-decorators#2357]
## Information

- **Version:** 7.29.1
- Packages: @tsed/schema

When using the `enums` function on a typescript enum that is used on a query parameter with the `@Default` decorator, the `"default"` property doesn't get added to the JSON schema.

## Example

```ts
enum Scope {
    PUBLIC = 'public',
    ADMIN = 'admin',
}

// argument for a controller:
@QueryParams('scope')
@Default(Scope.PUBLIC)
@Enum(Scope)
scope: Scope = Scope.PUBLIC,
```

The above code will create a schema like this (Note the "default" property):

```json
          {
            "in": "query",
            "name": "scope",
            "required": false,
            "schema": {
              "type": "string",
              "enum": [
                "public",
                "admin"
              ],
              "default": "public"
            }
          },
```

However, when adding
```
enums(Scope).label('Scope');
``` 
... the default property disappears from the schema:

```json
          {
            "in": "query",
            "name": "scope",
            "required": false,
            "style": "deepObject",
            "schema": {
              "$ref": "#/components/schemas/Scope"
            }
          },
```
```json
      "Scope": {
        "type": "string",
        "enum": [
          "public",
          "admin"
        ]
      },
```

I understand that this would be difficult to get to work from TS.EDs side since the "default" property would sit on the Scope schema in the OAS file. Would it be possible to somehow set a default on the shared Scope enum?

**Comment by Romakita** [comment]
Hello @markusenglund 
Thanks for this issue. But it’ll be very complex to fix that from the decorator as you higlight it ;)
Maybe your solution is more suitable ;)

Ienums util manipulate a partial schema so it could be possible to add some extra methods like default :)

see you

**Comment by Romakita** [comment]
Have you tried that ? Because it works ^^

```ts
enums(Scope).label('Scope').default(Scope.PUBLIC)
```

See you
Romain

**Comment by markusenglund** [comment]
Ok thanks, that should work for our use-case.

**Comment by Romakita** [comment]
Note: Not a bug. In OAS shared component cannot be used with other rules without using $allOf.

**Comment by Romakita** [comment]
Workaround works. Improvement isn't required.

**Comment by Romakita** [comment]
You can try with 7.36.5 now
