### ISSUE TITLE
[BUG] POST with form data not working

### ISSUE THREAD

**Issue by MatejSkrbis** [TypedProject/ts-express-decorators#2386]
## Information

- **Version:** 7.33.1

I have an endpoint with `@Consumes('application/x-www-form-urlencoded')` that accepts form data.
Everything is fine until additional middlewares are added into config when bootstraping the server.
In that case the endpoint stops receiving form data and starts returning status 400, `PARAM_VALIDATION_ERROR`.
I'm presuming that already existing middlewares are overwritten by the new array?

## Example

Here is the repository to reproduce the issue:
https://github.com/MatejSkrbis/tsed-v6-v7

**Comment by Romakita** [comment]
Hello @MatejSkrbis 
I really wasted my time for nothing :(

please remove this line in index.ts. Array field aren't merged between settings in index and `@Configuration()`. Set middlewares on Configuration or index.ts but not on both levels.

```ts
const conf = {
  // As long as middlewares are added here there is a problem with posting formdata
  middlewares: [
    "cors"
  ],
};
```
See you
Romain

**Comment by MatejSkrbis** [comment]
> Hello @MatejSkrbis I really wasted my time for nothing :(
> 
> please remove this line in index.ts. Array field aren't merged between settings in index and `@Configuration()`. Set middlewares on Configuration or index.ts but not on both levels.
> 
> ```ts
> const conf = {
>   // As long as middlewares are added here there is a problem with posting formdata
>   middlewares: [
>     "cors"
>   ],
> };
> ```
> 
> See you Romain

I'm sorry about that. I thought it was meant to be merged per documentation:
https://tsed.io/docs/platform-api.html#inject-service-in-the-server

![image](https://github.com/tsedio/tsed/assets/13940777/9145445e-83a7-4040-b6c2-9e1c0c2fbf9e)

It says extra settings so I presumed it must be merged. I used this to load extra configuration since v5 together with `@Configuration(...)` that is in the base module (as a package) for my services. I just never used middlewares property, but used component scan instead.

**Comment by Romakita** [comment]
No worries.

But this props isn't configured to be merged. For me there is no sense because global middleware order is really importante in express. 
Because I have looked the `@Configuration` I haven't seens the cors set in index.ts 😅

Resolve this bug isn't planed and can be confusing if the array is merged.
The only prop that is merged is mount.

See you
