### ISSUE TITLE
[BUG] Type Boolean in swagger docs is a object

### ISSUE THREAD

**Issue by thanhchuongbmd** [TypedProject/ts-express-decorators#2392]
## Information

- **Version:** 7.34.0
- Packages: "@tsed/common": "7.34.0",
    "@tsed/core": "7.34.0",
    "@tsed/exceptions": "7.34.0",
    "@tsed/json-mapper": "7.34.0",
    "@tsed/platform-express": "7.34.0",
    "@tsed/socketio": "7.34.0",
    "@tsed/swagger": "7.34.0",
    "@tsed/typeorm": "7.34.0"

In a swagger doc generate boolean is a object and can not receive value this property on product. isOutStock

## Example

```ts
import { Property } from "@tsed/schema";
export class Product {
    @Property()
    isOutStock: boolean;
}
```
<img width="179" alt="Screen Shot 2023-07-22 at 11 34 32" src="https://github.com/tsedio/tsed/assets/67777599/c90742f9-19ab-42ee-91c5-d1a4cc88d3c7">

**Comment by Romakita** [comment]
Hello @thanhchuongbmd 

Isn't possible this scenario is widely covered in unit test and integration test. And many project in production works also.
Your given example works.

Please verify your code (tsconfig, schema etc) ;), generate a small project with CLI, create a small model with a boolean props and you'll see that works as expected.

See you
Romain
