### ISSUE TITLE
[BUG] Exceptions (and descendants) have stack: undefined

### ISSUE THREAD

**Issue by mistergreen-christopher** [TypedProject/ts-express-decorators#2402]
## Information

- **Version:** 7.34.2
- Packages: @tsed/exceptions

Currently, when throwing an Exception or descendant, the stack trace is undefined. Please see the below example and check the log response in the terminal (when running locally).

## Example

```ts
import { Controller } from '@tsed/di'
import { Get } from '@tsed/schema'
import { Exception } from '@tsed/exceptions'

@Controller('/hello-world')
export class HelloWorldController {
  @Get('/')
  get() {
    throw new Exception()
  }
}
```

### Log output
```
[2023-08-01T11:05:27.214] [ERROR] [TSED] - {
  method: 'GET',
  url: '/rest/items',
  route: '/rest/items',
  headers: {
    'content-type': 'application/json',
    'user-agent': 'PostmanRuntime/7.32.3',
    accept: '*/*',
    'postman-token': 'aa69983a-d99d-406d-9fa0-72c39d5ea5b1',
    host: 'localhost:8083',
    'accept-encoding': 'gzip, deflate, br',
    connection: 'keep-alive',
    'content-length': '28'
  },
  body: { namee: 'Item name' },
  query: {},
  params: {},
  reqId: 'e94351b6a36a40b6b878515058e6b454',
  time: 2023-08-01T09:05:27.214Z,
  duration: 9,
  error: {
    name: 'INTERNAL_SERVER_ERROR',
    message: '',
    status: 500,
    errors: [],
    stack: undefined
  },
  stack: undefined
}
```

## Suggested fix
Add `super.captureStackTrace()` in the constructor of the Exception class: https://github.com/tsedio/tsed/blob/83bc31d70aa58c672df3aea05daab38045b3d704/packages/specs/exceptions/src/core/Exception.ts#L40

Please see [Error.captureStackTrace](https://nodejs.org/api/errors.html#errorcapturestacktracetargetobject-constructoropt) for more details.

## Acceptance criteria

- [ ] Exception class should capture stack in constructor
- [ ] Stack trace should be visible in log
- [ ] Stack trace should be visible in response when Env.DEV === true

**Comment by Romakita** [comment]
@mistergreen-christopher Thanks for the issue. Can you open PR, please ?

**Comment by Romakita** [comment]
@mistergreen-christopher Based on the nodejs doc `error.stack` should do the same thing.

```ts
const myObject = {};
Error.captureStackTrace(myObject);
myObject.stack;  // Similar to `new Error().stack` 
```
