### ISSUE TITLE
[Question] @Constant/@Value are not available inside the constructor

### ISSUE THREAD

**Issue by ktalebian** [TypedProject/ts-express-decorators#2407]
## Information

- **Version:** 7.34.2
- Packages:

When using `@Constant` or `@Value` to inject the configuration into a client/service, the value is `undefined` inside the constructor. 

## Example

For example, I have

```ts
@Service()
export class GoogleClient {
  @Constant('sso.google')
  config: GoogleSSOConfig;

  constructor() {
    console.log(this.config);
  }

  doSomething() {
    console.log(this.config);
  }
```

In the example above, when the app boots, the constructor prints `undefined` but when I call `doSomething()` the config value exists. How come?

## Acceptance criteria

- [ ] Criteria 1

**Comment by Romakita** [comment]
Hello @ktalebian 

It's an intended behavior. Decorators used on properties like Constant/Value/Inject are filed by the injector service after the construtor. All props are filled before the $onInit hook.

If you need settings on constructor just inject the Configuration service:

```ts
construtor(settings: Configuration){
  const value = settings.get<string>('myValue');
}
```
Is equivalent of:

```ts
export class MyService {
  @Constant('myValue')
  value: string;

  $onInit(){
    console.log(this.value)
  }
```

See you
Romain
