### ISSUE TITLE
Readiness/liveness check for non-Kubernetes?  

### ISSUE THREAD

**Issue by ktalebian** [TypedProject/ts-express-decorators#2410]
## Information

We have https://tsed.io/tutorials/terminus.html but is there a readiness/liveness for non-Kubernetes systems? 

## Acceptance criteria

- [ ] Criteria 1

**Comment by Romakita** [comment]
Hello @Romakita 
I'm sorry but I don't understand your question but it seems to be addressed to terminus developer team. Ts.ED just wrap the @godaddy/terminus npm module ;)

See you

**Comment by Romakita** [comment]
https://www.npmjs.com/package/@godaddy/terminus

**Comment by ktalebian** [comment]
@Romakita ya terminus is for K8 only. I guess wrapping https://www.npmjs.com/package/lightship would probably be an alternative because it supports normal, containerized and k8 all in one package.

**Comment by Romakita** [comment]
Ok I didn't know that ^^. I use terminus for a normal dockerized app. Maybe not on all features ^^.

Tell me if you need help for lightship integration ;).

See you
