### ISSUE TITLE
[BUG] TSC cant build @tsc\schema `Cannot find module '\node_modules\@tsed\schema\lib\esm\components.js'`

### ISSUE THREAD

**Issue by DaniGTA** [TypedProject/ts-express-decorators#2411]
## Information

- **Version:** 7.34.5
- Packages:
    "@tsed/common": "^7.34.5",
    "@tsed/components-scan": "^7.34.5",
    "@tsed/core": "^7.34.5",
    "@tsed/di": "^7.34.5",
    "@tsed/exceptions": "^7.34.5",
    "@tsed/json-mapper": "^7.34.5",
    "@tsed/platform-express": "^7.34.5",
    "@tsed/schema": "^7.34.5",
    "@tsed/socketio": "^7.34.5",

## Example
I upgrade from `^7.34.2` to `^7.34.5` and was running `npm ci`
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'myfolder\node_modules\@tsed\schema\lib\esm\components.js' imported from myfolder\node_modules\@tsed\schema\lib\esm\utils\getJsonSchema.js
```

I checked the node modules my self and 
![image](https://github.com/tsedio/tsed/assets/20490672/63a034f4-d138-4289-98a1-613e435eed19)
![image](https://github.com/tsedio/tsed/assets/20490672/27ef9001-f71f-4329-a014-387b57d060b2)
there is no components .js

## Acceptance criteria

- [ ] successfull tsc build with @tsed/schema esm modules

**Comment by Romakita** [comment]
Ha it's because in esm I have to write an explicite import of the correct file : components/index.js
I'll try to fix that
