### ISSUE TITLE
[BUG] Page Seq - /tutorials/seq

### ISSUE THREAD

**Issue by victorsmits** [TypedProject/ts-express-decorators#2425]
Error when doing request made server crash.

```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot destructure property 'message' of 'data[0]' as it is undefined.
    at SeqAppender.write (C:\Users\victo\Documents\21JumpClick\tablet-api\node_modules\@tsed\logger-seq\src\SeqAppender.ts:55:14)
```

**Comment by Romakita** [comment]
@victorsmits the problem seems to be here.
https://github.com/tsedio/logger/blob/7df2ba5804324297390a50d4346f9df51e32f074/packages/seq/src/SeqAppender.ts#L55

Can you edit node_module and fix the problem locally?
If you have a time to make a small PR it would be awesome ;)

see you

**Comment by Romakita** [comment]
Fix is on going

**Comment by Romakita** [comment]
Fix released
