### ISSUE TITLE
[BUG] tsed cli build error

### ISSUE THREAD

**Issue by TyCoding** [TypedProject/ts-express-decorators#2426]
When using tsed init . to build the application, the following error occurs:

 stderr: 'npm ERR! code ETARGET\n' +
      'npm ERR! notarget No matching version found for @tsed/platform-views@7.34.8.\n' +
      'npm ERR! notarget In most cases you or one of your dependencies are requesting\n' +
      "npm ERR! notarget a package version that doesn't exist.\n" +
      '\n' +
      'npm ERR! A complete log of this run can be found in:\n' +
      'npm ERR!     /Users/tycoding/.npm/_logs/2023-09-04T06_24_17_671Z-debug-0.log',
      
 node v18.0.0

**Comment by Romakita** [comment]
@TyCoding Node v18.0.0 ? are you sure? isn't a LTS version ^^.

**Comment by Romakita** [comment]
Works as expected on v18.17.1:
<img width="432" alt="Capture d’écran 2023-09-04 à 09 17 35" src="https://github.com/tsedio/tsed/assets/1763311/4c4d4698-c3c2-48a7-8afe-647e3520069e">

See you
