### ISSUE TITLE
[BUG] Deserialization of mongoose `Ref`s when given strings

### ISSUE THREAD

**Issue by ochrstn** [TypedProject/ts-express-decorators#2439]
### Describe the bug

The deserialize function is not correctly converting an array of string IDs. Instead, it's creating an array of instances given by the Ref<Type>.

The deserialization works as expected without the `@Ref(Type)` decorator. 

See the code snippet.

### To Reproduce

1. create a new project
2. execute the code snippet

### Expected behavior

should deserialize to
```
TestEntity {
  categories: [ '650af2ec0973520c84fc6f2c', '650af2f15f8ac42c8234373f' ]
}
```

### Code snippets

```TypeScript
import { $log } from "@tsed/common";
import { deserialize } from "@tsed/json-mapper";
import { Ref } from "@tsed/mongoose";
import { Property } from "@tsed/schema";

class OtherEntity {
  @Property()
  id: string;
}

class TestEntity {
  @Property()
  @Ref(OtherEntity)
  categories: Ref<OtherEntity>[];
}

const serialized = {
  categories: ["650af2ec0973520c84fc6f2c", "650af2f15f8ac42c8234373f"],
};

const deserialized = deserialize(serialized, {
  type: TestEntity,
});

$log.info("deserialized", deserialized);
/*
  deserialized:
    TestEntity {
      categories: [ OtherEntity { id: undefined }, OtherEntity { id: undefined } ]
    }

  expected:
    TestEntity {
      categories: [ '650af2ec0973520c84fc6f2c', '650af2f15f8ac42c8234373f' ]
    }
  */
```

### OS

macOS

### Node version

v18.16.0

### Library version

v7.36.0

**Comment by Romakita** [comment]
Hello @ochrstn,

Your test case isn't correct because Ref decor doesn't work like that. But I know where is the bug.
Personally, I would like to not have this decorator ^^ because it broke all possible perf optimisation.

See you

**Comment by ochrstn** [comment]
> Hello @ochrstn,
> 
> Your test case isn't correct because Ref decor doesn't work like that. But I know where is the bug. Personally, I would like to not have this decorator ^^ because it broke all possible perf optimisation.
> 
> See you

How is the decorator supposed to work if not like that? 🤔 (https://tsed.io/tutorials/mongoose.html#references)

**Comment by Romakita** [comment]
It doesn’t return a list of string but a list of ObjectID.
So the reproduction case isn’t totally correct ;)

**Comment by Romakita** [comment]
@ochrstn You can review the PR https://github.com/tsedio/tsed/pull/2440
You'll see the reproduction case isn't easy ;)

**Comment by ochrstn** [comment]
> It doesn’t return a list of string but a list of ObjectID. So the reproduction case isn’t totally correct ;)

Yeah, so another problem is that the `Ref` type (https://github.com/tsedio/tsed/blob/production/packages/orm/mongoose/src/decorators/ref.ts#L101) is basically wrong because when used with `@Ref()` decorator it is an ObjectId and not a string.

Thats also the case for `@ObjectID("id") _id: string;`.

Do you have any idea/solution on how to handle that (in the future)?

**Comment by Romakita** [comment]
The Ref type is correct. You don't need really to type the property as ObjectID, because ObjectID implement the String interface. In which case, it could be benefit for you ?

But actually can type the _id using `ObjectID` type annotation, it works.

```ts
@ObjectID("id") _id: ObjectID; // @tsed/monoose => export type ObjectID = Types.ObjectId;
```

Ref type isn't type as ObjectID, but is it really important ?

**Comment by Romakita** [comment]
But changing that isn't a huge change (and isn't really a breaking change)

Ref type should the following:

```
export type Ref<T> = T | string | ObjectID;
```
