### ISSUE TITLE
automatically infer validation and swagger docs from types

### ISSUE THREAD

**Issue by pdeveltere** [TypedProject/ts-express-decorators#2442]
### Is your feature request related to a problem? Please describe.

RIght now, when typing a PathParam or a property with an enum, we need to write: `@PathParams('campaignListType') @Enum(CampaignListType) campaignListType: CampaignListType`. Why do we need to write `@Enum(CampaignListType)` explicitly? Can't we infer the validation and swagger documentation automatically from the type?

**Comment by Romakita** [comment]
Can you clean you code example please!
Use 3 back tick to describe a code block.

**Comment by Romakita** [comment]
@pdeveltere  because Enum is not infered as you think.
Typescript set `Object` as metadata.

see you

**Comment by Romakita** [comment]
And more globally, Typescript doesn’t store value only classes or primitive type!
It excludes: type keyword, generics annotation, variable and enums.
