### ISSUE TITLE
[BUG] TsEd Prisma Decorator Email() is not exported into model

### ISSUE THREAD

**Issue by faltenberg** [TypedProject/ts-express-decorators#2455]
### Describe the bug

With tsed version 7.35 and prisma version 5.2.

Following to the [tsed/prisma tutorial](https://api-docs.tsed.io/api/specs/schema/types/decorators/common/Email.html), I may use decorators in my prisma schema and they should be part of the generated TypeScript model. However, I cannot see the `@Email()` decorator in the generated model and when I create a new entry via my REST API, the email field can take any string instead of throwing an expected error.

### To Reproduce

prisma.schema
```
generator client {
  provider = "prisma-client-js"
}
generator tsed {
  provider = "tsed-prisma"
  output = "../src/generated/tsed/"
  emitTranspiledCode = false
}
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model Client {
  /// @TsEd.Groups("!creation")
  id         String    @id @default(cuid())
  /// @TsEd.Groups("!creation")
  createdAt  DateTime  @default(now())
  name       String
  /// @TsEd.Email()
  email      String    @unique
  status     String
} 
```

Run `npx prisma generate`.

The generated *src/generated/tsed/models/ClientModel.ts* file:
```ts
import { Client } from "../client";
import { Required, Property, Format } from "@tsed/schema";

export class ClientModel implements Client {
  @Property(String)
  @Required()
  id: string;

  @Property(Date)
  @Format("date-time")
  @Required()
  createdAt: Date;

  @Property(String)
  @Required()
  name: string;

  @Property(String)
  @Required()
  email: string;

  @Property(String)
  @Required()
  status: string;
}
```

### Expected behavior

A `@Email()` decorator for `ClientModel.email` field in the generated TypeScript file as well as an error when trying to create a client with a invalid email string.

### OS

Ubuntu 22.04

### Node version

Node v20.5.1

### Library version

@tsed v7.35, prisma v5.2

**Comment by Romakita** [comment]
It’s probably an issue around the comment parser here:

https://github.com/tsedio/tsed/blob/production/packages/orm/prisma/src/generator/utils/parseDocumentationAttributes.ts

but the test seems to be ok:

https://github.com/tsedio/tsed/blob/f7494bba5d2f0206b63b8f9eb9abc0b8bf3e6613/packages/orm/prisma/src/generator/utils/parseDocumentationAttributes.spec.ts#L5

**Comment by Romakita** [comment]
In your example, the groups decorators are missing also.
Maybe it’s related to a breaking change with the prisma v5.
Or the parser are not called for an unexpected reason.

**Comment by faltenberg** [comment]
Is there some particular information I might share that would help to gather insight?

**Comment by Romakita** [comment]
@faltenberg no your example is ok. I just added some notes for other people which could be interested by this issue for the hacktoberfest ;)

**Comment by Romakita** [comment]
Hello @faltenberg 
I'm not able to reproduce the issue. For me it works. 
Here is my working example: https://github.com/tsedio/tsed-example-prisma/pull/2/files

> Note: I added to two configuration to generate Code. One inside node_module and another one in a custom output location, to see if there is a difference. But all config works as expected.

I suggest you to create a reproducible repository example ;)

See you

**Comment by Romakita** [comment]
Ok found your issue:

```
model Client {
  /// @TsEd.Groups("!creation")
  id         String    @id @default(cuid())
  /// @TsEd.Groups("!creation")
  createdAt  DateTime  @default(now())
  name       String
  /// @TsEd.Email()
  email      String    @unique
  status     String
} 
```

Replace `@TsEd` => `@TsED`

See you
