### ISSUE TITLE
[BUG] Regression in browser support of @tsed/core

### ISSUE THREAD

**Issue by jojoxd** [TypedProject/ts-express-decorators#2480]
### Describe the bug

Hi Romain,

It seems browser-support of `@tsed/core` is broken again.

```
isBuffer.ts:7 Uncaught ReferenceError: Buffer is not defined
    at x (isBuffer.ts:7:37)
    at $t (isClass.ts:22:9)
    at _A.type (JsonSchema.ts:643:21)
    at _A.set (JsonSchema.ts:750:43)
    at JsonSchema.ts:725:18
    at Array.forEach (<anonymous>)
    at _A.assign (JsonSchema.ts:724:17)
    at new _A (JsonSchema.ts:62:18)
    at _A.from (JsonSchema.ts:128:16)
    at v.build (JsonClassStore.ts:22:35)
```

It seems to be broken by this change; [edb7624d6 isBuffer](https://github.com/tsedio/tsed/commit/edb7624d6efa7b1ff7a3ec51475b086647c8159c#diff-4e3c0b840a28ce1509dfafd4db59c5d42f738897306aaf757a0494c256f7fbda)

### To Reproduce

1. Setup a project to run in the browser, doesn't matter what framework
2. Install `@tsed/schema` and `@tsed/core`.
3. Create a model using `@tsed/schema`
4. run a `getJsonSchema()` on that model.
5. Open in browser, check the logs :smile: 

### Expected behavior

There should be no error, and I should get my json schema.

### OS

Fedora Core 38 (KDE Spin)

### Node version

V8

### Library version

v7.39.0

### Potential fix:

The change in [edb7624d6](https://github.com/tsedio/tsed/commit/edb7624d6efa7b1ff7a3ec51475b086647c8159c#diff-4e3c0b840a28ce1509dfafd4db59c5d42f738897306aaf757a0494c256f7fbda) should be reverted.

**Comment by Romakita** [comment]
Arf…. It’s a problem, I haven’t a way to prevent this regression and clearly I need to shareable utils on core level. :(

is it possible to have something that broke the CI if the code isn’t browser compliante? @jojoxd

**Comment by jojoxd** [comment]
You could maybe run a test suite using [cypress](https://www.cypress.io) or [playwright](https://playwright.dev) against a real browser.

Playwright supports jest ([jest-playwright](https://github.com/playwright-community/jest-playwright)), which might play nice with the current test setup.

**Comment by Romakita** [comment]
Got a solution to for isBuffer:
https://github.com/feross/is-buffer/blob/master/index.js
it seems to be compliant with browser env.

revert code isn’t possible, and my prioritary point is nodejs env. browser env support is a plus. But to avoid future regression, adding integration test using jest-playwright is mandatory.

see you
