### ISSUE TITLE
Graphql v1/v2 endpoints does not work

### ISSUE THREAD

**Issue by radoslavirha** [TypedProject/ts-express-decorators#2487]
Hi I was playing with GraphQL and I wanted to create two endpoints `/v1/graphql` and `/v2/graphql`, but it doesn't work.

I forked template repo and created https://github.com/radoslavirha/tsed-example-graphql as an example.

I expect query
```
{
    recipes {
        id
        title
        description
    }
}
```
sent to `http://0.0.0.0:8083/v1/graphql` should return id 1 and `http://0.0.0.0:8083/v2/graphql` should return id 2.

It seems import order is important [here](https://github.com/radoslavirha/tsed-example-graphql/blob/54cb583162bf2b68892acf675b3354e7d0a0575d/src/Server.ts#L10)

Both endpoints returns result from first imported module, even when they are separated, have separate path and resolvers.

Thanks

_Originally posted by @radoslavirha in https://github.com/tsedio/tsed/discussions/2470_

**Comment by Romakita** [comment]
Hello @radoslavirha 
You code example is on the wrong Ts.ED version (v6).
Please use CLI to generate a project or fork a project and update dependencies before opening issue!
See you

**Comment by radoslavirha** [comment]
Hello @Romakita my apologies! I was trying it on my project using Ts.ED v7 and then forked your repo and I did not notice it's outdated.

I created new server via cli now.

Thanks

**Comment by Romakita** [comment]
No issue, I updated the dependencies and code. The fix is almost done. I get the opportunity of this issue to integration new features ;)

see you

**Comment by Romakita** [comment]
Don’t waste your time ;)

**Comment by radoslavirha** [comment]
it's already pushed :)

**Comment by Romakita** [comment]
PR is Ready.
- It add support of Subscription using graphql-ws.
- Allow context injection
- Fix the multiple graphql server usage using typegraphql
- Improve documentation

**Comment by radoslavirha** [comment]
@Romakita you're awesome! Thank you!
