### ISSUE TITLE
[BUG] Body Validation not working as expected

### ISSUE THREAD

**Issue by EinfachHans** [TypedProject/ts-express-decorators#2497]
### Describe the bug

I'm currently migrating a express application to Ts.ED. I used joi for the validation before and currently try to make AJV work, as i like the direct support & swagger integration.

I have a problem making the following work:

```ts
import { Integer, Required } from '@tsed/schema';

export class Test {
  @Integer()
  @Required()
  value: number;
}
```

```ts
@Post('/some-url')
async someFunction(@BodyParams() body: Test) {
  ...
}
```

Also writing `@BodyParams(Test) ...` does not work.

I don't find an exact documentation for this, except from `Any model used on parameter and annotated with one of JsonSchema decorator will be validated with AJV.` [written here](https://tsed.io/docs/validation.html). So i guess my usage is correct and should work?

Also in my `server.ts` i have:

```ts
import '@tsed/ajv';
```

What does work for me is something like:
```ts
@Post('/some-url')
async someFunction(@BodyParams('value') @Integer() @Required value: number) {
  ...
}
```
but i would like to validate the whole body. Is this possible?

### To Reproduce

Should be quite is to set up, see above.

Because this is also a kind of "should this be even possible" - issue, i dind't create an extra reproducable repo. If you need one, let me know.

### Expected behavior

I would expect the full body to be validated correctly when used as described above. The request should ail with the ajv error.

### OS

macOS

### Node version

18.17.1

### Library version

7.41.2

**Comment by Romakita** [comment]
Hello @EinfachHans 
This the base of tsed and it work as expected (there is a lot of integration test that cover these scenario).

have you generated the project with the CLI?

**Comment by EinfachHans** [comment]
I did, but i already did a lot in my migration process. I will try to reproduce this in a cli starter project tomorrow and will follow up here.

**Comment by Romakita** [comment]
Ok ;)

**Comment by EinfachHans** [comment]
Hey, can't reproduce this in a starter, will dig into whats going on in my project.

Thank you and i really appreciate this project, works great so far 👍🏼

**Comment by Romakita** [comment]
Thanks @EinfachHans ;) 
Tell me if you don’t see where the problem!

**Comment by EinfachHans** [comment]
@Romakita not sure what change exactly, but make it worked now, thank you 👍🏼

Other question: I created a custom AJV keyword which also modifies the data. This seems to doesn't work with the current implementation of the **AjvService.ts**:

Here it always returns the input data, while the localData maybe has been adjusted by AJV:
https://github.com/tsedio/tsed/blob/c75fe924c512500f7a30eb7bbfcebbbbaf615353/packages/specs/ajv/src/services/AjvService.ts#L49C18-L49C18

Is this indeed? Is there any other configuration of stuff i'm missing?

**Comment by Romakita** [comment]
@EinfachHans have you imported the new keyword class in server.ts using es6 import :

import "./keywords/MyKeyword"

**Comment by Romakita** [comment]
Haa sorry, your keyword modify the data?
Isn’t voluntary supported because ajv try to coerce data but this operation can occurs some bad behavior when the @tsed/json-mapper deserialize data.
But this problem maybe not occurs today, since the new json-mapper implementation.
I’ll take time too investigate.

**Comment by Romakita** [comment]
But to solve your issue, you can use `@BeforeDeserialize` decorator.

**Comment by EinfachHans** [comment]
Yeah exactly, from my debugging (maybe it helps you):

- AJV says in their documentation [here](https://ajv.js.org/guide/modifying-data.html#general-considerations):

  > You can also define keywords that modify data.

- My Keyword looks like this:

```ts
@Keyword({
  keyword: 'version',
  type: 'string'
})
export class VersionKeyword implements KeywordMethods {
  compile(): AjvDataValidateFunction {
    return (value: string, ctx: DataValidationCxt) => {
      const version = valid(value);
      if (version) {
        ctx.parentData[ctx.parentDataProperty] = version;
        return true;
      }
      return false;
    };
  }
}
```

- Data Manipulation in tests works as expected
- When debugging into the **AJVService.ts** i mentioned:
  - The schema is validated against a deep copy of the initial object [(ref)](https://github.com/tsedio/tsed/blob/c75fe924c512500f7a30eb7bbfcebbbbaf615353/packages/specs/ajv/src/services/AjvService.ts#L33C4-L33C4)
  - This new `localData` is correctly adjusted after [the next line](https://github.com/tsedio/tsed/blob/c75fe924c512500f7a30eb7bbfcebbbbaf615353/packages/specs/ajv/src/services/AjvService.ts#L34)
  - But because the initial data is returned, the change happened to the localData is not passed to the final controller

**Comment by Romakita** [comment]
A simple test should be te return data and run integration test to see if it impact something.
I’m not on my computer. But you can try it locally, fork tsed, update code and run yarn test:integration

**Comment by EinfachHans** [comment]
Okay, i just did. First: You seem to have a great test setup & coverage, really nice 👍🏼 Second: I adjusted the `validate` function of the **AJVService** to return the `localValue` after a successfully validation and the integration test passed

**Comment by Romakita** [comment]
Ok let’s go for the PR ;)
