### ISSUE TITLE
[BUG] Logger Summary

### ISSUE THREAD

**Issue by EinfachHans** [TypedProject/ts-express-decorators#2505]
### Describe the bug

Hey again,

i'm currently implementing a logger into my application and have some questions and a (possible) bug report about this:

## 1. Swagger Logs

Would it be possible to turn off these logs:
```
[default] Swagger JSON is available on http://0.0.0.0:8000/doc/swagger.json
[default] Swagger UI is available on http://0.0.0.0:8000/doc/
```

### 2. Typings

It seems that the types for the `logger` object of the `TsED.Configuration` are not defined somewhere?

I found `PlatformLoggerSettings` (@tsed/common) and  `TsED.Configuration` in code but no combined configuration and no definition within the Configuration itself, why my IDEA also offers no auto complete. I found for example [this types](https://github.com/tsedio/tsed/blob/e660d5b94b7c0978e81055d5536c5bbac9a6c746/packages/di/src/common/services/DIConfiguration.ts#L87) but here also is not a combined object used.

### 3. Small bug in format

My info logs print as:

```
[2023-11-03T16:58:08.264] [INFO ] [TSED]
```

There is an extra whitespace in the log level breclets

### 4. Export defaultReqIdBuilder

It would be cool if the [`defaultReqIdBuilder`](https://github.com/tsedio/tsed/blob/e660d5b94b7c0978e81055d5536c5bbac9a6c746/packages/platform/common/src/utils/createContext.ts#L8-L10) could be exported somehow. My Goal is to override the reqId generator, check a header value and if this header doesn't exist, use the default handler.

### 5. RequestFields

I found out that the `requestFields` option only applies to `.info` logs. Thats not documented (or i didn't found it) and i'm wondering if this is correct. If a request fails, the logger logs the `request.end` event with the complete request with all fields. When i'm thinking of a login endpoint and a user enters wrong data, his plain output would be printed to console, which should absolutely not be the case imo (for example i would be able to see his login requests and his entered passwords)

### To Reproduce

Let me know if you need something, but the code here is here:

https://github.com/tsedio/tsed/blob/e660d5b94b7c0978e81055d5536c5bbac9a6c746/packages/platform/platform-log-middleware/src/middlewares/PlatformLogMiddleware.ts#L111-L122

### Expected behavior

1. Be able to turn off the swagger logs
2. The type definition should be added correctly
3. No extra whitespace
4. Possibility added to call the default req id generator
5. The `requestFields` should apply to all kind of loggings

### OS

macOs

### Node version

18.17.1

### Library version

7.43.0

**Comment by Romakita** [comment]
@EinfachHans 
Look this page: https://tsed.io/docs/logger.html#configuration

you can implement your own reqId generator. By default, it generate the id from request.headers[x-request-id] or from uuid/v4. 

If you generate a project from CLI you’ll see a configuration for logger. In production the log fotmat is JSON and not the basic format (for dev). The documentation give you all possibilities to change the log format to your needs.
so I won’t change the basic log output format ;)

the requestFieds is applied only on info. It’s totally intended. The log error have to log all necessary data/headers etc to let dev to analyze issue. I agree if it’s a sensible endpoint, some date shouldn’t be logged. In this specific cass you have no choice to override the PlatformLogMiddleware as is described in the doc.

> note: for the typings for me it works as expected if I write something in th @Configuration decorator. But after checking code you’ve right something strange. I don’t retrieve the interface where settings are merged. I’ll check tomorrow

excepted the typings (needs investigation) other of your points aren’t bug ;). But if you think something needs to be improved, I encourage you to open a feature request instead.

see you

**Comment by EinfachHans** [comment]
Hey @Romakita , thanks for your quick response!

About point 1: i can't find an answer or something in the docs, is it already possible to disable the swagger logs?

About point 3: I don't want to change the basic log output format, it appears as a small bug for me that the log level has an extra whitespace, i would expect `[INFO]` instead of `[INFO ]` 🤔

About point 4: I now i can override it, my question was more like if you could export the default one, so i would be able to do something like: `(req) => req.get('xy') || defaultReqIdBuilder(req)`

About point 5: Okay got you, i will then play around with PlatformLogMiddleware-Override. But i think that the `requestFields` only applies to **INFO** should be noted in the docu [here](https://tsed.io/docs/logger.html#configuration)

**Comment by Romakita** [comment]
1.  You right, the log isn't possible to be disabled but isn't really important because if you use this configuration, this log will be displayed in production mode as JSON format using this configuration:

```ts
import {$log, PlatformLoggerSettings} from "@tsed/common";
import {isProduction} from "../envs/index";

if (isProduction) {
  $log.appenders.set("stdout", {
    type: "stdout",
    levels: ["info", "debug"],
    layout: {
      type: "json"
    }
  });

  $log.appenders.set("stderr", {
    levels: ["trace", "fatal", "error", "warn"],
    type: "stderr",
    layout: {
      type: "json"
    }
  });
}

export default <PlatformLoggerSettings> {
  disableRoutesSummary: isProduction
};
```
Isn't a bug, but an enhancement.


3. in Dev mode, it use the basic layout for a better dev experience (logs are more readable rather than the json), the white space is volunteers to have a good alignment between the different levels:  error, fatal, debug, info, trace logs. I won't change because you can customize the basic output by registering your own layout (or appenders) https://logger.tsed.io/layouts/

4. there is no interest to export the code if you want to customize it ;)
```ts
function defaultReqIdBuilder(req: any) {
  return req.get("x-request-id") || v4().split("-").join("");
}
```

5. Agree with you :)

For one of my project is implement this CustomLogMiddleware:

```ts
import { Context } from "@tsed/common";
import { OverrideProvider } from "@tsed/di";
import { PlatformLogMiddleware } from "@tsed/platform-log-middleware";

@OverrideProvider(PlatformLogMiddleware)
export class CustomPlatformLogMiddleware extends PlatformLogMiddleware {
  attributesToHide = ["password", "client_secret"];

  private redactAttributes(body: any): any {
    if (body) {
      for (const attribute of this.attributesToHide) {
        if (body[attribute]) {
          body[attribute] = "[REDACTED]";
        }
      }
    }
    return body;
  }

  requestToObject(ctx: Context): any {
    const { request } = ctx;
    const routeToLog = new URL(request.url, "http://localhost");
    routeToLog.search = "";
    return {
      method: request.method,
      url: request.url,
      route: request.route || routeToLog.pathname,
      headers: request.headers,
      body: this.redactAttributes(request.body),
      query: request.query,
      params: request.params
    };
  }
}
```
But my point of view: it should be on the logger level. But I didn't have time to do something cleaner

**Comment by EinfachHans** [comment]
1. Okay, will add a feature request to disable them

3. I'm unsure if we talk about the same thing 😃 If you compare theses two logs:

```
[2023-11-04T12:36:43.169] [INFO ] [TSED] - Some info log
[2023-11-04T12:36:43.179] [ERROR] [TSED] - Some error
```

The info one has an extra whitespace `[INFO ]`, while the error has not `[ERROR]` - with the same default format

4. Yeah my goal was to extend that default function to only add one more get and if undefined just use the default one.

**Comment by Romakita** [comment]
2. It’s intentional. The last ] is at the same col as the next line for the same char. The number char is strictly the same until the `-`. Again I won’t change that because it’s configurable by changing the layout logger and this layout is used only in dev mode. This layout shouldn’t be used to a production app and shouldn’t be parsed by a log forwarder (json layout is here for that).

4. ok… but maybe you don’t won’t the x-request-id header behavior xD?

**Comment by EinfachHans** [comment]
2. Ahhhh now i get it 😃
3. Yeah understand that you don't want to export it, i will then copy the logic i guess
