### ISSUE TITLE
[BUG] Exceptions not catched

### ISSUE THREAD

**Issue by EinfachHans** [TypedProject/ts-express-decorators#2506]
### Describe the bug

I have created a ExceptionFilter according to the docs [here](https://tsed.io/docs/exceptions.html#exception-filter):

```ts
@Catch(Error)
export class ExceptionsFilter implements ExceptionFilterMethods {
  catch(exception: Error, ctx: PlatformContext): void {
    ...
  }
}
```

I just mentioned that it seems to not catch every error, for example the `AjvValidationError` and `NotFound` are not catched by this filter.

### To Reproduce

Repo: https://github.com/EinfachHans/tsed-exception-filter

Send a request to an unknown URL **OR** send a POST to `/rest/hello-world` without the required body. Both errors are not logged by the exception filter.

The Exception Filter itself works, you can see that if you call GET `/rest/hello-world/error` - the error is logged

### Expected behavior

Because i add `Error` to the `@Catch()` decorator i would expect every error to be catched in the filter.

### OS

macOS

### Node version

18.17.1

### Library version

7.43.0

**Comment by Romakita** [comment]
@EinfachHans Your code example works as expected. The log is correctly displayed in the terminal.

<img width="1110" alt="Capture d’écran 2023-11-06 à 09 03 30" src="https://github.com/tsedio/tsed/assets/1763311/fa6d53b4-6f73-47e8-8f69-fa3b51f55a6e">

See you

**Comment by Romakita** [comment]
curl http://0.0.0.0:8083/rest/hello-world/error

**Comment by EinfachHans** [comment]
Yeah that one works, that is what i described above:

> Send a request to an unknown URL OR send a POST to /rest/hello-world without the required body. Both errors are not logged by the exception filter.
The Exception Filter itself works, you can see that if you call GET /rest/hello-world/error - the error is logged

The other ones does not

**Comment by EinfachHans** [comment]
@Romakita Can you re-open this issue? 😃

**Comment by Romakita** [comment]
Ho I see sorry. In fact, @Required decorator has no effect on the body, because express.js and koa.js always set an `{}`.
Ajv check the given value and it's correct! I can't fix that without causing a huge breaking change and it'll probably not correct to fix that.

For the second point see the dedicated section 404 resource not found:
https://tsed.io/docs/exceptions.html#_404-resourcenotfound

Re-open issue isn't necessary regarding my answers ;)

**Comment by EinfachHans** [comment]
@Romakita Ajv Errors in general are not catched by global exception filter.

For the first: If you send `{}` (so without the property `key` that is required) a AJV exception is thrown and returned to the caller. This error is not catched and imo it should.

To the second: I saw that part in the documentation, but the `ResourceNotFound` exception also is a `Error` at the end of the day, isn't it? So shouldn't it be catched as well?

**Comment by Romakita** [comment]
Ok for the 1st point I’ll check it.

the second point is volunteers because depending on the used platform (koa/express) isn’t handled in the same way.

but you can register the same class for differents errors.

**Comment by Romakita** [comment]
Ha I remember now. Because there is an ExceptionFilter already registered by Ts.ED to catch all error that inherit from `@tsed/exception`. This filter have a priority over default ErrorFilter. It explain why you haven't the Ajv error also, because the error inherit also from `Exception`.

**Comment by Romakita** [comment]
Use: `@Catch(Error, Exception)`, I'll fix the documentation.
