### ISSUE TITLE
[BUG] AjvService throws error with `messages: false`

### ISSUE THREAD

**Issue by EinfachHans** [TypedProject/ts-express-decorators#2507]
### Describe the bug

When configuring **ajv** by setting `messages: false` in the server configuration the AjvService throws an error, while trying to replace the error message.

### To Reproduce

The related code is:

https://github.com/tsedio/tsed/blob/e660d5b94b7c0978e81055d5536c5bbac9a6c746/packages/specs/ajv/src/services/AjvService.ts#L113

### Expected behavior

The configuration should not break the usage of the AjvService

### OS

macOs

### Node version

18.17.1

### Library version

7.43.0

**Comment by Romakita** [comment]
hello @EinfachHans 
Why do you need to remove messages? because this message is really important to analyze the error. I find it stupid that AJV offers this option...

**Comment by EinfachHans** [comment]
Hi @Romakita,

i played around with AJV and error messages and mentioned this error and thought it would make sense to report 😃

What i'm currently try to archive somehow (because i had it with joi before) is throwing an specific exception when a validation fails. I have an exception implemented that is able to localize a specific text according to the current user language. but looks like something like this is not possibile?

**Comment by Romakita** [comment]
Hum localize technical message? Maybe ajv have a plugin for that ^^.

I already created a PR to fix the issue ^^

**Comment by EinfachHans** [comment]
It's more like, i have an error that should be used for all client errors thrown backend side. 

I have a message and code there. Message could be a translated message like "Invalid Email" and code is a custom enum with a lot of codes that a frontend can use to act accordingly to it.

I didn't find a way to archive that 🤔
