### ISSUE TITLE
[BUG] Cannot set global hook at`$afterInit` stage

### ISSUE THREAD

**Issue by ktalebian** [TypedProject/ts-express-decorators#2510]
### Describe the bug

You cannot use an `$afterInit` global middleware (i.e. middleware to run after your controllers as the final step). Doing so throws the following error:

```
TypeError: Cannot set properties of undefined (setting 'next')
    at /Users/koushatalebian/demo/application/gateway/node_modules/@tsed/platform-express/src/components/PlatformExpress.ts:155:6
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at runInContext (/Users/koushatalebian/demo/application/gateway/node_modules/@tsed/di/src/node/utils/asyncHookContext.ts:29:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[ERROR] 15:07:18 TypeError: Cannot set properties of undefined (setting 'next')
```

Hook was installed using `{ use: LogMiddleware, hook: '$afterInit' }` in the `@Configuration` but the same behavior happens if you use the `$afterInit() { this.app.use(LogMiddleware); }` method.

### To Reproduce

1) Clone this repo https://github.com/ktalebian/tsed-bug
2) `npm install` followed by `npm start` 
3) Then do `curl http://0.0.0.0:8083/rest/hello-world`

### Expected behavior

Error should not happe occur

### OS

macOS

### Node version

Node v18

### Library version

7.43.1

**Comment by Romakita** [comment]
Hello @ktalebian 
Are you sure the $afterInit is the correct hook in your case to add LogMiddleware? Or is just to highlight the issue?

**Comment by Romakita** [comment]
Isn't mentioned in the doc, but $afterInit hook cannot be used with a Ts.ED middleware, because the $ctx isn't already initialized at this step and won't be injectable in the use method. Only raw express middleware can be added.

I suggest you to use `$beforeRoutesInit` hook if you want to add Ts.ED middleware.

**Comment by ktalebian** [comment]
Thanks @Romakita  - I'll use regular middleware then cause I need this middleware to run last, after the controller. 

Ya, the log was for example. I'll use the raw express. Thank you!

**Comment by Romakita** [comment]
@ktalebian so you can … afterInit is a hook that is emitted just after DI creation. This is why I asked you before about the wanted behavior.
Look the hook page documentation. The is a lot of hook that must be used to add logger. But Ts.ED provide logger. You don’t to implement  a middleware for that.

read that : https://tsed.io/docs/hooks.html
And https://tsed.io/docs/logger.html#configuration
