### ISSUE TITLE
question: AfterDeserialize for single property

### ISSUE THREAD

**Issue by EinfachHans** [TypedProject/ts-express-decorators#2512]
### Is your feature request related to a problem? Please describe.

Is it possible to use `AfterDeserialize` for a single property?

My usage would be like:

```ts
@HeaderParms('key') @MyDecorator() key: string
```

while `MyDecorator` is something like

```ts
export function MyDecorator() {
  return useDecorators(CustomKey('xy', null), Default('123'), AfterDeserialize((value) => {
    // do something with the value
    return value;
  }));
}
```

but this is never called.

I want to implement something like this for a header that should have a default value if not set.

I know i can do `@HeaderParms('key') @MyDecorator() key: string = 'default'` but i use this header param in many functions and want to set the default globally.

What i currently did as a workaround is this:

```ts
@HeaderParams({type: MyHeader, useValidation: true, useMapper: true}) header: MyHeader
```

while `MyHeader` is:

```ts
@AfterDeserialize((value: MyHeader) => {
  if (!value.key) {
    value.key = 'default';
  }
  return value;
})
export class MyHeader {
  @MyDecorator()
  key: string;
}
```

which works but creates this in swagger:

![Bildschirmfoto 2023-11-06 um 12 11 23](https://github.com/tsedio/tsed/assets/20899975/d8fa9758-9545-45d9-b7eb-84668530a31a)

**Comment by Romakita** [comment]
Hello @EinfachHans 
The header params isn’t a property and it’s always a string value. Apply a model on this params isn’t correct. This is why the mapper usage is disabled on HeaderParams. But I see what you want. Use the pipe feature ;) it’s here for that.

note: afterDeserialize is not applicable as parameter decorator. 

See you

**Comment by EinfachHans** [comment]
Every day i love this project more and more. Thanks, pipes works like a charm!
