### ISSUE TITLE
feat: validate raw path params

### ISSUE THREAD

**Issue by EinfachHans** [TypedProject/ts-express-decorators#2515]
### Is your feature request related to a problem? Please describe.

**First**: I hope i don't annoy you with all of my tickets. If that is the case, let me know^^

I'm currently trying to achieve something like described in [this](https://tsed.io/docs/pipes.html#async-transformation-use-case) of your docs, **but** i would like to validate the path param before the pipe uses it. 

The documentation says:

> In this example, our pipe need to be called with RawPathParams to work properly, because our pipe return an instance of PersonModel. PathParams call automatically the DeserializerPipe and it's not what we want. This is why we using RawPathParams.

I understand this, but for me it doesn't sound like the validation is a problem here, but the mapping is? If that is the case it would be cool to be enable validation for raw params as well 🤔

In my project i created this decorator:

```
return UseParam({
    paramType: ParamTypes.PATH,
    dataPath: '$ctx.request.params',
    expression,
    useValidation: true
  });
```

so i copy & pasted the `RawPathParams` and added the `useValidation: true` which seems to work.

So i'm wondering if this is something which would make sense to add to the library as well, because i would like to use the validation stuff before the pipe so i can ensure the value is correctly.

### Describe the solution you'd like

Atm `RawPathParams` can only by called by the `expression`. It would be good to be able to call it similar to the `PathParams` also with:

```ts
RawPathParams({expression: 'xy', useValidation: true})
```

**Comment by Romakita** [comment]
> First: I hope i don't annoy you with all of my tickets. If that is the case, let me know^^

No. Your issues are clear and highlight some problems and real bug. It help me a lot ;)

~ok so if I understand you want to change the `useValidation` to `true` by default ?~ ha no you want option to configure the RawPathParams. Ok, it should be not a problem ;)

**Comment by Romakita** [comment]
The problem described in the doc required that the validation is disabled, because in this case, the validator will take the PersonModel as schema validation. It's completely wrong, because, the input is an ID.

I realize my example is probably not complete to reflect a real valid usecase. The correct custom decorator implementation should be that:

```ts
import {string} from "@tsed/schema";

export function UsePersonParam(expression: string): ParameterDecorator {
  
  return useDecorators(
     RawPathParams({expression, useValidation: true, useType: String}), 
     Schema(string().required().pattern("some pattern")), 
     UsePipe(PersonPipe)
  );
}
```

But it's not the problem of your issue here ;)

**Comment by Romakita** [comment]
PR ready #2517

**Comment by EinfachHans** [comment]
Hey @Romakita,

with your explanation i managed to create a decorator by:

```ts
return PathParams({
  expression,
  useType: Number
}
```

i was not 100% aware of the `useType` - but i think your pr makes sense anyway?

**Comment by Romakita** [comment]
The useType is here to override the original type set on the parameter. By default Ts.ED use the metadata stored by Typescript to generate the schema validation. But in this case, the type set on parameters is the final result expected by the dev, but the type that should be used as model validation for ajv ;). So it's really important to override it (for ajv and swagger doc).

**Comment by EinfachHans** [comment]
Awesome, `useType: Number` works like a charm for me here 👍🏼
