### ISSUE TITLE
question: Inject in code

### ISSUE THREAD

**Issue by EinfachHans** [TypedProject/ts-express-decorators#2519]
### Is your feature request related to a problem? Please describe.

I have a question about the `di` Injector:

I have a **static** method (after destroy hook of a sequelize model) where i want to execute a function from a provided service. Is there a way to inject a service in code directly, similar to `PlatformTest.get(...)` in test environment?

I found the `GlobalProviders` in code, but i'm unsure if this is
1. Safe to use
2. and more important: the preferred way

**Comment by Romakita** [comment]
It's possible but not recommended :)

The principle is to store the injector created by the index.ts somewhere in your code:

```ts
const platform = await PlatformExpress.bootstrap(Server, {})
 // get the injector
setSomeTheInjector(platform.injector)
await platform.listen();
```

GlobalProviders is a registry it won't help you ;). PlatformTest is factory that save the injector in the static property:
https://github.com/tsedio/tsed/blob/production/packages/platform/common/src/services/PlatformTest.ts#L67

It should be the same idea for you ;)

See you
