### ISSUE TITLE
[BUG] 7.36 and above broke useDecorator and pipes

### ISSUE THREAD

**Issue by ktalebian** [TypedProject/ts-express-decorators#2521]
### Describe the bug

This is the pipe I've been using

```ts
@Injectable()
export class PaginationContextPipe
  implements PipeMethods<Record<string, string>, Pagination>
{
  private static DEFAULT_PAGE_SIZE = 10;

  transform(queryParams: Record<string, string>): Pagination {
    // Get all query params
  }
}

/**
 * Denotes the object to use the {@link PaginationContextPipe} pipe
 * @constructor
 */
export function PageContext() {
  // @ts-ignore
  return useDecorators(RawQueryParams(), UsePipe(PaginationContextPipe));
}
```

This worked just fine, and the `transform` function was getting _all_ query parameters passed. However, something in `7.36.0` release and above has caused this to break.

If I `console.log(queryParams)` in the `PipeMethod` using 7.35.0, I see the query parameter. However, after upgrading, that value is always `undefined`

### To Reproduce

Use a hook with `RawQueryParam`. Include version 7.36 and above. 

### Expected behavior

It should behave as before

### OS

macOS

### Node version

Node 18

### Library version

v7.36.0

**Comment by Romakita** [comment]
Hello @ktalebian 
As I see the only feature released with the v7.36.0 is the new @tsed/json-mapper. I'll take a time to look but a repo could be useful, because, it's probably not related to your example but how the pipe is used in the controller.

See you
Romain

**Comment by ktalebian** [comment]
@Romakita here is a repo: https://github.com/tsedio/tsed/issues/2521

Also, while putting this together, I found some interesting results. 

So the issue happens _if_ in the controller, you set the type, i.e. you have something like

```ts
@Get('...')
 fetch(@PageContext() context: Pagination)
```

When you do this, inside the `transform`, the variable `params` becomes actually of type `Pagination` ... and that breaks populating it in 7.36.0 and above. 

Now interestingly, if you change `fetch(@PageContext() context: Pagination)` to `fetch(@PageContext() context: any)`, then it works just fine. 

OR if you directly. use the two annotations `fetch(@PRawQueryParams(), UsePipe(PaginationContextPipe) context: Pagination)`

**Comment by Romakita** [comment]
Thanks for the investigation @ktalebian. You totally found the problem. The new json-mapper is more strict and relies on the typed model rather than checking if the type is correct relative to the input format.
Normally the RawQueryParams should not be requested to map it. I'm going to check all that.

**Comment by Romakita** [comment]
Meanwhile, you can set try that: @PRawQueryParams({useMapper: false})

**Comment by Romakita** [comment]
PR Ready #2526
