### ISSUE TITLE
[BUG] Controller function stripping OneOf field from deserialized response

### ISSUE THREAD

**Issue by KGMaxey** [TypedProject/ts-express-decorators#2531]
## Issue
Any type that uses a field with a `OneOf` type has that field stripped off in the response.

(Thanks in advance for the help :) )

## Description
I've created a reproduction repo using the example `Event` types that are used in the docs and in the tests [here](https://github.com/KGMaxey/tsed-demo/tree/main). 

In the [HelloWorldController](https://github.com/KGMaxey/tsed-demo/blob/main/src/controllers/rest/HelloWorldController.ts) I added the events type as well as an additional container type `EventContainer` with a single field called `Event` that uses the `OneOf` decorator with the `OneOfEvents` type.

```ts
class EventContainer {
  @OneOf(Event)
  event: OneOfEvents
}
```

I then added an endpoint that creates an object of this type, deserializes it, console logs the result, and finally returns. The console log after deserialization shows the object correctly deserialized. The actual http return has the field `url` from the `PageView` Event removed.

```ts
// THIS DOESN'T WORK - 'url' FIELD IS STRIPPED ON RETURN
@Get("/")
@Returns(200, EventContainer)
get() {
  const result = deserialize<EventContainer>({
    event: {
      type: 'page_view',
      value: 'hello',
      url: 'world'
    }
  }, { type: EventContainer })

  // CONSOLE LOG CORRECTLY SHOWS 'url' FIELD IS PRESENT IN DESERIALIZED RESULT
  console.log(JSON.stringify(result))

  return result
}
```

Lastly, I added a sanity check endpoint that uses a field with `PageView` explicitly defined to confirm this works as expected.

## Swagger Results
Note that the swagger return type is listed as expected, however the tested response is missing the `url` field
![TSED-Demo-Swagger](https://github.com/tsedio/tsed/assets/29131033/aad8fe48-6c7b-44e5-86cc-b7f6feb13dcb)

## Console Log After Deserialization
![TSED-Demo-Log](https://github.com/tsedio/tsed/assets/29131033/40c72149-aa05-4f3f-962d-4d9cd0d47903)

### To Reproduce

1. Fetch the reproduction repo [here](https://github.com/KGMaxey/tsed-demo/tree/main)
2. Run npm install
3. Run npm start
4. Navigate to swagger page at `http://localhost:8083/doc`
5. Run both get requests and note missing `url` field on the 'rest/hello-world` GET endpoint

### Expected behavior

HTTP return object matches the object returned by the `deserialize` method.

### Code snippets

```TypeScript
class EventContainer {
  @OneOf(Event)
  event: OneOfEvents
}


// THIS DOESN'T WORK - 'url' FIELD IS STRIPPED ON RETURN
@Get("/")
@Returns(200, EventContainer)
get() {
  const result = deserialize<EventContainer>({
    event: {
      type: 'page_view',
      value: 'hello',
      url: 'world'
    }
  }, { type: EventContainer })

  // CONSOLE LOG CORRECTLY SHOWS 'url' FIELD IS PRESENT IN DESERIALIZED RESULT
  console.log(JSON.stringify(result))

  return result
}
```

### Repository URL example

https://github.com/KGMaxey/tsed-demo/tree/main

### OS

macOS

### Node version

Node v18.16.0

### Library version

v7.44.1

**Comment by Romakita** [comment]
Hello @KGMaxey 
Perfect issue, I'll take a time check where is the problem ;)

**Comment by KGMaxey** [comment]
Awesome thanks!

Something I did forget to note is that using `OneOf` as a return type of an endpoint function still works perfectly. So for example, this function works like a charm.

```ts
@Get("/array")
@Returns(200, Array).OneOf(Event)
getArray() {
  const result = deserialize<Event>([
    {
      type: 'page_view',
      value: 'hello',
      url: 'world'
    }
  ], { type: Event })

  console.log(JSON.stringify(result))

  return result
}
```

### Array Swagger Reseponse
![TSED-Demo-Array](https://github.com/tsedio/tsed/assets/29131033/0e8a2eaf-521e-45e9-aee9-2467a0f79fad)

**Comment by Romakita** [comment]
Ok I reproduce the bug. Something seems to be missing over the discriminator feature in this case.
