### ISSUE TITLE
feat(bullmq): improvements

### ISSUE THREAD

**Issue by EinfachHans** [TypedProject/ts-express-decorators#2534]
### Is your feature request related to a problem? Please describe.

Hey again,

i'm currently looking into the `bullmq` package and think i found some stuff to optimize. I can do this and create a PR, but before i would like to talk about what i would change:

1. Remove `disableWorker` from config - this is unused and not needed because of `workerQueues`
2. Deprecate `defaultJobOptions` and add `defaultQueueOptions` - currently you can only set the `defaultJobOptions` option for a queue, while a queue itself has more options to configure
3. Add queue specific options - In case you want to configure two queues differently, you can not do this atm. I thought to use a type like `queueOptions: Record<string, QueueOptions>`, where the key should be the queue name?
4. Same goes for workers. You can't configure them atm, so i would add a `defaultWorkerOptions` applied to every worker and `workerOptions` (like in 3.) to configure some workers specifically
5. Also i would like to add some listeners to the workers as described in the bullmq docs like:

```ts
worker.on('completed', (job: Job<DataType, ResultType, NameType>, result: ResultType) => {
  // add some logic...
});

worker.on('failed', (job: Job<DataType, ResultType, NameType> | undefined, error: Error) => {
  // add some logic...
});

worker.on('error', (failedReason: Error) => {
  // add some logic...
});
```

users should be able to add these accordingly to their needs, im unsure about what the best way to handle this is. Any recommendations? 🤔

**Comment by EinfachHans** [comment]
Linking in @abenerd as you seem to be the bullmq maintainer? 😊

**Comment by abenerd** [comment]
Hey @EinfachHans, for 2-4 you're definitely right, we should allow for queue and worker specific options. But maybe we can keep the `defaultJobOptions` and keep using them as global job options and add a field like `queueSpecificOptions` that like you said looks like `Record<string, QueueOption>`, that can override the global defaults. The same can be applied to workers too. 

For your first point, I think I would like to keep that option as it allows me to explicitly state the workers used, if none are specified it will just fall back to the queues that are already defined.

To your last point that is already possible, albeit not documented. You can do this for example in a custom module. 

```ts
import { Module } from '@tsed/di';
import { InjectorService, type OnReady } from '@tsed/common';
import { type Worker } from 'bullmq';
import { captureException } from '@sentry/node';

@Module()
export default class BullMQModule implements OnReady {
  constructor(private readonly injector: InjectorService) {}

  public async $onReady() {
    this.injector.getMany<Worker>('bullmq:worker').map((worker) =>
      worker.on('failed', (job, error) =>
        captureException(error, (scope) =>
          scope.setContext('bullmq', {
            id: job.id,
            job: job.name,
            queue: job.queueName,
            data: job.data,
            timestamp: job.timestamp,
            attempt: job.attemptsMade,
            failedReadon: job.failedReason,
            finishedOn: job.finishedOn,
          })
        )
      )
    );
  }
}
```

The queues can retrieved the same way using

```ts
this.injector.getMany('bullmq:queue').map(queue => /* do something */);
```

**Comment by EinfachHans** [comment]
Hey @abenerd , thanks for your quick response!

To 1: I want to remove `disableWorker`, not `workerQueues`. `disableWorker` seems to be unused?

To 2: I want to deprecate `defaultJobOptions`, in favor of a `defaultQueueOptions`, so give users the option to configure more than only the `defaultJobOptions` for every queue. Via `defaultQueueOptions` they would be able to confure the same and even more:

```ts
defaultQueueOptions: {
  defaultJobOptions: {
    ...
  },
  ...
}
```

Ahh last point is good to know, thanks 👍🏼

**Comment by abenerd** [comment]
Oh damn, you're right it isn't used! Yeah, might as well deprecate it, not sure if removing it would be a breaking change even tho it does nothing. 

Also I like the idea of being able to configure the whole queue / worker and not just the job options, that might be worth looking into. Can also immediately allow to have different options for different queues.

**Comment by EinfachHans** [comment]
i will add you as a reviewer you on my PR, thanks for your input so far 👍🏼

**Comment by abenerd** [comment]
No problem, thank you for your feedback!
