### ISSUE TITLE
feat(bullmq): add default job handler

### ISSUE THREAD

**Issue by EinfachHans** [TypedProject/ts-express-decorators#2537]
### Is your feature request related to a problem? Please describe.

At the moment a `JobController` needs to be specified with a explicit job name.

In case you want to use a variable job name, you can not use either the job controller handler or the dispatcher.

### Describe the solution you'd like

A solution could be to add a `DefaultJobController` for every job that is not set up explicit and called for every job where no job controller is found.

### Describe alternatives you've considered

An alternative which would be really awesome but harder to implement i guess would be to support some kind of regexes, for example to declare a `@JobController` with a name pattern like `event:*`, which would be called for every event like

- event:123
- event:test
- event:xyz

This could be also be a great addition, but might be overhead to implement, maintain and test.

### Additional context

@abenerd what do you think? 😊

**Comment by abenerd** [comment]
I'm not a fan of the regex approach it seems like a lot of overhead and is also not something that is natively supported by bullmq afaik.
But we definitely could go the `DefaultJobController` route, although I think I would rather call it `FallbackJobController` to better indicate that this should in fact not the default but will only be used if for some reason the user has not defined a controller themselves.
