### ISSUE TITLE
[BUG] TypeError: fs.readFile is not a function

### ISSUE THREAD

**Issue by VictoriqueMoe** [TypedProject/ts-express-decorators#2597]
### Describe the bug

Updating to the latest version of `tsed` `7.61.1` while trying to render an EJS file, i get the error `TypeError: fs.readFile is not a function`
https://github.com/tsedio/tsed/blob/production/packages/engines/src/utils/cache.ts#L80

It seems that the methd `read` inside of `cache.js` now imports `fs-extra` but `fs-extra` does not have the method `readFile`.

It might be worth noting i am using ESM

![image](https://github.com/tsedio/tsed/assets/27996712/1b871c78-8897-4a60-9e45-4f84c3e0413b)

### To Reproduce

* install latest TSED under ESM (might not be relevent)
* set up EJS
* set up a `@View()` in controller to ejs file
* load the page

### Expected behavior

the file is rendered and page loads

### OS

Windows 11

### Node version

v20.11.0

### Library version

7.61.1

**Comment by Romakita** [comment]
Hello @VictoriqueMoe 
Thanks for the detailled I’ll try to fix that tomorrow. Maybe use fs-extra in this case isn’t relevant. 
I recently updated the fs-extra version but the CI haven’t detected this issue.

I’ll come back to you when the bug is solved ;)
See you

**Comment by VictoriqueMoe** [comment]
> Hello @VictoriqueMoe Thanks for the detailled I’ll try to fix that tomorrow. Maybe use fs-extra in this case isn’t relevant. I recently updated the fs-extra version but the CI haven’t detected this issue.
> 
> I’ll come back to you when the bug is solved ;) See you

awesome thanks! i just reverted version for the time beaing and it works. not sure why `fs-extra` was introdiced here. but yea :)

big fan of the framework, i use it extensively on 3 of my large projects and it's wonderful! thanks for the hard work!

**Comment by Romakita** [comment]
In the previous version fs-extra was imported on top of the cache.ts but because fs-extra in the latest version, is pure ESM module, I had to move it in the code using the dynamic `import()` instruction to doesn't break the package in the Commonjs version. I should have gone further and even asked if it was still useful to go through fs-extra just to read a file ;)

Thanks a lot for your feedback !!

The PR is ready #2598

**Comment by nakedmcse** [comment]
Thank you

**Comment by VictoriqueMoe** [comment]
I can confirm this fixes the issue, thank you! <3
