### ISSUE TITLE
[BUG] UseCache does not work on services

### ISSUE THREAD

**Issue by ktalebian** [TypedProject/ts-express-decorators#2612]
### Describe the bug

I cannot use `UseCache` on the method of a Service - it never caches the response

### To Reproduce

1. Clone https://github.com/ktalebian/tsed-bug
2. `npm i && npm run dev`
3. `curl localhost:8083/cache` twice
4. You see `MyService.doSomething is called` twice (should only be once) 

### Expected behavior

I expect only to see `MyService.doSomething is called` once

### Code snippets

```TypeScript
Cache has been enabled as seen on https://github.com/ktalebian/tsed-bug/blob/main/src/Server.ts#L13

Class that is using `@UseCache` is https://github.com/ktalebian/tsed-bug/blob/main/src/services/MyService.ts

It is being used in https://github.com/ktalebian/tsed-bug/blob/main/src/controllers/rest/Controller.ts#L18
```

### Repository URL example

https://github.com/ktalebian/tsed-bug

### OS

macOS

### Node version

Node v18

### Library version

v7.62.2

**Comment by ktalebian** [comment]
Also, https://tsed.io/docs/cache.html#configuration says to import `import { UseCache } from '@tsed/common';` which is incorrect - it should be imported from `@tsed/platform-cache`

**Comment by Romakita** [comment]
The error is probably here:
```ts
import { Injectable } from "@tsed/di";
import { $log } from "@tsed/logger";
import { UseCache } from "@tsed/platform-cache";

@Injectable()
export class MyService {
    @UseCache({ key: 'some-provider', canCache: () => true })
    public doSomething = () => { /// Why do you set an arrow function here ?
        $log.info('MyService.doSomething is called');
        return 'test-123';
    }
}
```
Typescript considers `doSomething` as property and not as a method. The decorator won't be able to intercept the method (it's an interceptor). Please next time to follow the given code example as is it ;). Don't try to do custom things.

I'll fix the type on the given code example for the import.

See you
