### ISSUE TITLE
Support `@Hidden` in query parameters

### ISSUE THREAD

**Issue by VictoriqueMoe** [TypedProject/ts-express-decorators#2635]
### Is your feature request related to a problem? Please describe.

This might not be a `bug` per say, but if you add `@Hidden` to a query param, the swagger doc is still generate, this is the case for both a paramater on the method OR as a model

```ts
export class FileUploadParameters {
    @Optional()
    @Property()
    @Hidden()
    public secret_token?: string;
}
public async addEntry(
	@QueryParams()
	params: FileUploadParameters,
): Promise<unknown> {}
```
`secret_token` is still displayed and `@Hidden()` seems to be totally ignored.

This seems to only happen for query and not actual schema object for body and stuff

### Describe the solution you'd like

`@Hidden()` should work the same for all, be it query or schema, it should be ignored when generating the open spec

**Comment by Romakita** [comment]
Hello @VictoriqueMoe 
Hidden decorator is only for hide method & class controller. Isn't applicable for a Model.
In this case, you have the `@Groups` decorator which is more indicated for your usecase. 

```ts
class FileUploadParameters {
    @Optional()
   @Groups("!summary") // "summary" is arbitrary
    public secret_token?: string;
}

public async addEntry(
	@QueryParams() @Groups("summary") 
	params: FileUploadParameters,
): Promise<unknown> {}
```

> Note: In this case, json-mapper pick the secret_token property from the given payload. It's maybe not your needs ?

**Comment by VictoriqueMoe** [comment]
> Hello @VictoriqueMoe Hidden decorator is only for hide method & class controller. Isn't applicable for a Model. In this case, you have the `@Groups` decorator which is more indicated for your usecase.
> 
> ```ts
> class FileUploadParameters {
>     @Optional()
>    @Groups("!summary") // "summary" is arbitrary
>     public secret_token?: string;
> }
> 
> public async addEntry(
> 	@QueryParams() @Groups("summary") 
> 	params: FileUploadParameters,
> ): Promise<unknown> {}
> ```
> 
> > Note: In this case, json-mapper pick the secret_token property from the given payload. It's maybe not your needs ?

duh of course, maybe it would be best to change it into a Class and method Decoratyor only then to i get type error

**Comment by VictoriqueMoe** [comment]
yeh, `@Group` was the only decorator i really never fully understood how to use correctly. all i want to do is hide a value from swagger, marshalling and unmarshalling from the JSON should work as expected

**Comment by VictoriqueMoe** [comment]
if i do the whole ` @Groups("!summary")` thing, when i supply a `secret_token` it won't appear in the object 
![image](https://github.com/tsedio/tsed/assets/27996712/277962f8-af52-4a13-b0e3-cb90b597bec3)
maybe it's not possible

**Comment by Romakita** [comment]
Yes, Groups has an effect on the json-mapper also. So if you just want hide the property on the swagger, it's complicated (currently), because, the same schema is used for Swagger, Json-mapper and Validation.

Reuse Hidden decorator for this purpose could be possible. But is it really a problem to display a field that is described by the model and that can be used by a consumer ? 

For my part, if the field exists and can be used by the client, then it should be documented ^^. Otherwise it's called a backdoor :)

**Comment by VictoriqueMoe** [comment]
> Yes, Groups has an effect on the json-mapper also. So if you just want hide the property on the swagger, it's complicated (currently), because, the same schema is used for Swagger, Json-mapper and Validation.
> 
> Reuse Hidden decorator for this purpose could be possible. But is it really a problem to display a field that is described by the model and that can be used by a consumer ?
> 
> For my part, if the field exists and can be used by the client, then it should be documented ^^. Otherwise it's called a backdoor :)

I think there are times where params and args won't be documented, ones that comes to mind are things like tracking tokens, ouath verifications and the likes.

I do, however agree. i will just move them to custom headers or something.

**Comment by Romakita** [comment]
Ok for oauth generally we use Header instead query params ^^

**Comment by Romakita** [comment]
Maybe tracking token could be a good reason. 🤔
