### ISSUE TITLE
[TECH] Migrate tests from jest to vitest

### ISSUE THREAD

**Issue by Romakita** [TypedProject/ts-express-decorators#2637]

**Comment by derevnjuk** [comment]
@Romakita what do you think about migrating to [the native test runner](https://nodejs.org/docs/latest-v20.x/api/test.html), thereby completely eliminating the need to use jest, vitest, and mocha? Like vitest it has a jest-compatible API, as result the migration process will be a quite straightforward.

**Comment by Romakita** [comment]
I haven’t tested a native test runner. But native test runner add some feature like coverage (autoUpdate, transformers, globalsetups) that are required by the current stack ;)
And I prefer to use a  tool that is used by major project to detect issue related to jest / vitest early.

**Comment by Romakita** [comment]
Done
