### ISSUE TITLE
[BUG] Swagger UI no longer loads

### ISSUE THREAD

**Issue by VictoriqueMoe** [TypedProject/ts-express-decorators#2692]
### Describe the bug

https://github.com/tsedio/tsed/issues/2683 is still an issue. see: https://github.com/tsedio/tsed/issues/2683#issuecomment-2090678538

### To Reproduce

1. enable ESM
2. set up swagger
3. try to load page

### Expected behavior

swagger UI loads

### OS

Windows 11

### Node version

v20.11.0

### Library version

7.68.3

**Comment by Romakita** [comment]
Hello @VictoriqueMoe 
I just tried to reproduce and this swagger load correctly in a pure ESM project.

I'll checkout your project to see if there is something different.

See you

**Comment by VictoriqueMoe** [comment]
> Hello @VictoriqueMoe I just tried to reproduce and this swagger load correctly in a pure ESM project.
> 
> I'll checkout your project to see if there is something different.
> 
> See you

weird, then you need this branch: https://github.com/waifuvault/WaifuVault/tree/bump-version

Thank you very much :(

**Comment by Romakita** [comment]
I'm not able to start the project, the DB doesn't start XD

**Comment by VictoriqueMoe** [comment]
> I'm not able to start the project, the DB doesn't start XD

use this env
```
PORT=localhost:8081
HTTPS=false
HTTPS_PORT=4000
SESSION_KEY=YourSessionKey
NODE_ENV=development
BASE_URL=http://localhost:8081
FILE_SIZE_UPLOAD_LIMIT_MB=512
```
should start. DB is just sqlite. should not have a problem

**Comment by VictoriqueMoe** [comment]
oh yeh, run `npm run runmigration` 

then it should work :)

**Comment by Romakita** [comment]
That's what I told myself and created the .env, but strangely I got this:

```
  event: 'SERVER_BOOTSTRAP_ERROR',
  message: 'no such table: user_model',
  stack: 'SqliteError: no such table: user_model\n' +
```

**Comment by VictoriqueMoe** [comment]
![image](https://github.com/tsedio/tsed/assets/27996712/52ee1edc-633e-4b2b-a702-6bc62a539092)

yeh, you need to do `npm run runmigration` to create the tables

**Comment by Romakita** [comment]
ok after running migration it works :)

**Comment by Romakita** [comment]
Here is the swagger docs:

<img width="1024" alt="Capture d’écran 2024-05-02 à 17 32 40" src="https://github.com/tsedio/tsed/assets/1763311/f5768bb9-7095-4639-a217-c3e881efe2ce">

**Comment by Romakita** [comment]
But isn't on your branch. I'll checkout your branch to see if there is dependencies issue

**Comment by VictoriqueMoe** [comment]
> But isn't on your branch. I'll checkout your branch to see if there is dependencies issue

oh yea, on the main branch it is ok. but the branch i posted is the issue one :)

**Comment by Romakita** [comment]
> oh yea, on the main branch it is ok. but the branch i posted is the issue one :)
On the main branch, I updated the packages. ho hey I don't make this kind of mistake yet :p

On your branch I have the swagger ui also :D

**Comment by Romakita** [comment]
<img width="1024" alt="Capture d’écran 2024-05-02 à 17 39 29" src="https://github.com/tsedio/tsed/assets/1763311/6331baac-ed11-47e5-a10d-42fe5f586021">

I have to clear the browser cache. After that, I saw the new swagger ui version ^^. Maybe you have to clear your cache also.

**Comment by VictoriqueMoe** [comment]
> I have to clear the browser cache. After that, I saw the new swagger ui version ^^. Maybe you have to clear your cache also.

Is this the new branch? clearing my cashe did nothing, and using different browsers
![image](https://github.com/tsedio/tsed/assets/27996712/77946026-5e29-4ce9-a94b-f6ee2110ab9b)

**Comment by Romakita** [comment]
I see you have 127.0.0.1, can you try with localhost ?

**Comment by Romakita** [comment]
Try also to curl this url: http://localhost:8081/api-docs/swagger-ui-standalone-preset.js

I have that in the console:

```
[2024-05-02T17:47:01.832] [INFO ] [TSED] - {
  reqId: 'efdf6738859042d7a89f7e8569a46ad4',
  method: 'GET',
  url: '/api-docs/swagger-ui-standalone-preset.js',
  duration: 8,
  route: '/api-docs',
  time: 2024-05-02T15:47:01.832Z,
  event: 'request.end',
  status: 200,
  status_code: '200',
  state: 'OK'
}

```

**Comment by VictoriqueMoe** [comment]
> I see you have 127.0.0.1, can you try with localhost ?

yes, i set my env to `BASE_URL=http://127.0.0.1:8081` because setting it to localhost doesn't work with the printed text on console.

but this doesn't fix it 
![image](https://github.com/tsedio/tsed/assets/27996712/f8d2400c-ac1f-4de0-acd5-7798d200fbea)

and CURL doesn't work too
![image](https://github.com/tsedio/tsed/assets/27996712/50c2506e-f1de-4097-9161-96b802e38785)

**Comment by Romakita** [comment]
Hum ok, but you have PORT=localhost:8081 ?

**Comment by VictoriqueMoe** [comment]
my env 

```
PORT=localhost:8081
SESSION_KEY=foo
HTTPS=false
HTTPS_PORT=4000
NODE_ENV=development
BASE_URL=http://localhost:8081
FILE_SIZE_UPLOAD_LIMIT_MB=9000
#CLAM_PATH="Y:\dp\Dropbox\Portable apps\clamav-1.2.1.win.x64"
BLOCKED_MIME_TYPES=application/x-dosexec,application/x-executable,application/x-hdf5,application/x-java-archive,application/vnd.rar
USE_CLOUDFLARE=false
MAX_URL_LENGTH=4096
SALT=3jS'f;£[
UPLOAD_SECRET=foobar
MS_DEFENDER_PATH="C:\Program Files\Windows Defender"
```

**Comment by VictoriqueMoe** [comment]
> Hum ok, but you have PORT=localhost:8081 ?

oh yeh, all the Webservices and home page load fine. just swagger

**Comment by VictoriqueMoe** [comment]
do you think this is a Windows issue?

https://github.com/tsedio/tsed/pull/2684/files#diff-07ce5883fa56206cafb68b3fe4fb05749942a433254ca1317f0cb4540ff64966R5

maybe use `path.sep`?

**Comment by Romakita** [comment]
heu.....yes probably XD

**Comment by Romakita** [comment]
can you edit the node_module/@tsed/swagger/dist/lib/constants.js and change the / pls ?

**Comment by VictoriqueMoe** [comment]
that said, Windows works with both `/` and `\` 

`path.sep` should give the right `/` based on OS, as should `path.normalize` and `path.resolve` but eh. weird

**Comment by VictoriqueMoe** [comment]
> can you edit the node_module/@tsed/swagger/dist/lib/constants.js and change the / pls ?

sure. one sec

**Comment by Romakita** [comment]
You have certainly right, this is probably the problem ;)

**Comment by VictoriqueMoe** [comment]
yeh.

```js
dirname(import.meta.resolve("swagger-ui-dist"))
```
resolves to: `file:///C:/Users/ray-q/IdeaProjects/WaifuVault/node_modules/swagger-ui-dist`
so 
```js
dirname(import.meta.resolve("swagger-ui-dist")).replace("file://", "")
```
resolves to: `/C:/Users/ray-q/IdeaProjects/WaifuVault/node_modules/swagger-ui-dist`
notice the `/` at the start :D

**Comment by Romakita** [comment]
Hum ok T.T
Now we can try to fix that xD

**Comment by VictoriqueMoe** [comment]
```js
export const SWAGGER_UI_DIST = normalize(dirname(import.meta.resolve("swagger-ui-dist"))).replace(`file:${sep}`, "");
```
seems to work... but not sure for linux

but i kinda hate it

**Comment by Romakita** [comment]
Can you try that:

```ts
export const SWAGGER_UI_DIST = dirname(url.fileURLToPath(import.meta.resolve('swagger-ui-dist')))
```
`normalize` function isn't necessary, because the SWAGGER_UI_DIST is path consumer by a Fs lib.

**Comment by VictoriqueMoe** [comment]
Sure, I'll try it when I'm back at my pc

**Comment by Romakita** [comment]
PR is ready ;).

**Comment by VictoriqueMoe** [comment]
> PR is ready ;).

Wohh, wait until I tested the above

**Comment by VictoriqueMoe** [comment]
Yes, this works too
