### ISSUE TITLE
[BUG] Swagger issue on loading an undefined resource

### ISSUE THREAD

**Issue by VictoriqueMoe** [TypedProject/ts-express-decorators#2695]
### Describe the bug

When i load Swagger (in Linux). i am getting some 404's on my network tab, these seem to be some sort of resource generated from an undefined.

see https://waifuvault.moe/api-docs/

![image](https://github.com/tsedio/tsed/assets/27996712/b7b76035-113f-47d2-9be5-c1c80d5e5bb5)
![image](https://github.com/tsedio/tsed/assets/27996712/008888ef-2398-436d-af9c-9bfdcfde0f84)

Oddly enough, on my pc (Windows). when i load swagger, i don't get this, but also, i don't get the "valid" tick at the bottom right either. so not sure why it only happens when deployed on my production server

### To Reproduce

1. deploy under production
2. load swagger page
3. get 404 on page

### Expected behavior

Loads swagger page with no errors

### OS

Ubuntu 23.10

### Node version

v20.11.1

### Library version

7.68.5

**Comment by VictoriqueMoe** [comment]
It seems to be coming from the validator badge

**Comment by Romakita** [comment]
Hello @VictoriqueMoe 

I finally decided to use the getAbsolutePath from `swagger-ui-dist/get-absolute-path.js` it seems to works correctly. I was thinking importing file directly (when exports isn't defined in the package.json of the module) doesn't works in ESM. Finally, if exports is missing, ESM can import any files in the package.

It should solve your issue ;)
See you

**Comment by VictoriqueMoe** [comment]
> Hello @VictoriqueMoe
> 
> I finally decided to use the getAbsolutePath from `swagger-ui-dist/get-absolute-path.js` it seems to works correctly. I was thinking importing file directly (when exports isn't defined in the package.json of the module) doesn't works in ESM. Finally, if exports is missing, ESM can import any files in the package.
> 
> It should solve your issue ;) See you

@Romakita 

unfortantly, this did not solve the issue, i still get these 404's and the validator badge still errors 
![image](https://github.com/tsedio/tsed/assets/27996712/0a771f44-83a8-4310-abe7-44896f33a5a4)
![image](https://github.com/tsedio/tsed/assets/27996712/a4475826-2814-4c5c-ac1d-10840ce6cb64)

i deployed the latest tsed and you can see the error here: https://waifuvault.moe/api-docs/

**Comment by Romakita** [comment]
Ok. But now the path is directly get from swagger-ui-dist. So it's not related to the latest changes. Maybe the problem is related to swagger-ui-dist itself?

**Comment by Romakita** [comment]
But we can see a undefined string in the url. I'll check if other changes have introduce this regression. It's a bit complicated to repro in local when the badge is only displayed on a non localhost domain. I'll keep you informed if I found something ;)
And sorry for this unresolved issue!

**Comment by VictoriqueMoe** [comment]
> But we can see a undefined string in the url. I'll check if other changes have introduce this regression. It's a bit complicated to repro in local when the badge is only displayed on a non localhost domain. I'll keep you informed if I found something ;) And sorry for this unresolved issue!

yeh, it's annoying for sure that is hard to test. editing the hosts file to proxy a localhost domain worked for me.

also, no problem! it's not really a blocker. However, this is a blocker: https://github.com/orgs/tsedio/discussions/2697 if that counts for anything :D 

thank you as always for your amazing support and help

**Comment by Romakita** [comment]
Ho shit missed this issue. I'll try to find a way to fix that ASAP @VictoriqueMoe ;)
