### ISSUE TITLE
[BUG] Custom `.Error` does not work on schemas other than `@Required`

### ISSUE THREAD

**Issue by ktalebian** [TypedProject/ts-express-decorators#2696]
### Describe the bug

Here is a request object:

```ts
class MyRequest {
  @Property()
  @MinLength(10).Error('Title must be at least 10 characters long')
  title: string;
}
```

And the controller

```ts
@Controller("/")
export class HelloWorldController {
  @Inject()
  myService: MyService;

  @Post("/body")
  @Returns(200, String)
  async cache(@BodyParams() body: MyRequest) {
    return 'done';
  }
}
```

I expect to get a custom error message when I make `curl localhost:8083/body -XPOST -H "Content-Type: application/json" -d '{"title":"short"}'` but still get the generic message:

```json
{
  "name": "AJV_VALIDATION_ERROR",
  "message": "Bad request on parameter \"request.body\".\nMyRequest.title must NOT have fewer than 10 characters. Given value: \"foo\"",
  "status": 400,
  "errors": [
    {
      "instancePath": "/title",
      "schemaPath": "#/properties/title/minLength",
      "keyword": "minLength",
      "params": {
        "limit": 10
      },
      "message": "must NOT have fewer than 10 characters",
      "data": "foo",
      "modelName": "MyRequest",
      "dataPath": ".title",
      "requestPath": "body"
    }
  ],
}
```

I tried a few different decorators. It looks like only the `@Required` decorator works.

### To Reproduce

1) Clone https://github.com/ktalebian/tsed-bug
2) `npm i`
3) `npm start`
4) `curl localhost:8083/body -XPOST -H "Content-Type: application/json" -d '{"prop1":"asd"}' | jq .`

### Expected behavior

Expected to see `Title must be at least 10 characters long` message.

### Repository URL example

https://github.com/ktalebian/tsed-bug

### OS

macOS

### Node version

Node 20

### Library version

v7.*

**Comment by Romakita** [comment]
@ktalebian thanks a lot for the issue. I'll try to that asap ;)
