### ISSUE TITLE
[BUG] ESM error in BullMQModule

### ISSUE THREAD

**Issue by EinfachHans** [TypedProject/ts-express-decorators#2705]
### Describe the bug

I just migrated my project to ESM. I get this error atm:

`Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/hans/IdeaProjects/project_name/node_modules/@tsed/bullmq/lib/esm/dispatchers.js' imported from /Users/hans/IdeaProjects/project_name/node_modules/@tsed/bullmq/lib/esm/BullMQModule.js`

When i look into `@tsed/bullmq/lib/esm/BullMQModule.js`, the line 8 is:

```js
import { JobDispatcher } from "./dispatchers.js";
```

while `dispatchers` is a folder, containing an `index.js`, so there is no file called `dispatchers.js`

### To Reproduce

Use the bullmq module in an esm project.

### Expected behavior

The import should be correct

### OS

macOS

### Node version

20.12.1

### Library version

7.69.2

**Comment by Romakita** [comment]
It shouldn't be an issue to fix that ;)
