### ISSUE TITLE
[BUG] New implementation of "nullable" decreases the accuracy of ajv errors.

### ISSUE THREAD

**Issue by Bugslive** [TypedProject/ts-express-decorators#2751]
### Describe the bug

The new implementation of "Nullable" prevents the developer/API client to capitalize on the AJV errors as all possible format validation errors are returned.

### To Reproduce

1. Fetch https://github.com/Bugslive/nullable
2. Install package with `npm install`
3. Start the app with `npm start`
4. Send POST request to `http://127.0.0.1:8083/rest/nullable` with body `{"name": "toto", "description": "aaaaaaaaaaaa"}`
5. Observe the answer and especially the number of errors (3 errors).
6. Compare with error with v7.75.3

### Expected behavior

The expected number of error is 1, and error to be:
    {
      "instancePath": "/description",
      "schemaPath": "#/properties/description/maxLength",
      "keyword": "maxLength",
      "params": {
        "limit": 10
      },
      "message": "must NOT have more than 10 characters",
      "data": "aaaaaaaaaaaa",
      "modelName": "ExampleModel",
      "dataPath": ".description",
      "requestPath": "body"
    }

### Repository URL example

https://github.com/Bugslive/nullable

### OS

macOS

### Node version

Node v22.4.1

### Library version

v7.75.4

**Comment by Romakita** [comment]
Doesn't seems to be a bug @Bugslive 

Ajv returns errors according to the applied schema. Before the previous fix, the schema was totally wrongs. So if ajv return more errors, but errors are consistent isn't an issue but the expected behavior!
