### ISSUE TITLE
[BUG] @Integer annotation is no more taking into model when used with @Nullable(Number)

### ISSUE THREAD

**Issue by Bugslive** [TypedProject/ts-express-decorators#2754]
### Describe the bug

@Nullable decorator, used in conjunction with @Integer(), causes AJV to return error (when a string is sent instead of a number) with expected type as "null, number" instead of "null, integer"

### To Reproduce

1.     Fetch https://github.com/Bugslive/nullable
2.     Install package with npm install
3.     Start the app with npm start
4.     Send POST request to http://127.0.0.1:8083/rest/nullable with body {"name": "toto", "description": "aaaaaaa", "itemCount": "toto"}
5.     Observe the answer, and especially error[0].params.type
6.     Compare with error with v7.75.3

### Expected behavior

expected params.type is [null, integer] instead of [null, number]

### Code snippets

```TypeScript
export class MySchema {
    @Property()
    @Integer()
    @Nullable(Number)
    itemCount: Number | null;
}

@Controller("/test")
export class TestController {
    @Post("/validation")
    validate(@BodyParams() body: MySchema) {
        return body;
    }
}
```

### Repository URL example

https://github.com/Bugslive/nullable

### OS

macOS

### Node version

Node v22.4.1

### Library version

v7.75.5

**Comment by Romakita** [comment]
JsonSchema on 7.75.3:

```json
{
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "Example name",
      "minLength": 1
    },
    "description": {
      "type": [
        "null",
        "string"
      ],
      "maxLength": 10,
      "description": "Example description"
    },
    "itemCount": {
      "type": [
        "null",
        "integer"
      ],
      "multipleOf": 1,
      "minimum": 0,
      "examples": [
        3600
      ],
      "description": "Example integer"
    }
  },
  "description": "Service account creation",
  "required": [
    "name"
  ]
}
```

Error:

```json
{
  "name": "AJV_VALIDATION_ERROR",
  "message": "Bad request on parameter \"request.body\".\nExampleModel.itemCount must be null,integer. Given value: \"toto3\"",
  "status": 400,
  "errors": [
    {
      "instancePath": "/itemCount",
      "schemaPath": "#/properties/itemCount/type",
      "keyword": "type",
      "params": {
        "type": [
          "null",
          "integer"
        ]
      },
      "message": "must be null,integer",
      "data": "toto2",
      "modelName": "ExampleModel",
      "dataPath": ".itemCount",
      "requestPath": "body"
    }
  ]
}
```

JSON schema 7.75.5

```json
{
  "name": "AJV_VALIDATION_ERROR",
  "message": "Bad request on parameter \"request.body\".\nExampleModel.itemCount must be null,integer. Given value: \"toto2\"",
  "status": 400,
  "errors": [
    {
      "instancePath": "/itemCount",
      "schemaPath": "#/properties/itemCount/type",
      "keyword": "type",
      "params": {
        "type": [
          "null",
          "integer"
        ]
      },
      "message": "must be null,integer",
      "data": "toto2",
      "modelName": "ExampleModel",
      "dataPath": ".itemCount",
      "requestPath": "body"
    }
  ],
 }
```
Error:

```json
{
  "name": "AJV_VALIDATION_ERROR",
  "message": "Bad request on parameter \"request.body\".\nExampleModel.itemCount must be null,integer. Given value: \"toto3\"",
  "status": 400,
  "errors": [
    {
      "instancePath": "/itemCount",
      "schemaPath": "#/properties/itemCount/type",
      "keyword": "type",
      "params": {
        "type": [
          "null",
          "integer"
        ]
      },
      "message": "must be null,integer",
      "data": "toto3",
      "modelName": "ExampleModel",
      "dataPath": ".itemCount",
      "requestPath": "body"
    }
  ]
}
```

Same result :)

See you
Romain

**Comment by Romakita** [comment]
<img width="593" alt="Capture d’écran 2024-07-16 à 18 38 14" src="https://github.com/user-attachments/assets/d84be424-4869-4bdb-9a71-30fb24baae91">


```ts
console.log(JSON.stringify(getJsonSchema(ExampleModel), null, 2))

```

**Comment by Bugslive** [comment]
Hello Romain,

I check again on my side with my "nullable" project and I confirm my remarks

**with 7.75.3:**
`{
  "name": "AJV_VALIDATION_ERROR",
  "message": "Bad request on parameter \"request.body\".\nExampleModel.itemCount must be null,integer. Given value: \"toto3\"",
  "status": 400,
  "errors": [
    {
      "instancePath": "/itemCount",
      "schemaPath": "#/properties/itemCount/type",
      "keyword": "type",
      "params": {
        "type": [
          "null",
          "integer"
        ]
      },
      "message": "must be null,integer",
      "data": "toto3",
      "modelName": "ExampleModel",
      "dataPath": ".itemCount",
      "requestPath": "body"
    }
  ],
  "stack": "PARAM_VALIDATION_ERROR: Bad request on parameter \"request.body\".\nExampleModel.itemCount must be null,integer. Given value: \"toto3\"\n    at new Exception (/Users/vincent/workspace/tmp/nullable/node_modules/@tsed/exceptions/src/core/Exception.ts:62:11)\n    at new ClientException (/Users/vincent/workspace/tmp/nullable/node_modules/@tsed/exceptions/src/core/ClientException.ts:6:5)\n    at new BadRequest (/Users/vincent/workspace/tmp/nullable/node_modules/@tsed/exceptions/src/clientErrors/BadRequest.ts:7:5)\n    at new ParamValidationError (/Users/vincent/workspace/tmp/nullable/node_modules/@tsed/platform-params/src/errors/ParamValidationError.ts:6:1)\n    at Function.from (/Users/vincent/workspace/tmp/nullable/node_modules/@tsed/platform-params/src/errors/ParamValidationError.ts:20:21)\n    at /Users/vincent/workspace/tmp/nullable/node_modules/@tsed/platform-params/src/builder/PlatformParams.ts:83:36\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at /Users/vincent/workspace/tmp/nullable/node_modules/@tsed/platform-params/src/builder/PlatformParams.ts:78:15\n    at async Promise.all (index 0)\n    at async Promise.all (index 1)"
}`

**with 7.75.5:**
`{
  "name": "AJV_VALIDATION_ERROR",
  "message": "Bad request on parameter \"request.body\".\nExampleModel.itemCount must be null,number. Given value: \"toto3\"",
  "status": 400,
  "errors": [
    {
      "instancePath": "/itemCount",
      "schemaPath": "#/properties/itemCount/type",
      "keyword": "type",
      "params": {
        "type": [
          "null",
          "number"
        ]
      },
      "message": "must be null,number",
      "data": "toto3",
      "modelName": "ExampleModel",
      "dataPath": ".itemCount",
      "requestPath": "body"
    }
  ],
  "stack": "PARAM_VALIDATION_ERROR: Bad request on parameter \"request.body\".\nExampleModel.itemCount must be null,number. Given value: \"toto3\"\n    at new Exception (/Users/vincent/workspace/tmp/nullable/node_modules/@tsed/exceptions/src/core/Exception.ts:62:11)\n    at new ClientException (/Users/vincent/workspace/tmp/nullable/node_modules/@tsed/exceptions/src/core/ClientException.ts:6:5)\n    at new BadRequest (/Users/vincent/workspace/tmp/nullable/node_modules/@tsed/exceptions/src/clientErrors/BadRequest.ts:7:5)\n    at new ParamValidationError (/Users/vincent/workspace/tmp/nullable/node_modules/@tsed/platform-params/src/errors/ParamValidationError.ts:6:1)\n    at Function.from (/Users/vincent/workspace/tmp/nullable/node_modules/@tsed/platform-params/src/errors/ParamValidationError.ts:20:21)\n    at /Users/vincent/workspace/tmp/nullable/node_modules/@tsed/platform-params/src/builder/PlatformParams.ts:83:36\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at /Users/vincent/workspace/tmp/nullable/node_modules/@tsed/platform-params/src/builder/PlatformParams.ts:78:15\n    at async Promise.all (index 0)\n    at async Promise.all (index 1)"
}`

**Comment by Bugslive** [comment]
and in my swagger for itemCount property,
**with 7.75.3:**
```JSON
"itemCount": {
  "type": "integer",
  "multipleOf": 1,
  "minimum": 0,
  "example": 3600,
  "description": "Example integer",
  "nullable": true
}
```

**with 7.75.5:**
```JSON
"itemCount": {
  "type": "number",
  "multipleOf": 1,
  "minimum": 0,
  "example": 3600,
  "description": "Example integer",
  "nullable": true
}
```

**Comment by Romakita** [comment]
@Bugslive Next time please be more precise about your issue, because you talking about ajv issue and not about swagger spec which is two different things. I consider your bug isn't really a bug whil multipleOf is present in the schema  ;)

**Comment by Romakita** [comment]
And for the error los, I haven't the same result as I said in my previous comment.

**Comment by Bugslive** [comment]
@Romakita , sorry if I was not clear.
The fact that in the swagger, and as well as in ajv error, the type is "number" in v7.75.5 instead of "integer" in v7.75.3 is for me a regression, even if it is minor and that's why I opened a bug.

**Comment by Bugslive** [comment]
Thanks a lot @Romakita

**Comment by Romakita** [comment]
Thank you too @Bugslive for your reactivity and your issues!
