### ISSUE TITLE
[BUG] adding optional path paramater duplciates the endpoint in swagger

### ISSUE THREAD

**Issue by VictoriqueMoe** [TypedProject/ts-express-decorators#2787]
### Describe the bug

If you create an endpoint with an optional path param (E.g: `@Put("/:bucketToken?")`) it will duplicate the endpoint. but one of those entries has the `bucketToken` and one does not.

![image](https://github.com/user-attachments/assets/f473a55c-8c4e-430d-87df-203a14865f66)
![image](https://github.com/user-attachments/assets/620b37c6-e162-4895-85e6-d943d8d7133c)
![image](https://github.com/user-attachments/assets/c7d792b8-b1b0-40c3-aa1b-cece51902df4)

you can see in the 2nd image the path param is there but maked as "required", what i expect is there to only be one endpoint with the path param not required (optional)

### To Reproduce

1. Create an endpoint with a optional path param
2. look at the swagger ui

### Expected behavior

there should be ONE endpoint with the path param maked as not required

### Code snippets

```TypeScript
@Put("/:bucketToken?")
    public async addEntry(
        @PathParams("bucketToken")
        bucketToken?: string,
    ): Promise<unknown> {}
```

### Repository URL example

https://github.com/waifuvault/WaifuVault

### OS

Windows 11

### Node version

v20.15.0

### Library version

v7.79.4

**Comment by Romakita** [comment]
Hello @VictoriqueMoe 
Isn't a bug. OAS 3 and swagger 2 doesn't allow to have path without `required: true`. Look the screenshot:

<img width="762" alt="Capture d’écran 2024-08-19 à 09 39 15" src="https://github.com/user-attachments/assets/4ac57322-09c7-49f5-b79e-92a7fe9f9e1d">

You can play with the swagger editor to reproduce the error message: https://editor.swagger.io/

You have no choices to accept to have two routes ^^

See you
Romain

**Comment by VictoriqueMoe** [comment]
I see. my bad, i did not realise this.
