### ISSUE TITLE
Add scalar integration

### ISSUE THREAD

**Issue by kucherenko** [TypedProject/ts-express-decorators#2855]
### Describe the solution you'd like

Add ability to use https://scalar.com/ instead of swagger for working with API

**Comment by Romakita** [comment]
Hi @kucherenko 

Good idea.
You can take the @tsed/swagger module as example here:

https://github.com/tsedio/tsed/tree/production/packages/specs/swagger

the module consume tsed server metadata to generate openAPI spec and give the spec to swagger-ui middleware.

based on the scalar express.js example, you have to replace swagger-ui by scalar ;)

see you

**Comment by Romakita** [comment]
Released with v8
