### ISSUE TITLE
[BUG] Module '"@tsed/prisma"' has no exported member 

### ISSUE THREAD

**Issue by zinootje** [TypedProject/ts-express-decorators#2867]
### Describe the bug

The most recent version of @tsed/prisma doesn't work with typescript anymore when importing generated models from'@tsed/prisma'.

the file \node_modules\@tsed\prisma\lib\types\index.d.ts cointains the following

`export * from "../.schema.js";`

when manually changing to 
`export * from "../.schema";`
(removing the file extenions)
everything works as expected
 

### To Reproduce

1. clone the prisma example repo (https://github.com/tsedio/tsed-example-prisma)
2. update packages to most recent version
3. try to build

### Expected behavior

import works as before (last tested version that works 7.36.5à

### Repository URL example

https://github.com/tsedio/tsed-example-prisma

### OS

Windows Os

### Node version

v20.18.0

### Library version

v7.83.4

**Comment by Romakita** [comment]
fixed :)
