### ISSUE TITLE
[BUG] @tsed/objection does not support commonjs

### ISSUE THREAD

**Issue by LonguCodes** [TypedProject/ts-express-decorators#2911]
### Describe the bug

Currnently @tsed/objection package is compiled to ESM only, while most (if not all other) @tsed packages are compiled to both. This renders it unusable in cjs projects

### To Reproduce

1. Install @tsed/objection
2. inspect the compiled package in node_modules

### Expected behavior

Package is compiled with both versions

### OS

Linux

### Node version

22.54.1

### Library version

v8.0.4

**Comment by Romakita** [comment]
Hi @LonguCodes 
All v8 packages are compiled to esm only. This is the main breaking change in the v8 package. See this page: https://tsed.dev/introduction/what-is-news-v8.html

You’ve probably missed something!

I close this issue. V8 won’t support commonjs runtime anymore!

see you

**Comment by Romakita** [comment]
`@tsed/platform-http` is esm only and all other v8 packages are esm only.
![IMG_3861](https://github.com/user-attachments/assets/49023078-86ad-44ea-9b30-a931ddb87b80)

**Comment by LonguCodes** [comment]
Thank you very much, that explaints a lot. Didn't realize my project uses v7 and installed wrong objection.
