### ISSUE TITLE
Chaining Interceptors

### ISSUE THREAD

**Issue by dgreasi** [TypedProject/ts-express-decorators#2914]
### Describe the bug

I am trying to call 2 interceptors (chained) before running a service using the `@Interceptor()` decorator. Only the 1st interceptor is triggered, never the 2nd one. Changing the order of the 2 interceptors has the same result (only the 1st one is triggered)

### To Reproduce

Environment:
```
"@tsed/ajv": "7.35.1",
"@tsed/common": "7.35.1",
"@tsed/core": "7.35.1",
"@tsed/di": "7.35.1",
"@tsed/exceptions": "7.35.1",
"@tsed/json-mapper": "7.35.1",
"@tsed/passport": "7.35.1",
"@tsed/platform-express": "7.35.1",
"@tsed/schema": "7.35.1",
```

Interceptors:
```
import { Interceptor, InterceptorContext, InterceptorMethods, InterceptorNext } from '@tsed/di';

@Interceptor()
export class SimpleInterceptorA implements InterceptorMethods {
  intercept(context: InterceptorContext<any>, next: InterceptorNext): any {
    console.log("SimpleInterceptorA executed");
    // Using await in `next()` is not changing the behavior
    return next();
  }
}

@Interceptor()
export class SimpleInterceptorB implements InterceptorMethods {
  intercept(context: InterceptorContext<any>, next: InterceptorNext): any {
    console.log("SimpleInterceptorB executed");
    // Using await in `next()` is not changing the behavior
    return next();
  }
}
```

Usage in service:
```
@Service()
export class MyService {
  @Intercept(SimpleInterceptorA)
  @Intercept(SimpleInterceptorB)
  async getEntityA(
    userId: string,
    companyId: string,
  ): Promise<any> {
    console.log('MyService -- getEntityA() started');
    return null;
  }

  @Intercept(SimpleInterceptorB)
  @Intercept(SimpleInterceptorA)
  async getEntityB(
    userId: string,
    companyId: string,
  ): Promise<any> {
    console.log('MyService -- getEntityB() started');
    return null;
  }
}
```

When calling `getEntityA`, I am getting the following:
```
SimpleInterceptorA executed
MyService -- getEntityA() started'
```

When calling `getEntityB`, I am getting the following:
```
SimpleInterceptorB executed
MyService -- getEntityB() started'
```

You can see that in both cases the 2nd interceptor is not triggered

### Expected behavior

Chaining of Interceptors should work as expected and both interceptors should be triggered

Example:

When calling `getEntityA`, I should get:
```
SimpleInterceptorA executed
SimpleInterceptorB executed
MyService -- getEntityA() started'
```

When calling `getEntityB`, I should get:
```
SimpleInterceptorB executed
SimpleInterceptorA executed
MyService -- getEntityB() started'
```

### OS

macOS

### Node version

v18.18.2

### Library version

v7.35.1

**Comment by Romakita** [comment]
HI @dgreasi 
have your the same issue with the v7.84.1?

> Note: the fix wil only applied on the latest v7, you have to update your tsed dependencies

**Comment by Romakita** [comment]
Hi @dgreasi 

By design, in v7 isn't possible to chaine interceptors. Isn't a bug, but a design issue. Changing that will be complicated (v7 is under maintenance now).

This PR add chained providers for v8 branch: https://github.com/tsedio/tsed/pull/2915

**Comment by dgreasi** [comment]
Hi @Romakita thanks for the clarification

**Comment by Romakita** [comment]
You’re welcome @dgreasi 
The workaround is to create an interceptor to call the twice other interceptors. Isn’t obvious and pretty dirty to do that. I’m really sorry for this issue! 
the DI in v8 was simplified and the fix is straight forward compared to v7. 

See you
