### ISSUE TITLE
[DI/FEAT] Can not inject two different instances of the same class

### ISSUE THREAD

**Issue by kalu111** [TypedProject/ts-express-decorators#386]
Hi @Romakita 

```typescript
@Service()
@Scope('request')
class TestService {

}

@Service()
class OtherService {
    constructor(
       @Inject(TestService) test1: TestService,
       @Inject(TestService) test2: TestService,
   ) {
    console.log(this.test1 === this.test2); // prints true
   }
}

**Comment by kalu111** [comment]
OK,
I thought that when I use `@Scope('request')` inject service will always inject a fresh new instance of a service.

I'm disappointed :(

**Comment by Romakita** [comment]
No the Scope per request mean the injector create the service per request.

**Comment by Romakita** [comment]
I'm not sure but this is the same behavior with Sprint mvc in Java

**Comment by kalu111** [comment]
What do you think to create another scope?

**Comment by kalu111** [comment]
In Java Spring exists "prototype" scope

**Comment by Romakita** [comment]
You can create a PR, if you want :).

Otherwise, you can do that:

```typescript
@Service()
class TestService {

}

@Service()
class OtherService {
    private test1: TestService,
    private test2: TestService,

    constructor(
       injector: InjectoService
   ) {
     this.test1 = injector.invoke(TestService);
     this.test2 = injector.invoke(TestService);
  }
}
```
More simple for you and me (any development is required from me :))

See you
Romain

**Comment by kalu111** [comment]
I think that the solution with `prototype` scope looks better than manually invoking a service.

If it is possible, yes I would like to have such feature :)

**Comment by kalu111** [comment]
Hi, 
How can I become a contributor?

I just wrote a new scope type and I would like to publish it.

**Comment by milewski** [comment]
@kalu111 you can start by submitting a pull request :)

more info here: https://romakita.github.io/ts-express-decorators/#/contributing?id=submitting-code

**Comment by kalu111** [comment]
Hi, thanks :)
After forked your repository I have just created a branch using `gflow` and wrote new feature.
I want to push my branch but what template of commit should I use?

**Comment by Romakita** [comment]
for example if you add a feature, the template of commit is:
```
feat(di): Add prototype scope

Something.....

Closes: #386

```

**Comment by Romakita** [comment]
@kalu111 Sorry if I take a long time to answer, I have a lot of things to do XD

**Comment by kalu111** [comment]
Hi,
Please check :)

**Comment by Romakita** [comment]
@kalu111 Can you create a PR ?

**Comment by Romakita** [comment]
As I seen, it should be ok :). Just create PR from your repo/branch to this repository ;)

**Comment by kalu111** [comment]
OK, thanks.
But I have some trubles with my local GIT and I forced to delete that branch.

I will create a new, but it is possible to detach old branch from this issue ?

**Comment by Romakita** [comment]
I don't know, but don't worry about that ;). Just create you new branch, push it and create a PR. History in this issue isn't really important.

**Comment by Romakita** [comment]
Ts.ED support ProviderScope.INSTANCE with v5.16.0
