### ISSUE TITLE
@Scope("request") Service is not singleton per request

### ISSUE THREAD

**Issue by nhabuiduc** [TypedProject/ts-express-decorators#430]
## Informations

Type | Version
---|---
Bug | 4.x

****

## Description
Scope "Request" should only create one instance per request, (singleton per request), but looks like it creates instance on each dependency.

## Example

Example of code with 1 controller and 2 services, they are all Scope("request")

```typescript
@Controller("/calendars")
@Scope("request")
export class CalendarCtrl {
    constructor(public innerService: InnerService, public outerService: OuterService) {
        console.log("Controller New Instance");
        console.log("innerService == outerService.innerService? ", 
        innerService == outerService.innerService);
    }

  @Get("/")
    async renderCalendars(): Promise<Array<Calendar>> {
        return [{ id: '1', name: "test" }];
    }
}
```
```typescript
@Service()
@Scope("request")
export class OuterService {
    constructor(public innerService: InnerService) {
        console.log("OuterService New Instance");
    }
}
```
```typescript
@Service()
@Scope("request")
export class InnerService {
    constructor(){
        console.log("InnerService New Instance");
    }
}
```

**Actual output when making request to /rest/calendars:**
```
InnerService New Instance
InnerService New Instance
OuterService New Instance
Controller New Instance
innerService == outerService.innerService?  false
```
**Expected output when making request to /rest/calendars:**

```
InnerService New Instance
OuterService New Instance
Controller New Instance
innerService == outerService.innerService?  true
```

Thanks for making this framework!.

**Comment by nhabuiduc** [comment]
For more context, what am i doing is want to have Middleware to inject user information to UserService per request (user information is in token in Request), and other services will consume user information from UserService. It's exactly the same as this issue: https://github.com/Romakita/ts-express-decorators/issues/58

But it's not working, unless i'm doing something wrong.

**Comment by Romakita** [comment]
Hello @nhabuiduc,
Effectively, the injector doens't work as expected. I look on the code how I can fix that ASAP :)

**Comment by hokkaido** [comment]
Just ran into this as well :(

**Comment by Romakita** [comment]
:tada: This issue is included in version 4.31.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/ts-express-decorators)
- [GitHub release](https://github.com/Romakita/ts-express-decorators/releases/tag/v4.31.0)

:package::rocket:

**Comment by hokkaido** [comment]
I've just upgraded to 4.31.13. Is this supposed to work with middlewares?

I have a request-scoped service that is injected both in a global, request-scoped middleware, and also inside a request-scoped controller and I get two different instances of the service.

**Comment by Romakita** [comment]
For me it's work when controller has Scope request and a service injected into the controller has the Scope request also.
Here an example: https://github.com/Romakita/ts-express-decorators/blob/master/test/integration/app/controllers/products/ProductsCtrl.ts

UseBefore isn't covered right now.

**Comment by hokkaido** [comment]
Yes, I think it works with only controllers and services. I've tested that and it seems to run fine now. But middlewares (global ones and with UseBefore) seem to still introduce their own instance, even if they have a request scope.

**Comment by nhabuiduc** [comment]
Any update on this for middleware, as we want to inject log per request , and middleware always resolve dependency as new instance. 

The idea is we just want to inject request information on  any nested service (without passing through arguments), is there any work around on this?

**Comment by nhabuiduc** [comment]
After reading through the code a little bit, the problem because in `EndpointBuilder` class 
```typescript
 private bindRequest(endpoint: EndpointMetadata, debug: boolean) {
    return (request: any, response: any, next: any) => {
      // some code here
      request.createContainer();
      // some code here
    };
  }
```
`request.createContainer()` has been called after any `global middleware ` has been used. 

A simple fix is to create a `global middleware`  just to call `request.createContainer()` before any middleware/controller. For Example:

```typescript
protected async loadMiddlewares(): Promise<any> {
      // some code here
      this.expressApp.use((res,res,next)=>{
          res.createContainer();
          next();
      })
      // some code here   
  }
```

Is it simple like that? @Romakita

**Comment by Romakita** [comment]
Yes it’s possible to load container for a request like that :D

**Comment by nhabuiduc** [comment]
Forgot to mention you also need to remove the code `request.createContainer();` in `EndpointBuilder`, because everytime you call createContainer, it will create a new Map.
```typescript
private bindRequest(endpoint: EndpointMetadata, debug: boolean) {
    return (request: any, response: any, next: any) => {
      // some code here
      //request.createContainer();
      // some code here
    };
  }
```
In the end my hack is something like this :)

```typescript
// use this before any other middlewares
this.expressApp.use((_req, _res, next) => {
      (_req as any).createContainer();      
      next();
    });
```

```typescript
Object.defineProperty((express as any).request, '_container', {
  get: function () {
    return this.__container;
  },
  set: function (c) {
    console.log('create container');
    if (this.__container) {
      return;
    }
    this.__container = c;
  },
});
```
Note: I can not overwrite method `createContainer` as it's readonly property, so I need to overwite the private `_container` field :)

I think it will be great if you can find time to fix it, or I will try to see to fix and create pull request (need to figure out how to build this project first).

Great framework anyway, really love it.

**Comment by Romakita** [comment]
Here the guide to work on Ts.ED http://tsed.io/contributing.html#how-to-work-on-ts-ed ;)
