### ISSUE TITLE
Merge params and Docs decorator

### ISSUE THREAD

**Issue by virus2016** [TypedProject/ts-express-decorators#434]
## Informations

Type | Version
---|---
Bug| 4.x

****

## Description
Unable to use the @Docs with @MergeParams.

```typescript
@MergeParams(true)
@Controller('/user')
@Docs('user')
export class UserController {
```

Swagger generated is empty.

**Comment by Romakita** [comment]
Hello @virus2016 ,

Can you send me your ServerSettings configuration ? And when you remove MergeParams it works ?
Have you tried to change the order of decorators ?

See you,
Romain

**Comment by virus2016** [comment]
Hey Romain,

Will send later. Removed MeegeParams and it worked as it should. Changes the order too.

Many thanks,
Cal

On 27 Aug 2018, at 07:25, Romain Lenzotti <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @virus2016<https://github.com/virus2016> ,

Can you send me your ServerSettings configuration ? And when you remove MergeParams it works ?
Have you tried to change the order of decorators ?

See you,
Romain
