### ISSUE TITLE
Integrate/Example Integration with Google Cloud Functions [Help Request]

### ISSUE THREAD

**Issue by kalani96746** [TypedProject/ts-express-decorators#456]
Help Request

Looking to understand how to integrate Ts.ED express routing with Google Cloud Functions.

Tried to use the AWS Lambda code but had no luck with using that for Google Functions.

Kalani

**Comment by Romakita** [comment]
@kalani96746 Do you need help ?

**Comment by cyraid** [comment]
@Romakita You can probably close this issue too.
