### ISSUE TITLE
Authenticated as class decorator bug

### ISSUE THREAD

**Issue by d0whc3r** [TypedProject/ts-express-decorators#467]
## Informations

Type | Version
---|---
Bug | 4.32.0

****

## Description
`@Authenticated` decorator in class decorator doesn't get options

## Acceptance criterias

```typescript
import { Authenticated, Controller, Get, RouteService } from '@tsed/common';

@Controller('/')
@Authenticated('somestring')
export class RestController {

  constructor(private routeService: RouteService) {
  }

  @Get('/')
  public getRoutes(): any {
    return this.routeService.getAll();
  }
}
```

```typescript
@OverrideMiddleware(AuthenticatedMiddleware)
export class AuthMiddleware implements IMiddleware {
  private JWT_SECRET = Buffer.from(process.env.JWT_SECRET || '', 'base64');

  constructor() {
  }
  use(
    @EndpointInfo() endpoint: EndpointMetadata,
    @Request() request,
    @Response() response,
    @Next() next: Express.NextFunction) {

    // endpoint is undefined
  }
}
```

How could I get options if endpoint is undefined?
`endpoint.store.get(AuthenticatedMiddleware)` doesn't work

**Comment by Romakita** [comment]
Hello,
Is not possible to use authenticated on class right know because authenticed decorator require option given to the decorator for the specific endpoint.
Isn’t a bug but an enhancement ;)

**Comment by d0whc3r** [comment]
Well, `@Authenticated` decorator works well as class decorator, but it can't accept "options"

**Comment by Romakita** [comment]
Hum yes, because, @EndpointInfo() endpoint: EndpointMetadata is the method to retrieve option given to authenticated decorator. 

The hack right now, should be something like that:

```typescript
@Controller('/')
export class RestController {

  @Authenticated('somestring')
  @All('/')
  all() {} // catch all requests

  @Get('/')
  public getRoutes(): any {
    return this.routeService.getAll();
  }
}
```
