### ISSUE TITLE
@Pattern works incorrect if regex has options

### ISSUE THREAD

**Issue by microshine** [TypedProject/ts-express-decorators#471]
## Informations

Type | Version
---|---
Bug | 4.32.0

****

### Schema

```ts
export class Client {

  @JsonProperty()
  @Required()
  @Pattern(/[a-z0-9]{10}/i)
  public client_id!: string;
  
  @JsonProperty()
  public client_secret!: string;

}
```

### Response

```
Bad request on parameter "request.body".
<br />At Client.client_id, value '01020304aa' should match pattern "[a-z0-9]{10}/"
```

## Acceptance criterias

- [ ] Example (log, usecase, etc...)
- [ ] Ts.ED version (bug/question)

**Comment by Romakita** [comment]
Hello @microshine
I found the problem.

Ajv doesn't support RegExp with flag

### pattern

The value of the keyword should be a string. The data to be valid should match the regular expression defined by the keyword value.

Ajv uses new RegExp(value) to create the regular expression that will be used to test data.

**Example**

- schema: `{ "pattern": "[abc]+" }`
- valid: "a", "abcd", "cde", any non-string `(1, [], {}, null, true)`
- invalid: "def", ""

Solution: Remove the `i` flag and the validator will work.
