### ISSUE TITLE
Is it possible to disable initial (and/or all) info logs?

### ISSUE THREAD

**Issue by kpapadatos** [TypedProject/ts-express-decorators#522]
Is it possible to disable initial (and/or all) info logs such as the following?
![image](https://user-images.githubusercontent.com/4640191/54785760-b11aac80-4c2f-11e9-8a27-b7ed10fed43a.png)

**Comment by Romakita** [comment]
Hello 
Here the doc to configure logger: http://tsed.io/configuration.html#shutdown-logger
See you

**Comment by kpapadatos** [comment]
@Romakita There isn't any option that will disable tsed's logger or just the info logs.

**Comment by Romakita** [comment]
You can specify the log level with $log.level.
```typescript
import {$log} from "ts-log-debug"
$log.level = "warn";  // disable log.info and log.debug
```
See you

**Comment by kpapadatos** [comment]
I tried that. I also tried `$log.level = "off";`. Neither have any effect.

**Comment by Romakita** [comment]
@kpapadatos I'd just released a new version which allows change the log level ;) (v5.4.0)

Now you are able to doing that:

```typescript
@ServerSettings({
   logger: {
    level: 'warn'
  }
})
```
See you,
Romain

**Comment by kpapadatos** [comment]
Cool, thanks! But maybe also include `off` since it is supported by `ts-log-debug`?
![image](https://user-images.githubusercontent.com/3382344/54979145-13b2d600-4fab-11e9-89b0-82f3fbc064a2.png)
