### ISSUE TITLE
Swagger not installable

### ISSUE THREAD

**Issue by renemueller90** [TypedProject/ts-express-decorators#523]
Hello,

in the latest version of TSED, Swagger cannot be installed via npm from your repository. Also the Github pages on npm are not callable.

**Comment by Romakita** [comment]
Hello @renemueller90 
For me it works fine. You can try the basic example with latest version of tsed packages here: https://github.com/TypedProject/ts-express-decorators/tree/production/integration/getting-started
See you
Romain
