### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by jchapelle** [TypedProject/ts-express-decorators#528]
In the https://tsed.io/docs/controllers.html#installation, it is said that to version the api, we can use this settings 

`@ServerSettings({
   rootDir,
   mount: {
      '/rest': `${rootDir}/controllers/*.js`
   }
})`

The .js should be changed in .ts

**Comment by Romakita** [comment]
True :)

**Comment by jchapelle** [comment]
There is another typo in the docs
In page https://tsed.io/tutorials/typeorm.html#typeormservice
    Mini**n**um -> should be change in Mini**m**um
