### ISSUE TITLE
[Question] More then one interceptor

### ISSUE THREAD

**Issue by OskarLebuda** [TypedProject/ts-express-decorators#532]
## Information

- **Version:** 5.6
- **Type:** Question

## Description
I just want to know if is it possible to use more than one interceptor on my controller method?

## Example

`interceptors/firstInterceptors.ts`
``` typescript
@Interceptor()
export class MyFirstInterceptor implements IInterceptor {
    constructor(injSrv: InjectorService) {
    }

    async aroundInvoke(ctx: IInterceptorContext<any>, opts?: any) {
        const data = await ctx.proceed();

        if (!data) {
            // return information about the empty data response
        }

        return data;
    }
}

```

`interceptors/secondInterceptor.ts`
``` typescript
@Interceptor()
export class MySecondInterceptorimplements IInterceptor {
    constructor(injSrv: InjectorService) {
    }

    async aroundInvoke(ctx: IInterceptorContext<any>, opts?: any) {
        const data = await ctx.proceed();

        // any another logic interceptor

        return data;
    }
}
```

`myController.ts`
``` typescript
@Get("/")
@Intercept(MyFirstInterceptor)
@Intercept(MySecondInterceptor)
async getAll(): Promise<Team[]> {
    return await this.service.getTeams();
}
```

**Comment by OskarLebuda** [comment]
@Romakita have you any tips for this?

**Comment by Romakita** [comment]
Hello @OskarLebuda 
Sorry for the late reply. Really, I haven't idea if it's works. I'm not the original develop for this feature but if I look on the code, the interceptor override the original method. So two Interceptor should override twice the method 0_o ? 
It should works but I haven't idea if the expected result will correct ;)
You can try and see :)

See you @OskarLebuda 
Romain

**Comment by OskarLebuda** [comment]
I saw that works only the last interceptor. Who is the creator of this module? Do you know?

**Comment by Romakita** [comment]
It's mitevs. But I worked on recently for the new DI version. 
Currently the code responsible to wrap and inject the interceptor is here: https://github.com/TypedProject/ts-express-decorators/blob/master/packages/common/src/interceptors/utils/interceptorInvokeFactory.ts

If you find a way to fix the problem, tell me :)
