### ISSUE TITLE
INJECTION_ERROR when using @Inject

### ISSUE THREAD

**Issue by seyaobey** [TypedProject/ts-express-decorators#534]
## Information

- **Version:** 5.2
- **Type:** Issue/Story

## Description
Pardon me if this is not the right place to ask this enquiry. I am trying to use a custom made `mongoose` model in my controller (`TestController`). I trying to inject into my controller using the `@Inject` decorator. But I consistently get this error:

`INJECTION_ERROR: Service TestController > model not found`

## Example

```
import { Inject, Controller } from '@tsed/common';
import { BaseController } from './my_base_controller';
import { MyModel } from './my_model';

@Controller('/test')
export class TestController {
    constructor(@Inject(MyModel) private model) {
    }
    ....
}

```

Is there something specific I should do before using the `@Inject` decorator, maybe somehow register my model some where? Thank you for your help.
And again apologies if this is not the right venue to ask this issue

**Comment by Romakita** [comment]
Hello @seyaobey 
Can you send me also `MyModel` code please ?

**Comment by seyaobey** [comment]
Hello, thank you for your answer. 

I will upload a sample project that illustrates the problem. 

In the project, I define my [Typegoose](https://github.com/szokodiakos/typegoose) model (`Mymodel`) in the `./models` folder, which is basically the mongoose schema definition. Then I create an instance of this schema definition which I try to inject into my controller. 
Install npm dependencies and run the app, you should get the error.
[sample project.zip](https://github.com/TypedProject/ts-express-decorators/files/3077266/sample.project.zip)

**Comment by Romakita** [comment]
Ok I see. The right way to doing that is to use the `registerFactory` function like this:
```typescript
import {registerFactory} from '@tsed/common'
import { Typegoose, prop } from 'typegoose';

// This class is basically the mongoose shema definition
export class Mymodel extends Typegoose {
    @prop({
        _id: true
    })
    _id: string;

    @prop()
    name: string;

    @prop()
    surname: string;
}

// Here I create an instance of the model (sort of)
// This is the object I am trying to inject
export const MymodelInstance = (new Mymodel()).getModelForClass(Mymodel);
registerFactory(Mymodel, MymodelInstance)
```
You can also create your custom decorator which can be used on your class model:

```typescript
function MongooseModel() {
   return (target: any) => {
      registerFactory(target, (new Mymodel()).getModelForClass(Mymodel))
  }
}
```
Then:

```typescript
@MongooseModel()
export class Mymodel extends Typegoose {
    @prop({
        _id: true
    })
    _id: string;

    @prop()
    name: string;

    @prop()
    surname: string;
}
```

Finally, you'r able to inject your model inside a Controller:

```typescript
@Controller('/test')
export class TestController extends BaseController<Mymodel & typeof Mymodel, Mymodel>{
    constructor(@Inject(MyModel) model: any) {
        super(model);
    }
}
```
Tell me if it works
See you
Romain

**Comment by seyaobey** [comment]
Thank you @Romakita your solution worked!
