### ISSUE TITLE
[Question] returning a base static file (image) if requested is not found

### ISSUE THREAD

**Issue by oscarcalvo** [TypedProject/ts-express-decorators#541]
Hi:

My frontend asks for several images that are served in a normal way. I want, if the image is not found, return a generic image.
For example, if frontend asks for the picture of the profile and this is not found I can send a generic profile picture.

I have implemented a NotFoundMiddleware and added in $afterRoutesInit but it only works if I make a redirect. 
If I use a response.sendFile (even new file exists) it returns a 404 event headersSent is false and I dont like to force a redirect for performance reasons because this is a more or less "common" situation.

Any idea of how can i implement this feature? obviously, i can manage it previously checking if the file exists etc etc but I think is cleaner with  $afterRoutesInit approach.

Thanks.
```

@Middleware()
export class NotFoundMiddleware implements IMiddleware {
  use(request: Request, response: Response) {
    if(request.url.indexOf("profile-image-")!=-1){
      response.sendFile("../../src/images/profilePicture.jpg");
    }
  }
}
```

**Comment by OskarLebuda** [comment]
@oscarcalvo try this:
```typescript
import {Middleware, Req, Res} from "@tsed/common";
import * as Express from "express";
import * as path from "path";
import * as fs from "fs";

@Middleware()
export class NotFoundMiddleware {
    async use(
        @Req() request: Express.Request,
        @Res() response: Express.Response
    ) {

        if (request.url.includes("profile-image-")) {
            const file = fs.readFileSync(path.join(__dirname, "yourFile"));
            response.status(202).send(file).end();
        }

        response.status(404).json({status: 404, message: "Not found"}).end();

    }
}
```

**Comment by oscarcalvo** [comment]
its works @OskarLebuda 
I think I have tried this code but maybe I didnt add the .end() i dont know

Anyway thanks a lot
