### ISSUE TITLE
Mongoose multiple databases - Could you provide a usage example?

### ISSUE THREAD

**Issue by oehm-smith** [TypedProject/ts-express-decorators#545]
## Information

- **Version:** TSED 5.6
- **Type:** Story

## Description
There is a brief reference to multiple mongoose databases at https://tsed.io/tutorials/mongoose.html#multi-databases, however it is not obvious how to achieve using this configuration within the TSED framework.  There are a number of examples of a multi-db implementation in raw Javascript but I'd rather not do this given I'm working within TSED.  There is nothing in the https://github.com/TypedProject/example-ts-express-decorator and I'm hoping you can add one.

Essentially what I am trying to implement is read a document based on some model from one database and write it as same model to second db.

Is there any chance someone could write this?

**Comment by OskarLebuda** [comment]
@oehm-smith I think that the `@tsed/mongoose` doesn't provide this option, but actually you can use the `@tsed/typeorm` and define multi connection.

For example:
```typescript
import {ServerSettings} from "@tsed/common";

@ServerSettings({
    // ...
    typeorm: [
        {
            name: "database1",
            type: "mongodb",
            url: "mongodb://localhost:27017/database1",
            entities: [
                `${__dirname}/entity/*.ts`
            ],
        },
        {
            name: "database2",
            type: "mongodb",
            url: "mongodb://localhost:27017/database2",
            entities: [
                `${__dirname}/entity/*.ts`
            ],
        }
    ],
})
```

then in your service:
```typescript
import {AfterRoutesInit, Inject, Service} from "@tsed/common";
import {Connection} from "typeorm";
import {TypeORMService} from "@tsed/typeorm";

@Service()
export default class MultiConnectionService implements AfterRoutesInit {

    private connection: Connection;
    private connection2: Connection;

    constructor(
        @Inject() private typeORMService: TypeORMService
    ) {
    }

    $afterRoutesInit() {
        this.connection = this.typeORMService.get("database1");
        this.connection2 = this.typeORMService.get("database2");
    }
}
```

**Comment by Romakita** [comment]
In fact, tsed/mongoose allow the possibility to define multi connection but the problem is, we haven't feature to associate a model with the right connection :/

We can add  this feature to the backlog.

**Comment by Romakita** [comment]
Here the official doc about https://mongoosejs.com/docs/models.html
But to doing that, we need to finish the feat/di-factory branch :/

**Comment by oehm-smith** [comment]
Thanks @Romakita & @OskarLebuda , I'm back to this now. 

I look forward to this being handled in TSED.

I guess that this modification requires that I change the `@Model`s to `@Entity`s.

I'll give it a go ...

**Comment by oehm-smith** [comment]
I am seeing some odd behaviour if I mix `@tsed` annotations in `typeorm` `@Entity`s.

Actually it only appears to be `@Description` from `@tsed/swagger`.

If I have `@Description` on any column, then only that column has a value.  

`@Description` seems to be the only one.  I tried with `@Required` from `@tsed/common` and `@Example` also from `@tsed/swagger` but it is only `@Description`.  I didn't test any further.

Now most interesting about this behaviour is that initially after the MongoDB Query, the returned object has values for all fields of the `@Entity`.  But then after an angular `http.post` only the fields with `@Description` exist.  Before being sent from the server, all the data is there.  But after it arrives at the client it is missing (looking at the Network tab or using Postman, it looks like the data is removed BEFORE it is sent across the wire).

I will close this issue out and create a new one for this problem.

**Comment by Romakita** [comment]
@oehm-smith the version 5.35.0 support multiple connection.

**Comment by oehm-smith** [comment]
Cool, great thanks Romain.
