### ISSUE TITLE
Virtual Refs not possible to pass aditional configurations

### ISSUE THREAD

**Issue by ghmendonca** [TypedProject/ts-express-decorators#546]
## Information

- **Version:** 5.13.0
- **Type:** Issue

## Description
I would like to pass aditional configurations to virtual refs, such as "justOne" and "localField", this isn't possible right now but is very easy doable.

## Example
In my case, I have a class which contains a field "account_id", which is the reference to the other Model. Also, I have a field called "account" which is my virtual reference, the thing is, I don't always need to populate that field but I always want the referenced id and in my case, my "account" field should be just an object when populated, not an array, and this is possible by passing an option "justOne: true" to the virtual reference configuration.

Below is my class that contains my virtual reference:

```
export class IAccountData {
    public _id?: ObjectId;

    @Required()
    public type?: String;

    @Required()
    public key?: String;

    @Required()
    @Default({})
    public value?: Object;

    @Ref(IAccount)
    @Required()
    public account_id?: Ref<IAccount>;

    @VirtualRef('Account', '_id')
    @PropertyName('account_id')
    public account?: VirtualRef<IAccount>;
}
```

You can see that I have to set the @PropertyName('account_id') to make it work, since it's the only way I found to override the "localField" property. But I can't set the "justOne" property which is more important.

To fix that, we can just do something like:

(virtualRef.ts)
```
export function VirtualRef(type: string, foreignField: string, justOne: Boolean = false) {
  return PropertyRegistry.decorate((propertyMetadata: PropertyMetadata) => {
    propertyMetadata.store.merge(MONGOOSE_SCHEMA, {
      ref: type,
      localField: propertyMetadata.name,
      foreignField,
      justOne
    });
  });
}
```

Or instead of passing more parameters, accept just one parameter of type Object which will contain all the configurations

**Comment by Romakita** [comment]
Hello @ghmendonca,
I prefer object configuration ;) but to not broke exiting implementation, we have to support twice signature. One with type and second one with object.

The feature is added to the backlog ;)

**Comment by Romakita** [comment]
Expected:
```typescript
export interface IVirtualRefOptions { // Maybe mongoose has an interface defined for VirtualRef
  type: string;
  foreignField: string; 
  justOne:  boolean;
}
export function VirtualRef(type: string | IVirtualRefOptions) {
}
```

**Comment by ghmendonca** [comment]
I agree, both signatures can work. I will search if mongoose has an interface and I will push a PR.

Thanks!
