### ISSUE TITLE
@Description in typeorm @Entity's causes all other fields to lose their values 

### ISSUE THREAD

**Issue by oehm-smith** [TypedProject/ts-express-decorators#551]
From work done in #545 

## Information

- **Version:** 5.6.0 and 5.15.0 (didn't test any other versions - 5.15.0 is the latest at this time)
- **Type:** Issue

## Description
I am seeing some odd behaviour if I mix `@tsed` annotations in typeorm `@Entitys`.

Actually it only appears to be `@Description from @tsed/swagger`.

If I have `@Description` on any column, then only that column has a value in the `@Entity`.

`@Description` seems to be the only one. I tried with `@Required from @tsed/common` and `@Example also from @tsed/swagger` but it is only `@Description`. I didn't test any further.

Now most interesting about this behaviour is that initially after the MongoDB Query, the returned object has values for all fields of the `@Entity`. But then after an angular http.post on the client side, only the fields with @Description exist. I also tried with `Postman` sith same result.  Before being sent from the server, all the data is there. But after it arrives at the client it is missing (looking at the Network tab or using Postman, it looks like the data is removed BEFORE it is sent across the wire).

## Example

```typescript
import {Column, Entity, Index, ObjectIdColumn, PrimaryColumn} from 'typeorm';
import {Description} from '@tsed/swagger';

@Entity('testtranslations')
export class TranslationApiModel {
    @Description('Database assigned id')
    @ObjectIdColumn()
    _id?: string;

    @Description('English text')
    @Example('blah')
    @PrimaryColumn()
    @Index()
    source: string;

    @Description('Unique key for the translation based on the source, translation model category + inc ver #')
    @PrimaryColumn()
    @Index()
    key: string;
```

## Acceptance criteria

- `@Description` can be used on 1,2 or n columns and all fields of the `@Entity` have the values sent from the server.

**Comment by Romakita** [comment]
Hello @oehm-smith 
Have you tried to change decorator order ? I'm not sure how TypeORM model works with serialization / deserialization model. I'll try to reproduce your problem ;)

See you
Romain

**Comment by Romakita** [comment]
@oehm-smith For me all works correctly. Description is correctly displayed and object is serialized correctly (with one exception described after).

Here the User model:

```typescript
import {Minimum, Required} from "@tsed/common";
import {Example, Description} from "@tsed/swagger";
import {Column, Entity, PrimaryGeneratedColumn} from "typeorm";

@Entity()
export class User {
  @Description('Database assigned id')
  @PrimaryGeneratedColumn()
  id: number;

  @Description('User firstname')
  @Column()
  @Required()
  firstName: string;

  @Description('User lastname')
  @Column()
  @Required()
  lastName: string;

  @Description('User Age')
  @Column()
  @Minimum(18)
  @Example(18)
  age: number;

  additional: string; // won't be serialized/deserialized by Ts.ED because @PropertyType or other Ts.ED decorator are missing
}
```
And the swagger description generated by Ts.ED:
<img width="395" alt="Capture d’écran 2019-05-21 à 07 59 41" src="https://user-images.githubusercontent.com/1763311/58071940-720cc700-7b9e-11e9-8b89-6753df47b219.png">

The main point is, Ts.ED only serialize fields decorated with `@Property` decorator (or decorator which inherit behavior from `@Property` like `@Description`). Using Typeorm decorators haven't effect on the Ts.ED serializer.

To fix the User model we must add the `@Property` decorator (or one of theses decorators http://tsed.io/docs/model.html#jsonschema)
```typescript
import {Minimum, Required} from "@tsed/common";
import {Example, Description} from "@tsed/swagger";
import {Column, Entity, PrimaryGeneratedColumn} from "typeorm";

@Entity()
export class User {
  @Description('Database assigned id')
  @PrimaryGeneratedColumn()
  id: number;

  @Description('User firstname')
  @Column()
  @Required()
  firstName: string;

  @Description('User lastname')
  @Column()
  @Required()
  lastName: string;

  @Description('User Age')
  @Column()
  @Minimum(18)
  @Example(18)
  age: number;

  @Property()
  additional: string; // won't be serialized/deserialized by Ts.ED because @PropertyType or other Ts.ED decorator are missing
}
```

Tell if I missunterstood something ;)
See you
Romain

**Comment by cyraid** [comment]
I'm looking through the issues, and it seems like we might need to have a bot do a cleanup if certain labels are on the issues (like question).. Something that says "Due to no response and inactivity, this issue is now closed. If the problem still persists, please re-create a new issue. Thank you for your understanding!"
