### ISSUE TITLE
[Bug] Mongoose Model .save() ignores changes

### ISSUE THREAD

**Issue by tobiasmuecksch** [TypedProject/ts-express-decorators#553]
## Information

- **Version:** 5.12.1
- **Type:** Bug

## Description
When I create a new document, set a few properties and save it, the properties are ignored.

## Example
```
// Create a new user model instance
const user = new this.User({Username: 'test user'});

// Set the create date
user.CreateDate = new Date();

// Eventually save the user
user.save();

```
When I have a look at the database, only the username is defined (the CreateDate property is defined in the model definition - of course!). This contradicts the [mongoose documentation](https://mongoosejs.com/docs/documents.html#updating).

**Comment by tobiasmuecksch** [comment]
The same behavior is occurring when I retrieve a model from the database, change a property and then save it.

**Comment by Romakita** [comment]
Hello @tobiasmuecksch 
Can you send me your model definition please. 

See you
Romain

**Comment by tobiasmuecksch** [comment]
This is my model. Please note, that the @Default decorator doesn't work(?)

```
import { Default, IgnoreProperty, MinLength, Required } from '@tsed/common';
import { Indexed, Model, MongooseIndex } from '@tsed/mongoose';

import { hashPassword, validatePassword } from '../utils/password.util';

export interface IUser {
	_id?: string;
	Username: string;
	Password: string;
	SessionToken: string | null;
	CreateDate: Date;
	LastLoginDate: Date | null;
	LastSessionValidationDate: Date | null;
}

@Model({
	name: 'users'
})
export class UserModel implements IUser {
	@IgnoreProperty() // exclude _id from mongoose in the generated schema
	_id: string;

	@Indexed({unique: true})
	@Required()
	@MinLength(1)
	Username: string;

	@Required()
	@MinLength(1)
	Password: string; // this is the HASHED password

	SessionToken: string | null;

	CreateDate: Date;

	@Default(null)
	LastLoginDate: Date | null;

	@Default(null)
	LastSessionValidationDate: Date | null;

	@IgnoreProperty()
	setPassword(newPassword: string): void {
		if (!newPassword) {
			throw new Error('Password invalid');
		}

		// Hash the password first
		const hashedPassword = hashPassword(newPassword);

		// Set the hashed password
		this.Password = hashedPassword;
	}

	@IgnoreProperty()
	validatePassword(password: string): boolean {
		return validatePassword(this.Password, password);
	}

}
```

**Comment by Romakita** [comment]
I added example here for default value with Class.
https://github.com/TypedProject/ts-express-decorators/blob/master/integration/mongoose/src/models/events/CalendarEvent.ts

I'm not sure if the `@Default` decorator works correctly. I'll re test ASAP.

**Comment by Romakita** [comment]
Note: All properties must be decorated at least by `@Property`.

**Comment by tobiasmuecksch** [comment]
@Romakita Thanks. That explains a lot. I'd suggest to add this info and a link to the example to the documentation.

**Comment by Romakita** [comment]
@tobiasmuecksch v5.18.0 fix some issues about mongoose. I updated the documentation http://tsed.io/tutorials/mongoose.html#feature
See you

**Comment by tobiasmuecksch** [comment]
@Romakita The section "declaring properties" is still very confusing as it declares properties without the `@Property` decorator.

http://tsed.io/tutorials/mongoose.html#declaring-a-mongoose-object-schema-or-model

**Comment by Romakita** [comment]
Yes the documentation isn't clear. In fact when you use a decorator to describe property for your model, automatically the Property decorator will be used for you.
So `@Required`, `@Minimum`, `@Maximum`, etc.. call `@Property`.
But you have to use at least `@Property` decorator if your property isn't decorated by one of decorators listed on this page http://tsed.io/docs/model.html#decorators

note: I need help to improve or rewrite doc ;) contributors are welcome also for that :)

See you

**Comment by Romakita** [comment]
I added more details on Model page http://tsed.io/docs/model.html#example
and mongoose http://tsed.io/tutorials/mongoose.html#feature
Tell meif you have another suggestion about documentation ;)

**Comment by tobiasmuecksch** [comment]
@Romakita that's much better. Thank you very much.
