### ISSUE TITLE
[Question] Mongoose: How to define default values in models

### ISSUE THREAD

**Issue by tobiasmuecksch** [TypedProject/ts-express-decorators#554]
## Information

- **Version:**  5.12.1
- **Type:** Question

## Description
Mongoose offers the option to define default values for fields. For example, every time a new user is created, I want the current date to be assigned to the field "CreateDate". I cannot find any information on default values in the tsed documentation.

So my question is; how can I define default values?

**Comment by Romakita** [comment]
Hello @tobiasmuecksch 
You have two way:
By using `@Default` decorator:
```typescript
import  {Default} from "@tsed/common"
@Schema()
class MyModel {
   @Default(Date.now)
   date: Date
}
```

By settings default value to your class property:

```typescript
@Schema()
class MyModel {
   @Property()
   date: Date = new Date()
}
```

Note: All decorators use to define a Ts.ED model can be to describe a mongoose model. See http://tsed.io/docs/model.html#jsonschema

**Comment by tobiasmuecksch** [comment]
Thanks, I'd suggest to add this to the "Declaring Properties" example [here](http://tsed.io/tutorials/mongoose.html#declaring-a-mongoose-object-schema-or-model)
