### ISSUE TITLE
[Question] Get authenticated user from authentication middleware

### ISSUE THREAD

**Issue by tobiasmuecksch** [TypedProject/ts-express-decorators#556]
## Information

- **Version:** 5.12.1
- **Type:** Question

## Description
I've created a custom authentication middleware like it is [described in the documentation](http://tsed.io/docs/authentication.html#usage). To every request a session token is attached in the header. The middleware searches the database for the user record which has the session token. If there is no user with that token the middleware throws an error.

**How can I provide the authenticated user, so I can access it in the controller?**

**Comment by tobiasmuecksch** [comment]
I found out that the (undocumented) [EndpointInfo.store](http://tsed.io/docs/middlewares.html#global-middleware) does what I need.

**Comment by Romakita** [comment]
EndpointInfo.store isn't here to store your user info. You should store authenticated user directly on the request object. Passport.js for example attach the user on `request`. Request is the context.

EndpointInfo.store is not documented for this reason. Isn't a kind of RequestContext. It's an Endpoint information (which endpoint - class and method name - is called by the request).
Please don't use store directly ;). Endpoint.store could be removed in future.

See you

**Comment by tobiasmuecksch** [comment]
Okay, but how can I attach something to a request? I already tried that, but the problem is, that the type of Express.Request doesn't allow that. I need a special place for that, that the client cannot set on their end.

**Comment by Romakita** [comment]
You have to extend Express.Request with .d.ts 

https://stackoverflow.com/questions/37377731/extend-express-request-object-using-typescript

**Comment by tobiasmuecksch** [comment]
Allright. Thank you for your help!
