### ISSUE TITLE
[Feat] Add possibility to turn off converters

### ISSUE THREAD

**Issue by exsoflowe** [TypedProject/ts-express-decorators#557]
## Information

- **Version:** 4.32.0
- **Type:** Issue/Story

## Description
I use @tsed/common v. 4.32.0 and can't update it. But I think my issue/proposition is actual for last version.<br/>
Is there possibility to turn off converters for model?
For example I can send to server
1. { "Id": "aaa" } // not correct because not number
2. { "Id": "3" } // not correct because number as string
3. { "Id": 3 } // correct because real number

Server waits for only real number (3, not '3'). I don't need to convert field, just validate type.

If I send '3', validation is success. I don't it. I would like to get validation error.
If I send 'aaa', of course I get error "Cast error. Expression value is not a number.".

If there is not possibility to turn off it, do I need to override PrimitiveConverter with OverrideProvider? And create custom converter?
Thanks.

## Example

```typescript
import {
  ExclusiveMaximum,
  ExclusiveMinimum,
  Required,
  Schema,
} from '@tsed/common';

export class MyApiModel {

  @Required()
  @ExclusiveMinimum(1)
  @ExclusiveMaximum(5)
  @Schema({ type: 'number' }) // to check for real number
  public Id: number; // only real number, not '3' or 'aaa'.

}

```

**Comment by Romakita** [comment]
Hello @exsoflowe 

Disable convertersService is probably possible if you override the ConvertersService but you'll loose the advantage to use a class and model. Endpoint method will receive a plain javascript object instead of the real class. It could be a problem if you model has some methods or getter/setter.

```typescript
@Controller('/')
export class MyCtrl {
  @Get('/') 
  get(@BodyParams() myApiModel: MyApiModel){
      console.log('myApiModel', myApiModel) // plain object if the converters is disabled. But Typescript annotation use MyApiModel. It could be confusing?
   } 
}
```

**Comment by exsoflowe** [comment]
Thanks for quick reply.

I used your/my custom PrimitiveConverter.

About ConverterRegistry and PrimitiveConverter. I can't import them in Typescript.
In current 4.32.0 version I get something like
Module '"@tsed/common"' has no exported member 'PrimitiveConverter'

Thanks.

**Comment by Romakita** [comment]
Ok I’ll publish tomorrow a quick fix on v4 to export theses classes ;)
