### ISSUE TITLE
[Question] How to use UseAfter middleware correctly

### ISSUE THREAD

**Issue by exsoflowe** [TypedProject/ts-express-decorators#558]
## Information

- **Version:** 4.32.0
- **Type:** Issue/Story

## Description
I use @tsed/common v. 4.32.0 and can't update it. I tried to use first v. 5 releases. The same.
It was question for [stackoverflow](https://stackoverflow.com/questions/55707891/how-to-use-useafter-middleware-correctly-in-tsed-typescript-express-decorators). But I didn't wait answers.

I try to use UseAfter middleware.
Use, UseBefore middlewares work. But UseAfter doesn't work.

I found UseAfter description here [issues/56](https://github.com/TypedProject/ts-express-decorators/issues/56)

> UseAfter middlewares added to the controller. They are called after the endpoints of the controller, if nothing response is sent.

and here [pull/105](https://github.com/TypedProject/ts-express-decorators/pull/105)

> will called after endpoints if nothing response has been sent

So I tried throw new Error('Error description') inside controller method. No result.

I copied instructions [how-to-format-the-response-with-middleware](https://github.com/TypedProject/ts-express-decorators/wiki/Middlewares#how-to-format-the-response-with-middleware). No result. Maybe is it correct behavior?

My working code with UseBefore:

## Example

``` typescript
// initial app.ts
import { ServerLoader, ServerSettings } from '@tsed/common';

@ServerSettings({
  httpPort: '3000',
  httpsPort: false,
  rootDir: path.resolve(__dirname),
  mount: {
    '/rest': `${path.resolve(__dirname)}/controllers/**/*.ts`,
  },
  componentsScan: [
    //...
  ],
})
export default class Server extends ServerLoader {
  public async $onMountingMiddlewares() {
    this.use(bodyParser.json({ limit: '5mb' }))
      .use(bodyParser.urlencoded({ extended: false }))
      .use(
        session({
          proxy: true,
          // secret: ,
          resave: true,
          saveUninitialized: true,
          cookie: {
            httpOnly: false,
            secure: false,
            // maxAge: ...,
          },
          name: 'id...',
        }),
      )
  }
}

new Server().start();
```

``` typescript
// Method with parameter which returns decorated middleware
export default function myMiddlewareWrapper(isBool: boolean = false) {

  @Middleware()
  class MyMiddlewareWrapper implements IMiddleware {
    public async use(@Next() next: Express.NextFunction) {
      console.log(`It works for Use, UseBefore, but not for UseAfter`);
      return next();
    }
  }

  return MyMiddlewareWrapper;
}
```

``` typescript
// My decorator
import myMiddlewareWrapper from '@middlewares/MyMiddlewareWrapper';
import { UseAfter, UseBefore } from '@tsed/common';

export function MyDecorator(isBool: boolean = false) {
  return UseBefore(myMiddlewareWrapper(isBool)); // It works
  // return UseAfter(myMiddlewareWrapper(isBool)); // It doesn't work
}
```

``` typescript
// My controller
@Controller('/data')
export class MyController {

  @Get('/get')
  @MyDecorator()
  public async getData(
    @Res() response: Express.Response,
    @Next() next: Express.NextFunction,
  ) {
    response.send([]); // If I comment send to don't send response, useAfter won't work
  }
}
```

**Comment by Romakita** [comment]
Hello @exsoflowe 
It's because you send response in you endpoint.

The right code is that:

```typescript
// My controller
@Controller('/data')
export class MyController {

  @Get('/get')
  @MyDecorator()
  public async getData() {
    return []
  }
}
```
You mustn't use Res and Next. It have a specific behavior and generally we use Req, Res and Next decorators for Middlewares ;)

The code of your endpoint method should be really simple. It should handle input data like body, params and query with is respective decorator `@BodyParams`, `@PathsParams` and `@QueryParams`  and return a value (Promise, Array, Object or Primitive value).
Try my example and tell me if the useAfter works now ^^

See you

**Comment by Romakita** [comment]
@exsoflowe sorry I'm not on stackoverflow (I'll create my account).
The github issues and gitter are my priviligied entries to discuss about bug or question ^^

**Comment by exsoflowe** [comment]
Now it works.

In controller I return empty array `return [];`

In MyDecorator I use MyMiddleware which returns empty object
```
@Middleware()
export default class MyMiddleware implements IMiddleware {
  public async use(@Res() response: Express.Response) {
    response.send({});
  }
}
```

Thanks.
