### ISSUE TITLE
[Question] How to deploy to server

### ISSUE THREAD

**Issue by tobiasmuecksch** [TypedProject/ts-express-decorators#560]
## Information

- **Version:** 5.12.1
- **Type:** Question

## Description
Nowhere in the docs it's described how to deploy a project to a server. I've assumed that I should run `npm run build` and then put the contents of the `dist` folder on the server.

But when I run `node index.js` or `node server.js` an error occurs.

![Bildschirmfoto 2019-05-28 um 08 42 08](https://user-images.githubusercontent.com/1294854/58456435-81eb5480-8124-11e9-94ad-7d00657b6073.png)

What is the correct way to deploy a project to a server?

[INFO] `npm run start` works perfectly

**Comment by tobiasmuecksch** [comment]
I found out that the error changes, if I build the project on the destination machine:

![Bildschirmfoto 2019-05-28 um 08 50 16](https://user-images.githubusercontent.com/1294854/58456908-aeec3700-8125-11e9-8b94-3158901fc9e7.png)

**Comment by Romakita** [comment]
Hello @tobiasmuecksch 
I reproduce the bug. So I'll fix that ASAP (high priority ;))
See you
Romain

**Comment by Romakita** [comment]
Hello @tobiasmuecksch 
I found the issue. 
Tsconfig if incorrectly configured in the getting-started example.

Here the right tsconfig:
```jsonc
{
  "compilerOptions": {
    "baseUrl": ".", // add baseUrl
    "outDir": "./dist",
    "target": "es2016",
    "lib": [
      "es2016",
      "dom"
    ],
    "typeRoots": [
      "./node_modules/@types"
    ],
    "module": "commonjs",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "sourceMap": true,
    "declaration": false,
    "allowSyntheticDefaultImports": true
  },
  "include": [
    "./src/**/*.ts"
  ],
  "exclude": [
    "node_modules",
    "./public",
    "dist",
    "test" // exclude test
  ]
}
```

And in your package.json add this line:

```
 "start:prod": "npm run build && cross-env NODE_ENV=production node dist/index.js"
```

Tell me if it works :)

See you

**Comment by chiqui3d** [comment]
In my case `start:dev` doesn't work either, it doesn't reload the server when I make a change

**Comment by chiqui3d** [comment]
I also have this error when running start:prod

```
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
```
config:

```
.use(session({
        secret: "mysecretkey",
        resave: true,
        saveUninitialized: true,
        maxAge: 36000,
        cookie: {
          path: "/",
          httpOnly: true,
          secure: false,
          maxAge: null
        }
      }))
```

**Comment by Romakita** [comment]
@chiqui3d Hot reload works as expected in getting-started example. But if you have a problem, see the right configuration with nodemon project :)

**Comment by tobiasmuecksch** [comment]
@Romakita With the corrected tsconfig it works. Thank you for the great support.
