### ISSUE TITLE
Warning: connect.session() MemoryStore is not designed for a production environment

### ISSUE THREAD

**Issue by chiqui3d** [TypedProject/ts-express-decorators#564]
## Information

- **Version:** 5.18
- **Type:** Issue

## Description
Applying the documentation session system throws me the following error:

```
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
```

## Example

```
  ........
   const expressSession = require('express-session');
    this.set('trust proxy', 1) ;
    this.use(expressSession({
      secret: 'keyboard cat',
      resave: false,
      saveUninitialized: true,
      cookie: {
        secure: false,  // `true` require HTTPS. Set `false` if you reach the server with HTTP
        path: "/",
        httpOnly: true,
        maxAge: null
      }
    }));

```

## Addicional Issue

Applying the example InitSessionMiddleware also gives me another error:

`Property 'session' does not exist on type 'Request'`

**Comment by Romakita** [comment]
Hi @chiqui3d 
A working example is now available here https://github.com/TypedProject/tsed-example-session ;)

See you
Romain

**Comment by chiqui3d** [comment]
Thanks so much
