### ISSUE TITLE
[Question] custom middleware decorator after auth

### ISSUE THREAD

**Issue by OskarLebuda** [TypedProject/ts-express-decorators#565]
## Information

- **Version:** 5.6
- **Type:** Question

## Description
I want to use my custom middleware with a decorator in my controller. So i created a decorator, middleware etc. But! Is there any way to use the Auth Middleware before I invoke my custom one? In my case the custom middleware runs before the auth one. I use the method `UseBefore` but I deduced that this run methods before any kind of middleware. So the question is - how to deal with it ;( 

## Example

```typescript
@Authenticated()
@Controller("/users")
export class UsersCtrl {
    @Post("/")
    @Returns(User)
    @EntityParam(Forwarder, "alias", "forwarder", API_ERRORS.FORWARDERS.NOT_FOUND)
    @Security("bearer")
    async create(...): Promise<User> {
        // ...
    }
```

```typescript
export function EntityParam<T>(entity: T, entityParam: string = "id", requestParam: string = "id", errorMessage?: IApiError) {
    return Store.decorate((store) => {
        store.set(EntityParamMiddleware, {
            entity, entityParam, requestParam, errorMessage
        });

        return UseBefore(EntityParamMiddleware);
    });
}


```

Or maybe there is any way to prepare the BodyParam to the TypeORM entity by custom field? 
For example:
I have the entity with `ManyToOne` relation. Like:
``` typescript
@Entity()
export class User {
    @PrimaryGeneratedColumn("uuid", {name: "id"})
    @JsonProperty()
    id?: string;

    @Column({length: 255, nullable: false})
    @Required()
    @MinLength(5)
    @JsonProperty()
    name: string;

    @ManyToOne(type => Forwarder)
    @JsonProperty()
    forwarder: Forwarder;
}
```

and the `Forwarder`:
```typescript
Entity()
export class Forwarder {
    @PrimaryGeneratedColumn("uuid", {name: "id"})
    @JsonProperty()
    id?: string;

    @Column({length: 255, nullable: false, unique: true})
    @Required()
    @JsonProperty()
    name: string;

    @Column({length: 255, nullable: false, unique: true})
    @Required()
    @JsonProperty()
    alias: string;
}
```

and I want to create the POST request to the `User` entity with only the alias from the forwarder like:
```json
{
  "name": "User1",
  "forwarder": "forwarder1"
}
```

I can't find any example for this, so I decided to create a custom middleware to find Entity and inject it to the request body
```typescript
@Middleware()
export class EntityParamMiddleware implements IMiddleware {
    async use(@Request() request: IAppRequest, @EndpointInfo() endpoint: EndpointMetadata) {

        const options = endpoint.get(EntityParamMiddleware) || false;

        if (options) {

            const connection = getConnection();
            const repository = connection.manager.getRepository(options.entity);
            const entity = await repository.findOne({[options.entityParam]: request.body[options.requestParam]});

            if (!entity) {
                throw new ApiError(options.errorMessage ? options.errorMessage : API_ERRORS.NOT_FOUND_ERROR);
            }

            request.body[options.requestParam] = entity;
        }
    }
}
```

BUT my custom middleware is running before the `Authenticated` - but this effect is not desirable

**Comment by Romakita** [comment]
@OskarLebuda Isn't  possible. If you add `@Authenticated()` on controller level, this decorator will be called before any middlewares added on endpoint method.

Two solutions:
- Move EntityParam to controller level before Authenticated
- Or Move Authenticated on endpoint level after EntityParam (don't forget to add Authenticated on other method).

See you

**Comment by OskarLebuda** [comment]
@Romakita Ok! I edit the description - could you read it once again? :)

**Comment by Romakita** [comment]
Maybe this solution should works:

```typescript
@UseBefore(EntityParamMiddleware) // can be replace by custom decorator also
@Authenticated()
@Controller("/users")
export class UsersCtrl {
    @Post("/")
    @Returns(User)
    @EntityParamOptions(Forwarder, "alias", "forwarder", API_ERRORS.FORWARDERS.NOT_FOUND)
    @Security("bearer")
    async create(...): Promise<User> {
        // ...
    }
```
And just change EntityParam decorator implementation by:

```typescript
export function EntityParamOptions<T>(entity: T, entityParam: string = "id", requestParam: string = "id", errorMessage?: IApiError) {
    return StoreSet(EntityParamMiddleware, {
            entity, entityParam, requestParam, errorMessage
        }) // with tsed v5.17+
    // or
    return Store.decorate((store) => {
        store.set(EntityParamMiddleware, {
            entity, entityParam, requestParam, errorMessage
        });
    });
}
```

I think this example will solve your problem ;)
See you

**Comment by OskarLebuda** [comment]
Ok, so now i have a problem with the `EndpointInfo` because it's `undefined`. I base on the metadata from the endpoint but when i move the middleware to top of the code - the middleware can't see the enpoint metadata. You use the store in your example, but could you show me how to use it in my middleware?

**Comment by Romakita** [comment]
Hum you've right, decorator added on Controller level doesn't have endpoint information, because the decorators are called before endpoint execution. Hum I have to create specific decorator to use before each endpoint the middleware `@UseBeforeEach`

```
@UseBeforeEach(EntityParamMiddleware) // Replace UseBefore by Use decorator
@Authenticated()
@Controller("/users")
export class UsersCtrl {
    @Post("/")
    @Returns(User)
    @EntityParamOptions(Forwarder, "alias", "forwarder", API_ERRORS.FORWARDERS.NOT_FOUND)
    @Security("bearer")
    async create(...): Promise<User> {
        // ...
    }
```

**Comment by Romakita** [comment]
@OskarLebuda The latest release introduce `@UseBeforeEach` decorator ;). It should solve your problem.

**Comment by OskarLebuda** [comment]
Thanks ! :)

**Comment by OskarLebuda** [comment]
Works fine! Thank you very much
