### ISSUE TITLE
Use mongoose model functions inside the model class itself

### ISSUE THREAD

**Issue by ghmendonca** [TypedProject/ts-express-decorators#566]
## Information

- **Version:** 5.x
- **Type:** Issue

## Description
I have a model class and it inherits a generic class, which has a function and inside this function I want to get data from the database.

## Example
In this example I have one model called "Character" which inherits from Entity and inside my Entity class I want to have a function that can call my mongoose model functions. I tried a lot of things so far, tried to inject the model by decorating my class with "Injectable" and "Service" but didn't work.

```
@Model({
    collection: 'characters',
    schemaOptions: {
        timestamps: {
            createdAt: 'createdOn',
            updatedAt: 'modifiedOn'
        }
    }
})
export class Character extends Entity<Character> {
    @ObjectID()
    _id: string

    @Ref(Account)
    account: Ref<Account>

    @Ref(Dominion)
    physicalDominion: Dominion

    @Ref(Dominion)
    dominion: Dominion

    @Ref(Coven)
    coven: Coven

    @Property()
    @Required()
    name: string

    @Property()
    @Default(false)
    bot: boolean = false
}
```
```
@Service()
export class Entity<T> {
    constructor(
        @Inject()
        private model: MongooseModel<T>
    ) {}

    @Property()
    baseEnergy: number

    @Property()
    energy: number

    @Property()
    @Enum(States)
    @Default(States.NORMAL)
    state: States = States.NORMAL

    @Property()
    @Default(0)
    power: number = 0

    @Property()
    @Default(0)
    resilience: number = 0

    async attack() {
        console.log(this.model.find) // undefined
    }
}
```

## Possible solution
I think that the Model decorator should give my class the mongoose functions so I can call them inside any functions in my class.

**Comment by Romakita** [comment]
Hi @ghmendonca 
Is not possible, Model are created  by Mongoose, not by Ts.ED. 
Adding `@Service` over Entity<T> is an error and has no effect.

Mongoose use the class to create a new instance of your class where your method are available.

I think the solution is to use PreHook, PostHook or Plugin http://tsed.io/tutorials/mongoose.html#register-hook

I haven't solution for you, this part is totally handled by mongoose.

See you,
Romain

**Comment by ghmendonca** [comment]
Ok, so I figure a way to do this without using hooks or anything like that. As my model is a mongoose model (because of the decorator), and in my code I only have its instances and not the mongoose model itself, to get the model from the instance, I have to do this:

```
async attack() {
        const model = <MongooseModel<T>> this.constructor
        const result = await model.findOne()
        console.log(result)
}
```
