### ISSUE TITLE
[FEAT] Mongoose dynamic reference by using refPath

### ISSUE THREAD

**Issue by ghmendonca** [TypedProject/ts-express-decorators#567]
## Information
I would like to use dynamic reference supported by mongoose through the 'pathRef' field when defining the model.

- **Version:** 5.x
- **Type:** Story

## Description
Mongoose supports dynamic reference by holding a field that contains the model name of the referenced model then when you populate, it will automatically get from the right collection. This is explained here: https://mongoosejs.com/docs/populate.html#dynamic-ref

Looking the source code of the latest version (5.18.2) I can confirm that this is not supported by the Ref decorator and also there is no RefPath decorator, so I suppose that this isn't possible to do right now.

I can submit a pull request to add this feature, but I would like to discuss the better approach, if this would be implemented in the Ref decorator or create a new decorator.

In the example below I put an any at the field that would be populated, but I don't know if this is right or if there's a way to make it know the exact model that will come to populate right.

## Example

```
class DynamicRef {
    // First argument: local field that contains the model name
    // Second argument: enum of possible model names
    @DynamicRef('type', ['Teacher', 'Studant'])
    person: any

    @Required()
    type: string
}

```

**Comment by Romakita** [comment]
Hello @ghmendonca.
I think create new DynamicRef decorator is the best approach :)
You're PR are welcome ;)
See you
Romain

**Comment by ghmendonca** [comment]
Great! I will start implementing this, will submit the PR in the next couple days. Thanks!
