### ISSUE TITLE
Howto pass array in path parameter

### ISSUE THREAD

**Issue by antonovicha** [TypedProject/ts-express-decorators#568]
## Information

- **Version:** 4.34.4
- **Type:** Question

## Description
How to pass array as path parameter?

## Example
Controller:
```typescript
  @Get("/:criteria")
  public async get(
    @PathParams("criteria", String) @Required() criteria: string[]) {
    // criteria is string here "[abc,asd]" or "abc,asd"
  }
```
I tried following URL's:
/api/controller/[abc,asd]
/api/controller/abc,asd

## Acceptance criteria

- [ ] criteria is string[] = ["abc", "asd"]

**Comment by Romakita** [comment]
Hello @antonovicha 

Is not possible. But you can parse the string or add create your own filter:

```typescript
import {ParamTypes} from "../interfaces/ParamTypes";
import {PathParamsFilter} from "../filters/PathParamsArrayFilter";
import {ParamRegistry, ParamTypes} from "@tsed/common";

export function PathParamsArray(expression?: string | any, useType?: any): Function {
  return ParamRegistry.decorate(PathParamsArrayFilter, {
    expression,
    useType,
    paramType: ParamTypes.PATH
  });
}
```

```typescript
import {ParseService, IFilter, Filter} from "@tsed/common";

@Filter()
export class PathParamsArrayFilter implements IFilter {
  constructor(private parseService: ParseService) {}

  transform(expression: string, request: any, response: any) {
      const value = this.parseService.eval(expression, request["params"])
      // parse value

      return value
  }
}
```
And finally:
```typescript
@Get("/:criteria")
  public async get(
    @PathParamsArray("criteria", String) @Required() criteria: string[]) {
    // criteria is string here "[abc,asd]" or "abc,asd"
  }
```

**Comment by antonovicha** [comment]
@Romakita Thank you for fast response. Will use query parameters for time being.

I have follow up question regarding then. I can not use string delimited values in query parameter like:

> http://localhost:3000/classification/?criteria=P1,P2

It is again parsed as string instead of string[].
However following one is parsed as array (I guess by express itself):
> http://localhost:3000/classification/?criteria=P1&criteria=P2

**Comment by Romakita** [comment]
Express doesn't parse criteria field when you have coma inside. So if you want change that, you have to develop your own filter also :)

**Comment by antonovicha** [comment]
Got it. Thanks for answers.

Would it make sense to extend tsed implementation of `@ParamsArray` and `@QueryArray` to accept those scenarios? I expected such behavior in first place. If so, I may try to do it as soon as I have little bit more time.

**Comment by Romakita** [comment]
Hum... what do you by extending tsed implementation ?
In your case, you have two choices. Override PathParamsFilter and QueryParamsFilter or define custom PathParamsArray and his filter.

See you :)

**Comment by antonovicha** [comment]
After reading about converters and *Params decorators I was under impression that tsed support parsing of array parameters of JS basic types out of the box, see http://v4.tsed.io/docs/converters.html#type-converters . And according to documentation it is possible to define custom converter and use it transparently with [Path|Query]Params decorator, see here http://v4.tsed.io/api/common/filters/decorators/QueryParams.html#description.

That is why I tried to use string[] path param with just PathParams decorator.

**Comment by Romakita** [comment]
Yes. It's supported for QueryParams when you send a request like that:
http://localhost:3000/classification/?criteria=P1&criteria=P2

This feature is supported because Express parse the query and store it in `request.query.criteria` as an array.

For pathParams, express does nothing and it store information as string on `request.path`. So If you want a specific behavior, you have to implement custom filter :)

See you,
Romain Lenzotti

**Comment by antonovicha** [comment]
My question is answered therefore I believe issues is closed. Thank you for your answers.

If you believe that adjusting tsed implementation is not right course of action, may be making a note in documentation of *Params decorators will be an option?

**Comment by Romakita** [comment]
Hum PathParamsArray decorator can be implemented. A PR are welcome :)

**Comment by antonovicha** [comment]
In such case there will be an inconsistency between deserialization [using custom serializer ](http://v4.tsed.io/api/common/filters/decorators/QueryParams.html#description) and *Params decorator:
```typescript
get(@QueryParams('users', User) users: User[]) {
```

vs
```typescript
get(@QueryArrayParams('users', String) users: string[]) {
```

Also isn't it the fact that `user` parameter is an array is available in metadata?
