### ISSUE TITLE
`PreHook`, `PostHook`, `MongoosePlugin`, and `MongooseIndex` not working on and after 5.18.0

### ISSUE THREAD

**Issue by parkjs814** [TypedProject/ts-express-decorators#574]
## Information

- **Version:** 5.19.1
- **Type:** Issue

## Description
I just upgraded Ts.ED from 5.17.1 to 5.19.1, and none of `@PreHook`, `@PostHook`, `@MongoosePlugin`, and `@MongooseIndex` works for me. I suspect that `applySchemaOptions` is not working properly after fixes in `5.18.0` (specifically cc6bb7e).

## Example

```ts
import {Model, PreHook} from "@tsed/mongoose";

@Model()
@PreHook("save", (car: CarModel, next: any) => {
  // this callback function never gets called.
  next();
})
export class CarModel {
  // ...
}
```

**Comment by parkjs814** [comment]
I think it is because `store.get(MONGOOSE_SCHEMA)` is `undefined` before getting `@Model()`ed. 

I am currently using a temporary bypass, and it works fine:
```ts
export const TempModel = () => {
  return (target: any) => {
    const schema = getSchema(target);
    // add prehook/posthook/plugin to the schema directly.
    registerModel(target, createModel(target, schema));
  };
};

@TempModel()
export class CarModel {
  // ...
}
```

**Comment by Romakita** [comment]
Hello @parkjs814 
Thanks for your feedback. The v5.20.1 fix this problem :)

**Comment by parkjs814** [comment]
Thank you for the awesome framework!
