### ISSUE TITLE
TypeORM predefined connection object

### ISSUE THREAD

**Issue by marghidanu** [TypedProject/ts-express-decorators#579]
## Information

- **Version:** 5.x
- **Type:** Issue

## Description

Hello, 

We are trying to create a test with **supertest** that uses two instances of ServerLoader apps both using the same database. The problem is that TypeORM manages connections is some sort of a Singleton object thus causing the application to fail silently. It would be nice if TypeORMService would check if the connection already exists using `getConnection(name)` from TypeORM and if the connection already exists it should reuse it.

**Comment by Romakita** [comment]
Hello @marghidanu,
Can you help me by creating a small PR with the required change (or copy paste here the code) ? I'll doing unit test for you ^^
Here the TypeORMService code https://github.com/TypedProject/ts-express-decorators/blob/master/packages/typeorm/src/services/TypeORMService.ts
See you
Romain
