### ISSUE TITLE
Nothing is loaded in v5.23.0 or greater

### ISSUE THREAD

**Issue by ghmendonca** [TypedProject/ts-express-decorators#603]
## Information

- **Version:** ^5.23.0
- **Type:** Issue

## Description
I just updated the version to 5.24.0 and suddenly all my routes stopped working. Testing this more, I noticed that services aren't working either, since graphql is not working. I tried 5.21.1 and 5.22.0 and both works, so I'm assuming the bug was introduced in 5.23.0.

One more thing that I noticed is that the 5.23.0 and 5.24.0 versions works on Ubuntu but not on Windows, so this leads me to believe this commit #b82a924 updated a dependency that introduced this bug, but I'm just guessing

**Comment by striquer** [comment]
I'm having the same problem on my local windows, but on AWS is working fine, nothing on the mount or componentScan properties are being loaded

**Comment by Romakita** [comment]
Hum I think the problem come from globby dependencies. I'll try to find a fix ASAP.

**Comment by Romakita** [comment]
Fast-glob change the behavior with forward-slash. It's a big breaking change on Windows. 
https://github.com/mrmlnc/fast-glob/releases/tag/3.0.0

**Comment by ghmendonca** [comment]
Can you provide us a work around for this? I read the breaking changes and I couldn't see a way to work around ☹

**Comment by ghmendonca** [comment]
I tried the following thing: `path.normalize(path.join(__dirname, '/services/**/*.ts')).replace(/\\/g, '/')` but it didn't work.. I can see that using this, it displays the right path, using only forward slashes and the right path, but still the server doesn't load anything

**Comment by ghmendonca** [comment]
I left the exact same code as I tried in the comment before and rolled back to 5.22.0 and it works, so maybe this is something else?

**Comment by Romakita** [comment]
I published a new version v5.24.1 with the fix :) (rollback to globby v9 )

**Comment by ghmendonca** [comment]
Awesome! Thanks man 😁
