### ISSUE TITLE
[Question] Is it possible to inject resolved/await promise object?

### ISSUE THREAD

**Issue by ringolin93** [TypedProject/ts-express-decorators#613]
## Information

- **Version:** 5.x
- **Type:** Issue/Question

## Description
I want to load the configuration from the resource file by an async function in my use case. However, it is not possible pass the unresolved configuration promise to ```@ServerSettings```. 

Other than passing promise to ```@ServerSettings``` , there is a similar situation when performing DI for some component classes.

As typescript does not support top-level await, I wonder is there any workaround that can inject a resolved promise for server setting/component class.

## Example for @ServerSettings 

IIFE approach:

```typescript
(async () => {
    let setting = await loadConfigFromFile();

    @ServerSettings(setting) //How to achieve this?
    export class Server extends ServerLoader {}
})();
```
Top level await approach:
```typescript
let setting = loadConfigFromFile();
@ServerSettings(await setting) //How to achieve this?
export class Server2 extends ServerLoader {}
```

## Example for DI in some component class
assume there is a component class:
```typescript
@Injectable()
export class BarComponent {
    public constructor(
        @Inject("FooValue") fooByValue: Foo,
        @Inject("FooFactory") fooByFactory: Foo
    ) {}
}
```

Top level approach: will not produce any error, but ```fooByValue``` and ```fooByFactory``` will be unresolved ```Promise<Foo>``` object :
```typescript
let foo = FooFactory.create(); //assume FooFactory.create is async method
registerProvider({
    provide: "FooValue",
    useValue: foo
});

registerProvider({
    provide: "FooFactory",
    useFactory: FooFactory.create
});
```

IIFE approach: this will produce error ```UnhandledPromiseRejectionWarning: INJECTION_ERROR``` when component class is initializing:
```typescript
(async () =>{
    let foo = FooFactory.create(); //assume FooFactory.create is async method
    registerProvider({
        provide: "FooValue",
        useValue: await foo
    });

    registerProvider({
        provide: "FooFactory",
        useFactory: await TestEnvironmentContext.getInstance
    });
})();
```

**Comment by Romakita** [comment]
Hello @ringolin93,
Currently, async provider isn't supported (it's planned on the roadmap).

One of the possibility is to use $onInit lifecycle on your server:

```typescript
@ServerSettings({
   // default config
})
export class Server extends ServerLoader {
   async $onInit() {
     let settings = await loadConfigFromFile();
     this.settings.set(settings);

     const foo = FooFactory.create(); //assume FooFactory.create is async method
     const testEnvCtx = TestEnvironmentContext.getInstance();

     this.injector.forkProvider({
         provide: Symbol.for("FooValue"),
         useValue: foo
     })
     this.injector.forkProvider({
         provide: Symbol.for("FooFactory"),
         useFactory() {
            return testEnvCtx
         }
     })
   }
}
```
if loading settings won't work correctly on $onInit hook, you can pass settings when you create a new server instance:

```typescript
(async () => {
    let settings = await loadConfigFromFile();
    const server = new Server()
    server.settings.set(settings)
    try {
      await server.start()
    } catch(er) {
       console.error(er)
    }
})()
```

Tell me if this example works fine for you :)

See you
romain

**Comment by ringolin93** [comment]
Thanks @Romakita

```server.settings.set()``` in IIFE example works fine. :)

But setting config in ```$onInit()``` hook does not work. The logger and ```server.settings``` able to show same values of ```settings.componentsScan``` & ```settings.mount``` as shown in IIFE example when the server starts. The application fail to mount routes and Swagger UI. It seems the settings in ```$onInit()``` does not takes any effect.
