### ISSUE TITLE
No getter/setter for swagger map entry in ServerSettingsService

### ISSUE THREAD

**Issue by jpc-dnr** [TypedProject/ts-express-decorators#627]
## Information

- **Version:** 5.27.4
- **Type:** Issue

## Description

The class `ServerSettingsService` does not have any getter/setter for the `swagger` map entry. As a result, it is necessary to set the swagger configuration using the `set` method from the `Map` parent class.

Is it the intended behavior?

## Example

```typescript
@ServerSettings({})
export class MyServer extends ServerLoader {
  constructor(settings = {}) {
     super({...settings })
     this.settings.swagger = [...] // does not work
     this.settings.set('swagger', [...]); // works
  }
```

**Comment by Romakita** [comment]
Yes. swagger key configuration is added by @tsed/swagger  and @tsed/common doesn't know this part of the configuration. Only keys used by @tsed/common have a getters / setters.

**Comment by jpc-dnr** [comment]
Thank you for your answer!
