### ISSUE TITLE
Unknown start up issue (Alpine build)

### ISSUE THREAD

**Issue by virus2016** [TypedProject/ts-express-decorators#640]
Hi @Romakita,

## Information

- **Version:** 5.x
- **Type:** Issue

## Description
We are starting to look at smaller builds. We have an Unknown start up issue stopping node running on alpine build.

```[2019-09-10T16:48:02.496] [ERROR] [TSED] - { inspect: [Function: inspect] }```

Here is our dockerfile:

```
FROM node as base

FROM node as devtsc
RUN npm install -g kill-port rimraf --silent
RUN npm install -g typescript  --silent
WORKDIR /usr/src/app
COPY package.json ./package.json
COPY package-lock.json ./package-lock.json
RUN npm install --ignore-scripts --silent

FROM node as dev
COPY --from=devtsc /usr/src/app /usr/src/app
WORKDIR /usr/src/app
COPY . .
RUN npm run buildProd

FROM node as test
COPY --from=dev /usr/src/app /usr/src/app
WORKDIR /usr/src/app
CMD ["node", "./dist/index.js"]

FROM node:alpine as prod
RUN npm install -g forever --silent
RUN apk add --no-cache curl git
WORKDIR /usr/src/app
COPY package.json ./package.json
COPY package-lock.json ./package-lock.json
RUN npm install --ignore-scripts --silent --production
COPY --from=dev /usr/src/app/dist /usr/src/app
EXPOSE 9011
ENV NODE_ENV production
CMD ["forever", "./index.js"]
```

Works fine on a Node image. Wondering if we need any apk packages?

**Comment by virus2016** [comment]
Looks like a Node v12 error... Works fine on a v8 alpine build. 

Do we have support for v12?

**Comment by Romakita** [comment]
Actually I haven’t tested on v12. I’ll test asap :)

**Comment by Romakita** [comment]
Works fine. Getting started example had a docker file example with node 12 alpine :)
