### ISSUE TITLE
"Storage" option on @MulterOptions got an error "is not a function*

### ISSUE THREAD

**Issue by ariframadhani** [TypedProject/ts-express-decorators#644]
## Information

- **Version:** 5.27.4
- **Type:** Issue/Story

## Description
I was trying to save uploaded image by its original name but I got an error (attachment included). Or maybe my implementation was wrong? 

## But "dest" Implementation Works Fine
```js
export const Constant = {
  UPLOAD_IMG_DIR: Path.resolve(__dirname, '../../public/upload/images'),
};

...

@MulterOptions({
     dest: Constant.UPLOAD_IMG_DIR,
)}

...
```

## Implementation (Error)

```js
import {Patch} from '@tsed/common';
import {MulterOptions, MultipartFile} from "@tsed/multipartfiles";

@Patch("/image")
@MulterOptions({
    storage: multer.diskStorage({
        filename(req: Express.Request, file: Express.Multer.File, callback: (error: (Error | null), filename: string) => void): void {
             callback(null, file.originalname);
          }
      })})
async updateAvatar(@MultipartFile() photo: Express.Multer.File){
    return photo;
}

```
## Error Preview
<img width="630" alt="2" src="https://user-images.githubusercontent.com/34822808/64979653-54e4cc80-d8e2-11e9-8f40-9606ce0efa9e.png">

**Comment by Romakita** [comment]
Hello @ariframadhani, a fix will be released soon ;)

**Comment by ariframadhani** [comment]
thank you soo much, helped my company tho, appriciate it.
