### ISSUE TITLE
How to define array of models in @Returns?

### ISSUE THREAD

**Issue by swarupbam** [TypedProject/ts-express-decorators#645]
## Information

- **Version:** 5.x
- **Type:** Issue/Story

## Description
````
@Returns(200, { description: "ok", type: UserInfo})
````
I expect array of UserInfo to be sent. How to define it?
Currently my api returns an array but in swagger it shows object as an response.

**Comment by Romakita** [comment]
Maybe ReturnsArray :)
https://tsed.io/tutorials/swagger.html (section decorators)

I agree isn’t evident :)

See you

**Comment by swarup-techprescient** [comment]
@Romakita  It worked. Thanks a lot. May be we should add this in the example.

**Comment by swarupbam** [comment]
@Romakita  It worked. Thanks a lot. May be we should add this in the example.

**Comment by Romakita** [comment]
Yes :)
