### ISSUE TITLE
PathParams must be always string

### ISSUE THREAD

**Issue by gabrielperales** [TypedProject/ts-express-decorators#653]
## Information
`@PathParam('paramName')` must be always type `string`.

- **Version:** 5.x
- **Type:** Issue/Story

## Description
I have this code:

```
  @Get('/:deploymentId')
  @UseAuth(UsernamePasswordMiddleware)
  public async getConfiguration(
    @Required()
    @PathParams('deploymentId')
    deploymentId: number,
    @QueryParams('v')
    version?: string
  ): Promise<version | version[]> {
     ...
  }
```

And I was expecting to have a number in `deploymentId` but it seems like it is not doing a casting, so a `@PathParam` is going to be always a string and TypeScript must raise an error saying that `number is not compatible with the type string`.

## Acceptance criteria

- [ ] @PathParams must return a variable of type `string`

**Comment by gabrielperales** [comment]
Don't really know how to fix this issue, I think we have to change this function

https://github.com/TypedProject/ts-express-decorators/blob/370f2aa91fc0c5baffeb8165acfe3b04da8895c2/packages/common/src/mvc/registries/ParamRegistry.ts#L85

And check there whether the `filter` is string and is "PATH" to set `param.type = "string"` or something like that @Romakita?

**Comment by Yaroslav-wb** [comment]
Hey @gabrielperales, I had same issue when `@PathParam` stopped casting param into correct type.
After researching I found that guys updated default parameters of `@PathParam` and now `useConverter` is false.
To allow `@PathParam` casts value into correct type, you have to put parameter `useConverter` as `true`, like:
`@PathParams({ expresion: 'deploymentId', useConverter: true })`

**Comment by gabrielperales** [comment]
@Yaroslav-wb cool, I had to make a custom filter in order to parse those PathParams in to integers... but `useConverter` is very handy. In the other hand the issue I'm describing still there, TypeScript should know that a PathParam is `string` if you are not using `useConverter`.

**Comment by Romakita** [comment]
@gabrielperales change the useFilter function doesn't make sense. 
useConverter is the right solution in absolute, but isn't the efficient solution. 

I'll fix the PathParams configuration to support by default the casting type.

**Comment by Romakita** [comment]
v3.31.4 will fix this regression :)
