### ISSUE TITLE
BODY Swagger ParameterName uppercase

### ISSUE THREAD

**Issue by dngconsulting** [TypedProject/ts-express-decorators#655]
## Information
- **Version:** 5.31
- **Type:** Issue

## Description
The Swagger Schema generated using @BodyParams prevent every Swagger CodeGen to generate the right sdk stub. 
Let's take a very straightforward sample :

```typescript
PassportCtrl.login(BodyParams() user : User) {
}
``` 

When we use official Swagger TypeScript Fetch generator, the following stub is generated :

```typescript
   passportCtrlLogin(options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling passportCtrlLogin.');
            } (...)
```

Instead of :
```typescript
passportCtrlLogin(**body: PassportCtrlLoginPayload**, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling passportCtrlLogin.');
            }
```

This is due to the fact that the body parameter in spec.json is spelled as BODY in uppercase instead of lowercase. Many code gen tools does not complaint and fail silently to generate the parameter. Others raise "Parameter Type does not exist" and stop. 
I'm surprised that I don't see any issue on this topic given that it is a nominal case... People don't use code gen with swagger ?

btw, Ts.ed is really an awesome project ...

Cheers,

Sami

**Comment by Romakita** [comment]
Hello @dngconsulting 

Hoo I see the problem. I remember I already fix this problem. But maybe latest release has introduce a regression. A quick fix is possible :)

See you

**Comment by Romakita** [comment]
Hello @dngconsulting 

For me the swagger is correctly generated. Here the swagger used by my unit test: https://github.com/TypedProject/ts-express-decorators/blob/master/test/integration/data/swagger.spec.json
it look sound good ^^

**Comment by dngconsulting** [comment]
Sorry to have opened this ticket for nothing @Romakita and have wasted your time. My Ts.ED version was recent but not the swagger module. That's better now. Cheers
