### ISSUE TITLE
@tsed/testing bootstrap method

### ISSUE THREAD

**Issue by OskarLebuda** [TypedProject/ts-express-decorators#689]
## Information

- **Version:** 5.32.2
- **Type:** Issue

## Description
I had a unit tests for my API. Now i see the `bootstrap` method from the `@tsed/testing` is deprecated. What should I use instead? 

## Example

```
describe("APICtrl", () => {

    before(bootstrap(Server));

    // test jere

});


```

## Acceptance criteria

- [ ] Criteria 1

**Comment by harshkothari410** [comment]
Use ```TestContext.bootstrap(Server)``` instead of above. @OskarLebuda
