### ISSUE TITLE
TestContext.bootstrap with DI: behavior changed

### ISSUE THREAD

**Issue by jpc-dnr** [TypedProject/ts-express-decorators#691]
## Information

- **Version:** 5.33.0
- **Type:** Issue

## Description

I'm currently migrating from 5.29.0 to 5.33.0 and I noticed that when using an injected object with `TestContext.bootstrap`, behavior has changed. Now the injected object is like:

```typescript
{
  args: Array(1) [MyClassImpl]
  logger: Object {level: "off"}
  __proto__: Object {...}
}
```

Am I doing something wrong?

Thanks

## Example

```typescript
interface MyClass {
  ...
}

class MyClassImpl implements MyClass {
  ...
}

const TYPES = {
  MyClass: Symbol.for('MyClass')
}

registerProvider({ provide: TYPES.MyClass, useClass: MyClassImpl });

const myClass = TestContext.injector.get<MyClass>(TYPES.MyClass);
await TestContext.bootstrap(MyServer, { args: [myClass] })();

class MyServer extends ServerLoader {
  public constructor(myClass: MyClass) {
    // this is where myClass object is not of type MyClass
  }
}
```

**Comment by Romakita** [comment]
Yes you’ve right. I introduced a breaking change on an undocumented arguments... sorry

**Comment by jpc-dnr** [comment]
Thanks for your quick answer.
As it is undocumented, is this something that will be fixed or should I use something else?

**Comment by Romakita** [comment]
You can use it. If the next time I change the signature arguments I’ll change the version to a major version ;)

**Comment by jpc-dnr** [comment]
Thanks for the information!
