### ISSUE TITLE
Error with integration tests

### ISSUE THREAD

**Issue by miguelsts** [TypedProject/ts-express-decorators#693]
## Information

- **Version:** 5.33.0
- **Type:** Issue

## Description
When trying to start testing I get the following error

`1) Transactions - API
       "before all" hook: before in "Transactions - API":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (.../.../transactions.controllers.spec.ts)
`
## Example

``` ts
import { TestContext } from "@tsed/testing";
import * as SuperTest from "supertest";
import { ExpressApplication } from "@tsed/common";
import { expect } from "chai";
import { Server } from "../../../src/server";

describe("Transactions - API", () => {
  let request: SuperTest.SuperTest<SuperTest.Test>;

  before(TestContext.bootstrap(Server));
  before(
    TestContext.inject(
      [ExpressApplication],
      (expressApplication: ExpressApplication) => {
        request = SuperTest(expressApplication);
      }
    )
  );
  after(TestContext.reset);

  describe("GET /api/transactions", () => {
    it("retornar uma lista das transações já criadas", async () => {
      const response = await request.get("/api/transactions").expect(201);
      expect(response.body).to.be.an("array");
    });
  });
});

```

## Acceptance criteria

- [ ] Run an integration test

**Comment by Romakita** [comment]
Hello @miguelsts 
Have you correctly registered chai as promised plugin ? 
Here an example : https://github.com/TypedProject/tsed-getting-started/blob/master/scripts/mocha/register.js

You can checkout the getting started example. The integration test works correctly.
https://github.com/TypedProject/tsed-getting-started/

See you
Romain

**Comment by miguelsts** [comment]
Already solved, the problem is that I was using version 5.33.0, while the one in the example is 5.18.0

**Comment by Romakita** [comment]
Ha ok so the 5.33.0 example is wrong ?

**Comment by ziofat** [comment]
So what is the correct bootstrap for 5.33.0?
