### ISSUE TITLE
common pkg: Cannot find module '../../../../di/src'

### ISSUE THREAD

**Issue by PAStheLoD** [TypedProject/ts-express-decorators#702]
## Information

- **Version:** 5.33.4
- **Type:** Issue

## Description

So in @tsed/common `./server/utils/loadInjector.d.ts` there's this line (2nd of the 2 lines only in the file):

```
export declare function loadInjector(injector: InjectorService, container?: Container): Promise<import("../../../../di/src").LocalsContainer<any>>;
```

And apparently changing the `di/src` to `di` works, otherwise `tsc` throws the error.

This seems to be a problem on both TS3.6 and on TS3.7.

**Comment by Romakita** [comment]
Ho shit. I'll change that ;)

**Comment by PAStheLoD** [comment]
Oh, that was fast! Thanks! (Looking at the diff, I have no idea how that gets turned into THAT, but fortunately you did :))

**Comment by Romakita** [comment]
I just imported exmplicitly the interface from the right package. TypeScript  by default infer the interface when is minssing  :)
