### ISSUE TITLE
Locals decorator not working - Passing data from auth middleware to controller

### ISSUE THREAD

**Issue by royibernthal** [TypedProject/ts-express-decorators#703]
Version: 5.33.5

I'm trying to pass data via locals from a custom auth middlewater, registered using a custom auth decorator (similarly to what's in the docs).

In the auth middleware, I have in use() the following argument:
`@Response() response: Express.Response`
for some reason Express.Response doesn't have locals in its typings, so I'm using it as any (logging it shows that locals is an empty object).

I'm setting the following within the use()'s body:
`(response as any).locals.bla = 1234;`

When entering the controller's middleware that uses the auth decorator, the only way I can extract that data is from response: Express.Response, as follows:
`(response as any).locals`

So the usual express way works.

From the docs, I understood that the Locals decorator is simply a nice way to inject response.locals.

However when I try to inject it in my controller using the Locals decorator, the value of locals is undefined.

```
@Post('/myFunc')
@Auth()
myFunc(@Locals() locals: any)
```

If I try Locals('bla') an error is thrown, since I'm trying to access bla of an undefined object.

```
@Post('/myFunc')
@Auth()
myFunc(@Locals('bla') bla: number)
```

The point is to pass information of an authenticated user from the auth middleware to the controller.

1) Why doesn't the Locals decorator work for me? Am I misunderstanding how it should be used?
2) Is there a prettier way to set locals? (same as Locals decorator, just for set instead of get)
3) Is there a better way to pass data between middlewares?

**Comment by Romakita** [comment]
Hello @royibernthal 

I'd just fix the problem with response.locals and I added more documentation over request persistence data. Here the documentation http://tsed.io/docs/request-data-persistence.html

**Comment by royibernthal** [comment]
@Romakita Perfect, it works now :)

After reading the documentation you mentioned, I tried importing Context, and it couldn't be found. Another bug?

**Comment by Romakita** [comment]
Arf I forgot to export the class T.T sorry
Fixup will be released tomorrow

**Comment by royibernthal** [comment]
Haha no problem :)

**Comment by Romakita** [comment]
Fixed ;)
