### ISSUE TITLE
"An accessor cannot be declared in an ambient context."

### ISSUE THREAD

**Issue by cyraid** [TypedProject/ts-express-decorators#707]
## Information

- **Version:** 5.34.4
- **Type:** Issue/Story
- **Typescript:** 3.5.3

## Description
A bunch of "An accessor cannot be declared in an ambient context." errors are popping up in the definition files. I had to revert back to 5.31

**Comment by Romakita** [comment]
@cyraid  I found the reason. I recently updated the typescript version to 3.7.1 and this version (previous version after 3.5) introduce accessor in ambiant files.

I reverted the typescript version to 3.5.0. The fix will be released in few minute :) (Ts.ED 5.34.5)

I you have a bug on express typings, just update the `@types/express` module to the latest version.

See you
Romain

**Comment by cyraid** [comment]
Thanks Romain!
