### ISSUE TITLE
Controllers mounting by mask seems to be broken

### ISSUE THREAD

**Issue by xrip** [TypedProject/ts-express-decorators#709]
## Information

- **Version:** 5.34.6
- **Type:** Issue
- **OS:** Windows

## Description
The following code seems to not work nor in my project nor in demo https://github.com/TypedProject/tsed-getting-started

## Example

```
import {} from "@tsed/common";
@ServerSettings({
	rootDir,
	mount: { '/': `${rootDir}/controllers/**/*` },
});
export class Server extends ServerLoader {
}
```
Controllers not autoloaded. 

Needs to be declared explictly:

```
import {} from "@tsed/common";
import { DataCtrl } from './controllers/DataCtrl';
import { StatisticsCtrl } from './controllers/StatisticsCtrl';

@ServerSettings({
	rootDir,
	mount: { '/': [DataCtrl, StatisticsCtrl] },
});
export class Server extends ServerLoader {
}
```

Controllers not autoloaded, works only if declared explicitly. May be other 'scan' related stuff broken also. Worked fine in 5.33.5

**Comment by xrip** [comment]
Possible it's only Windows related problem. Here https://github.com/TypedProject/ts-express-decorators/pull/708 a related PR-fix

**Comment by Romakita** [comment]
@xrip  Yes the globby module is responsible. The PR is merged. Release will be available soon.
Thanks for your issue ;)
