### ISSUE TITLE
SendResponseMiddleware should not send a response if it has already been done

### ISSUE THREAD

**Issue by EkiGui** [TypedProject/ts-express-decorators#711]
## Information

- **Version:** 5.31.0
- **Type:** Issue

## Description
Hi, I would like to respond to a request manually, based on the result of an asynchronous method. This is a simplified example of my controller's method: 

```ts
   @Get('/:id')
   get(@Res() res: Response, @PathParams('id') id: string): void {
     myAsyncMethod(id).then((result: boolean) => {
       if (result) res.sendStatus(200)
       else res.sendStatus(404)
     }) 
   }
```

Problem is that when the promise resolves,  the `SendResponseMiddleware` has already closed the request and I get the Express error `Cannot set headers after they are sent to the client` (because I'm trying to respond to a request that is already closed)

This is the implementation of `SendResponseMiddleware` today:

```ts
    if (data === undefined) {
      return response.send();
    }

    if (isStream(data)) {
      data.pipe(response);

      return response;
    }

    if (isBoolean(data) || isNumber(data) || isString(data) || data === null) {
      return response.send(data);
    }

    return response.json(this.converterService.serialize(data));
```

I think the middleware should **either**:
- Do nothing if `data` is `undefined`, not to interfere with pending promises.
- Check that `res.headerSent === false` in the first place. In that case, I could return a promise in my controller and send my response before the middleware, without triggering any Express error.

 I don't know which is best and I sincerely hope I didn't miss something in the docs. Again, thanks a lot @Romakita and all the contributors for this very handful and well-thought framework!

**Comment by Romakita** [comment]
Here the right way to send your response:

```typescript
const {NotFound} from "ts-httpexceptions"

 @Get('/:id')
   @Status(204) // 204 is the right status code to return empty response
   async get(@PathParams('id') id: string): Promise<void> {
     const result = await myAsyncMethod(id)
     if (!result){
       throw new NotFound("Resource not found")
     } 
   }
```
> Do nothing if data is undefined, not to interfere with pending promises.
Yep but your method doesn't return the promise (it return undefined instead of Promise<undefined>) so the HandlerBuilder (the class responsible to handle the endpoint response), isn't able to waiting your response.

This code should workd also:
```typescript
@Get('/:id')
   get(@Res() res: Response, @PathParams('id') id: string): Promise<void> {
     return myAsyncMethod(id).then((result: boolean) => { // add a return
       if (result) res.sendStatus(200)
       else res.sendStatus(404)
     }) 
   }
```

See you

**Comment by EkiGui** [comment]
Hey thanks a lot @Romakita for your message !

My first snippet with the empty response was just a VERY simplified example, far from my real use case, but thanks for correcting the syntax and making it more compliant with your framework.

My point was that whatever the async action you want to perform in your controller, if you try to send a response manually (using `res.send` or `res.json` or any other `res.something`) you will get a _Cannot set headers after they are sent to the client_, because the `SendResponseMiddleware` will try to send a response as well.

If you check the way the middleware is implemented (see below), you see that in every _if_ branch we're trying to send something.

```ts
if (data === undefined) {
      return response.send();
    }

    if (isStream(data)) {
      data.pipe(response);

      return response;
    }

    if (isBoolean(data) || isNumber(data) || isString(data) || data === null) {
      return response.send(data);
    }

    return response.json(this.converterService.serialize(data));
```

I guess the middleware should at least check for a `res.headerSent === false` condition, don't you think ?  :speak_no_evil:
