### ISSUE TITLE
Exclude property on ServerSettings doesn't work

### ISSUE THREAD

**Issue by striquer** [TypedProject/ts-express-decorators#713]
## Information

- **Version:** 5.34.7
- **Type:** Issue

## Description
I'm on windows and i need to exclude some Services from the initialization, because i'm splitting the code in two servers, but the exclude property doesn't work for me. I've tried many options, but couldn't figure out why.

## Example

```
@ServerSettings({
    rootDir,
    httpPort: process.env.PORT || 8080,
    httpsPort: false,
    debug: process.env.NODE_ENV === 'production' ? false : false,
    logger: {
        logRequest: process.env.NODE_ENV === 'production' ? false : false,
        requestFields: ["reqId", "method", "url", "headers", "body", "query", "params", "duration"]
    },
    acceptMimes: ["application/json"],
    mount: {
        '/api': '${rootDir}/controllers/**/*.ts',
    },
    componentsScan: [
        '${rootDir}/services/**/*.ts',
        '${rootDir}/models/**/*.ts',
        '${rootDir}/controllers/**/*.ts'
    ],
    exclude: [
        '${rootDir}/servicesQueue/NpcService.ts',
        '${rootDir}/servicesQueue/NpcService.js',
        '${rootDir}/servicesQueue/AgendaService.ts',
        '${rootDir}/servicesQueue/AgendaService.js',
        '${rootDir}/servicesQueue/**/*.ts',
        '${rootDir}/servicesQueue/**/*.js',
        'NpcService.ts',
        'NpcService.js'
    ],
    routers: {
        mergeParams: false,
        strict: true,
        caseSensitive: true
    },
    swagger: [
        {
            path: '/docs',
            spec: {
                securityDefinitions: {
                    Bearer: {
                        type: 'apiKey',
                        name: 'authorization',
                        in: 'header'
                    }
                },
                security: [
                    {
                        Bearer: []
                    }
                ]
            }
        }
    ]
})

```

**Comment by Romakita** [comment]
Hello @striquer 
I'd just published a fix base on the normalize-path module. It should fix the problem on windows. Can you test the new version please ?

See you
Romain

**Comment by striquer** [comment]
Hi @Romakita,
It still didn't work for me, it loaded the NpcService on the wrong server again.

This is what the Debug showed:

![image](https://user-images.githubusercontent.com/6987504/69869653-327d1100-128c-11ea-9ec4-5712527410fa.png)

**Comment by Romakita** [comment]
@striquer Your configuration is a bit strange. Directory servicesQueue isn't listed by componentScan so it cannot be loaded by componentScan excepted if your service is used by another services listed by componentScan.

Can you check your code ^^

Can you give an access to your project ? 

See you
Romain

**Comment by striquer** [comment]
Hey @Romakita, you were right, the 5.34.8 solved the problem, after that my mistake is that i was injecting the service that i didn't want on another service included on componentScan. Thanks for the update 😊.

Many Thanks,
Giovanne.
