### ISSUE TITLE
Swagger doesn't work if there's another route that matches

### ISSUE THREAD

**Issue by Madd0g** [TypedProject/ts-express-decorators#715]
## Information

- **Version:** 5.34.9
- **Type:** Issue

## Description
I have something that mounts on `/:param` and it causes `/api-docs` to not work, only works if I comment out this mount. 

## Example

```
@ServerSettings({
    swagger: [
        {
            path: '/api-docs'
        }
    ],
    mount: {
        '/': './dist/controllers/CatchAllParam.js',
    },
```

and CatchAllParam does something like:

```
@Controller('')
export class CatchAllCtrl {
    @Get('/:param')
```

**Comment by Romakita** [comment]
Fixed :)

**Comment by Romakita** [comment]
Hello @Madd0g 

It a normal behavior. Swagger ui is mounted after the rest API. So to fix your problem you have to change the controller path and mount this under /rest or /myapipath to solve it.

**Comment by Madd0g** [comment]
It is impossible. I must have a `/:anything` controller :(

**Comment by Romakita** [comment]
Ok you can try that:

```typescript
import {ServerLoader } from "@tsed/common"
import {SwaggerModule} from "@tsed/swagger"

@ServerSettings({})
class Server extends ServerLoader {
   $beforeRoutesInit() {
      // Force swagger initialization on $beforeRoutesInit()
      this.injector.get(SwaggerModule).$onRoutesInit()
   }
}
```

**Comment by Madd0g** [comment]
The UI does work, but it says "No operations defined in spec!"

**Comment by Madd0g** [comment]
@Romakita thank you for the quick turnaround!
