### ISSUE TITLE
while running npm start, cookie_parser_1.default is not a function

### ISSUE THREAD

**Issue by gangasiddhi** [TypedProject/ts-express-decorators#726]
[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): src/**/*.ts
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node src/index.ts`
[2019-12-24T16:23:51.784] [INFO ] [TSED] - Call hook $beforeInit
[2019-12-24T16:23:51.786] [INFO ] [TSED] - Call hook $onInit
[2019-12-24T16:23:51.786] [INFO ] [TSED] - Build providers
[2019-12-24T16:23:51.793] [INFO ] [TSED] - Call hook $afterInit
[2019-12-24T16:23:51.794] [INFO ] [TSED] - Call hook $onMountingMiddlewares
[2019-12-24T16:23:51.794] [INFO ] [TSED] - Call hook $beforeRoutesInit
[2019-12-24T16:23:51.794] [ERROR] [TSED] - TypeError: cookie_parser_1.default is not a function

**Comment by Romakita** [comment]
Hello @gangasiddhi ,

How do you import the cookie parser?
Look on cookie parser github the way to import correctly the module in es6/typescript. 
The problem isn’t related to tsed framework ;)
See you,
Romain

**Comment by gangasiddhi** [comment]
import {GlobalAcceptMimesMiddleware, ServerLoader, ServerSettings} from "@tsed/common";
import bodyParser from "body-parser";
import compress from "compression";
import cookieParser from "cookie-parser";
import methodOverride from "method-override";

const rootDir = __dirname;

@ServerSettings({
  rootDir,
  acceptMimes: ["application/json"]
})
export class Server extends ServerLoader {
  /**
   * This method let you configure the express middleware required by your application to works.
   * @returns {Server}
   */
  public $beforeRoutesInit(): void | Promise<any> {
    this
      .use(GlobalAcceptMimesMiddleware)
      .use(cookieParser())
      .use(compress({}))
      .use(methodOverride())
      .use(bodyParser.json())
      .use(bodyParser.urlencoded({
        extended: true
      }));
  }
}

**Comment by Romakita** [comment]
https://github.com/TypedProject/tsed-getting-started/blob/master/src/Server.ts

**Comment by stephanram** [comment]
It can be resolved if you use require instead of import syntax

var bodyParser = require('body-parser');
var compress = require('compression');
var cookieParser = require('cookie-parser');
var methodOverride = require('method-override');

**Comment by gangasiddhi** [comment]
Thanks a lot , its fixed my issue.

**Comment by oehm-smith** [comment]
The https://tsed.io/getting-started.html#create-your-express-server docs need to be updated to reflect this.  Ie:

    import {GlobalAcceptMimesMiddleware, ServerLoader, ServerSettings} from "@tsed/common";
    import * as bodyParser from "body-parser";
    import * as compress from "compression";
    import * as cookieParser from "cookie-parser";
    import * as methodOverride from "method-override";
    
    const rootDir = __dirname;
    ...

Also the `script > start` in `package.json` needs to be changed to be (ie. `index.ts` instead of `Server.ts`):

        "start": "nodemon --watch \\\"src/**/*.ts\\\" --ignore \\\"node_modules/**/*\\\" --exec ts-node src/index.ts",

Remind me where this can be done and I'll do it for you :)

**Comment by Romakita** [comment]
True ;). Thanks @oehm-smith I'll fix that
